### ISSUE TITLE
State /Props Values Not rendering dynamically 

### ISSUE THREAD

**Issue by nihalgadhavi9** [react-native-community/react-native-tab-view#1001]
### Current behaviour

Currently, State/Props value are not being updated in tabs , while in render() it reflects updated data 

### Expected behaviour

State/Props values should be updated in all the tabs
 

### What have you tried

I have tried to correct navigationState and SceneMap

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |
| react-native                 |
| react-native-tab-view        |
| react-native-gesture-handler |
| react-native-reanimated      |
| node                         |
| npm or yarn                  |

**Comment by shubhamkakkar** [comment]
can you provide some way to recreate your issue, it would of great help

**Comment by bonadio** [comment]
I have the same problem, follow the code that reproduce the error

`import React, { Component } from 'react'
import { Dimensions, Text, View, StyleSheet, SafeAreaView, Button, ScrollView,TouchableOpacity, TextInput } from 'react-native'
import { globalStyle } from '../../../utils/styles/globalStyle'
import { TabBar, TabView, SceneMap } from 'react-native-tab-view';


class EstatScreen extends Component {
	constructor(props) {
		super(props);
		this.state = {
			test: 0,
			index: 0,
			routes: [
				{ key: 'week', title: 'Semana' },
				{ key: 'month', title: 'Mes' },
				{ key: 'year', title: 'Ano' },
			]
		}
	}

	WeekRoute = () => (
		<View style={[styles.scene]}>
			<Text style={{ color: 'black', fontSize: 15, textAlign: 'center', marginTop: 10 }}>{this.state.test}</Text>
		</View>
	)

	MonthRoute = () => (
		<View style={[styles.scene]}>

		</View>
	)
	YearRoute = () => (
		<View style={[styles.scene]}>
			
		</View>
	)

	renderScene = SceneMap({
		week: this.WeekRoute,
		month: this.MonthRoute,
		year: this.YearRoute,
	});
	
	_bootstrap = async () => {

		this.setState({test: 10});
    };

    componentDidMount() {
		this._bootstrap();
	}
	
	setIndex = (ind) => {
		this.setState({
			index: ind
		})
	}
	renderTabBar = props => (
		<TabBar
		  {...props}
		  indicatorStyle={{ backgroundColor: 'white' }}
		  style={globalStyle.g_bgColor}
		/>
	  );

	render() {
		return (
			<TabView
				renderTabBar={this.renderTabBar}
				navigationState={this.state}
				renderScene={this.renderScene}
				onIndexChange={this.setIndex}
				initialLayout={this.initialLayout}
			/>
		)
	}
	


}
export default EstatScreen

const styles = StyleSheet.create ({

	scene: {
		flex: 1,
	},
	tabbar: {
		backgroundColor: 'red',
	  },
})`

**Comment by EyadAyman658** [comment]
any solution?

**Comment by Evan-Younan** [comment]
The solution is to not use SceneMap. Use a function that renders a scene based on the key given by the route.

**Comment by DeVoresyah** [comment]
> The solution is to not use SceneMap. Use a function that renders a scene based on the key given by the route.

can u give the example, I also got this bug when using `SceneMap`

**Comment by satya164** [comment]
It's already explained in the README how to pass additional props https://github.com/react-native-community/react-native-tab-view#renderscene-required

**Comment by DeVoresyah** [comment]
> It's already explained in the README how to pass additional props https://github.com/react-native-community/react-native-tab-view#renderscene-required

can't fix it, don't close first la unless we found the right solution
