### ISSUE TITLE
Switch Tab not working while rendering common component for tabs

### ISSUE THREAD

**Issue by arun1705** [react-native-community/react-native-tab-view#1005]
hello team,
Scroll and swipe functionality properly working  for my tabs but when it comes to switch the tabs its not working i am using common component for all tabs.

 const [index, setIndex] = React.useState(0);
    <TabView
      navigationState={{index, routes}}
      renderScene={renderScene}
      renderTabBar={renderTabBar}
      onIndexChange={setIndex}
      initialLayout={initialLayout}
    />

on press of tabs OnIndexChange not updating the state
   "react-native": "0.62.2",
  "react-native-tab-view": "^2.14.0",

**Comment by Natkarock** [comment]
@arun1705 hello! did you solve your problem?
