### ISSUE TITLE
How to use position ?

### ISSUE THREAD

**Issue by Lizhooh** [react-native-community/react-native-tab-view#1007]
**After updating to 2.0, position safety is broken and the previous method of use.**

```js 
export default function TabViewExample() {
    const [index, setIndex] = useState(0);
    const [position] = useState(() => new Animated.Value(0));
    const [routes] = useState([
        { key: '1', title: 'Home' },
        { key: '2', title: 'Test' },
    ]);

    const renderScene = SceneMap({
        1: FirstRoute,
        2: SecondRoute,
    });

    return (
        <TabView
            position={position}
            navigationState={{ index, routes }}
            renderScene={renderScene}
            onIndexChange={setIndex}
            initialLayout={initialLayout}
            renderTabBar={({
                navigationState,
                position
            }) => (
            <Animated.View style={{
                height: lineHeight,
                width: lineWidth,
                marginLeft: width / (num * 2) - lineWidth / 2,
                backgroundColor: theme,
                transform: [{
                    translateX: position.interpolate({
                        inputRange,
                        outputRange,
                    }),
                }],
            }} />
            )}
        />
    );
}
```

### Code sample

For Syntax Highlighting check this [link](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

### Screenshots (if applicable)
![20200510222433](https://user-images.githubusercontent.com/19299088/81502044-1fc43900-930e-11ea-8958-23b41862b740.png)
![20200510223148](https://user-images.githubusercontent.com/19299088/81502048-28b50a80-930e-11ea-9b46-19409ffedf1f.png)

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | android 
| react-native                 | 0.62
| react-native-tab-view        | ^2.14.0
| react-native-gesture-handler | ^1.6.1
| react-native-reanimated      | ^1.8.0
| node                         | 12.10.0
| npm or yarn                  | yarn

**Comment by Lizhooh** [comment]
Since one of my projects used an 1.x version to upgrade to 2.x, an error occurred, and now I need to change Animated to `react-native-reanimated` and run it normally.

~~import { Animated } from 'react-native';~~

import Animated from 'react-native-reanimated';

**Comment by YanvegHD** [comment]
THANK YOU @Lizhooh !! My animation was stopping when the user released his finger while sliding (I was using the 'left' style prop), and thanks to you it works now when using 'translateX', I didn't think about it and I was struggling, big thank 🎉

**Comment by NyashaNziramasanga** [comment]
For anyone else looking at this `react-native-reanimated` changed `interpolate` to `interpolateNode`

update is:
```javascript
 const translateX = Animated.interpolateNode(position, { inputRange, outputRange });
```
