### ISSUE TITLE
tslint problems 

### ISSUE THREAD

**Issue by jose920405** [react-native-community/react-native-tab-view#1008]
### Current behaviour

![Screen Shot 2020-05-11 at 10 47 28 AM](https://user-images.githubusercontent.com/12536184/81581798-d5c26e00-9374-11ea-8d06-1dc21bcfeeb1.png)

### Expected behaviour

For an strange reason this is the only module that cause problems with tslint configuration. Exactly with the `.d.ts` files.

### Code sample

This is my linter script:

```
"lint": "tsc --noEmit && tslint -c tslint.json -p tsconfig.json '**/*.ts{,x}' -e '**/node_modules/**'",
```

And in my `tslint.json` file

i have this rule 

```
"linterOptions": {
    "exclude": [
      "node_modules"
    ]
  },
```

and in my `tsconfig.json` file i have

```
"exclude": [
    "node_module"
  ]
```

**Comment by satya164** [comment]
Looks like you're using an older version of TypeScript which doesn't support type imports/exports. You need to update your TypeScript version.

**Comment by sidferreira** [comment]
If anyone finds this: replace `tslint` by `eslint-typescript` and you won't need `tsc` part anymore
