### ISSUE TITLE
How to custom the TabBarTop's style?

### ISSUE THREAD

**Issue by scriptfans** [react-native-community/react-native-tab-view#101]
Hi, I want to implement a custom component use this plugin, but I don't know I to change the tabbar's style, can you help me? thanks!

![image](https://cloud.githubusercontent.com/assets/359790/21769995/5b2ee1dc-d6bc-11e6-99e0-110d936a2fdd.png)

**Comment by satya164** [comment]
You can pass a `style` object to the tab bar.
