### ISSUE TITLE
ScrollPager does not always scroll when Tab is pressed

### ISSUE THREAD

**Issue by Evan-Younan** [react-native-community/react-native-tab-view#1011]
### Current behaviour

The ScrollPager that is exported in this package does not always scroll when a tab is pressed.

### Expected behaviour

When a tab is pressed, the ScrollPager should scroll to the proper page.

### Code sample

```
import React from "react";
import { View, Text, Dimensions } from "react-native";
import {
    TabView,
    Route,
    SceneRendererProps,
    ScrollPager
} from "react-native-tab-view";

const initialLayout = { width: Dimensions.get("window").width };
const routes: Route[] = [
    { key: "1", title: "tab 1" },
    { key: "2", title: "tab 2" },
    { key: "3", title: "tab 3" }
];

type RenderSceneProps = SceneRendererProps & {
    route: Route;
};

export default () => {
    const [index, onIndexChange] = React.useState(0);

    const renderScene = ({
        route: { title }
    }: RenderSceneProps): React.ReactNode => (
        <View style={{ height: 200 }}>
            <Text>{title} tab data</Text>
        </View>
    );

    return (
        <TabView
            navigationState={{ index, routes }}
            renderPager={(props) => <ScrollPager {...props} />}
            {...{ onIndexChange, initialLayout, renderScene }}
        />
    );
};

```

### Screenshots (if applicable)

![bug-gif](https://user-images.githubusercontent.com/28550574/81695451-a5400a00-9430-11ea-8b5f-2b47daf48f75.gif)

### What have you tried

I've tried everything from the default `TabBar` with no props set, the TabBar with props set, usage in conjunction with `@react-navigation/material-top-tabs` and have still observed the same bug.

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | ios
| react-native                 | 0.63.0-rc.1
| react-native-tab-view        | 2.14.0
| react-native-gesture-handler | 1.6.1
| react-native-reanimated      | 1.8.0
| node                         | 12.16.1
| npm or yarn                  | 6.13.1

**Comment by Aryk** [comment]
Awesome, I had the exact same issue.
