### ISSUE TITLE
all tabs height increase when one tab is list and scrolls

### ISSUE THREAD

**Issue by anjumpaul** [react-native-community/react-native-tab-view#1019]
all tabs height increase when one tab is list and scrolls

### Code sample

For Syntax Highlighting check this [link](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |
| react-native                 |
| react-native-tab-view        |
| react-native-gesture-handler |
| react-native-reanimated      |
| node                         |
| npm or yarn                  |

**Comment by tsaohucn** [comment]
Me too +1

**Comment by tsaohucn** [comment]
????

**Comment by FilipMaslovaric** [comment]
This generally happens when `<TabView>` is wrapped by a `<ScrollView>` parent component.

**Comment by satya164** [comment]
https://github.com/react-native-community/react-native-tab-view#avoid-rendering-tabview-inside-scrollview
