### ISSUE TITLE
Spacing between tab bar items

### ISSUE THREAD

**Issue by vijayst** [react-native-community/react-native-tab-view#1020]
### Current behaviour

I am not able to specify spacing between tab bar items.  Using margin right on tab style gives the desired spacing. But also increases the indicator width.

### Expected behaviour

Able to specify spacing between tab bar items.

### Code sample

```
renderTabBar = props => {
    return (
      <TabBar
        {...props}
        indicatorStyle={Styles.tabBarIndicatorStyle}
        style={Styles.tabBarStyle}
        tabStyle={Styles.tabBarTabStyle}
        labelStyle={Styles.tabBarLabelStyle}
      />
    )
  }
```

Styles are:
```
tabBarStyle: {
    backgroundColor: 'white',
    marginTop: moderateScale(20),
    marginLeft: moderateScale(16),
    shadowColor: 'black',
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: {
      height: 0,
      width: 0,
    },
  },
  tabBarIndicatorStyle: {
    backgroundColor: '#FE7C85',
    height: 3,
    paddingRight: 32,
  },
  tabBarLabelStyle: {
    color: 'black',
    textTransform: 'capitalize',
    fontFamily: fonts.gilroyBold,
    fontSize: moderateScale(17),
  },
  tabBarTabStyle: {
    width: 'auto',
    padding: 0,
    marginRight: 32,
  },
```

### Screenshots (if applicable)
<img width="286" alt="Screenshot 2020-05-28 at 8 07 38 PM" src="https://user-images.githubusercontent.com/3457565/83155473-e7e72f00-a11e-11ea-8b36-8559fb70048c.png">

### What have you tried

Tried margin right on tabStyle to space items.
To remove indicator stretching, tried setting right: 32 on indicatorContainerStyle and paddingRight: 32 on indicator style

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | ios latest
| react-native                 | 0.61
| react-native-tab-view        | latest
| react-native-gesture-handler | 1.5.3
| react-native-reanimated      | 1.4.0
| node                         | 10
| npm or yarn                  | 1.21

**Comment by vijayst** [comment]
I was able to resolve this issue with a custom indicator 
```
        renderIndicator={indicatorProps => {
          const width = indicatorProps.getTabWidth(this.state.index) - 32
          return <TabBarIndicator {...indicatorProps} width={width} />
        }}
```

**Comment by mlecoq** [comment]
The solution of @vijayst works fine but the ripple effect on bar item is bigger than indicator, alternative is to customize renderTabItem method with a View that acts as separator

```
 renderTabBarItem: (props) => (
              <React.Fragment key={props.route.key}>
                <TabBarItem {...props} />
                <View style={{width: 29}} />
              </React.Fragment>
            ),
```

and then adjust left position of the indicator 

```
  tabBar={(props) => (
            <MaterialTopTabBar {...props} indicatorStyle={[props.indicatorStyle, {left: props.state.index * 29}]} />
          )}
```

**Comment by mlecoq** [comment]
I was not happy with the behavior of the indicator on swipe, so finally I had to modify translation :

```
  renderTabBarItem: (props) => (
              <React.Fragment key={props.route.key}>
                <TabBarItem {...props} />
                <Separator />
              </React.Fragment>
            ),
            renderIndicator: (props) => {
              const {
                navigationState: {routes},
                getTabWidth,
                position,
              } = props;
              const translateX =
                routes.length > 1 ? getTranslateX(isTablet ? 29 : 19, position, routes, getTabWidth) : 0;

              const indicatorStyle = {
                transform: [{translateX}] as any,
                height: 3,
                backgroundColor: theme.primary,
                borderRadius: 2,
                padding: 0,
              };

              return <TabBarIndicator {...props} style={indicatorStyle} />;
            },

```


and getTranslateX method 

```
const getTranslateX = memoize(
  (separator: number, position: Animated.Node<number>, routes: Route[], getTabWidth: GetTabWidth) => {
    const inputRange = routes.map((_, i) => i);

    // every index contains widths at all previous indices
    const outputRange = routes.reduce<number[]>((acc, _, i) => {
      if (i === 0) {
        return [0];
      }
      return [...acc, acc[i - 1] + getTabWidth(i - 1) + separator];
    }, []);

    const translateX = interpolate(position, {
      inputRange,
      outputRange,
      extrapolate: Extrapolate.CLAMP,
    });

    return multiply(translateX, I18nManager.isRTL ? -1 : 1);
  },
);
```

**Comment by romelgomez** [comment]
Hi @mlecoq 

Thanks for sharing your code. I have some troubles try to implementing that workaround and I was wondering if you could extend the solution, so I can see the full picture.  

![Screenshot from 2020-12-22 19-26-32](https://user-images.githubusercontent.com/2358251/102945586-2910a900-448c-11eb-9346-d9e9d3e68520.png)

... All the red underlined are errors `Cannot find ....` 

I wanna build tabs with this design requirement  

![Screenshot from 2020-12-22 19-33-07](https://user-images.githubusercontent.com/2358251/102945759-b3f1a380-448c-11eb-8952-c13dbfe259a9.png)

**Comment by mlecoq** [comment]
Here is the memoize function 

```

function memoize<Result, Deps extends readonly any[]>(callback: (...deps: Deps) => Result) {
  let previous: Deps | undefined;
  let result: Result | undefined;

  return (...dependencies: Deps): Result => {
    let hasChanged = false;

    if (previous) {
      if (previous.length !== dependencies.length) {
        hasChanged = true;
      } else {
        for (let i = 0; i < previous.length; i++) {
          if (previous[i] !== dependencies[i]) {
            hasChanged = true;
            break;
          }
        }
      }
    } else {
      hasChanged = true;
    }

    previous = dependencies;

    if (hasChanged || result === undefined) {
      result = callback(...dependencies);
    }

    return result;
  };
}

```

**Comment by mostafabrazi** [comment]
>  renderIndicator={indicatorProps => {
>           const width = indicatorProps.getTabWidth(this.state.index) - 32
>           return <TabBarIndicator {...indicatorProps} width={width} />
>         }}

This solution worked for me and want to make the indicator in the middle, so my final solution was:

```const TAB_MARGIN = 24;```

```
renderIndicator={indicatorProps => {
          const width = indicatorProps.getTabWidth(this.state.index) - TAB_MARGIN
          return <TabBarIndicator {...indicatorProps} width={width} />
}}
indicatorStyle={{
      backgroundColor: 'black',
      height: 4,
      left: TAB_MARGIN / 2,
 }}
```
