### ISSUE TITLE
Tab switching rerenders the inside views, even with React.memo

### ISSUE THREAD

**Issue by mgpepe** [react-native-community/react-native-tab-view#1026]
### Current behaviour

When switching between tabs, all children rerender, even when using React.memo

### Expected behaviour

Children do not rerender.

### Code sample

https://snack.expo.io/10RkVrLln

### Screenshots (if applicable)

none needed

### What have you tried

https://github.com/react-native-community/react-native-tab-view#avoid-unnecessary-re-renders

=> states if we use `React.memo()` should avoid rerender of the component.

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |
| react-native                 |0.62.2
| react-native-tab-view        |^2.14.0
| react-native-gesture-handler |
| react-native-reanimated      |
| node                         |
| npm or yarn                  |

**Comment by satya164** [comment]
It's because you're creating react components during render. Move them outside of render to top level of the file.
