### ISSUE TITLE
Text alignment issue 

### ISSUE THREAD

**Issue by keerthanarbt** [react-native-community/react-native-tab-view#103]
Hi,we are trying to place the tab bar heading text in center but we couldn't do that.help us

**Comment by satya164** [comment]
Can you explain more what you're trying to do?

**Comment by jankalfus** [comment]
I think this is the mentioned issue:

![3](https://cloud.githubusercontent.com/assets/12714276/22645051/64a5be0c-ec65-11e6-9241-2bab4e25ea59.png)

As you can see, longer text makes the button expand. I think that the buttons should be of same size, regardless of text length, and the text should be centered.

Is there any way to solve this?

**Comment by satya164** [comment]
The new percentage feature in RN will fix it. you can fork the tabbar till I update

**Comment by vidhyalakshmirbt** [comment]
styles of what @satya164  . can you just post a small example. i would be helpful

**Comment by jankalfus** [comment]
I fixed this by changing line 436 in TabBar.js to: `tabContainerStyle.width = finalTabWidth;`
I don't think this is a correct solution (if you have more tabs than you can fit on screen, they will be too small), but it works nicely for two tabs.

**Comment by satya164** [comment]
@vidhyalakshmirbt `width` property in `tabStyle`. check the readme

@jankalfus `tabContainerStyle.width = finalTabWidth` will work fine if you have more tabs than you can fit on screen as long as you have `scrollEnabled: true`. the only problem with this approach is `finalTabWidth` is not available before we measure the layout, so there'll always be one frame delay. I'm hoping RN's new percentage width feature will help with this.

**Comment by jordanfloyd** [comment]
@vidhyalakshmirbt this should work:
    const {width} = Dimensions.get('window');
   const numberOfTabs = 2;
    renderHeader = (props) => (<TabBar {...props} tabStyle={{width: width/numberOfTabs}}/>);

**Comment by CharlesMangwa** [comment]
Closed #103
