### ISSUE TITLE
Can't perform a React state update when adding a second scene to SceneMap

### ISSUE THREAD

**Issue by zaarheed** [react-native-community/react-native-tab-view#1034]
### Current behaviour

I get a warning `Can't perform a React state update...` when adding a second scene to `SceneMap`. If I only have one property in the `SceneMap`, the error doesn't appear. I have reduced my components down to `<Text>`s and the warning still appears.

### Expected behaviour

Not to see the warning.

### Code sample

https://snack.expo.io/votgR9yPg

### Screenshots (if applicable)

<img width="402" alt="Screenshot 2020-06-16 at 23 42 42" src="https://user-images.githubusercontent.com/17533006/84835265-1f187400-b02b-11ea-8ffd-7e15e56ea014.png">

### What have you tried

Replaced my original components with `<Text>`s hoping that would help me debug where the bug was. Did not expect to see the warning when i was only rendering a `<Text>` as the tab component.

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | ios simulator
| react-native                 | 0.62.0
| react-native-tab-view        | 2.14.4
| react-native-gesture-handler | 1.5.2
| react-native-reanimated      | 1.7.1
| node                         | 12.18.0 (Mac)
| npm or yarn                  | npm

**Comment by zaarheed** [comment]
Updated both packages and the issue still exists

**Comment by satya164** [comment]
Don't create components in render.

**Comment by zaarheed** [comment]
I replaced my code with the example in the README, and I still get the warning.

```
import * as React from "react";
import { Dimensions, StyleSheet, Text, View } from "react-native";
import { SceneMap, TabView } from "react-native-tab-view";

const FirstRoute = () => <Text>One</Text>;

const SecondRoute = () => <Text>Two</Text>;

const initialLayout = { width: Dimensions.get("window").width };

export default function Tabs() {
  const [index, setIndex] = React.useState(0);
  const [routes] = React.useState([
    { key: "first", title: "First" },
    { key: "second", title: "Second" }
  ]);

  const renderScene = SceneMap({
    first: FirstRoute,
    second: SecondRoute
  });

  return (
    <TabView
      navigationState={{ index, routes }}
      renderScene={renderScene}
      onIndexChange={setIndex}
      initialLayout={initialLayout}
    />
  );
}
```

@satya164 any other ideas of what might be causing it?

**Comment by yicru** [comment]
Same here.

**Comment by heyoppa-admin** [comment]
Same issue

**Comment by denmilos** [comment]
Same here.

**Comment by lokomass** [comment]
Same issue
