### ISSUE TITLE
When I wrap it inside a ScrollVIew, it can not adjust the height automatically

### ISSUE THREAD

**Issue by changyu2hao** [react-native-community/react-native-tab-view#1036]
###  Code sample
      <ScrollView>
        <Text
            style={{
              fontSize: fontScale * hp(hStr(16)),
              marginHorizontal: wp(wStr(16)),
              marginVertical: hp(hStr(4))
            }}
          >
            Hello World! 
          </Text>
            <TutorDetailTabView user={user} />(This is a component of the tab)
        </ScrollView>
For Syntax Highlighting check this [link](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

My version:
react-native-tab-view: ^2.7.0

**Comment by kevinmcalear** [comment]
I have the exact same issue. Here are the versions I'm using:
```
"react-native-tab-view": "^2.14.4"
"react-native-gesture-handler": "^1.5.0"
"react-native-reanimated": "^1.4.0"
```

**Comment by Miluaaa** [comment]
+1

**Comment by changyu2hao** [comment]
> I have the exact same issue.
> 
> Here are the versions I'm using:
> 
> ```
> "react-native-tab-view": "^2.14.4"
> "react-native-gesture-handler": "^1.5.0"
> "react-native-reanimated": "^1.4.0"
> ```
> 
> After further investigation, this issue is happening because I have 3 tabs, one of them much longer than the other two. All three tabs are the same height so the two shorter tabs with less content still scroll the full height of the longest tab's content. Any way to stop this?
> 
> **EDIT:** It looks like this library isn't designed to be used like this: #1019
> 
> The UI we have requires things to be scrollable before getting to this tab section in the app. Any suggestions on how to do something like this would be ve

**Comment by changyu2hao** [comment]
I have exactly the same issue, please let me know when you get solutions

**Comment by xmflsct** [comment]
@changyu2hao or if the content rendered in the `renderTabBar` can catch scrolling, then I can avoid wrapping it inside s scrollview.
