### ISSUE TITLE
TabView Font color changing issue

### ISSUE THREAD

**Issue by keerthanarbt** [react-native-community/react-native-tab-view#104]
we tried using labelStyle for changing font color, background color and font type but we couldn't
can you help us with the same?
Thanks

**Comment by jkhedani** [comment]
@keerthanarbt If you need more control over labels in the `<TabBarTop>` element, simply construct a component template and pass it into the inherited prop `renderlabel`:

```
class Some Class {
  ...
  renderLabel = ({route, index}) => (
   <View style={{ backgroundColor: 'rgb(0,0,0)'}}>
       <Text style={{fontFamily: 'Arial', color}}>{route.title}</Text>
   </View>
  )
  renderHeader = (props) => <TabBarTop {...props} renderLabel={this.renderLabel} />
  render() {
    return(
      <TabViewAnimated renderHeader={this.renderHeader} />
    )
  }
}
```

Hope this helps!

**Comment by keerthanarbt** [comment]
Nope! the text is getting hidden and cannot able to see the label..

**Comment by jkhedani** [comment]
@keerthanarbt Do you mind sharing some of your code base so I can help you troubleshoot what's going on? I was able to completely revamp the styles of the tab to fit the needs of my project no problem. 
![screen shot 2017-01-19 at 11 14 33 am](https://cloud.githubusercontent.com/assets/1855878/22125643/9807e2ce-de38-11e6-8481-b093be077c84.png)

**Comment by Msspl-PrashenjeetRoy** [comment]
Does anyone have idea that how to change the current tab color.
`<TabBarTop 
        {...props} 
        style={styles.tabViewTop} 
        renderLabel={this._renderLabel(props)}
        indicatorStyle={styles.indicator}
        scrollEnabled={false}
        renderIcon={this._renderIcon}
        renderIndicator={this._renderIndicator}
        tabStyle={styles.tab}
        />;`

I want to change the current tab color.

**Comment by kristoforusrp** [comment]
We have problem with current tab color too, We want the background color tab is white. Is there a way to achieve this without changing the backgroundColor style of TabBar.js in the node_modules?

`tabBar: {
    backgroundColor: '#2196f3',
    elevation: 4,
    shadowColor: 'black',
    shadowOpacity: 0.1,
    shadowRadius: StyleSheet.hairlineWidth,
    shadowOffset: {
      height: StyleSheet.hairlineWidth,
    },
    zIndex: 1,
  },`

**Comment by satya164** [comment]
@kristoforusrp you can just pass a `style` prop to tab bar.
