### ISSUE TITLE
not able to put the tab inside a <Animated.View>

### ISSUE THREAD

**Issue by changyu2hao** [react-native-community/react-native-tab-view#1041]
I put the component inside <Animated.View>, it does not show there

**Comment by quangduz** [comment]
You need to wrap it buy a `View` like this:

```
<View style={{flex: 1, width: '100%', height: '100%', position: 'relative', display: 'flex', flexDirection: 'row'}}>
          <TabView
            navigationState={{ index, routes }}
            renderScene={renderScene}
            onIndexChange={setIndex}
            initialLayout={initialLayout}
          />
</View>
```

**Comment by changyu2hao** [comment]
> You need to wrap it by a `View` like this:
> 
> ```
> <View style={{flex: 1, width: '100%', height: '100%', position: 'relative', display: 'flex', flexDirection: 'row'}}>
>           <TabView
>             navigationState={{ index, routes }}
>             renderScene={renderScene}
>             onIndexChange={setIndex}
>             initialLayout={initialLayout}
>           />
> </View>
> ```

Thanks for the answer, but my scrollview in each tab does not scrollable inside the <Animated.View>, do you know why?
