### ISSUE TITLE
Swipe gesture triggering onPress (revisited)

### ISSUE THREAD

**Issue by Aryk** [react-native-community/react-native-tab-view#1045]
I'm still getting this issue that was reported in #550.

When I swipe between tabs, anything that responds to onPress is subject to getting "pressed" and I don't believe I have access to the controls to disable it.

I'm on 2.14.0 and curious if anyone is experiencing this issue or if I overlooked a setting on how to prevent touch events while swiping.

react-native-tab-view: 2.14.0
react-native-gesture-handler: ~1.6.0
react-native-reanimated: ~1.9.0

**Comment by Aryk** [comment]
I updated it

**Comment by Aryk** [comment]
never mind, using ScrollPager fixes the issue

**Comment by chazzaoui** [comment]
Hi! 

Currently experiencing the same issue.. How did you end up solving it?

I see you mentioning scrollpager. You mean the React-native-Pager-view?

**Comment by IsmetGlumcevic** [comment]
I have the same issue. Is this issue with scrollview/flatlist or tab view?

**Comment by vinayr** [comment]
Using `TouchableOpacity` from `react-native-gesture-handler` solves the issue for me.
https://github.com/ptomasroos/react-native-scrollable-tab-view/issues/1159#issuecomment-974039869
