### ISSUE TITLE
Improve TouchableItem press animation

### ISSUE THREAD

**Issue by fmatoss** [react-native-community/react-native-tab-view#11]
If you touch quickly on the tab item button, the ripple effect won't trigger, so what I suggest is that you put ```delayPressIn: 0``` in defaultProps to give a nice feedback effect when the button is pressed, no matter how fast you touch the screen.

I think this should be the default in React Native, maybe some people don't want this, so it would be nice if there's a way to pass props to TouchableItem through TabBarTop and TabBar.

Great component btw :+1:

**Comment by satya164** [comment]
@fmatoss Yeah, sounds reasonable. Up for PR? :)

**Comment by fmatoss** [comment]
Here: https://github.com/react-native-community/react-native-tab-view/pull/12
