### ISSUE TITLE
Change Tab Automatically on an Interval?

### ISSUE THREAD

**Issue by joncursi** [react-native-community/react-native-tab-view#110]
I'm designing an interface with multiple slides and I'd like to tab between them automatically, i.e. slide to the next after 4 seconds. Something like this:

![d64538ec0ef4d69d3d20649c1d6dacfe](https://cloud.githubusercontent.com/assets/4974609/22356997/4879c030-e403-11e6-9bc5-67ff655cca04.png)

Any ideas on how to achieve this cleanly? Maybe a new prop?

**Comment by satya164** [comment]
Just do a `setState` in a `setInterval`

```js
componentDidMount() {
  this._interval = setInterval(() =>  {
    if (this.state.index < this.state.routes.length - 1) {
      this.setState({ index: this.state.index + 1 )};
    } else {
      clearInterval(this._interval);
    }
  }, 1000);
}

componentWillUnmount() {
  clearInterval(this._interval);
}
```

**Comment by joncursi** [comment]
@satya164 the issue I'm having with the above proposed solution is that the user can't reclaim control of the movement of the tabs if there is an interval running on it. The only function available to us in the API is `onRequestChangeTab`, which gets called both from user interaction (swiping) and programmatic code (interval).

Is there a way I can distinguish from a change in tab due to a user swipe vs programmatic code? My goal is to move through the tabs on an interval UNTIL the user swipes somewhere, in which case the interval is cleared and the user is given full control.

**Comment by satya164** [comment]
`onRequestChangeTab` shouldn't be called if you already did a `setState`.
