### ISSUE TITLE
How are you implementing the navigation bar header?

### ISSUE THREAD

**Issue by GollyJer** [react-native-community/react-native-tab-view#114]
I'm learning, so bear with me. :-)

In all your Exponent examples there is a header bar with a screen title.
But, when I go to an [example](https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/TopBarTextExample.js) I don't see how the header (the section above the tabs) is created.

I'm looking to do this as recommended and need a little help.
Thanks!

**Comment by satya164** [comment]
It's here https://github.com/react-native-community/react-native-tab-view/blob/master/example/main.js#L162
