### ISSUE TITLE
keyboardShouldPersistTaps on TabViewPagerScroll (also @ExNav requires)

### ISSUE THREAD

**Issue by dguillamot** [react-native-community/react-native-tab-view#115]
Hi, 

We are using ExNav's SlidingTabNavigation which in turn uses react-native-tab-view internally. 

We need to specify the keyboardShouldPersistTaps='always' on the ScrollView inside the react-native-tab-view TabViewPagerScroll component.

This is so we can capture Taps/Touches after focusing a keyboard input field, without having to double-tap. 

At the moment, having a keyboard input field inside of react-native-tab-view (or ExNav's SlidingTabNavigation) appears to require 2 taps to trigger a button/component.

**Comment by satya164** [comment]
We already do this https://github.com/react-native-community/react-native-tab-view/blob/master/src/TabViewPagerScroll.js#L134

**Comment by satya164** [comment]
BTW exponent uses an older version which doesn't have this change.
