### ISSUE TITLE
show view only on state 1, when i slide to state 2, nothing happen

### ISSUE THREAD

**Issue by fadlifebriansyah** [react-native-community/react-native-tab-view#116]
Hi, I really dont know why, i already set the state like this ;

state = {
    index: 0,
    routes: [
      { key: '1', title: 'Create Invoice' },
      { key: '2', title: 'Invoice List' },
    ],
	loaded: true,
  };

when I run the code, view is opening the key '1' which is Create Invoice. (Screenshot provided)
![screenshot_9](https://cloud.githubusercontent.com/assets/18573470/22625250/9a79aa86-ebc3-11e6-9fcf-5fa8324eed20.png)

But the problem is, when I slide to key '2' which is Invoice List, it didnt showing anything, its blank, I already give up, maybe you can check 
![screenshot_10](https://cloud.githubusercontent.com/assets/18573470/22625258/c69eb07a-ebc3-11e6-9dbc-77d7161dc834.png)

for the code you can check here. (i convert to txt because not support)

[DummyPage.txt](https://github.com/react-native-community/react-native-tab-view/files/752859/DummyPage.txt)

**Comment by fadlifebriansyah** [comment]
this is my render scene function

_renderScene = ({ route }) => {
	var dumb = route.key
	ToastAndroid.show("" + dumb, ToastAndroid.SHORT);
	switch (dumb) {
    case '1':
      return (
		<View style={styles.container}>
			<View style={styles.container_all}>
				<View style={{width: 365, alignItems: 'center',}}>
							
						<View> 
							<TextInput
							  ref={component => this._textOrderNumber = component}
							  style={styles.text_input}
							  onChange={(order_number) => this.setState({order_number})}
							  onFocus={this.generateOrderNumber.bind(this)}
							  placeholder="Order Number (Touch to Auto-generate)"
							/>
						</View>
						
						<Text style={{color: 'white', fontSize: 4}}> Title Transaction </Text>
						
						<View> 
							<TextInput
							  style={styles.text_input}
							  onChangeText={(amount) => this.setState({amount})}
							  onSubmitEditing={this.search}
							  keyboardType="numeric"
							  placeholder="Amount"
							/>
						</View>
						
						<Text style={{color: 'white', fontSize: 4}}> Title Transaction </Text>
						
						<View> 
							<TextInput
							  style={styles.text_input}
							  onChangeText={(description) => this.setState({description})}
							  onSubmitEditing={this.search}
							  placeholder="Description"
							/>
						</View>
						
						<Text style={{color: 'white', fontSize: 4}}> Title Transaction </Text>
						
						<View> 
							<TextInput
							  ref={component => this._textInputDate = component}
							  style={styles.text_input}
							  onFocus={this.showDatePicker.bind(this, 'min', {date: this.state.minDate, minDate: new Date(),})}
							  onChangeText={this.showDatePicker.bind(this, 'min', {date: this.state.minDate, minDate: new Date(),})}
							  onChange={(date) => this.setState({date})}
							  onSubmitEditing={this.search}
							  placeholder="Expiry date"
							/>
						</View>
							
						<Text style={{color: 'white', fontSize: 4}}> Title Transaction </Text>
							
						<View style={{marginBottom: 55}}> 
							<TextInput
							  ref={component => this._textInputTime = component}
							  style={styles.text_input}
							  onFocus={this.showTimePicker.bind(this, 'simple_time', {})}
							  onChangeText={this.showTimePicker.bind(this, 'simple_time', {})}
							  onChange={(time) => this.setState({time})}
							  placeholder="Expiry time"
							/>
						</View>
							
						<View style={styles.btnSubmit}> 
							<TouchableHighlight style={styles.btnSubmit}
								onPress={this.gotoNext.bind(this)}>
								<Image source={require('./btnSubmit.png')} style={{width: 157, height: 50}} />
							</TouchableHighlight> 
						</View>
							
					</View>			
				</View>
			</View>
		);
    case '2':
      return (
				<View style={{width: 365, alignItems: 'center',}}>
							
						<View> 
							<TextInput
							  ref={component => this._textOrderNumber = component}
							  style={styles.text_input}
							  onChange={(order_number) => this.setState({order_number})}
							  onFocus={this.generateOrderNumber.bind(this)}
							  placeholder="Order Number (Touch to Auto-generate)"
							/>
						</View>
						
						<Text style={{color: 'white', fontSize: 4}}> Title Transaction </Text>
						
						<View> 
							<TextInput
							  style={styles.text_input}
							  onChangeText={(amount) => this.setState({amount})}
							  onSubmitEditing={this.search}
							  keyboardType="numeric"
							  placeholder="Amount"
							/>
						</View>
						
						<Text style={{color: 'white', fontSize: 4}}> Title Transaction </Text>
						
						<View> 
							<TextInput
							  style={styles.text_input}
							  onChangeText={(description) => this.setState({description})}
							  onSubmitEditing={this.search}
							  placeholder="Description"
							/>
						</View>
						
						<Text style={{color: 'white', fontSize: 4}}> Title Transaction </Text>
						
						<View> 
							<TextInput
							  ref={component => this._textInputDate = component}
							  style={styles.text_input}
							  onFocus={this.showDatePicker.bind(this, 'min', {date: this.state.minDate, minDate: new Date(),})}
							  onChangeText={this.showDatePicker.bind(this, 'min', {date: this.state.minDate, minDate: new Date(),})}
							  onChange={(date) => this.setState({date})}
							  onSubmitEditing={this.search}
							  placeholder="Expiry date"
							/>
						</View>
							
						<Text style={{color: 'white', fontSize: 4}}> Title Transaction </Text>
							
						<View style={{marginBottom: 55}}> 
							<TextInput
							  ref={component => this._textInputTime = component}
							  style={styles.text_input}
							  onFocus={this.showTimePicker.bind(this, 'simple_time', {})}
							  onChangeText={this.showTimePicker.bind(this, 'simple_time', {})}
							  onChange={(time) => this.setState({time})}
							  placeholder="Expiry time"
							/>
						</View>
							
						<View style={styles.btnSubmit}> 
							<TouchableHighlight style={styles.btnSubmit}
								onPress={this.gotoNext.bind(this)}>
								<Image source={require('./btnSubmit.png')} style={{width: 157, height: 50}} />
							</TouchableHighlight> 
						</View>
							
					</View>
				
				);
    default:
      return null;
    }
  };

**Comment by satya164** [comment]
Probably you need to put `flexGrow: 1` on the container view

**Comment by fadlifebriansyah** [comment]
which container view? in the key 1 or in the key 2?

**Comment by CharlesMangwa** [comment]
Hi @fadlifebriansyah! Thanks for the full code! I created an example on Sketch based on it and tried to reproduce your bug without success: https://sketch.expo.io/SJDmTH2sx.
You can edit this code and send us the new link if you are able to reproduce the bug!
