### ISSUE TITLE
IOS TabViewAnimated overflow: hidden in scene container

### ISSUE THREAD

**Issue by orenklein** [react-native-community/react-native-tab-view#117]
When overflow is needed between tabs, such as in Coverflow example (using translateX), we see that the neighbor tab Views are clipped.

Solution: changing to overflow:visible on https://github.com/react-native-community/react-native-tab-view/blob/master/src/TabViewAnimated.js#L100 or giving the option to set it by a prop.

Reproduce:
Run the Coverflow example on ios.

**Comment by satya164** [comment]
Now only scroll and viewpager based pagers will hide overflow. So coverflow should work fine.
