### ISSUE TITLE
Error while updating property 'transform'

### ISSUE THREAD

**Issue by dccarmo** [react-native-community/react-native-tab-view#118]
So I'm going through the process to update RN from 0.37 to 0.41, and I've run into an issue with react-native-tab-view (I'm on the latest 0.0.55):

![screen shot 2017-02-09 at 18 41 59](https://cloud.githubusercontent.com/assets/638474/22802327/86801556-eef7-11e6-89bd-10c37fb200e0.png)

Here's what we're doing:

```
    _renderIndicator = (props: Object) => { // props are actually passed in from react-native-tab-view/TabBar.js
        const { position, width } = props;
        const translateX = Animated.multiply(position, new Animated.Value(width));

        return (
            <Animated.View style={[this.b('tab-indicator'), { width, transform: [{ translateX }] }]}>
                <View style={this.b('tab-indicator__inner')}>
                    <Icon name="ArrowDown" fill={c('core primary')} width="13" height="13" />
                </View>
            </Animated.View>
        );
    }
```

and

```
            <TabBar
                {...this.props}
                style={this.b('tabs')}
                renderIndicator={this._renderIndicator}
                renderLabel={this._renderLabel()}
            />
```

The issue is happening with this line:

`<Animated.View style={[this.b('tab-indicator'), { width, transform: [{ translateX }] }]}>`

Looking at Android's adb log, I found this:

`02-09 18:10:10.448  6363  6363 E unknown:ViewManager: Caused by: com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type 'double', but had type 'null'`

It seems this is related to this issue https://github.com/facebook/react-native/issues/9841. It wasn't happening before (RN on 0.37 and react-native-tab-view on 0.0.40).

Any idea what can we do to fix this (or at least how to investigate?) I tried printing `translateX` but honestly couldn't find an issue with it.

**Comment by satya164** [comment]
Does downgrading tabview fix the issue? Do you have a sample project I can play with?

**Comment by dccarmo** [comment]
@satya164 it doesn't. I'm going to try and come up with a sample project and post here.

**Comment by cdimitroulas** [comment]
I think I'm having the same issue. Using RN v0.38

**Comment by CharlesMangwa** [comment]
Hi @dccarmo @cdimitroulas! Here is a working example with a custom indicator: https://sketch.expo.io/ry532xrnx. Let me know if it solves your problem! Btw: you can also edit the code and send it back to us if you can reproduce your bug.

**Comment by Hermanya** [comment]
it seems like TabViewAnimated requires something like
```
initialLayout={{
  height: 0,
  width: Dimensions.get('window').width,
}}
```

**Comment by rajscet** [comment]
I have fixed
https://stackoverflow.com/questions/59078949/react-native-app-getting-crashed-on-navigate/59967700#59967700
