### ISSUE TITLE
TabView inside a ScrollView.

### ISSUE THREAD

**Issue by nabeelvalapra** [react-native-community/react-native-tab-view#122]
I'm not able to see or scroll (when I try to give a fixed height at [here](https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/ScrollViewsExample.js#L124) in the [ListViewExample](https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/ListViewExample.js)) the content when using a TabView inside a ScrollView. How can I achive this feature. Is there any param I need to pass?

TopBarTextExample from [ScrollViewsExample](https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/ScrollViewsExample.js);
ListViewExample form [ListViewExample](https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/ListViewExample.js);
```
<ScrollView style={{flex:1}}>
    <ImageSlider images={[
        'http://placeimg.com/640/480/any',
        'http://placeimg.com/640/480/any',
        'http://placeimg.com/640/480/any'
    ]}/>
    <TopBarTextExample/>
</ScrollView>
```

How to achive TabView inside a ScrollView. In here, I need to fade away the ImageSlider content when scrolling the TopBarTextExample, then again scrolling means should scroll the contents of TopBarTextExample.

**Edit:**

Also, how do I make `<TabBar>` content of `<TopBarTextExample>` sticky. Right now after the workaround #105, both child gets scrolled. I do want both child to scroll, but the `<TopBar>` to be sticky.

**Comment by jbrodriguez** [comment]
@nabeelvalapra I guess it's happening to you on Android (not on iOS).

If that's the case, check #105 for a workaround

**Comment by nabeelvalapra** [comment]
@jbrodriguez Yea, the workaround worked. But any Idea on how to make`<TabBar>` content of `<TopBarTextExample>` static(floating).

**Comment by jbrodriguez** [comment]
@nabeelvalapra not really, I think I saw a similar question in one of the issues.

Check there or open another issue :)

**Comment by satya164** [comment]
It's just a React component. Figure out what you'd need to do if you wrote such a component and do the same thing.

**Comment by firashamila33** [comment]
same problem :anger: , could not be solved following many issues ..
I reproduced the problem [here](https://snack.expo.io/@plazma33/tab-bar-nested-in-scrollview-problem) ,
any solutions ??
