### ISSUE TITLE
react-native-tab-view with react-native-side-menu

### ISSUE THREAD

**Issue by rohithramachandran** [react-native-community/react-native-tab-view#124]
Hi, This is not an issue but need assistance on this ... I have a side menu from react-native-side-menu and  swipable tab from react-native-tab-view in same screen.Now i want to open up the side menu by swiping right if the swipe is starting from screen edge and switch the tabs if swipe is not from screen edge...How can i achieve this

**Comment by satya164** [comment]
I don't think it's possible yet unless you disable the swipe. Though probably we can add a prop on `TabViewPanPager` to configure to leave some space on edges.

**Comment by rohithramachandran** [comment]
@satya164  Thanks man...I cant find any documentation on `TabViewPanPager`  ..Can you please provide a sample ?

**Comment by satya164** [comment]
> I can't find any documentation on TabViewPanPager

It's there in the readme - https://github.com/react-native-community/react-native-tab-view#tabviewpagerpan-

> Can you please provide a sample ?

Sample for what?

**Comment by rohithramachandran** [comment]
Sample for leaving some space on edges ??

**Comment by CharlesMangwa** [comment]
Hi @rohithramachandran! <TabViewPagerPan /> is just a "simple" view, which means that you can add a simple prop to use any style you'd like, right here: https://github.com/react-native-community/react-native-tab-view/blob/master/src/TabViewPagerPan.js#L166.

**Comment by CharlesMangwa** [comment]
Closed #124.
