### ISSUE TITLE
Choppy transition when tabbed pages contain long lists 

### ISSUE THREAD

**Issue by jephtta** [react-native-community/react-native-tab-view#125]
Out of a 5 tab layout, 2 of the tabbed pages contain a listview. When the list grows really long, transitions when swiping or switching between tabs become really unresponsive. Scrolling through the listview itself works fluidly as expected.

**Comment by CharlesMangwa** [comment]
Hi @jephtta! Can you add a visual example of your issue please?

**Comment by j-rul** [comment]
@CharlesMangwa 
I traced the problem down to an issue with the version of react native I had just upgraded to. Could not determine what was going on beneath the scenes, but reverting to my old version of RN solved the issue. (Was a bit busy and forgot I had raised the issue. Sorry about that.)
Thanks.

**Comment by jephtta** [comment]
I traced the problem down to an issue with the version of react native I had just upgraded to. Could not determine what was going on beneath the scenes, but reverting to my old version of RN solved the issue. (Was a bit busy and forgot I had raised the issue. Sorry about that.)
Thanks
