### ISSUE TITLE
Restrict the tab Click when the process is incomplete in the initial tab

### ISSUE THREAD

**Issue by keerthanarbt** [react-native-community/react-native-tab-view#126]
Hi,
I am having a API call in TabView.. until and unless data loaded from API in first tab i should not allow the user to click or swipe to the consecutive tabs..
But i android it allows the user to click the next tab and it crashes when the data is not completely loaded..
Please help us with same

**Comment by satya164** [comment]
You can use `canJumpToTab` to disable a tab. https://github.com/react-native-community/react-native-tab-view#tabviewanimated-

Though you should show a spinner when data is being loaded. It's better than preventing to go to the tab.
