### ISSUE TITLE
Incorrect positioning of indicator when scrollEnabled and scrolled

### ISSUE THREAD

**Issue by jbrodriguez** [react-native-community/react-native-tab-view#127]
When you scroll the tabbar, the indicator positioning becomes erratical.

This is with a 
```
react-native init testtab
yarn add react-native-tab-view
# copy/paste example/src/TopBarTextExample.js into index.ios.js
```

RN: 0.41.2
react-native-tab-view: 0.0.55

Scrolling the items, then hitting the edge items works fine, but when you press an item in the middle, the repositioning of the indicator is all over the place.

It's best to describe it with a video

![tabview](https://cloud.githubusercontent.com/assets/1305422/22982965/a39cf4f8-f36e-11e6-954e-3c4366443e48.gif)

**Comment by satya164** [comment]
Should be fixed by https://github.com/react-native-community/react-native-tab-view/commit/9eae4cc00ffec888a03cae6c18131f908e1f3595
