### ISSUE TITLE
Rapidly switching tabs causes a crash on iOS

### ISSUE THREAD

**Issue by siderakis** [react-native-community/react-native-tab-view#1277]
### Current behavior

Switching tabs rapidly for a bunch of times causes the app to crash.

### Expected behavior

App doesn't crash

### Reproduction

existing sample app 

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Environment

    "react-native-tab-view": "^3.1.1",
    "react-native": "0.64.2",

**Comment by ashlyWeiting** [comment]
I have the same issue with react-native 0.65.1

**Comment by brianwachira** [comment]
> 2.16.0

I decided to downgrade and it now works well. 
Let me see if I will decide to use apply react-native pager-view patch
