### ISSUE TITLE
Is it possible to create a transparent tabbar?

### ISSUE THREAD

**Issue by j-rul** [react-native-community/react-native-tab-view#128]
I'm using the code here as an example: https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/TopBarIconExample.js, except I'm creating a bottom tab bar instead. I have tried setting a transparent background color on both the Tabbar component, and TabViewAnimated component. Solid colors work, but the tabbar still has a solid white background when I set to transparent. How do I do this. Thanks.

**Comment by satya164** [comment]
Have you tried setting the `position: 'absolute'` in `tabStyle`? It should work.

**Comment by j-rul** [comment]
Thanks man.
Using these styles

      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
It works!!
