### ISSUE TITLE
Tutorial on adding tabs dynamically

### ISSUE THREAD

**Issue by spezzino** [react-native-community/react-native-tab-view#130]
Is there a way to load tabs dynamically?
For example, I call a service and then populate the routes array with every tab I want to show.

**Comment by satya164** [comment]
@spezzino I've never tried that, but it should be possible by just updating the `routes` array in the state. if it doesn't work properly happy to investigate why and fix it. though what I had done in a previous app was just show a loading spinner without the tabview and then when I get the list, show the tabview with the new set of tabs.

**Comment by spezzino** [comment]
It worked.

In case anyone needs an example, I'll do a PR in a moment to your `example` project

**Comment by satya164** [comment]
@spezzino sounds good

**Comment by CharlesMangwa** [comment]
Problem seems to have been solved here, closing 👍

**Comment by brendandestefano** [comment]
@spezzino did this tutorial ever happen? looking for dynamic tabs at the moment

**Comment by lcardosozago** [comment]
an example would be nice

**Comment by pratikkarad** [comment]
@satya164 have you uploaded loading dynamic tab example?
@brendandestefano did you find any solution on dynamic tabs thing?
@spezzino after executing it's giving me an error, if you can provide any working example on expo, that would be very great
