### ISSUE TITLE
Android APP Crashes 

### ISSUE THREAD

**Issue by keerthanarbt** [react-native-community/react-native-tab-view#133]
Hi,
when the data is loading from API in one tab which is in progress mean while the user trying swiping on to the next tab crashes the app..when the data is not completely loaded from the API.
How to enable the swipe only when the data is completely loaded in one tab and make the user to swipe to the consecutive tabs.please help us

**Comment by satya164** [comment]
Do you have a stack trace for the crash report? I can't think of a reason this will happen.

You can do `swipeEnabled={false}` when you don't want to enable swipe. Check the README.

**Comment by CharlesMangwa** [comment]
Closed #133.
