### ISSUE TITLE
Add padding to TabBar indicatorContainer

### ISSUE THREAD

**Issue by jesouhaite08** [react-native-community/react-native-tab-view#134]
I'd like to add padding to the indicatorContainer, in order to get the following look:

<img width="400" alt="screen shot 2017-02-20 at 8 00 45 am" src="https://cloud.githubusercontent.com/assets/7729839/23126044/eb87a5c4-f742-11e6-82c0-dba6768e9cbd.png">

Is this possible? I don't see any props on the TabBar indicatorContainer, and it is currently positioned absolute to the bottom.

**Comment by CharlesMangwa** [comment]
Hi @jesouhaite08! This is possible, you just have to pass your style (`bottom: 5` for instance) to `<TabBar />` through the `indicatorStyle` prop. I created a simple example on Sketch if it may help: https://sketch.expo.io/rk-X-B3ie.

**Comment by CharlesMangwa** [comment]
Closed #134.
