### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by jbrodriguez** [react-native-community/react-native-tab-view#135]
Hi @satya164, what's the license for this library ?

I'm assuming MIT, please advise otherwise.

**Comment by joshfriend** [comment]
`package.json` does specify MIT. However, it would be a good idea to specify the license more explicitly as the automatic license granted by agreeing to the GitHub ToS basically only allows you to view the code, not do anything useful with it:

> If you set your pages and repositories to be viewed publicly, you grant each User of GitHub a nonexclusive, worldwide license to access your Content through the GitHub Service, and to use, display and perform your Content, and to reproduce your Content solely on GitHub as permitted through GitHub's functionality. You may grant further rights if you adopt a license.

 https://help.github.com/articles/github-terms-of-service/#5-license-grant-to-other-users

**Comment by jbrodriguez** [comment]
Thanks @joshfriend, I hadn't noticed the package.json license bit.

**Comment by CharlesMangwa** [comment]
Thanks @joshfriend!

**Comment by CharlesMangwa** [comment]
Closed #135.
