### ISSUE TITLE
Will it handle 300+ slides without a lag in a Coverflow "style"

### ISSUE THREAD

**Issue by grundmanise** [react-native-community/react-native-tab-view#136]
Hi, thanks for such a great component 👍 

I saw your blog post on medium and there was [this image](https://cdn-images-1.medium.com/max/600/1*F3nHDERcZyMPLD_fVV7PaQ.gif). This is just what I need 😃
I am wondering will it handle 300+ slides without a lag? I saw your "Optimize large number of routes" part in Readme will it be sufficient for this task?

Thanks!

**Comment by satya164** [comment]
> I saw your "Optimize large number of routes" part in Readme will it be sufficient for this task?

It always depends on how complex your slides are. You can try it and let me know.

**Comment by CharlesMangwa** [comment]
Closed #136.
