### ISSUE TITLE
Fix the difference in height from a tab to another

### ISSUE THREAD

**Issue by moerabaya** [react-native-community/react-native-tab-view#137]
The height stays the same as the longest tab view, it's not updated when switching from one to another. 

Thank you.

**Comment by CharlesMangwa** [comment]
Hi @moerabaya! Can you provide any visual example please :) ?

**Comment by satya164** [comment]
This is a non-goal for this project. If you need this in your app, you can add `onLayout` to your scene and animate the height when active route changes.

**Comment by eduardojunio** [comment]
@satya164 could you make a simple example please?

**Comment by dinesh547** [comment]
@satya164 can you please share some code how to handle height changes ?
