### ISSUE TITLE
Indicator width not rendered properly when the number of tabs are more

### ISSUE THREAD

**Issue by rahulmishra-goibibo** [react-native-community/react-native-tab-view#139]
<img width="374" alt="screen shot 2017-02-22 at 2 41 22 pm" src="https://cloud.githubusercontent.com/assets/20772089/23204626/5857f930-f90d-11e6-94eb-3d83e9eb8282.png">

Hi

Thanks for the great view. However i ran into an issue when i had to increase to my tab count to 5. When the tab count is till say 3, the indicator(underline below the tab's text) works fine. But when the number of tabs are increased it still renders the width of the indicator equal to the width of the screen/number of tabs and not exactly covering the text of the tab header. Is there any props that can be passed for this functionality?

**Comment by satya164** [comment]
Do you have `scrollEnabled` on tab bar? And have you set `width` in `tabStyle`?

**Comment by rahulmishra-goibibo** [comment]
oops my mistake. Missed the scrollenabled on the tab bar. Thanks for your quick reply
