### ISSUE TITLE
Animated Views don't work properly when using the library RN 0.40

### ISSUE THREAD

**Issue by moerabaya** [react-native-community/react-native-tab-view#142]
I'm suffering from frames drops when using any type of animated views with this library, very slow animations and glitches.

Thank you.

**Comment by satya164** [comment]
I don't see how this library can cause any glitches or slow animations.

**Comment by moerabaya** [comment]
@satya164 This shouldn't be closed, it's not solved yet. the library suffers from lack of performance and high ram usage!!!
