### ISSUE TITLE
Interactive TopBar

### ISSUE THREAD

**Issue by navratill** [react-native-community/react-native-tab-view#148]
Hi, 

is there way to create something like this? 

https://www.androidpolice.com/wp-content/uploads/2016/06/nexus2cee_Modern_Android.gif

It is default behaviour of swipable bars in Android. Thanks

**Comment by CharlesMangwa** [comment]
Hi @navratill! Yes it's possible! Considering that `< TabViewAnimated  />`'s `renderHeader` prop use by default `<TabBar />` which accepts a style prop: you can use the Animated library to decrease the bar height on scroll for instance. 

Long story short: if you want this in your app, you just have to get your hands dirty with some animations :)

**Comment by CharlesMangwa** [comment]
Closed #148.

**Comment by escobar5** [comment]
Hi @CharlesMangwa, I'm trying to do the same, do you know how can I listen to the scroll to decrease the bar height?

**Comment by navratill** [comment]
@escobar5 I think that @CharlesMangwa meant to listen on ScrollView/ListView and send onScroll delta by callback (or another way) into TabView props. After renderHeader will be called and you should react on this onScroll delta there.

**Comment by escobar5** [comment]
@navratill thanks, it's clearer now. Did you manage to do it?

**Comment by escobar5** [comment]
@navratill  ok, let me know if you get somewhere, I'll let you know as well 😉
