### ISSUE TITLE
How to change accent, primary an primaryDark color in the tabs?

### ISSUE THREAD

**Issue by csacanam** [react-native-community/react-native-tab-view#149]

**Comment by CharlesMangwa** [comment]
You can find a working example [here](https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/TopBarTextExample.js) and try it live right [there](https://expo.io/@rncommunity/react-native-tab-view-demos) :)

**Comment by CharlesMangwa** [comment]
Closed #149.
