### ISSUE TITLE
Customize or extend Route type in TabViewTypeDefinitions

### ISSUE THREAD

**Issue by Kudo** [react-native-community/react-native-tab-view#151]
Hi,
react-native-tab-view is well written with flow internally.
However, it is not easy for react-native-tab-view's user to leverage with flow.

My use case is to fill more information to route.
Such as adding icon definitions 
```es6
      this.state = {
        index: 0,
        routes: [
          { key: '1', icon: 'foo' },
          { key: '2', icon: 'bar' },
        ],
      };
```
The code is pretty much like the one in https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/TopBarIconExample.js#L36-L39

Here are type definitions in my component:
```
  type MyRoute = {
    key: string,
    icon: string,
  };

  type State = {
    index: number,
    routes: Array<MyRoute>,
  };
```

And flow will raise warnings like that
```
src/components/foo.js:96
 96:       <TabViewAnimated
           ^ React element `TabViewAnimated`
 15:   routes: Array<Route>;
                     ^^^^^ property `testID`. Property not found in. See: node_modules/react-native-tab-view/src/TabViewTypeDefinitions.js:15
 34:   routes: Array<MyRoute>,
                     ^^^^^^^ object type

src/components/foo.js:96
 96:       <TabViewAnimated
           ^ React element `TabViewAnimated`
 15:   routes: Array<Route>;
                     ^^^^^ property `title`. Property not found in. See: node_modules/react-native-tab-view/src/TabViewTypeDefinitions.js:15
 34:   routes: Array<MyRoute>,
                     ^^^^^^^ object type

src/components/foo.js:96
 96:       <TabViewAnimated
           ^ React element `TabViewAnimated`
 34:   routes: Array<MyRoute>,
                     ^^^^^^^ property `icon`. Property not found in
 15:   routes: Array<Route>;
                     ^^^^^ object type. See: node_modules/react-native-tab-view/src/TabViewTypeDefinitions.js:15
```

I am new to flow and currently have no idea to handle this.
But just to workaround the Route as `Object` type.
Do you have any suggestions for my case?

**Comment by CharlesMangwa** [comment]
Hi @Kudo! About your state typing, you can directly use something like: 

```
type State = {
  index: number,
  routes: Array<{
    key: string,
    icon: string,
  }>,
}
```

How do use your type btw? It sounds like you have something going wrong with the props you passed to `TabViewAnimated`

**Comment by satya164** [comment]
Flow is a bit tricky and I don't have a solution yet. I'll try to come up with something when I get some time.

**Comment by Kudo** [comment]
@CharlesMangwa The code snippet you shown has error in flow as well. I think the problem is the type conflict between react-native-tab-view internal and caller, i.e. cannot extend or override react-native-tab-view's type definitions.

@satya164 Thanks and take your time. It's just a nice to have improvement and a chance for me to learn more about flow.

**Comment by satya164** [comment]
I just opened a new PR with this ability https://github.com/react-native-community/react-native-tab-view/pull/215

Will appreciate if you take a look.

**Comment by satya164** [comment]
Closing this since the PR is merged to master now. Please open a new issue if you still face problems with Flow.

**Comment by Kudo** [comment]
Thank you @satya164. The change looks great and cool to use flow generic type.
Learn a lot from your code, thanks.
