### ISSUE TITLE
Tabbar width automatically fix the title inside?

### ISSUE THREAD

**Issue by baolamsentifi** [react-native-community/react-native-tab-view#157]
Hi, i'm looking for a feature that the Tabbar items width will be fixed text inside. I see there is an prop named 'tabWidth'. But seem it not working. Thank for you response.

**Comment by satya164** [comment]
Pass `tabStyle={{ width: 80 }}`

**Comment by baolamsentifi** [comment]
Hi @satya164. Could we set width for every single tab?

**Comment by juergengunz** [comment]
@baolamsentifi +1

**Comment by caioavila-arvore** [comment]
How I can use variable width for variables contents?

**Comment by riryjs** [comment]
any update about this? Could we set width for every single tab?

**Comment by Meycon** [comment]
?
