### ISSUE TITLE
Can anyone help on this issue?

### ISSUE THREAD

**Issue by BipinBhandari** [react-native-community/react-native-tab-view#16]
![screen shot 2016-08-19 at 8 43 06 pm](https://cloud.githubusercontent.com/assets/5967448/17814041/a56eb89c-664d-11e6-9cd9-73b613bd10b3.png)

**Comment by BipinBhandari** [comment]
solved this issue `npm install --save react-addons-shallow-compare`

**Comment by chirag04** [comment]
`react-addons-shallow-compare` is a peerDep. @satya164 should it be dep?

**Comment by satya164** [comment]
@chirag04 I prefer it to be a `peerDep` so that the version of `react` and `react-addons-shallow-compare` stay in sync. I should document it.
