### ISSUE TITLE
First tab is mounted twice

### ISSUE THREAD

**Issue by br4nnigan** [react-native-community/react-native-tab-view#160]
it's mounted twice, but gets unmounted immediately. You can easily reproduce.

tested with 
version 0.0.56 + react-native 0.39.2 and 0.40.0, iOS simulator

**Comment by dondragon2** [comment]
same issue here

**Comment by dondragon2** [comment]
@satya164 I have upgrade to version 0.0.57 but I am still getting the issue where `componentWillMount` and `componentWillReceiveProps` for the first tab is called multiple times. This tells me that the component is being called many times.

```
9:39:34 AM will mount Tab 1
9:39:34 AM Handling URL: exp://localhost:19000
9:39:34 AM will mount Tab 1
9:39:34 AM will mount Tab 1
9:39:34 AM Handling URL: exp://localhost:19000
9:39:34 AM will mount Tab 1
9:39:37 AM componentWillMount Tab 2
9:39:37 AM componentWillReceiveProps  Tab 1
9:39:37 AM componentWillReceiveProps Tab 1
9:39:38 AM Navigation Dispatch:
```

**Comment by satya164** [comment]
Can you post code?

**Comment by dondragon2** [comment]
I have uploaded the Gist files below.
[gist](https://gist.github.com/dondragon2/796ea8dab90045e5d5f2253b7e759859)

**Comment by satya164** [comment]
You are using `react-navigation`. Did you update the `react-native-tab-view` dependency manually?

**Comment by dondragon2** [comment]
yes

```
✗ yarn add react-native-tab-view
yarn add v0.21.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ react-native-tab-view@0.0.57
✨  Done in 25.54s.
```

**Comment by satya164** [comment]
This doesn't ensure that `react-navigation` will use the new version. Can you verify that there's no other copy of `react-native-tab-view` under your `node_modules`?

**Comment by dondragon2** [comment]
it seems `react-navigation` has an older version in its `node_modules`

**Comment by satya164** [comment]
@dondragon2 you can try replacing the folder until my PR gets merged.

**Comment by dondragon2** [comment]
thanks. I did that and it seem to have worked.

**Comment by mukesh-rbsl** [comment]
I'M facing same first tab mounted twice as i am using
"react-native": "^0.57.4"
"react-native-tab-view": "^1.3.1"
"react-navigation": "^3.0.0"
 Platform: android
Does this issue still exsit with RN 0.57.4 ?
