### ISSUE TITLE
How to prevent change tab by gesture when using TabViewAnimated

### ISSUE THREAD

**Issue by musicode** [react-native-community/react-native-tab-view#162]

**Comment by CharlesMangwa** [comment]
Hi @musicode! This use case is explained into [NoAnimationExample.js](https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/NoAnimationExample.js). You can [see the result directly on your phone](https://expo.io/@rncommunity/react-native-tab-view-demos).

**Comment by CharlesMangwa** [comment]
Closing #162.
