### ISSUE TITLE
Using a custom top toolbar only shows toolbar

### ISSUE THREAD

**Issue by yinoneliraz** [react-native-community/react-native-tab-view#164]
When using my own toolbar in renderHeader function, the result is only the toolbar without the tabs.
Height does not affect it.
```
_renderHeader = (props) => {
  return <TopToolbar text="Hi" navigator={this.props.navigator}/>;
};
```
Where TopToolbar is my component.

**Comment by CharlesMangwa** [comment]
HI @yinoneliraz! Can you provide a visual example of your issue please :) ?
