### ISSUE TITLE
focused state doesn't change 

### ISSUE THREAD

**Issue by iremlopsum** [react-native-community/react-native-tab-view#165]
I'm rendering my scenes in a dedicated component for it and I want to know which tab is currently in view, but the focused state always stays the same and does not get update while navigating between tabs.

And to add to that, how to pass on props to the scene without rerendering the scenes?

Current code

```
<TabViewAnimated
  ref="animatedView"
  navigationState={this.state.routes}
  style={styles.container}
  renderScene={this.renderScene}
  onRequestChangeTab={this.handleChangeTab}
  onChangePosition={this.onChangePosition}
/>

renderScene(route) {
  return <StackNavigator route={route} />
}
```

And want to do something like

```
<TabViewAnimated
  {..other stuff}
  renderScene={(route) => this.renderScene(route, this.state.inTransition)}
  {..other stuff}
/>

renderScene(route, inTransition) {
  return <StackNavigator route={route} inTransition />
}
```

Any solution for this?

**Comment by CharlesMangwa** [comment]
Hi @iremlopsum! You can use `onRequestChangeTab` prop to detect the current tab. About your second question: you can handle this with React's `shouldComponentUpdate()` for instance.
