### ISSUE TITLE
how to get text on "navigation bar" and back arrow?

### ISSUE THREAD

**Issue by aracchi** [react-native-community/react-native-tab-view#169]
Hi, I noticed you have the 'Text only Top Bar' and a back arrow in your demo gif. May I know how to get it? Do I merge it with NavigationBar or can you point me to the right direction? I am lost.

**Comment by CharlesMangwa** [comment]
Hi @aracchi! Here is the [`TopBarTextExample` example code](https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/TopBarTextExample.js), that you can try [directly on your phone with Expo](https://expo.io/@rncommunity/react-native-tab-view-demos)., it's the `Text only top bar` example. I hope it will help you understand how to solve you problem!
Regarding the back button, it's handle by the router you're using, not `react-native-tab-view` :)
