### ISSUE TITLE
On state change not re-render

### ISSUE THREAD

**Issue by uc-asa** [react-native-community/react-native-tab-view#17]
Hi Team,

If state change then It'll not render again, I need to re render content when state change.
Plz suggest me

**Comment by satya164** [comment]
Hey! It'll only re-render if the `navigationState` changes. If you want it to re-render on any other change, add that prop to the `navigationState` object.

**Comment by uc-asa** [comment]
routes         : [ ... ], generate error here

**Comment by satya164** [comment]
@uc-asa that's just an example. Can you post your code here so I can say what changes you need to do?

**Comment by satya164** [comment]
Also added this to the readme which should give you a better idea, https://github.com/react-native-community/react-native-tab-view#caveats

**Comment by uc-asa** [comment]
I have created a function for search and created using tab view
showarr () {
		var s = [];
		if(!this.state.isLoading && this.arr.length > 0) {
			for(let i in this.arr){
				try {
					if(this.state.text != '') {
						if(((this.arr[i]['snippet']).toLowerCase()).indexOf((this.state.text).toLowerCase()) > -1 || ((this.arr[i]['content']).toLowerCase()).indexOf((this.state.text).toLowerCase()) > -1) {
							s.push(
								<View key={i} style={[styles.pmd,styles.mtMd,styles.marginWidth]}>
				
									<Text style={styles.toc_content} >{this.arr[i]['content']}</Text>
								</View>
							)
						}
					}
					else {
						s.push(
							<View key={i} style={[styles.pmd,styles.mtMd,styles.marginWidth]}>
								<Text style={styles.toc_content} >{this.arr[i]['content']}</Text>
							</View>
						)
					}
				}
				catch(err) {
					console.log("Some error occur" + err);
				}
			}
		}
		return s;
	}

//
_renderScene = ({ route }) => {
		switch (route.key) {
			case '1':
				return <ScrollView>{this.showarr()}</ScrollView>;
			default:
				return null;
		}
	};

render() {
		return (
			<View style={[styles.fullHeight]}>
				<Navbar title={this.props.title} style={styles.navbar} rightButton={false}/>
			 	<TabViewAnimated
			         style={styles1.container}
			         navigationState={this.state.navigation}
			         renderScene={this._renderPage}
			         renderHeader={this._renderHeader}
			         onRequestChangeTab={this._handleChangeTab}
				 navigationState={this.state}
		       />
			</View>
		);
	}

**Comment by satya164** [comment]
@uc-asa You can just put the items in `this.state.navigation` to `this.state` directly, e.g. - 

What you have,

```js
{
    text: '',
    isLoading: false,
    navigation: {
       index: 0,
       routes: [],
    },
}
```

Change it to,

```js
{
    text: '',
    isLoading: false,
    index: 0,
    routes: [],
}
```

And the in your render, where you're doing `navigationState={this.state.navigation}`, just do `navigationState={this.state}` instead.

**Comment by uc-asa** [comment]
I have keep more variable in this.state so I have created 
this.state = {
			navigation: {
				index: 0,
				routes: [
				    { key: '1', title: 'Table of content' },
				],
				 text: '',
			}
}
and I updated using 
let navigation = this.state.navigation;
navigation['text'] = text;
this.setState({ navigation: navigation });

console.log(this.state.navigation) // It print value of text but unable to re-render

**Comment by satya164** [comment]
instead of that, do this,

```js
this.state = {
    index: 0,
    routes: [
        { key: '1', title: 'Table of content' },
    ],
    text: '',
}
```

Then, to update,

```js
this.setState({ text: text });
```

and instead of `navigationState={this.state.navigation}`, do `navigationState={this.state}`

**Comment by satya164** [comment]
The problem with your code is actually here,

```js
let navigation = this.state.navigation;
navigation['text'] = text;
this.setState({ navigation: navigation });
```

You're mutating the `navigation` object. You should do this instead,

```js
let navigation = this.state.navigation;
this.setState({
    navigation: { ...navigation, text },
});
```

I'd suggest you do the following instead,

instead of what you're doing, do this,

```js
this.state = {
    index: 0,
    routes: [
        { key: '1', title: 'Table of content' },
    ],
    text: '',
}
```

Then, to update,

```js
this.setState({ text: text });
```

and instead of `navigationState={this.state.navigation}`, do `navigationState={this.state}`

**Comment by satya164** [comment]
Lemme know if it worked or not.

**Comment by uc-asa** [comment]
Its not work but I have done by another way
Thanks

**Comment by Nicomalacho** [comment]
@uc-asa can you tell me how you did it ?

**Comment by ethanyuwang** [comment]
Having the same problem. 

My `TabView` has navigationState prop:

```
<TabView
          style={styles.editorContainer}
          navigationState={this.state}
          renderTabBar={this._renderTabBar}
          renderScene={SceneMap({
            text: this._renderText,
            paragraph: this._renderParagraph,
          })}
          onIndexChange={index => this.setState({ index })}
/> 
```

My `_renderText` method is as below:

```
  _renderText = () => {
    return (
      <ScrollView style={styles.container}>
        {this._renderTextButton()}
        {this._renderTextStyleButton()}
        {this._renderColorButton(TEXT_COLOR)}
        {this._renderColorButton(BACKGROUND_COLOR)}
        {this._renderTextClearFormatButton()}
      </ScrollView>
    )
  }
```

and inside `_renderTextStyleButton`,  I have a `Text` element that displays a string inside state:

```
<Text style={styles.text}>
            {this.state.currentTextStyleName}
</Text>
```

However, after `this.state.currentTextStyleName` has been updated to other value, the view still stays the same. What am I missing?

**Comment by satya164** [comment]
@ethanyuwang https://github.com/react-native-community/react-native-tab-view#scenemap
> All the scenes rendered with SceneMap are optimized using React.PureComponent and don't re-render when parent's props or states change. If you don't want this behaviour, or want to pass additional props to your scene components, use renderScene directly instead of using SceneMap.

**Comment by Shahzaib1999** [comment]
still no luck. I am using filter in my component but it does not rerender on updating the state. Please help
Thanks in advance.

**Comment by puneetkansal04** [comment]
@SanjanaTailor @satya164 @Shahzaib1999 did you get any solution to rerender a component on state change in it
