### ISSUE TITLE
TabBar styling is broken. Need fix.

### ISSUE THREAD

**Issue by jsartisan** [react-native-community/react-native-tab-view#170]
![issue](https://cloud.githubusercontent.com/assets/6636360/23909686/6bdf4fda-08fd-11e7-8bc1-e3f698a61600.gif)

Don't why this great plugin does have a good documentation on how to style the TabBar component.

**Comment by jsartisan** [comment]
![user profile](https://cloud.githubusercontent.com/assets/6636360/23909820/c44229d6-08fd-11e7-96fd-660335efe037.jpg)

This is what i really wanted . Any idea how to achieve it ?

Don't know how to style bottom border. It just disappear after animating. Any fix for this ?

**Comment by jsartisan** [comment]
@satya164 Any fix sir for this ? or any idea how do i achieve the desired styling  with your package ?

**Comment by CharlesMangwa** [comment]
Hi @jankalfus! It's a little bit difficult to help you out without seeing your code 😅

However, you have [this `TopBarTextExample` example in the doc](https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/TopBarTextExample.js) that achieve the same goal than what I see in your image. You can see the result [here with Expo](exp.host/@rncommunity/react-native-tab-view-demos), hope it will be helpful!

**Comment by CharlesMangwa** [comment]
Closed #170
