### ISSUE TITLE
Using List View within tab view. (question)

### ISSUE THREAD

**Issue by jasan-s** [react-native-community/react-native-tab-view#171]
Is there an example of using List view within this component? I wanted to render few hundred list items with avatars on each of the multiple tabs.  I am just starting out and looked at [react-native-scrollable-tab-view ](https://github.com/skv-headless/react-native-scrollable-tab-view) but it seems with the new verision of react-native 0.42 there is a significant lag at this moment.  So In my search I found this lib. Has anyone used listview within this component? Would very much love to hear your feedback. thanks.

**Comment by satya164** [comment]
You can use any type of view. Nothing specific with listview, though you might have to do `removeClippedSubviews={false}` due to an RN bug.

**Comment by jasan-s** [comment]
@satya164  i thought keeping removeClippedSubviews value to true improved performance. Why would in this case you would recommend.

**Comment by satya164** [comment]
I don't recommend it, but sometimes you'll face this bug https://github.com/facebook/react-native/issues/1831 and there's no other choice.

**Comment by yogi9999999** [comment]
I am using listview in both the tabs and onPress when I am pushing the page on <PushingPage> I am getting this error :
 this.props.navigator.push({id: 8,}); it giving me error "undefined is not object(evaluating 'this.props.navigator.push')"
