### ISSUE TITLE
How to configure tabs slide transition?

### ISSUE THREAD

**Issue by you-fail-me** [react-native-community/react-native-tab-view#173]
When I set new index to state of tabview (i.e. switch tabs programatically, from a button click) tabs switch too fast for me, I'd like to have a slower transition. Docs say there's `configureTransition` callback, but don't say how should it be written and how does that 'transition configuration' that it should return should look like. Could you please, pour some light on it and update the docs?

**Comment by CharlesMangwa** [comment]
Hi! You can use `configureTransition` as following:
```
  configureTransition={() => ({
    timing: Animated.spring,
    tension: 300,
    friction: 35,
  })}
```
If it can help you out, you also have[ `TransitionConfigurator`'s type with Flow](https://github.com/react-native-community/react-native-tab-view/blob/272cc3a555e665916024cc97ded5f80e5b567485/src/TabViewTransitionerTypes.js) and you can check out how the callback is used under the hood [right here](https://github.com/react-native-community/react-native-tab-view/blob/e37ffa9d4452194aaf3ab83555abe4ecde141f3a/src/TabViewTransitioner.js#L144-L153) :)

**Comment by Druux** [comment]
@CharlesMangwa does this still work as described? For me the `configureTransition` prop has no effect. It doesn't get executed at all.
