### ISSUE TITLE
Selecting an image in one of the scenes

### ISSUE THREAD

**Issue by nickkapoor** [react-native-community/react-native-tab-view#176]
1) Like the package.

2) Having some difficulty with understanding navigation.  In particular, consider the situation, there is a scenes (Scene 1) with an image (Image 1) , which a user selects.  I want to take them to another page (Scene 1.1), which shows the details on the image.  I do not want to create a tab for the details page (Scene 1.1).  How can I insert Scene 1.1 without creating another tab at initial load, render the scene 1.1. as part of Scene 1 but the component is switched in Scene 1 to the component for Scene 1.1.  

3) Additionally, consider the case I dynamically add a scene (Scene 1.1).  Now I want to go back to Scene 1 and select another image (Image 2).  This time I want to go back to Scene 1.1 but with the new props being provided to Scene 1.1 (with props of the second image).  I tried changing the state of loaded: false, and tried it with true also, but the Scene 1.1 never calls the componentDidMount.  Is there another method within a component that is called when Scene 1.1 is being navigated back to?

How can we address the above 2 use cases?  Many thanks.

**Comment by satya164** [comment]
This is only a tab navigation library. See http://reactnavigation.org/ for a library for navigation.

**Comment by nickkapoor** [comment]
Got it.  However, I was able to address #3 after getting the reference to the object.
