### ISSUE TITLE
how to go on second tab directly on button click 

### ISSUE THREAD

**Issue by prasann278** [react-native-community/react-native-tab-view#179]
i have two tabs in one view.  when i click on button it come on first tab but not coming on second tab directly 

how to go on second tab directly on button click 
please help me out in this '

**Comment by fufuninja** [comment]
just do this.setState({ index : 1 }) on button clicked.

**Comment by prasann278** [comment]
@fufuninja 
my button is on different page and tab view is in different page.

i have two tabs in one view. when i click on button it come on first tab but not coming on second tab directly

how to go on second tab directly on button click

**Comment by CharlesMangwa** [comment]
You just have to define your `state.index` at `1` so that RNTV will directly show your second tab. Here is a working example: https://sketch.expo.io/Hy1VqgSnl.
