### ISSUE TITLE
Pan responder not working before new props received since 0.0.25

### ISSUE THREAD

**Issue by ryankask** [react-native-community/react-native-tab-view#18]
It looks like in 22a95a887b13ddbee589e7c0e8bedb5bfa47f9b3 the underlying `TabPageView` component's `_panHandlers` are only set when props are received.

The result is that you can't change tabs by panning until new props are received. Once the props are updated, for example, by tapping a tab label in the header, you can then switch tabs via panning.

**Comment by satya164** [comment]
ouch! sorry for that. will fix this in a moment.

**Comment by ryankask** [comment]
No, problem! Thanks for such a high quality library.

Next I'll provide a PR instead...

**Comment by satya164** [comment]
@ryankask thanks for the bug report. I should've tested more thoroughly. a PR is always appreciated :)
