### ISSUE TITLE
Different Tab Width

### ISSUE THREAD

**Issue by juergengunz** [react-native-community/react-native-tab-view#181]
Is it possible to have for example 3 tabs and only one of the tab has a fixed width?

**Comment by CharlesMangwa** [comment]
Yes you can do this, you just have to add some style to your specific tab.

**Comment by juergengunz** [comment]
@CharlesMangwa  How? If i do <tabbar tabStyle={{ width: 80 }}, it effects all tabs?

**Comment by CharlesMangwa** [comment]
@juergengunz I mean that you can use RNTV `renderHeader` prop to pass your very own Tab bar. And there, you can display it as you want it to be!
