### ISSUE TITLE
[Request] Add bouncing

### ISSUE THREAD

**Issue by enstulen** [react-native-community/react-native-tab-view#182]
Is it possible to add bouncing of the indicator at the edge of the screen?

**Comment by CharlesMangwa** [comment]
If you need this particular effect in your app, you can use `<TabBar />`'s `renderIndicator` prop to pass you custom component. You'll just have to write it and handle the bounciness ([here is how it's defined in this library](https://github.com/react-native-community/react-native-tab-view/blob/master/src/TabBar.js#L193-L204)). Feel free to submit a PR, they are always welcome!

**Comment by CharlesMangwa** [comment]
Closing #182.
