### ISSUE TITLE
How to pass data between pages?

### ISSUE THREAD

**Issue by aracchi** [react-native-community/react-native-tab-view#183]
Hi what i have is listview in each tab, using toptabtextexample as a guide. upon clicking on a listview, i want to view "more info" on that selected item, e.g 
listview: HARRY POTTER
moreinfo: harry potter movie timings. 

passing over would be the "id" of the movie. Previously i have been using NAVIGATION to pass data. however, i am having problems integrating.. 

it will be great if you can guide me 👍

**Comment by CharlesMangwa** [comment]
Hi @aracchi! If I got it right: this is rather a routing related problem than a RNTV one?

**Comment by aracchi** [comment]
it is conflicting. so i am trying to integrate them together...

**Comment by aracchi** [comment]
@CharlesMangwa before i used RNTV, i have been using navigator. but it is causing me inconvenience so i am now switching to RNTV. However, i am trying to pass data with RNTV instead of navigator. But i am unsure of how i can do it. hope this clarifies..

**Comment by CharlesMangwa** [comment]
OK I'm seeing it more clearly now. RNTV isn't a routing library so be careful with what you want to do with it! However you can use the `renderScene` prop to handle which component should be displayed but that's not the best solution for your use case. You'd rather spent some time on your router library to see how you can make this work.

**Comment by aracchi** [comment]
Yes, in my TopBarTab.js _renderScene, i have :
```
case "ItemList":
        return <ItemList />
 case "Info":
        return <Info bus={route.data} />
```
In my ItemList.js
i have a list of json data and i am trying to use props to pass my bus object over to the Info.js

so previously i have something like
```
this.props.navigator.push({
key: 'Info'
data: bus})
```
Any idea how i can pass as props? I don't understand react native's document.

**Comment by AishwaryaSurana** [comment]
@aracchi How were you able to pass the props to different scene??

**Comment by junedomingo** [comment]
```
_renderScene({ route }) {
		switch (route.key) {
			case '1':
				return <Tab1 data={'hello'} />;
			case '2':
				return <Tab2 data={'world'} />;
			default:
				return null;
		}
	}
```
