### ISSUE TITLE
RTL is not supported!

### ISSUE THREAD

**Issue by moerabaya** [react-native-community/react-native-tab-view#184]
What i'm suffering from is that the tabs still functioning the same as the LTR after switching to RTL, I know what seems to be the issue because I have a custom indicator, but i'm not able to use negative values to translate them to the opposite.

Thank you so much.

![untitled](https://cloud.githubusercontent.com/assets/12199727/24356535/b80fb316-12fa-11e7-9a82-14c41bff94e9.gif)

**Comment by satya164** [comment]
Can you send a PR to fix this?

**Comment by moerabaya** [comment]
@satya164 I never send one, i'm not sure how to do that?

**Comment by yaronlevi** [comment]
This bug also affects react-navigation. The TabNavigator is not working:

https://github.com/react-community/react-navigation/issues/860

**Comment by yaronlevi** [comment]
Inside TabViewPagerScroll.js putting `flexDirection: 'row-reverse'` on the `<ScrollView />` fixes the problem partially. The tab's contents is shown but the order is reverse.

**Comment by dastoori** [comment]
#https://github.com/facebook/react-native/issues/11960

**Comment by dastoori** [comment]
@yaronlevi, look at my last comment here: https://github.com/facebook/react-native/issues/11960#issuecomment-292732636

@moerabaya, I sent a PR #194, until it merged, you can use one of these:
- `npm i -S https://github.com/dastoori/react-native-tab-view.git#rtl-support`
- `npm i -S https://github.com/dastoori/react-navigation.git#rtl-support`

**Comment by satya164** [comment]
Re-opening this since RTL is not yet supported in `TabViewPagerScroll`, hence unsupported on iOS.

**Comment by dastoori** [comment]
@satya164, iOS ScrollView has been fixed in ReactNative v0.43.2 (https://github.com/facebook/react-native/issues/11960#issuecomment-292732636)

**Comment by satya164** [comment]
Nice. I think we may still need to handle the scroll position etc.

**Comment by dastoori** [comment]
I checked this in version `0.0.59`, i used the examples in `examples` folder. These examples does not works properly:

- "1. Scrollbar top bar"

![scrollabletopbar](https://cloud.githubusercontent.com/assets/2003143/25232217/ca6c2e10-25ef-11e7-82ea-ba38419d9549.gif)

- "3. Bottom bar with indicator"

![bottombarwithindicator](https://cloud.githubusercontent.com/assets/2003143/25232216/ca6a6ac6-25ef-11e7-976b-4c9a8f33e2bc.gif)

Other examples are works fine:

![scrollviews](https://cloud.githubusercontent.com/assets/2003143/25232218/ca70f170-25ef-11e7-85e3-90af95c7c248.gif)

**Comment by satya164** [comment]
> 3. Bottom bar with indicator

This one uses a custom indicator, that's why. Should be easy to fix.

> "1. Scrollbar top bar"

Yeah, this one will be more involved

**Comment by 0xori** [comment]
Any updates on this one?

**Comment by satya164** [comment]
If you need this, pull requests are welcome.

**Comment by noambonnie** [comment]
@satya164 - I created a pull request to add support for RTL. I hope it can be accepted and merged.

Thank you.

**Comment by noambonnie** [comment]
Adding a link to the PR - not sure if 2 months is a reasonable time or not. I'm sure the team is busy...

https://github.com/react-native-community/react-native-tab-view/pull/556

**Comment by horodnicdragos** [comment]
Hey there @noambonnie. I've taken a look at your fix and I've tested it on both iOS and android. While this fixes the issue on android, it breaks iOS so I've just added a platform specific condition. Take a look at my fork:

https://github.com/horodnicdragos/react-native-tab-view

Not sure if this is the best approach on the long term but having this merged would be amazing. Do you want to update your PR or should I do one?

**Comment by noambonnie** [comment]
@horodnicdragos what's broken on iOS? Does your code (ignoring iOS for those calculation) work fine on iOS RTL?

If broken on iOS we'll need to fix it there too. If your fix works on both platforms in RTL (and LTR...) then fine

**Comment by horodnicdragos** [comment]
Yes, for some reason the calculations are not required on iOS. I'll make the PR and hope for the best.

**Comment by noambonnie** [comment]
@horodnicdragos please note that your PR failed the linter requirements. Follow the test procedures at the bottom of the project page (under "Contributing"). Otherwise it won't even be considered.

**Comment by horodnicdragos** [comment]
@noambonnie Done!

**Comment by gabimoncha** [comment]
@satya164 can you check #602 and merge it?

**Comment by noambonnie** [comment]
I hope it gets merged soon...

**Comment by 0xori** [comment]
is it going to be merged soon?

**Comment by satya164** [comment]
it is already merged and released. but the PR is Android only.

**Comment by horodnicdragos** [comment]
@0xori It is working just fine on iOS for me. Did you encounter any RTL issues?

**Comment by MahmoudAliIbrahim** [comment]
still having the same issue on android , for ios it is fixed using this #675

**Comment by FadiAboMsalam** [comment]
any updates on this ?

**Comment by satya164** [comment]
@FadiAboMsalam It's marked as "help wanted". PR welcome.

**Comment by Abdo-zayed** [comment]
in TabBar.js
modify this function
_this.resetScroll = function (value) {
const tabLength=this.props.navigationState.routes.length-1;

        const target=I18nManager.isRTL?tabLength-value:value;
        console.log(tabLength+' '+target)
        if (_this.props.scrollEnabled) {
            _this.scrollView && _this.scrollView.scrollTo({
                x: _this.getScrollAmount(_this.props, _this.state,target),
                animated: true
            });
        }
    };

**Comment by hosseinmd** [comment]
this issue doesn't fix, please don't close

**Comment by satya164** [comment]
@hosseinmd please open a new issue with a runnable repro as mentioned in the issue template.

**Comment by hosseinmd** [comment]
I resolve this, that is my fault

**Comment by matifriaz** [comment]
I am having the same issue on IOS. Did anyone manage to solve it?

**Comment by YogiHa** [comment]
+1

**Comment by saravanakumargn** [comment]
+1

**Comment by syedamirali14** [comment]
this issue is still happening

**Comment by syedamirali14** [comment]
i have fixed this issue on iOS will make a new PR
