### ISSUE TITLE
Disable Scroll

### ISSUE THREAD

**Issue by leoaccorsi** [react-native-community/react-native-tab-view#185]
How can i disable scroll? I want to change tabs only when i click on it

**Comment by satya164** [comment]
https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/NoAnimationExample.js

**Comment by jasan-s** [comment]
add this to 
```
<TabViewAnimated 
 animationEnabled={false}
 swipeEnabled={false}/>
```
