### ISSUE TITLE
Scrollable tab bar

### ISSUE THREAD

**Issue by elie222** [react-native-community/react-native-tab-view#186]
Does this package handle cases where there are 5+ items in the top tab bar?

I have a sketch with an example where I tried to make the tabbar scrollable when it has many items although that didn't exactly help:
https://sketch.expo.io/rkc9NCUnx

This is the behaviour I'd like to emulate:
<img width="375" alt="screen shot 2017-03-27 at 21 11 23" src="https://cloud.githubusercontent.com/assets/3090527/24370963/f4785a7e-1331-11e7-867f-2f45cdec620f.png">

**Comment by satya164** [comment]
https://github.com/react-native-community/react-native-tab-view#tabbar-
