### ISSUE TITLE
is there any method to change the tab color text and indicator color?

### ISSUE THREAD

**Issue by yogi9999999** [react-native-community/react-native-tab-view#187]

**Comment by CharlesMangwa** [comment]
https://github.com/react-native-community/react-native-tab-view#tabbar

**Comment by yogi9999999** [comment]
I have read the documents but couldn't find possible solution can you tell where i miss?

**Comment by brunocavallarigois** [comment]
I had the same problem, to change the indicator color use the prop "indicatorStyle". Example:
<TabBar {...props}
        indicatorStyle={{ backgroundColor:'rgb(0,144,209)', height: 5}}
        style={{
            backgroundColor: 'rgb(0, 81 , 112)',
        }}
    />
