### ISSUE TITLE
On state change need re-render 

### ISSUE THREAD

**Issue by uc-asa** [react-native-community/react-native-tab-view#19]
When state change in my component then I need to re-render
<TabViewAnimated
				         style={styles1.container}
				         navigationState={this.state.navigation}
				         renderScene={this._renderPage}
				         renderHeader={this._renderHeader}
				         onRequestChangeTab={this._handleChangeTab}
			       />

plz suggest me

**Comment by knowbody** [comment]
You just closed the previous issue with the same problem? https://github.com/react-native-community/react-native-tab-view/issues/17

**Comment by satya164** [comment]
@uc-asa please refer to the caveats section in README which deals with this issue - https://github.com/react-native-community/react-native-tab-view#caveats
