### ISSUE TITLE
Error when updated to latest version.

### ISSUE THREAD

**Issue by rendomnet** [react-native-community/react-native-tab-view#191]
ReactNativeJS: Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `TabViewTransitioner`.

**Comment by CharlesMangwa** [comment]
Hi @rendomnet! Did you track down the piece of code generating this error?

**Comment by judgejab** [comment]
I'm seeing this too. Have you found a fix for this @rendomnet?
