### ISSUE TITLE
this.props.navigator.push() is not working in listview   inside the <Component/> on both tabs

### ISSUE THREAD

**Issue by yogi9999999** [react-native-community/react-native-tab-view#192]
I am using listview in which is inside the pure component  and onPress when I am pushing the page  this.props.navigator.push({id: 8,});

 it giving me error "undefined is not object(evaluating 'this.props.navigator.push')"

**Comment by CharlesMangwa** [comment]
As described in the error: you should probably make sur the component has received `navigator` in its props.

**Comment by yogi9999999** [comment]
I have read the documents but couldn't find possible solution can you tell where i miss?

**Comment by witalobenicio** [comment]
For me, the same. But only on production builds.
