### ISSUE TITLE
[Android] ScrollView and Keyboard Bug

### ISSUE THREAD

**Issue by flaviotobi** [react-native-community/react-native-tab-view#193]
Hi, 
Components:
First Tab Bar: has TextInput
Second Tab Bar: has ScrollView

The problem is that if you have two tab bar, and click on a text Input and open the keyboard, and with the keyboard up, scroll to second tab bar, it continue on the first bar.
But if you remove the scrollView it works fine. and it works fine on iOS.
Se in more detail in the video:

<img src="https://cloud.githubusercontent.com/assets/13239857/24830473/c193ce9e-1c7e-11e7-9c31-93a2af119c2a.gif" width="350" />

React-Native Version: 0.41.2
react-native-tab-view:  0.0.56
Platform: Android

**Comment by satya164** [comment]
Does passing this prop to `TabViewAnimated` solve your issue?

```js
onChangePosition={Keyboard.dismiss}
```

You can import `Keyboard` from `react-native`

**Comment by flaviotobi** [comment]
@satya164 Nope it doesn't work :/

**Comment by flaviotobi** [comment]
I believe the problem is in: ViewPagerAndroid
I just change the TabViewAnimeted.js component to this and now it works:
```
let TabViewPager;
TabViewPager = require('./TabViewPagerScroll').default;

// switch (Platform.OS) {
// case 'android':
//   TabViewPager = require('./TabViewPagerAndroid').default;
//   break;
// case 'ios':
//   TabViewPager = require('./TabViewPagerScroll').default;
//   break;
// default:
//   TabViewPager = require('./TabViewPagerPan').default;
//   break;
// }
```

In the ViewPagerAndroid docs it says this: 
And what is the meaning?:
> It is important all children are <View>s and not composite components.

**Comment by shrutic** [comment]
I have the same issue on iOS. The option of adding
'''onChangePosition={Keyboard.dismiss}''' 
to < TabViewAnimated> did not work for me

**Comment by flaviotobi** [comment]
@shrutic have you tried my solution ?

**Comment by CharlesMangwa** [comment]
Closing since @flaviotobi seems to have solved this issue.

**Comment by kasaiee** [comment]
I have the problem too in android with ant design
