### ISSUE TITLE
canJumpToTab not working properly on Android

### ISSUE THREAD

**Issue by Viktor6713** [react-native-community/react-native-tab-view#195]
Hi there, I have a problem with `canJumpToTab` on Android(real device and simulator).
When changing tabs by swiping, the newly swiped scene stays still rendered, even if it should jump back to one I swiped from, only indicator in `TapBar` jumps back and correct tab label is active.
This works on iOS(tested on simulator) without problem. I am using the newest version.

**Comment by satya164** [comment]
This should be fixed as of the latest version. Please let me know if that's not the case.
