### ISSUE TITLE
TabBar don't show

### ISSUE THREAD

**Issue by 7laria** [react-native-community/react-native-tab-view#196]
I'm using the TabViewExample to get a test but the top tab bar isn't show. how I can fix?

![photo6012822161791756233](https://cloud.githubusercontent.com/assets/16237713/24949548/4a509144-1f6e-11e7-8ebe-ec0cb15885fa.jpg)

**Comment by 7laria** [comment]
if i remove the nav bar it work but how I can place the navbar of route flux and the tab bar of this?

**Comment by 7laria** [comment]
Solved.

**Comment by sibelius** [comment]
@7laria could you post your solution here?

**Comment by 7laria** [comment]
Simply adding a style to tabbar with some MarginTop
