### ISSUE TITLE
Is there a way to change selected tab header?

### ISSUE THREAD

**Issue by FacuAcosta** [react-native-community/react-native-tab-view#198]
Basically, I want to change the backgroundColor and the label color whenever you select a tab, but I don't know If there is a property or a method to do so. For example, I have this 2 tabs: 

![screen shot 2017-04-13 at 10 48 50](https://cloud.githubusercontent.com/assets/19332669/24999802/e4cb3c60-2036-11e7-84bd-1d4e3b4dc4ea.png)
And I want them to look like this:
![screen shot 2017-04-13 at 10 50 07](https://cloud.githubusercontent.com/assets/19332669/24999850/0a232af4-2037-11e7-8e2d-cd60bba46649.png)

![screen shot 2017-04-13 at 10 50 17](https://cloud.githubusercontent.com/assets/19332669/24999862/11e549a2-2037-11e7-8a13-b1c0715d6100.png)

As you can see, depending on which one is selected, its styling changes.

**Comment by CharlesMangwa** [comment]
Hi @FacuAcosta! You just have to use the [`renderHeader` prop](https://github.com/react-native-community/react-native-tab-view/blob/272cc3a555e665916024cc97ded5f80e5b567485/example/src/TopBarTextExample.js#L86) to do so. Then you can styled your header as you wish ([example here](https://github.com/react-native-community/react-native-tab-view/blob/272cc3a555e665916024cc97ded5f80e5b567485/example/src/TopBarTextExample.js#L53-L63)).
