### ISSUE TITLE
Changing tab index programmatically does not change selected tab indicator

### ISSUE THREAD

**Issue by j-rul** [react-native-community/react-native-tab-view#199]
My setup is the same as in this example: https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/NoAnimationExample.js, except that I have swiping and animation enabled.

I am using setState to change the selected tab like so: setState({ index: 1 }),  and it changes the current scene, but the tab indicated as selected in the tabbar (in my case, with a different icon color) does not change. Any way to implement this?

**Comment by CharlesMangwa** [comment]
Hi @j-rul! You should make sure that you read the doc and the provided examples correctly. Based on what you said, I tried to reproduced your bug without success : https://snack.expo.io/HyTpDJbRe. Don't hesitate to re-open your issue if needed/you reproduce your bug on [Snack](snack.expo.io).
