### ISSUE TITLE
Tracking analytics / integration with react-navigation

### ISSUE THREAD

**Issue by joncursi** [react-native-community/react-native-tab-view#201]
NavExp has been deprecated in favor of `react-navigation`, which pretty much has [built-in support](https://reactnavigation.org/docs/guides/screen-tracking) for screen tracking analytics.

However, if your screen is a tab view, with multiple (potentially deep and complex) tabs, react-navigation only interprets this as one single screen. So you lose a lot of insight into what your users are doing in your app if your screens are composed of lots of tab views.

This could encourage the developer to drop react-native-tab-view in favor of using a TabNavigator in react-navigation, in order to automatically capture precisely what the user is looking at.

I'd like to stay with `react-native-tab-view` if I can. But I think it needs to have some sort of bindings into `react-navigation` so that these analytics can be captured, or at least a README / guide on how this can be accomplished with a custom Redux middleware or helper function.

**Comment by CharlesMangwa** [comment]
Hi @joncursi! Although your issue is quite relevant, given that these are `react-navigation`'s problems, you should probably post it on [its repo](https://github.com/react-community/react-navigation/issues) first.

**Comment by joncursi** [comment]
Looks like react navigation uses this library under the hood. Didn't realize that. So I just switched over from using this library directly to using the Tabs component in React Navigation to get the best of both worlds: slick tabs interface + tracking analysis.
