### ISSUE TITLE
Programmatically jump from on page to another from another component

### ISSUE THREAD

**Issue by suprb** [react-native-community/react-native-tab-view#202]
Hi, 

Is it possible to jump from one page (index) to another from different imported components? 

Thanks

**Comment by roshangm1** [comment]
I have this same issue. I want to jump to particular tab from the certain component without pressing the tabs itself.

**Comment by satya164** [comment]
You can pass a function which updates the state as a prop. It's same as how you'd update the state of one component from a different component in React.
