### ISSUE TITLE
Is it possible to style particular tab ? 

### ISSUE THREAD

**Issue by roshangm1** [react-native-community/react-native-tab-view#203]
I want to add some vertical separator between the tabs. How do I achieve this ? Is it possible with the current tab view, or should i add the code to get those behaviour?

**Comment by satya164** [comment]
You can use `tabStyle` to add a border

**Comment by mlecoq** [comment]
I have tried to add a right border on tab items 

Unfortunately, It has side effects on the border radius added on the indicator 

<img width="220" alt="Capture d’écran 2020-08-18 à 15 55 18" src="https://user-images.githubusercontent.com/3649784/90521923-62967800-e16b-11ea-84c3-3e5047094562.png">

and when I tap on a tab, the ripple effect is visible right to the border (on android at least)

**Comment by mlecoq** [comment]
see #1020
