### ISSUE TITLE
Android tab bar icon won't overflow

### ISSUE THREAD

**Issue by rad182** [react-native-community/react-native-tab-view#206]
Hi, I'm trying to replicate the Facebook Messenger tabs where the Camera button overflows the tab bar. Currently testing this with the react navigation sample code NativePlayground.

Under SimpleTabs.js i also added showIcon for tabBarOptions and tabBarPosition to be "bottom".
I modified this code and added margin bottom.
```js
MyChatScreen.navigationOptions = {
  tabBar: {
    label: 'Chat',
    icon: ({ tintColor, focused }) => (
      <Ionicons
        name={focused ? 'ios-chatboxes' : 'ios-chatboxes-outline'}
        size={26}
        style={{ color: tintColor, marginBottom: 20 }}
      />
    ),
  },
};
```
Results
iOS
<img width="375" alt="screen shot 2017-04-21 at 12 25 53 pm" src="https://cloud.githubusercontent.com/assets/71201/25262890/fea4142e-268d-11e7-88bc-90ac5b763f96.png">

Android
<img width="511" alt="screen shot 2017-04-21 at 12 26 02 pm" src="https://cloud.githubusercontent.com/assets/71201/25262893/048690e2-268e-11e7-8354-efc8746f9d57.png">

Also tried this https://stackoverflow.com/questions/41912313/element-overflow-hidden-in-react-native-android but no luck

Seems to be fine on iOS but for android there's a top view blocking the icon. 
Is there any way to achieve this? TIA

**Comment by karanjthakkar** [comment]
@rad182 Can you post a minimum reproducible example of this on https://snack.expo.io? I'd love to look into it for you.

**Comment by satya164** [comment]
React Native on Android doesn't support `overflow: visible`

**Comment by guoliang1206** [comment]
@satya164  could you give me a link that how to design a overflow tabbar item? I have search much websites and issues, but I still can't find one effective.Thanks

**Comment by landmass** [comment]
+1
If you find a solution, I hope you can let me know. Thank you. @satya164

**Comment by est7** [comment]
@landmass If you find a solution, I hope you can let me know. Thank you.

**Comment by landmass** [comment]
@est7 
react-native-tab-view\src\TabViewAnimated.js
`render() {
  ....
  return(
   <View style={[styles.container, this.props.style]}>
     ......
     <TouchableOpacity
        style={{ backgroundColor:'orange',position:'absolute',bottom:25, }}
        onPress={ ()=>{
           //do something
          } 
        }
     >
        <Text style={{width:36,height:36,fontSize:22,color:'#999',textAlign:'center',textAlignVertical:'center',}}>+</Text>
     </TouchableOpacity>
   </View>
 )
}`

**Comment by est7** [comment]
@landmass thanks!

**Comment by est7** [comment]
@landmass 
modify the source code is not good for VCS ,is it?

**Comment by rcorrie** [comment]
Why are this issue and #341 closed? Seems to me like a legitimate bug and there has not been any resolution to it.

**Comment by nicomontanari98** [comment]
@rad182 in android to change the overflow of the element you have to change the elevation, while in iOS you have to change the zIndex
