### ISSUE TITLE
2 Tabs in TabViewAnimated with one of tabs with text input requires 2 click to change tabs

### ISSUE THREAD

**Issue by shrutic** [react-native-community/react-native-tab-view#209]
The scenario is that there is a text input in tab one. 
If the keyboard is up, it takes 2 clicks to change to tab 2:

- one click for dismissing keyboard
- another for changing tabs

React native version : 0.43.3
platform: iOS

**Comment by satya164** [comment]
You can wrap the input in a scrollview and customize `keyboardShouldPersistTaps` behaviour - https://facebook.github.io/react-native/docs/scrollview.html
