### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by iRoachie** [react-native-community/react-native-tab-view#213]
Hey man! Great library. Just wondering if you're interesting in having typescript definitions for this library (for those wanting to use react native with typescript). I already have stubbed them out in a few of my projects. Let me know @fson

**Comment by ligaz** [comment]
Hey @iRoachie can you please share your typings? 😄

**Comment by iRoachie** [comment]
lol @ligaz they're are far from complete since I haven't used all the methods/props. Lol I wish there was a table in readme like showing the all the props and their values

**Comment by iRoachie** [comment]
@ligaz I could make it a public gist and we could work on it

**Comment by satya164** [comment]
Not opposed to have typings, but they need to stay up-to-date. So if you want to maintain them, feel free to send a PR with the typings (also maybe a test case to ensure I don't break them accidentally) :D

The library is fully-typed with Flow. You can find the exported flow types at https://github.com/react-native-community/react-native-tab-view/blob/master/types.js

For the prop types of individual components like `TabBar` and `TabViewAnimated`, you need to check the individual files.

**Comment by iRoachie** [comment]
@satya164 Thanks! That makes it 10x easier. Will start work on it

**Comment by CharlesMangwa** [comment]
Closing (waiting for @iRoachie PR 😉).

**Comment by iRoachie** [comment]
@CharlesMangwa Haha thanks for reminder

**Comment by iRoachie** [comment]
WIP here #271
