### ISSUE TITLE
Is is possible to embed a tab inside a tab?

### ISSUE THREAD

**Issue by LaloHao** [react-native-community/react-native-tab-view#214]

**Comment by karanjthakkar** [comment]
@LaloHao Do you have a screenshot/gif of what exactly you're hoping to achieve?

**Comment by LaloHao** [comment]
4 tabs above, and each tab should have the 2 children below
![img](https://anonimag.es/i/WhatsAppImage2017-04-20at18.29.197c57e.jpg)

**Comment by LaloHao** [comment]
I managed to workaround by making another component which modifies the tab-view state, but its hacky, so i would stilll like to know if theres a cleaner way of doing it

**Comment by satya164** [comment]
Not sure what problem you are having. Can you post your code?
