### ISSUE TITLE
Reduce indicator size when the tab has margin specified

### ISSUE THREAD

**Issue by shrutic** [react-native-community/react-native-tab-view#216]
As per our design requirement, we needed to restrict the tab bar to have margins top and bottom as below.
![image](https://cloud.githubusercontent.com/assets/4141641/25464247/2f5e7052-2ab0-11e7-838c-e3a46696253e.png)

Below is the implementation of the renderIndicator in the library

```
  private renderIndicator(props) {
        const { width, position } = props;
        const translateX = Animated.multiply(position, width);
        return (
            <Animated.View
                style={[ImageSelectionViewStyleSheet.container, { transform: [{ translateX }], width }]}
            >
                <View style={ImageSelectionViewStyleSheet.indicator} />
            </Animated.View>
        );
    }
```

How can I modify this so that the indicator doesnt overflow like shown in the screenshot above. My Animated API understanding is limited and I could not figure it out

react native version : 0.43.3
Librayr version : 0.0.59

**Comment by karanjthakkar** [comment]
@shrutic Can you post a minimum working example of this on https://snack.expo.io? At first look, this doesn't seem to be an issue with this library. It should be solvable by styling appropriately. I can give you more info on how to solve this once we have reproducible example from you.

**Comment by Flavien** [comment]
This is definitely a problem with the library. The full width that the TabBar uses is the full width of the screen so if you have margins, the indicator width will be wrong.

@shrutic Did you find a solution?

**Comment by shrutic** [comment]
Well I solved it by changing the design to use a tab underline indicator instead of a rectangular box. In this case it doesn't look awkward like my screenshot

**Comment by satya164** [comment]
`renderTabBar` function receives `layout` in the `props` object which you can modify before passing to the `TabBar` if you need to tweak the width. You can also render your custom tab bar and/or indicator.

**Comment by Flavien** [comment]
👍 Thanks for the tips, I modified the ``layout`` property in ``renderHeader`` before passing it down.
