### ISSUE TITLE
Run the indicator Aimation and the Label text color change animation in parallel

### ISSUE THREAD

**Issue by shrutic** [react-native-community/react-native-tab-view#217]
Is it possible to run the label text color change animation and the indicator animation in parallel? Currently when I animate in renderLabel() and in renderIndicator(), the animations seem to run in sequence and does not look refined

react native version : 0.43.3
Librayr version : 0.0.59

**Comment by satya164** [comment]
Not sure what you mean. Can you post a GIF/video?

**Comment by satya164** [comment]
Closing due to no response
