### ISSUE TITLE
quick Jumping between Tabs Weird Loop 

### ISSUE THREAD

**Issue by jasan-s** [react-native-community/react-native-tab-view#219]
I have 3 tabs , one of them containing ListView(not sure if its relevant to the error). WHen I swipe quickly back and forth between the tabs, the animation gets stuck in a loop even after I stop swiping.  The Same behavior occurs when I quickly jump back and forth between tabs by tapping as well.  
 iOS Device only shows this behavior , Android Device does not: 
```
"react": "16.0.0-alpha.6",
"react-native": "0.43.3",
"react-native-tab-view": "^0.0.61",
```

**Comment by satya164** [comment]
Please mention your platform, React Native version and version of the library.

**Comment by jasan-s** [comment]
![giphy 2](https://cloud.githubusercontent.com/assets/13863953/25485339/73fbc860-2b12-11e7-9c33-0902cdbe41ea.gif) 
@satya164  Here is a screen grab from the iphone. I tested it on android and I cant seem to replicate it on android device.

**Comment by jasan-s** [comment]
it may be because on ios the user taps are registered without any delay, and by the time I press to go to Third Tab the animation is still in process of going to Second Tab.  On Android the subsequent taps are just ignored if i'm tapping to quickly between tabs.  So Is there a way to ignore taps in iOS if there too close apart in duration?

**Comment by satya164** [comment]
I'll look into it today

**Comment by satya164** [comment]
Hey, I don't have an iOS device and I was unable to repro on the simulator since it's so hard to swipe there.

Can you try this PR to see if it fixes the issue? https://github.com/react-native-community/react-native-tab-view/pull/220

**Comment by jasan-s** [comment]
@satya164  Thanks, that PR definitely fixed the strange behavior from occurring  when tapping between tabs :+1:  . But the same weird behavior still occurs if I swipe between tabs quickly.  Is there a suggestion for it?

**Comment by satya164** [comment]
Hmm. Lemme try. Kinda hard due to no device, but will see.

**Comment by satya164** [comment]
It's a shot in dark. But does #221 help?

**Comment by jasan-s** [comment]
That fixed It. :+1:  But new Weird behavior is introduced from PR [#220](https://github.com/react-native-community/react-native-tab-view/pull/220).  When the App loads initially  Tapping on any other tabs does not change the View.  Only after swiping to another tab then tapping on other tabs has any effect.

**Comment by satya164** [comment]
Thanks a lot for keeping up! I just sent #222 which should fix the issue.
