### ISSUE TITLE
Can we render tab just on slight scroll?

### ISSUE THREAD

**Issue by prtkkmrsngh** [react-native-community/react-native-tab-view#224]
I'm trying to initialize camera on scroll of tab just like whatsApp. Is it possible here?

**Comment by satya164** [comment]
You can listen to the `onChangePosition` callback and do what you want (that's how lazy loading is implemented). But I can't guarantee that it'll be performant.

**Comment by prtkkmrsngh** [comment]
I'm doing this in onRequestChangeTab callback by changing states of particular scene. 
onChangePosition is not performing well.
