### ISSUE TITLE
Upgrade to 0.0.62 cause error.

### ISSUE THREAD

**Issue by johnnylc** [react-native-community/react-native-tab-view#226]
When I upgrade from 0.0.61 to 0.0.62, I met the error: "The specified child already has a parent. You must call removeView() on the child's parent first". In 0.0.61 version, there is no error.

**Comment by sibelius** [comment]
could you provide a repo to reproduce this?

**Comment by satya164** [comment]
Closing due to no response. If you have a repro, please comment.
