### ISSUE TITLE
Android: Tabbar still animating when configureTransition is set to NULL

### ISSUE THREAD

**Issue by atpunk** [react-native-community/react-native-tab-view#228]
`<TabViewAnimated
               configureTransition={null}
                  style={styles.container}
                  navigationState={this.state}
                  renderScene={this._renderScene}
                  renderFooter={this._renderFooter}
                  onRequestChangeTab={this._handleChangeTab}
                />`

**Comment by satya164** [comment]
There is no `configureTransition={null}`. Use `animationEnabled={false}` - https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/NoAnimationExample.js#L163
