### ISSUE TITLE
Android: Tabbar Badge does not display

### ISSUE THREAD

**Issue by atpunk** [react-native-community/react-native-tab-view#229]
Stylesheet
`badge: {
    flex:1,
    backgroundColor: '#EFEFF2',
    marginTop: 4,
    alignSelf: 'flex-end',
    right:dim.width/11,
  },`

render badge method with the above style works on iOS.

**Comment by sibelius** [comment]
@joncursi try to use `zIndex`

https://github.com/react-native-community/react-native-tab-view#tabbar-disappears-or-shows-weird-behaviour-when-conditionally-rendering-items

**Comment by CharlesMangwa** [comment]
Closing given that this is covered in the documentation as reminded by @sibelius.
