### ISSUE TITLE
scrollEnabled={false}  does not work in <TabBar>

### ISSUE THREAD

**Issue by dileepkantapop** [react-native-community/react-native-tab-view#237]
I have written in 

 _renderHeader = (props) => {
        return <TabBar {...props}
            renderIcon={this._renderIcon}
            indicatorStyle={styles.indicator}
            style={styles.tabbar} 
            scrollEnabled={false}/>;
    };

and i am calling _renderHeader like this: 
 <TabViewAnimated
                        ...
                        ...
                        ...
                        renderHeader={this._renderHeader}
                       ...
                    />

**Comment by satya164** [comment]
I'm not sure what you mean `scrollEnabled={false}` is the default, so you don't need to specify that. Please reopen with a repro gif/video if you have.

**Comment by dileepkantapop** [comment]
By default it scroll so i wrote the statement scrollEnabled={false} inside <TabBar>.

**Comment by satya164** [comment]
I'm not sure I understand. What scrolls by default? I'm 100% sure the TabBar does not.

**Comment by dileepkantapop** [comment]
By default the tab scrolls by swiping the views between them. I need to disable the swiping of the tabs to change the child view of the tab

**Comment by satya164** [comment]
You are looking for `swipeEnabled={false}` https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/NoAnimationExample.js#L160

**Comment by dileepkantapop** [comment]
Thanks Satya. The library is very helpful.

**Comment by DevFranzBeta** [comment]
@satya164  You saved my time thanks
