### ISSUE TITLE
tab inside tab doesnt show child tab views

### ISSUE THREAD

**Issue by yogi9999999** [react-native-community/react-native-tab-view#239]
In my design have to create a tab inside a tab but the child-view tab component doesn't get reflected....????

**Comment by sibelius** [comment]
try to use `zIndex`

https://github.com/react-native-community/react-native-tab-view#tabbar-disappears-or-shows-weird-behaviour-when-conditionally-rendering-items

**Comment by TaiPA** [comment]
@sibelius 
I have the save problem here, could you tell me more detail on use zIndex ?

**Comment by TaiPA** [comment]
No One have the same problem with me...?
Please help me...

**Comment by satya164** [comment]
try using:

```js
_renderPager = props => <TabViewPagerPan {...props} />;

render() {
  return (
    <TabViewAnimated
      ...
      renderPager={this._renderPager}
    />
  );
}
```

**Comment by CharlesMangwa** [comment]
Hi @yogi9999999, @TaiPA: can I close this issue 🙂 ?

**Comment by infinityblockchainlabs** [comment]
@CharlesMangwa 
Sure, please close this.
It is not completely solve my problem but almost done.
Thank you !

**Comment by TaiPA** [comment]
@CharlesMangwa 
Sure, please close this.
It is not completely solve my problem but almost done.
Thank you !
