### ISSUE TITLE
Can not be displayed on the Android phone

### ISSUE THREAD

**Issue by yejiajieicanqly** [react-native-community/react-native-tab-view#24]
In _renderScene(), Android phones can not be a normal rendering of the component I want to render, such as a background color component, can normal rendering in iPhone, in the Android equipment but not normal rendering components contained in is not rendered.

**Comment by satya164** [comment]
what do you mean by cannot be displayed? can you provide an example?

**Comment by satya164** [comment]
I'm going to close this issue since there has been no response.

**Comment by developer239** [comment]
He was saying that it does not work on android.
