### ISSUE TITLE
Unknown props in div in View in TabViewTransitioner created by TabViewAnimated

### ISSUE THREAD

**Issue by pqminh** [react-native-community/react-native-tab-view#240]
![error](https://cloud.githubusercontent.com/assets/13993984/25882645/29c9a296-356f-11e7-8eaf-2318a44ea766.png)

I use windows 10 and "react-native-tab-view": "0.0.56".

**Comment by satya164** [comment]
That's a very old version. Please upgrade to a newer version.

**Comment by aizigao** [comment]
same problem with react-native-web, lots of warning Unknown props 
![image](https://user-images.githubusercontent.com/14126445/29918050-83e49136-8e76-11e7-86e2-7d4d13fc30e8.png)

![image](https://user-images.githubusercontent.com/14126445/29918094-ae4759fe-8e76-11e7-95d7-9cda38fceb45.png)
