### ISSUE TITLE
How to pass additional props using SceneMap?

### ISSUE THREAD

**Issue by joncursi** [react-native-community/react-native-tab-view#241]
How do you pass additional props to a tab using `SceneMap`?

```jsx
  _renderScene = SceneMap({
    [TAB_KEY_ONE]: TabOne,
    [TAB_KEY_TWO]: TabTwo,
  });
```

`TabOne` and `TabTwo` may be functional components, or classes. How do you pass additional props to them?

**Comment by satya164** [comment]
You can define them as `key: () => <TabOne prop={this.props.someProp} />`, but note that it won't update as `this.prop.someProp` changes (it didn't with a normal `renderScene` function` anyway). 

Scenes defined this way also won't update if the state changes, which is great for perf. If you absolutely need them to update, you should use the function manually as you did before.

**Comment by pacozaa** [comment]
@flaviolc18 any solution?

**Comment by pacozaa** [comment]
@satya164 why your answer contradicts with the document?

**Comment by satya164** [comment]
@pacozaa my answer is from 2 years ago with an older version of the library :/

**Comment by asososo** [comment]
> @flaviolc18 any solution?

from document, use a custom renderScene function:

```
const renderScene = ({ route }) => {
  switch (route.key) {
    case 'first':
      return <FirstRoute foo={this.props.foo} />;
    case 'second':
      return <SecondRoute />;
    default:
      return null;
  }
};
```

**Comment by ShubhamKushwah** [comment]
Requesting re-open of this issue, it's not solved yet!

**Comment by NoahVandy** [comment]
@ShubhamKushwah  You have to define the route with the component separately.

`export default function BottomNav({ currentUser }: appProps) {

  const MarketplaceRoute = () => (
    <Marketplace 
      currentUser={currentUser}
    />
  )

  const [index, setIndex] = useState(3);
  const [routes] = useState([
    { key: 'Marketplace', title: 'Market', icon: 'shopping-outline' },
    { key: 'Stores', title: 'Stores', icon: 'store-outline' },
    { key: 'CreateAListing', title: 'CreateAListing', icon: 'plus-circle-outline' },
    { key: 'Favorites', title: 'Favorites', icon: 'heart-outline' },
    { key: 'Profile', title: 'Profile', icon: 'account-circle-outline' },
  ]);

  const renderScene = BottomNavigation.SceneMap({
    Marketplace: MarketplaceRoute,
    Stores: Stores,
    CreateAListing: CreateAListing,
    Favorites: Favorites,
    Profile: Profile
  });

  return (
    <BottomNavigation
      navigationState={{ index, routes }}
      onIndexChange={setIndex}
      renderScene={renderScene}
    />
  );
}`

**Comment by philly-vanilly** [comment]
@ShubhamKushwah 

Does it make sense to use memoization here?

> ```
>   const MarketplaceRoute = React.useMemo(() => (
>     <Marketplace 
>       currentUser={currentUser}
>     />
>   ), [currentUser]);
> ```

**Comment by philly-vanilly** [comment]
> Probably would help with the re-rendering. I moved away from this library because it re-renders every screen on every click of the different tabs.

What are you using now?

**Comment by NoahVandy** [comment]
@philly-vanilly I've moved to just react-native-navigation. It has a little bit more configuration as you have to style everything by hand but has a lot more customization and control than this library.

**Comment by Patryk-Szylin** [comment]
I've just passed it as an additional prop on the route object and now the tab that needs additional data just accesses it from the `route` prop that gets automatically passed in through the `renderScene`. Remember since these are objects, you can add extra properties to the route object however you like. Here is an example of what I've got

Here is my route declaration
```ts
const [routes] = React.useState([
    { key: "first", title: "Your Plans", plans: plans },
    { key: "second", title: "Made For You" },
  ]);
```

Here is the TabView component
```ts
      <TabView
        renderTabBar={renderTabBar}
        navigationState={{ index, routes }}
        renderScene={renderScene}
        onIndexChange={setIndex}
        initialLayout={{ width: layout.width }}
      />
```

And finally here is the tab that needs extra data from the props.
```ts
const YourPlans = ({ route }: any) => (
  <View style={{ flex: 1 }}>
    <TouchableOpacity onPress={() => {}}>
      <Text>{JSON.stringify(route.plans)}</Text>
    </TouchableOpacity>
  </View>
);
```

**Comment by phuocantd** [comment]
> 

plans in YourPlans not change when plans changed

**Comment by phuocantd** [comment]
> > @flaviolc18 any solution?
> 
> from document, use a custom renderScene function:
> 
> ```
> const renderScene = ({ route }) => {
>   switch (route.key) {
>     case 'first':
>       return <FirstRoute foo={this.props.foo} />;
>     case 'second':
>       return <SecondRoute />;
>     default:
>       return null;
>   }
> };
> ```

using custom then rerender when change tab :(
