### ISSUE TITLE
[0.65.0] Android tab content coming up blank?

### ISSUE THREAD

**Issue by joncursi** [react-native-community/react-native-tab-view#243]
Pretty much all of my tabs on Android are rendering blank content on `0.65.0`. iOS is fine, just Android. Consider the following:

```jsx
       _renderScene = SceneMap({
         [TAB_KEY_GENERAL]: TabGeneral,
         [TAB_KEY_INTEGRATIONS]: TabIntegrations,
       });

        ...

        <TabViewAnimated
          navigationState={{
            index,
            routes,
          }}
          onRequestChangeTab={this._handleChangeTab}
          renderHeader={(props): React$Element<*> => (
            ...
          )}
          renderScene={this._renderScene}
        />

```

Result:

<img width="677" alt="screen shot 2017-05-10 at 10 56 04 am" src="https://cloud.githubusercontent.com/assets/4974609/25905207/5a157560-356f-11e7-9635-1424aca22dd1.png">

I have tried applying a `style` prop on TabViewAnimated with heights, widths, flex properties, etc. Nothing is getting the tab content to come up.

**Comment by joncursi** [comment]
FWIW, when I remove TabViewAnimated and render the tab content straight up, it renders correctly. But when I nest it inside TabViewAnimated via `renderScene`, I get blanks.

**Comment by prtkkmrsngh** [comment]
I upgraded the package to 0.0.65 and everything is working as expected. Can you debug it with debugger?

**Comment by satya164** [comment]
Do you have some code/repo I can check?

**Comment by joncursi** [comment]
@satya164 unfortunately my code is very coupled to business logic ATM. I'll keep playing with it, but I wanted to post here to see if others were having the same issue. I'll report back soon, and if all else fails, I'll create a repro.

**Comment by satya164** [comment]
@joncursi thanks. a repro will help

**Comment by sibelius** [comment]
@joncursi try to use `zIndex`

https://github.com/react-native-community/react-native-tab-view#tabbar-disappears-or-shows-weird-behaviour-when-conditionally-rendering-items

**Comment by vince-fly** [comment]
i have the same issue.

**Comment by sibelius** [comment]
```jsx
renderTabHeader = props => {
    return (
      <TabBar
        {...props}
        style={{ zIndex: 0 }}
      />
    );
  };
```

**Comment by kelset** [comment]
I had a quite similar issue, setting the `zIndex: 0` didn't help, but instead @sibelius's solution for fixing issue #246 using renderPager did the trick.

**Comment by ChrnoLynch** [comment]
I have the same error and like @Kelset say and after some days searching a solution, renderPager fix the error.

```
<TabViewAnimated
             style={styles.container}
              navigationState={this.state}
              renderPager={this._renderPager}
              renderScene={this._renderScene}
              renderFooter={this._renderFooter}
              onRequestChangeTab={this._handleChangeTab}
/>

_renderPager = (props) => {
   return (Platform.OS === 'ios') ? <TabViewPagerScroll {...props} /> : <TabViewPagerPan {...props}/>
}

```

**Comment by CharlesMangwa** [comment]
Closing thanks to @sibelius' workaround (and @kelset & @ChrnoLynch for the confirmation).

**Comment by ozexpert** [comment]
Hmm. what is the solution to this? My tab content is shown in iOS but not on Android.

**Comment by brunolemos** [comment]
I had this problem and was able to fix it. In my case, the issue was that I was doing:

`_renderScene = ({ navigationState: { index }}) => this.props.renderTabContent(index)}`

After changing to `route.key` the issue was fixed:

`_renderScene = ({ route }) => this.props.renderTabContent(route.key)`
