### ISSUE TITLE
prop loaded on View

### ISSUE THREAD

**Issue by jefferscn** [react-native-community/react-native-tab-view#244]
`<View
        onLayout={this._handleLayout}
        loaded={this.state.loaded}
        style={[styles.container, this.props.style]}
      >`
Here is code from TabViewAnimated.js , what's the usage of loaded prop.
There is no description aboue "loaded" in document of react-native's View.

**Comment by satya164** [comment]
It's not a public API. It's used to implement lazy load internally.
