### ISSUE TITLE
Is is possible to have a loop tab ?

### ISSUE THREAD

**Issue by TaiPA** [react-native-community/react-native-tab-view#247]
It is possible to have a loop tab ? (Like swiper)
Ex, i have 4 tab (Tab1, Tab2, Tab3, Tab4)

Tab3 <-> `Tab1 <-> Tab2 <-> Tab3` <-> Tab1

**Comment by satya164** [comment]
Not currently. Maybe we need overscroll support. However it might be difficult/impossible on Android with native pagers.

**Comment by CharlesMangwa** [comment]
Closing since it's not possible (for now 😏…).
