### ISSUE TITLE
Method onRequestChangeTab not called?

### ISSUE THREAD

**Issue by namdq1969** [react-native-community/react-native-tab-view#248]
I try 2 things:
- put a console.log() inside onRequestChangeTab, but it will never be called.
- remove this onRequestChangeTab props from TabViewAnimated and it warns me this method is required by default.
Please check this issue for me. Thanks.

**Comment by shardick** [comment]
Happens also to me. Tap on tabs don't work anymore after update to 0.65

**Comment by Exilz** [comment]
It's working fine for me with react-native 0.44 and tab-view 0.0.65.
However, I now need to pass the `onRequestChangeTab` prop explicitly, where I used to ommit it.

```javascript
...
onRequestChangeTab={this._onRequestChangeTab}`
```

```javascript
    _onRequestChangeTab (index) {
        this.setState({ index });
    }
```

**Comment by satya164** [comment]
@namdq1969 I can't repro the issue. Do you have a repro somewhere I can check?

@Exilz you always needed to. tab view is a controlled component. it was a bug if it used to work without doing it

**Comment by namdq1969** [comment]
@satya164 i use this component like below:
`<TabViewAnimated
          lazy
          swipeEnabled={false}
          navigationState={this.state}
          renderScene={scene => this.renderScene(scene)}
          onRequestChangeTab={(index) => {
            console.log(index);
          }}
        />`
when I setState({index: this.state.index + 1}) new tab will be rendered, but there's no console.log in onRequestChangeTab.

**Comment by Exilz** [comment]
You should set the index with the value from onRequestChangeTab, and not
increment it

**Comment by namdq1969** [comment]
@Exilz well, because I hide TabBars and disable swiping, so I put a next button on the screen for user to go to next tab. this tab component i use for stepping procedure in create new user account.

**Comment by satya164** [comment]
> when I setState({index: this.state.index + 1}) new tab will be rendered, but there's no console.log in onRequestChangeTab.

`onRequestChangeTab` only fires when you swipe/tap on tab bar etc. .i.e when the library requests you to change the index in state. If you're doing a `setState` with an index, `onRequestChangeTab` will not fire.

If you need to know when the tab changed regardless who did it, try in `componentWillUpdate` or `componentDidUpdate`

```js
componentDidUpdate(prevProps, prevState) {
  if (prevState.index !== this.state.index) {
    console.log("Tab changed to:", this.state.index);
  }
}
```
