### ISSUE TITLE
How do I enter text in topbar?

### ISSUE THREAD

**Issue by mmatheusmmiguel** [react-native-community/react-native-tab-view#250]
Hey guys,

In the demo -> https://raw.githubusercontent.com/satya164/react-native-tab-view/master/demo/demo.gif

How can i put this text "Text only topbar" on the basic example who is in the project readme?

Thanks,
Sorry my bad english.

**Comment by mmatheusmmiguel** [comment]
Any?

**Comment by satya164** [comment]
It's just a view. put another view above it like you would do with normal react native components.

**Comment by mmatheusmmiguel** [comment]
But should I put the view over which component? The TabBar or TabViewAnimated?

**Comment by satya164** [comment]
That's upto you. Both will achieve the same result.

**Comment by mmatheusmmiguel** [comment]
Ok, thanks!

**Comment by mmatheusmmiguel** [comment]
Hey Man,

https://image.prntscr.com/image/f481a2b328cc443584bfe28d42b00a44.png

Do you know how to remove this black shadow on this image?

**Comment by satya164** [comment]
Pass `style={{ elevation: 0, shadowOpacity: 0 }}` to the `TabBar`

**Comment by mmatheusmmiguel** [comment]
Oh thanks, man!
