### ISSUE TITLE
Add a license file 

### ISSUE THREAD

**Issue by zalesky** [react-native-community/react-native-tab-view#251]
Hi, in package.json you have key "license": "MIT", but there is no license file in project. 
Can you be so kind and add it? Thanks you a lot.

**Comment by zalesky** [comment]
@satya164 Please accept pr #245 or give me a feedback. I can't use this component without this.
 Otherwise I will have to write this component by myself🙄

**Comment by satya164** [comment]
Since the license is already mentioned in `package.json`, why is it important to add the file? I'm not very familiar with the licensing.

**Comment by zalesky** [comment]
Thx you a lot. It's a best practice  https://help.github.com/articles/licensing-a-repository/
