### ISSUE TITLE
Arranging tabs using flex properties

### ISSUE THREAD

**Issue by lslima91** [react-native-community/react-native-tab-view#252]
Imagine the following tabbar:
[Tab1, spaceeeeeeeeeeeeeeeee, Tab2]

To implement a layout like this I would do something like:
```
tabStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between'
}
```

The problem is that if I set flexDirection to row the tabs disappear

**Comment by satya164** [comment]
You cannot do that, but you can prolly just use a custom tab bar. https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/NoAnimationExample.js#L94
