### ISSUE TITLE
Keeping scroll position for next tab

### ISSUE THREAD

**Issue by andrerfneves** [react-native-community/react-native-tab-view#253]
Great package. Use it heavily in my application and couldn't ask for more. I do however have a specific requirement that I haven't found a workaround for. I need to set a specific scroll position for the sibling tabs based on my scroll of my current tab. Is there any way to keep the scroll position the same across tabs?

I thought of using the `onChangePosition` props of `TabViewAnimated` but wasn't sure if that was the correct approach. 

Has anyone dabbled in this before?

Cheers!

**Comment by satya164** [comment]
Hey! I'm not sure what you want to achieve. Do you have an example/gif somewhere?

**Comment by andrerfneves** [comment]
@satya164 yes sure. I'll get a gif in a little bit

**Comment by karanjthakkar** [comment]
@satya164 From what I understand based on the title and OP's description, lets say we have a tab view with three tabs: A, B, C. You scroll 100px on A. Now you change the tab and move to B. OP wants B to be scrolled by 100px on load. Is that right @andrerfneves?

**Comment by andrerfneves** [comment]
Hey @karanjthakkar. yeah that's pretty similar to what I am asking for. @satya164 sorry just been super busy and was unable to get a GIF going till just now.

Github doesn't allow me to render this GIF directly, but here it is:
https://im2.ezgif.com/tmp/ezgif-2-bdbd96cbc4.gif

Basically, I have an Animated Navbar with a diffClamp that allows me to hide and show the Navbar onScroll. However, when I scroll and thus hide the Navbar in Tab A, Tabs B, C and D have an empty space between the Tabbar and the first component inside the Tab (the exact height of the Navbar that is now hidden). 

Here's the distance:
![Image](https://i.imgur.com/rPBr0B1.png)

So my question is whether there is a way to automatically scroll Tabs B. C and D when I scroll Tab A. And if there is, then I should be able to only scroll them up the necessary amount (the size of the Navbar).

Does this explain a little more? Sorry it's quite a confusing situation.

**Comment by andrerfneves** [comment]
My GIF is not available anymore. Basically just want a way for all tabs to scroll along with one specified tab. No one has had to achieve anything similar?

**Comment by ixje** [comment]
@andrerfneves have you tried something like the following?
Keeping a reference of all ScrollViews in your tabs, and then use the [onScroll](https://facebook.github.io/react-native/docs/scrollview.html#onscroll) prop to pass a callback to track scrolling, and use that to adjust the 'non-active' tabs position with the [scrollTo](https://facebook.github.io/react-native/docs/scrollview.html#scrollto) method?

I haven't tried it myself, but it sounds totally reasonable to me.

**Comment by andrerfneves** [comment]
@ixje I've actually had to change my UI and therefore won't need this specific use-case but will test your implementation out. Thanks. Closing this for now!
