### ISSUE TITLE
Setting auto focus on an input is causing the keyboard to popup on launch in an unrelated tab

### ISSUE THREAD

**Issue by Jarrio** [react-native-community/react-native-tab-view#255]
I have a youtube video component in the top half of the screen and underneath the video, I have the `TabViewAnimated` component. Below is a gif of the issue:

![gif](https://cloud.githubusercontent.com/assets/748557/26226519/77e61b7e-3c24-11e7-8044-6c39007fc337.gif)

My code setup is as follows:
```text
- View
   - View
      - Youtube Component
   - View
      - TabViewAnimated
```
My routes are defined as:

```text
private function renderScene(router:Dynamic) {		
	trace('${router.index}', router);
	switch(router.index) {
		case 0: 
 			return jsx('<Scene1 />');
		case 1:
			return jsx('<Scene2 />');
	}
}
```

Now, this issue has only just appeared from a UI change. I've used this component before but due to changing the way my UI is I decided to have the menu bar under the playing video. After moving everything around this issue has appeared. I'm not sure why it has randomly appeared when all I've done in this case is just add something above the tabs.

The trace from the above method results in the following on launch: 
![image](https://cloud.githubusercontent.com/assets/748557/26226415/21a2b9ca-3c24-11e7-946c-9e1f9e50100d.png)

I can't say if this is normal behaviour for it to cycle through the options like this or whether it was doing this prior to the UI change as I never needed to test this. Could anyone provide any feedback or advice?

**Comment by CharlesMangwa** [comment]
Hi @Jarrio! Did you try to set your `autofocus` at true solely if the current tab is the one with the TextInput component?

**Comment by CharlesMangwa** [comment]
Hi @Jarrio! Did you try to set your `autofocus` at true solely if the current tab is the one with the TextInput component? This should prevent the keyboard from showing off everywhere.

**Comment by Jarrio** [comment]
Sure I can do that as a temporary fix but that sounds more like a hack rather than a fix, surely? Or is it just not possible to "fix" as a global solution?
