### ISSUE TITLE
Overlay tab bar

### ISSUE THREAD

**Issue by danielreuterwall** [react-native-community/react-native-tab-view#257]
I'm using the tab navigator in react navigation and I want to have the tabbar overlay the pager. The problems comes down to the `renderFooter`/`renderHeader` of `TabViewAnimated`.

On iOS I got it working by placing the tab bar in the footer (so it renders after the pager) and adding `position: absolute` and `top: Dimensions.get("window").height * -1`. It's a bit quirky but it gets the job done. However, on Android this doesn't do the trick. I suppose it comes down to the position absolute issues on Android.

I tried to set `position: absolute` and 'top: 0' on the view containing the footer in `TabViewAnimated` and this works for both iOS and Android. The same solution used in `ScrollableTabView`, which has support for `overlayTop` and `overlayBotton` for its tab bar,
https://github.com/skv-headless/react-native-scrollable-tab-view/blob/cefeaadb7bec26c7e764836d6f8c1ea909619ce8/index.js#L237

Any chance I missed something and can accomplish the same thing with react navigation and this component? If not, is this something that be implemented here as well?

**Comment by satya164** [comment]
What happens when you do `position: absolute` in React Navigation?

**Comment by danielreuterwall** [comment]
On Android it just disappears from the screen. I tried to position it in
any way I could come up to but it doesn't work.

**Comment by satya164** [comment]
@danielreuterwall you have a repro I can try? Maybe on http://snack.expo.io ?

Could be a bug

**Comment by danielreuterwall** [comment]
Unfortunately not but I could try to reproduce it in a more vanilla app and
share the repo. Hope to find some extra time over the weekend.

**Comment by danielreuterwall** [comment]
Is there any existing example of an overlay header or footer? Thinking of
alternative approaches...

**Comment by danielreuterwall** [comment]
I think manage to get this working with create-react-native-app and react-navigation. I still having trouble migrating this to my existing app but I guess it's just about taking it step by step to see where things get weird. Sorry about this, I really thought I tested this thoroughly before posting this issue. Closing this now.
