### ISSUE TITLE
ListView does not render in tab until tab has fully rendered

### ISSUE THREAD

**Issue by stief510** [react-native-community/react-native-tab-view#26]
In the demo you display as a gif, the tab view slides over when you switch tabs. However, I have two listviews - one for each tab - and they only render once the tab is fully rendered

**Comment by satya164** [comment]
@stief510 Can you give an example of what you mean?

**Comment by stief510** [comment]
Each route within the Tab View consists of a `<ListView/>`. When I change tabs the list view does not render until the view has completely moved to the next tab.

**Comment by satya164** [comment]
@stief510 That's not expected. Can you give the example a try and see if you can repro it? There's an example with ListViews.

https://github.com/react-native-community/react-native-tab-view/tree/master/example

It always helps to see the code and examples in case of an issue.

**Comment by satya164** [comment]
@stief510 Did you find something, happy to investigate if you provide code sample.

**Comment by stief510** [comment]
So my two renders are as follows

**Comment by satya164** [comment]
It looks fine to me. In fact I've an example with List views here - https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/ScrollViewsExample.js which renders the listviews upfront.

Can you provide the full code for me to debug? Hint: try exponent to share it easily

**Comment by stief510** [comment]
Does the mobx computed cause any issues here?

**Comment by satya164** [comment]
It shouldn't really. One guess is that rendering takes too long. Try `initialListSize={1}` maybe?

**Comment by stief510** [comment]
We were wiping the datasource in the listViews when not in view. So all is good now. Thanks
