### ISSUE TITLE
Api for selecting pager

### ISSUE THREAD

**Issue by zeljkoX** [react-native-community/react-native-tab-view#262]
I am experiencing problems with tab view on android.
Tabs are placed in parent ScrollView and scroll view height is programatically changed with tab index change.

On iOS everything works great but on android it's buggy, tabs changes are weird. By using Tab TabViewPagerPan it's working great but for using it on android I need to change switch statement. Api is needed to use custom tab view pager.

**Comment by satya164** [comment]
I'm not sure what you mean by `need to change switch statement`. Also you can use a custom pager with `renderPager`
