### ISSUE TITLE
Issues with scrolling and indicator when scrolling is enabled

### ISSUE THREAD

**Issue by nehvaleem** [react-native-community/react-native-tab-view#266]
I've got an problem with react-native-tab-view. When i set tabbar to be scrollable via `scrollEnabled` prop and style my tabs to have different widths based on their labels the indicator and scrolling is messed up. 

Screenshot below demonstrates this issue. (recipes tab is active. it is misaligned and indicator is simply wrong).

![screen shot 2017-05-24 at 22 44 00](https://cloud.githubusercontent.com/assets/210136/26424828/df0afae2-40d2-11e7-8b72-d6888c25d9a7.png)

Can I do something about it or maybe react-native-tab-view doesn't support various width in tabs? If so - are there any plans to add it?

**Comment by ashrithks** [comment]
Can you post your code?

**Comment by nehvaleem** [comment]
@ashrithks I am using react-native-tab-view via react-navigation and this is the way i've configured it in my navigator

```
(...)
tabBarOptions: {
      scrollEnabled: true,
      style: {
        backgroundColor: 'rgba(0,0,0,0.7)',
        height: 40,
        position: 'absolute',
        bottom: 0,
      },
      activeTintColor: 'white',
      inactiveTintColor: 'rgba(255,255,255,0.8)',
      tabStyle: {
        height: 40,
        width: 'auto',
      },
      indicatorStyle: {
        backgroundColor: ForShapeTheme.primaryColor
      }
    },
(...)
```

**Comment by satya164** [comment]
Right now the indicator cannot work with dynamic tab width. It's a bit complicated to implement it. PRs welcome.

**Comment by nehvaleem** [comment]
@satya164 thanks for the clarification.

**Comment by ricardofbarros** [comment]
Hey @nehvaleem a quick (dirty) workaround is to set your indicator via the `renderIcon` method.

I don't know how you integrated react-native-tab-view into react-navigation, but using the example on readme you could do the following:

```

export default class TabViewExample extends PureComponent {
  state = {
    index: 0,
    routes: [
      { key: '1', title: 'First' },
      { key: '2', title: 'Second' },
    ],
  };

  _handleChangeTab = index => this.setState({ index });

  _renderIndicator = (position) => {
    return ({ index }) => {
      let style = {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: 2
      }

      if (position === index) {
        style = {
          ...style,
          borderTopWidth: 2,
          borderColor: 'orange'
        }
      }

      return (<Animated.View style={style} />)
    }
  }

  _renderHeader = props => 
    <TabBar 
      {...props}
      renderIndicator={() => null}
      renderIcon={this._renderIndicator(props.navigationState.index)}
    />;

  _renderScene = SceneMap({
    '1': FirstRoute,
    '2': SecondRoute,
  });

  render() {
    return (
      <TabViewAnimated
        style={styles.container}
        navigationState={this.state}
        renderScene={this._renderScene}
        renderHeader={this._renderHeader}
        onRequestChangeTab={this._handleChangeTab}
      />
    );
  }
}
```

@satya164 What's your opinion on injecting the `indicatorStyle` [here](https://github.com/react-native-community/react-native-tab-view/blob/master/src/TabBar.js#L472) instead of [creating a separate component for the indicator](https://github.com/react-native-community/react-native-tab-view/blob/master/src/TabBar.js#L364)?. If you create a separated component it will be harder and more prone to bugs, why not just extend the style object of the selected tab? You can get the currently selected tab through the index of the navigation state.

**Comment by nehvaleem** [comment]
Awesome, thanks @ricardofbarroa - I'll have a look at your idea.

**Comment by satya164** [comment]
@ricardofbarros Indicator moves independently, which is apparent especially when you have a scrollable tab bar. There are issues with animation (currently) when the indicator is not independent from the scrollable area of the tab bar. But using `renderIcon` or `renderLabel` to render indicator is a reasonable workaround.

**Comment by donnes** [comment]
Any update about this issue?

**Comment by AnisDerbel** [comment]
Same issue here
