### ISSUE TITLE
what's the best way to achieve margin spacing between scenes?

### ISSUE THREAD

**Issue by faceyspacey** [react-native-community/react-native-tab-view#269]
Say you have a logo behind your scenes, and your scenes are transparent and you can slightly see it. But when you swipe between pages, you want to see the logo in all its glory in between pages (Hotel Tonight used to do this). 

Basically you want to put about 100 `marginRight` between scenes, and having snapping and the animated line in the tab bar all still work.

**Comment by satya164** [comment]
This is not possible with ScrollView or ViewPagerAndroid AFAIK. But you should be able to achieve it by using `TabViewPagerPan` and customising the styles. See the [CoverFlow](https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/CoverflowExample.js#L48) example on how to customize it.

**Comment by faceyspacey** [comment]
Awesome. Thanks!
