### ISSUE TITLE
Android: v0.0.66 - initial screens not loading properly 

### ISSUE THREAD

**Issue by atpunk** [react-native-community/react-native-tab-view#275]
Device: Samsung Galaxy S5
Navigation: react-native-router-flux
app.js: react-native-tab-view {Tab1, Tab2, Tab3, Tab4, Tab5}
3rd tab: Secondary react-native-tab-view {Tab3-1, Tab3-2}

When viewing my app's 3rd tab, the Tab3-1 is not loaded. The screen remains white until I change to 3-2. Only then am I able to swipe and view freely.

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
