### ISSUE TITLE
hi, how to show many items 

### ISSUE THREAD

**Issue by banli17** [react-native-community/react-native-tab-view#276]
i have many items,tabbar width is not enough, but can't scroll left or right to show tabbar。

**Comment by zivchen** [comment]
+1

**Comment by JensDebergh** [comment]
We are having similar issues in our app. Long labels push outside the bounds of any phone which is ok as long as the tabbar header is scrollable. 

Wrapping a `<ScrollView>` around `<TabBarTop>` makes it scrollable but labels and active state are screwed.

![screen shot 2017-06-22 at 12 19 58 pm](https://user-images.githubusercontent.com/6651506/27429384-2b3fd62a-5745-11e7-894e-45238d2b45d0.png)

**Comment by satya164** [comment]
@JensDebergh do you have a repro? can you show o https://snack.expo.io ?

**Comment by JensDebergh** [comment]
I'm unable to post our codebase but I'll try to make a reproducable example soon.

The problem I imagine is using  `ScrollView` which needs a style prop `height: fixedHeight` or `flex: 1` to work properly. 

Setting a fixed height on the header works but the label offsets aren't correct afterwards.

**Comment by satya164** [comment]
A repro will help me debug.

**Comment by mohitjuyal98** [comment]
try this <TabBar scrollEnabled {...props} />

**Comment by sibelius** [comment]
`<TabBar scrollEnabled {...props} />` works fine

we can close this

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
