### ISSUE TITLE
Flow / ESLint errors when importing named modules

### ISSUE THREAD

**Issue by joncursi** [react-native-community/react-native-tab-view#277]
I've been having this issue for the past few months and finally bugged me enough to create an issue :)

When I import anything from this module, say:

```
import { SceneMap, TabViewAnimated } from 'react-native-tab-view';
```

Flow and ESLint complain:

![screen shot 2017-06-06 at 6 25 25 pm](https://user-images.githubusercontent.com/4974609/26854764-941b876e-4ae5-11e7-9680-325a3ac4e127.png)

Even though the modules still work properly in the code. Any ideas on why this is?

**Comment by satya164** [comment]
Seems like a problem with your setup. I'm closing this since I can't repro it.
