### ISSUE TITLE
does it possible to enableScroll only if tab items width is > than screen size?

### ISSUE THREAD

**Issue by scerelli** [react-native-community/react-native-tab-view#279]

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
