### ISSUE TITLE
Infinite routes behavior

### ISSUE THREAD

**Issue by Freddy03h** [react-native-community/react-native-tab-view#281]
Hi,
I'm working on a Planning component, on a feature that allows sliding between days. I think this component can achieve this behaviour. Each tab (route) is a day, but routes are redefined after each `changeTab`.

I tried to implement this behaviour (but with number instead of a date).

## Sliding to the right is OK:
![tab-view-right](https://user-images.githubusercontent.com/1412159/27192847-1c8f56e8-51fd-11e7-8162-edcfa4592391.gif)

## Slide to the left is weird:
![tab-view-left](https://user-images.githubusercontent.com/1412159/27192856-268aa0f8-51fd-11e7-8cd4-699da58ef6e3.gif)

## Code:
It works well if we go to the right because we are adding a route at the end of the list without redefining the index given by `onRequestChangeTab`. But when we go to the left, we need to keep the previous index and just add a route a the beginning, but it triggers an unwanted animation.

```js
export default class Planning extends Component {

  // 5 routes is ok to never feel the end of the list
  // index 2 : start in the middle
  state = {
    index: 2,
    routes: [
      { key: '1', title: '1' },
      { key: '2', title: '2' },
      { key: '3', title: '3' },
      { key: '4', title: '4' },
      { key: '5', title: '5' },
    ],
  }

  handleChangeTab = (index) => {
    const { routes, index: oldIndex } = this.state

    const newRoutes = [...routes]
    const currentRoute = routes[oldIndex]
    const currentRouteKey = parseInt(currentRoute.key)

    let newIndex = index

    // go to the right
    if (newIndex > oldIndex) {
      const lastRoute = newRoutes[newRoutes.length - 1]
      const lastRouteKey = parseInt(lastRoute.key)

      // anticipate 2 routes
      if (Math.abs(lastRouteKey - currentRouteKey) < 3) {
        // new key route
        const newKey = lastRouteKey + 1

        // add the new route at the end
        newRoutes.push({key: String(newKey), title: String(newKey)})
      }

    // go to the left
    } else {
      const firstRoute = newRoutes[0]
      const firstRouteKey = parseInt(firstRoute.key)

      // anticipate 2 routes
      if (Math.abs(firstRouteKey - currentRouteKey) < 3) {
        // new key route
        const newKey = firstRouteKey - 1

        // add the new route at the begin
        newRoutes.unshift({key: String(newKey), title: String(newKey)})
        // and increment index because of the unshift
        newIndex++
      }
    }

    this.setState({
      routes: newRoutes,
      index: newIndex,
    })
  }

  renderHeader(props) {
    return (
      <TabBar
        {...props}
        scrollEnabled
      />
    )
  }

  renderScene({ route }) {
    return (
      <View style={styles.page}>
        <Text style={styles.title}>{ route.title }</Text>
      </View>
    )
  }

  render() {
    return (
      <TabViewAnimated
        style={styles.container}
        navigationState={this.state}
        renderScene={this.renderScene}
        renderHeader={this.renderHeader}
        onRequestChangeTab={this.handleChangeTab}
      />
    )
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.SOFT_GRAY,
  },
  page: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center'
  },
  title: {
    fontSize: 38,
  }
})

```

Do you have an idea if this can be fixed? It feel like it can complicated because instead of giving an index, we should provide the selected key to the component. But I know this structure (`{ routes: [], index }`) is here to match the react-navigation API.

Do you have an idea if this behaviour is possible with react-native-tab-view ?
Thank you.

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
