### ISSUE TITLE
Swipe delay

### ISSUE THREAD

**Issue by Rafaell416** [react-native-community/react-native-tab-view#282]
Hello guys, I'm having a trouble with the tab bar, when I swipe or tap the items. There's a delay in the transitions.
Help me please.

[video.mp4.zip](https://github.com/react-native-community/react-native-tab-view/files/1087194/video.mp4.zip)

**Comment by brainahdev** [comment]
Yes I too face the same issue. Can any one share your ideas?

**Comment by herarya** [comment]
Yes I too face the same issue, only android , ios work fine

**Comment by 11et401012** [comment]
hi  I  am  also  getting  same issue, only android , ios work fine
please help  me

**Comment by Fuhrmann** [comment]
yeah, having the same problem using Android API version 19.

**Comment by jlkalberer** [comment]
Did anyone come up with a fix for this?

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
