### ISSUE TITLE
Cannot get route to re-render with new props following README.md

### ISSUE THREAD

**Issue by farhanmannan** [react-native-community/react-native-tab-view#283]
I have the following code in my 'parent' component:
```
  _renderScene = SceneMap({
    '1': () => <Weight weights={ramda.path(['user', 'user', 'weights'], this.props)} />,
    '2': StepsRoute,
    '3': SleepRoute,
  });
``` 
which, if i save the file for <Weight>, forcing a hot reload, will work. (To clarify, `ramda.path` call returns `undefined` until the `this.props.user.user.weights` is defined and then returns it).

I followed the instructions in `README.md` i.e. I added `loaded.false` to state (and tried changing the line `renderScene={this.renderScene} to `renderScene={_this.renderPage}` although I don't understand what that would do, and it caused an error), and it still doesn't reload when the props come through to the parent component. 

Is there a more detailed guide or example for getting my `<Weight>` component (i.e. a "route") to reload when the props to the parent component (the one importing `TabViewAnimated`, `TabBar` and `SceneMap`) are updated? 

Thank you!

**Comment by satya164** [comment]
Don't use `SceneMap` if you need to use `this.props`. Check the examples folders for alternative usage.

**Comment by kylebebak** [comment]
@satya164  @farhanmannan 

I had the same issue. Linking to the example in question might be a nice idea, it looks like it's [right here](https://github.com/react-native-community/react-native-tab-view#caveats) in the README.

**Comment by benhannel** [comment]
Thanks @kylebebak for pointing me in the right direction. For anyone who needs a little more detail about how to get a tab to re-render, there are two things you must do. The relevant state must be in the navigationState prop, and you must replace SceneMap (as below)

 >_renderScene = SceneMap({
		'1': () => \<MyPosts listData={this.state.listData} />,
		'2': () => \<MyApplications />
	});

with something more like this

>_renderScene = function(route) {
		const scenes = {
			'1': \<MyPosts listData={route.navigationState.listData} />,
			'2': \<MyApplications />
		};
		return scenes[route.route.key];
	};

**Comment by venkatmithunk** [comment]
@satya164  please mention clearly in docs/examples to not use sceneMap if you have this.props
