### ISSUE TITLE
How to embed tab-view inside a bigger view

### ISSUE THREAD

**Issue by avratmic** [react-native-community/react-native-tab-view#287]
I have a requirement where the tab-view is created as per the button clicked in the footer. So basically there are 3 buttons at the footer and clicking any of these should create specific tab-view with a footer (so there will be two footers) and the scene will be generated on the basis of the tab selected in tab-view. So the cumulative effect is that a the scene is determined by both the footer's selected value. 

To implement this I am trying to define TabViewAnimated inside View so that I can add a sibling to it. Doing this results in empty screen. How to fix this?

**Comment by azundo** [comment]
Try setting `style={{flex: 1}}` on your TabView - sounds to me like it currently has 0 height. Check the flex styling on any containing views as well - somewhere in your view hierarchy you're likely missing a flex style that is causing the view to be 0 height.

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.

**Comment by rohit-ganapathy** [comment]
Hey @avratmic  Did you finally solve this this?
