### ISSUE TITLE
Rendering pages twice 

### ISSUE THREAD

**Issue by happierco** [react-native-community/react-native-tab-view#29]
I am trying tabview using the example code given in the readme using two components as pages. The pages are rendered twice at the beginning. Do you have any idea why and any suggestions?

**Comment by satya164** [comment]
@happierco It's probably due to `onLayout` firing. As mentioned in the README, you should apply `shouldComponentUpdate` to your individual pages anyways - https://github.com/react-native-community/react-native-tab-view#optimization-tips

**Comment by satya164** [comment]
Feel free to close the issue if this answers your question @happierco

**Comment by happierco** [comment]
It is solved. Thank you @satya164.
