### ISSUE TITLE
Shadow in android 

### ISSUE THREAD

**Issue by hyochan35** [react-native-community/react-native-tab-view#291]
![image](https://user-images.githubusercontent.com/20625109/27918797-fd332112-62aa-11e7-9daf-ed4a5a2b60e3.png)

There is shadow in android and how can I get rid of it when I make your tab-view with small size?

It looks ok and Iphone

**Comment by ChrisGatzo** [comment]
Looks like the shadow comes from the elevation property applied to the tabBar. I had to pass a style property to override it like this 

` renderHeader = props => <TabBar style={{elevation:0}} {...props} />;`

and then to the TabViewAnimated

`  renderHeader={this.renderHeader}`

This worked for me but not sure what issues it might cause by not having an elevation there.

**Comment by satya164** [comment]
It's the correct way to remove shadow on Android.

**Comment by hyochan35** [comment]
It's solved. Thank you!
