### ISSUE TITLE
Tabview "ScrollEnabled" not working 

### ISSUE THREAD

**Issue by nandhakishore14** [react-native-community/react-native-tab-view#292]
<TabBar
      {...props}

      indicatorStyle={styles.indicator}
      style={styles.tabbar}
      renderLabel={this.renderLabel}
      renderIcon={this._renderIcon}
      scrollEnabled ={false}
      
    />

**Comment by coderdave** [comment]
No update on this? Setting `scrollEnabled` to `false` has no effect.

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
