### ISSUE TITLE
undefined is not an object (evaluating 'navigatiomState.routes.map)

### ISSUE THREAD

**Issue by twisstosin** [react-native-community/react-native-tab-view#293]
Trying to integrate the basic thing as on the readme, but this error keeps popping up.
![screen shot 2017-07-07 at 4 47 36 pm](https://user-images.githubusercontent.com/12116352/27966067-cc97aa10-6335-11e7-9745-aed7b14c2755.png)

**Comment by ixje** [comment]
I expect it's one of the following 2 causes (or both):

1. You've not provided a `navigationState` prop to `TabViewAnimated`
2. (most likely cause), you provided a state does not have `routes` key
follow the format from the example, e.g:
```
  state = {
    index: 0,
    routes: [
      { key: '1', title: 'First' },
      { key: '2', title: 'Second' },
    ],
  };
```

**Comment by twisstosin** [comment]
Fixed, state was in the wrong position.
