### ISSUE TITLE
Jump to tab programmatically 

### ISSUE THREAD

**Issue by yogevlahyani** [react-native-community/react-native-tab-view#296]
Hi! I am trying to make a tab change when onPress an inside route component button and I can't manage to pass props and change the state of the index.

HomeScreen (Child) Component:
`<Button title="Add new" onPress={() => { pass index number to Parent Component Where TabViewAnimated is }>`

Main (Parent) Component:
`_renderScene = SceneMap({
    '1': AddNew, // Trying to get to here
    '2': HomeScreen,
  });`

I've been searching all over google and can't manage to pass props and change the state ..

**Comment by ixje** [comment]
have a call back in your Main Component and pass that to your HomeScreen via props

**In Main**

```
_updateRoute(newIdx) {
this.setState({index: newIdx})
}

```
pass the handler together in the TabViewAnimated:
```
      <TabViewAnimated
        style={styles.container}
        navigationState={this.state}
        renderScene={this._renderScene}
        renderHeader={this._renderHeader}
        onRequestChangeTab={this._handleChangeTab}
        changeRoute={this._updateRoute.bind(this)}
      />
```

**In HomeScreen**
`<Button title="Add new" onPress={this.props.changeRoute(<route number>)}>`

**Comment by yogevlahyani** [comment]
@ixje Thank you!!

**Comment by zhukovka** [comment]
This doesn't work for the version 0.0.69. I can't find a way to do it.

**Comment by ixje** [comment]
@zhukovka probably because of the [breaking changes](https://github.com/react-native-community/react-native-tab-view/commit/bb74c814275d2ec2931cda2144d37831076487e4). Try renaming the `onRequestChangeTab` prop to `onIndexChange`.

**Comment by befirst** [comment]
> SceneMap
> Helper function which takes an object with the mapping of route.key to React components and returns a function to use with renderScene prop.
> 
> renderScene = SceneMap({
>   first: FirstRoute,
>   second: SecondRoute,
> });
> Each scene receives the following props:
> 
> route: the current route rendered by the component
> jumpTo: method to jump to other tabs, takes a route.key as it's argument

so just make a prop "jumpTo(key)" in your component and use it, for example in doc it FirstRoute and SecondRoute
