### ISSUE TITLE
Lazy doesn't render other tabs

### ISSUE THREAD

**Issue by yogevlahyani** [react-native-community/react-native-tab-view#298]
Hello, I am using react native with RTL support (RTL FORCE on android) and RN-tab-view works great.

I want it to render as the user opens the tab.

when I add lazy it renders only the first scene, when I slide to another tab it gets me back to the initial tab screen but on the tabs it shows me that the active tab is the tab before, when I slide again it switches to the next tab but doesn't render.

`
<TabViewAnimated
        lazy
        style={styles.tabBarView}
        navigationState={this.state}
        renderScene={this._renderScene}
        renderFooter={this._renderFooter}
        onRequestChangeTab={this._handleChangeTab}
      />
`

**Comment by andrerfneves** [comment]
Also experiencing the issue above

**Comment by andrerfneves** [comment]
If I don't use `SceneMap` utility func, the `lazy` property works.

**Comment by antoinerousseau** [comment]
I have this happening only on Android

**Comment by flowYogi** [comment]
+1

**Comment by jordanmkoncz** [comment]
Just ran into this issue as well. For now I'm just setting `lazy` to `false` on Android, as I don't want to lose the optimisations that are provided by `SceneMap`. Hopefully this can be fixed soon!

**Comment by satya164** [comment]
There is no `lazy` prop anymore. Also, it was never the default, so you don't need to set it to `false`
