### ISSUE TITLE
When we click the tab, the change of the tab text is the opacity,not the color.

### ISSUE THREAD

**Issue by spicyboiledfish** [react-native-community/react-native-tab-view#299]
### Expected behaviour
The text color of the tab is black by default. And when we click one of the tab, current color changes to blue.Another tab's color still black.

### Actual behaviour
Now the code shows that the text opacity is 0.7 by default, and when we click one of the tab, current   opacity changes to 1.

### Code sample, screenshots
In the TabBar.js, the 394 line.
const outputRange = inputRange.map(
    inputIndex => (inputIndex === i ? 1 : 0.7),
);

### What have you tried
I tried to add a variable like opacity to change color,but in vain.

**Comment by ixje** [comment]
If I understand you correctly you want the active tab label to have a colour and the non-active tab labels to be black. If so, have a look at example 5 "Scroll views with lazy load", specifically the [_renderLabel](https://github.com/react-native-community/react-native-tab-view/blob/8ed6baaf9e1fcb118780bf1538ffafe88879ef1a/example/src/ScrollViewsExample.js#L65-L80) part.

**Comment by spicyboiledfish** [comment]
Thank U. It worked.

**Comment by ixje** [comment]
You're welcome :-)

Please close the issue if you're problem is solved.
