### ISSUE TITLE
Tabs Header Lowercase text and auto width

### ISSUE THREAD

**Issue by michelarteta** [react-native-community/react-native-tab-view#306]
I am trying to lowercase the title but can't find where the title is inserted into the tabs, just see an array which is in lower case also how can I set the with to auto on the tabs. Thanks 

<img width="373" alt="screen shot 2017-07-19 at 1 31 22 pm" src="https://user-images.githubusercontent.com/4356002/28380966-31e2b2ac-6c87-11e7-8812-5cf7883647fc.png">

**Comment by andrejunqueira1** [comment]
You can use `renderLabel` callback from TabBar, and you can style your label, ex : 

`_renderLabel = scene=><Text style={ styles.labelStyle }>{ scene.route.title }</Text>
<TabBar 
        {...props} 
         renderLabel={ this._renderLabel }
         onTabPress={({index})=>{ this.setState({index})}}
         style={ styles.tabBar }
         tabStyle={ styles.tabStyle }
       />;
`

**Comment by satya164** [comment]
You can use [`getLabelText` prop](https://github.com/react-native-community/react-native-tab-view#props-4) for lowercase text.

Auto-width is not possible currently.

**Comment by ashokkumar88** [comment]
For auto width you can try https://github.com/madhu314/react-native-tabbed-view-pager-android
