### ISSUE TITLE
Example application  is not working

### ISSUE THREAD

**Issue by jakubmichalko** [react-native-community/react-native-tab-view#309]
I am trying to run your example application  from https://github.com/react-native-community/react-native-tab-view that is not working properly. 
My target is to manualy switch the tabs, but I made no success. 
I am using:   "react-native-tab-view": "0.0.67", 

### Expected behaviour
1. no warning
2. click on tab should switch the content 
### Actual behaviour
1. It evokes warning: Failed prop type: The prop 'onRequestCangeTab' is marged as required in 'TabViewAnimated', but its value is indefined. 

2.  I can swipe (by finger) the content and the tab indicator in header is showing current tab properly. But if I click on tab header, the content is not switching. 

### Code sample, screenshots
import React, { PureComponent } from 'react';
import { View, StyleSheet } from 'react-native';
import { TabViewAnimated, TabBar, SceneMap } from 'react-native-tab-view';

const FirstRoute = () => <View style={[ styles.container, { backgroundColor: '#ff4081' } ]} />;
const SecondRoute = () => <View style={[ styles.container, { backgroundColor: '#673ab7' } ]} />;

export default class TabViewExample extends PureComponent {
  state = {
    index: 0,
    routes: [
      { key: '1', title: 'First' },
      { key: '2', title: 'Second' },
    ],
  };

  _handleIndexChange = index => this.setState({ index });

  _renderHeader = props => <TabBar {...props} />;

  _renderScene = SceneMap({
    '1': FirstRoute,
    '2': SecondRoute,
  });

  render() {
    return (
      <TabViewAnimated
        style={styles.container}
        navigationState={this.state}
        renderScene={this._renderScene}
        renderHeader={this._renderHeader}
        onIndexChange={this._handleIndexChange}
        onRequestCangeTab={(index)=>{}}
      />
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});
### What have you tried
1. I added empty function   onRequestCangeTab={(index)=>{}}  to silence the warning
2. I tried to switch it manualy (from other button). by method "tab._jumpToIndex(1)" manualy, but with no result

**Comment by lf-alves** [comment]
I was having the same problem. I simply added onRequestChangeTab={this._handleIndexChange} to <TabViewAnimated />and it seems to work properly now.

**Comment by satya164** [comment]
Sorry, there has been an API change in master. For latest published version, you can find the example here https://github.com/react-native-community/react-native-tab-view/tree/v0.0.67

**Comment by ihorkolomoyskyi** [comment]
I have same problem.  
https://github.com/react-native-community/react-native-tab-view/tree/v0.0.67

I tried it with above link.  but same error occurred.
