### ISSUE TITLE
Can I use replace TouchableItem with my own container component?

### ISSUE THREAD

**Issue by stackia** [react-native-community/react-native-tab-view#310]
### Expected behaviour
I implemented a custom button component and want to use it on TabBar instead of the default TouchableItem. But currently there is no easy way to do this. Could you add a prop on TabBar to let users provide their own container component? For example:

```
<TabBar
  renderLabelContainer={(scene, onPress) => <MyCustomButton onPress={onPress} />}
/>
```

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
