### ISSUE TITLE
Handle click event in TabBar (TouchableItem)

### ISSUE THREAD

**Issue by BenoitClaveau** [react-native-community/react-native-tab-view#311]
### Handle click event.

My project use react-navigation with redux StackNavigator and TabNavigatror

### Code sample, screenshots
in ToucheableItem.js

_handlePress = () => {
    global.requestAnimationFrame(this.props.onPress);
};

### What have you tried

If I replace the line global.requestAnimationFrame(this.props.onPress); by just calling the this.props.onPress() the buf i fixed and the current tab change. 

Benoît.

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
