### ISSUE TITLE
[Android] In a nested tab, can't navigate to another page

### ISSUE THREAD

**Issue by Minishlink** [react-native-community/react-native-tab-view#312]
Context: On Android, I have a TabViewPagerAndroid inside a TabViewPagerPan (using `react-navigation`). When calling `setPage` of the `TabViewPagerAndroid`, the new page should appear.

### Expected behaviour
The button at the bottom right is clicked and the corresponding page is focused.
![works mp4](https://user-images.githubusercontent.com/82368/28498677-1c409a8a-6fa3-11e7-8070-a8054f838214.gif)

### Actual behaviour
The button at the bottom right is clicked but the corresponding page is not focused.
`setPage` is called but `onPageSelected` is not.
![doesntwork mp4](https://user-images.githubusercontent.com/82368/28498678-1f53b0a4-6fa3-11e7-9a08-ff14f332cb66.gif)

### Code sample, screenshots
See above gifs

### What have you tried
1. Changing `lazy` doesn't do anything
2. Forcing using TabViewPagerPan works but the implementation has wrong feelings in transitions (and you can't force it using react-navigation)
3. Setting an initialLayout to minimum `{ width: 1, height: 1 }` fixes the issue. In order to have the full page rendered during the first render, I set it to `Dimensions.get('window')`.

So there's a workaround (similar to #297), but it seems hacky.
Here are commits with the hacky workaround: [react-native-tab-view](https://github.com/Minishlink/react-native-tab-view/commit/2ce4bad66445a1d5c2b9f13e0fbf648915ced179) ; [react-navigation](https://github.com/Minishlink/react-navigation/commit/c326c9ba43e101d85b8e590ba9fba9ee0652d5c9)

**Comment by jordanmkoncz** [comment]
I'm having a similar problem, and it seems to be happening in versions `0.0.65` through to `0.0.69`. I'm using react-native-tab-view in the context of react-navigation. I have a tab bar that works perfectly fine on iOS, but on Android when I press on a tab to switch to it, the tab bar does not actually switch to the tab I pressed, it just does nothing. I know that the press itself is being registered (as a `Navigation/NAVIGATE` action is dispatched in response` but the tab bar just doesn't update to show the new correct tab.

I used your fix in https://github.com/Minishlink/react-navigation/commit/c326c9ba43e101d85b8e590ba9fba9ee0652d5c9 of setting `initialLayout` and this resolved the problem for me and got the tab bar to behave correctly.

Interestingly, the solution posted at https://github.com/react-community/react-navigation/issues/662#issuecomment-290938479 of setting `swipeEnabled: false, animationEnabled: false` (setting `lazyLoad: true` was not necessary for me) also resolve the problem for me.

**Comment by ACCTFORGH** [comment]
I had similar issue in 0.0.74. I nested a react-native-tab-view (tabview2) under the tab of another  one(tabview1), and tabview2 just couldn't navigate when clicked on the tabs.

**Comment by ACCTFORGH** [comment]
I found a hacky workaround. If you don't mount the nested tabview same time as the parent tabview, the problem got resolved. For example, you can 1) set lazy loading and shift the tab with the nested tabview away from the 1st tab or 2) sacrifice performance and use a timer to trigger the mounting of the nested tabview. I found similar issues with other tabview/viewpager libraries as well. I suspect it's more related to the underlying Animate API.

**Comment by XiaoweiLiu0812** [comment]
> I found a hacky workaround. If you don't mount the nested tabview same time as the parent tabview, the problem got resolved. For example, you can 1) set lazy loading and shift the tab with the nested tabview away from the 1st tab or 2) sacrifice performance and use a timer to trigger the mounting of the nested tabview. I found similar issues with other tabview/viewpager libraries as well. I suspect it's more related to the underlying Animate API.

amazing!!!
