### ISSUE TITLE
[Android] App crash : output range must have at least 2 elements 

### ISSUE THREAD

**Issue by zhuyifan2013** [react-native-community/react-native-tab-view#313]
### Expected behaviour
TabBar should work well
### Actual behaviour
App crash some times
### Code sample, screenshots
I debugged TabBar's render method, the correct way is :
<img width="1173" alt="2017-07-25 12 23 07" src="https://user-images.githubusercontent.com/3753079/28555731-66f03f08-7134-11e7-8597-09a0d23ebc8e.png">

And the crash way is : 
<img width="1174" alt="2017-07-25 12 24 01" src="https://user-images.githubusercontent.com/3753079/28555740-6fa0b8da-7134-11e7-8364-165e4a72c551.png">

### What have you tried
Debug render method

**Comment by zhuyifan2013** [comment]
It always occurs when I open "Don't keep activities" in android Developer Options

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
