### ISSUE TITLE
Does not work in android

### ISSUE THREAD

**Issue by developer239** [react-native-community/react-native-tab-view#314]
...gonna use something else...

**Comment by satya164** [comment]
I use it on Android (lots of people do actually) and I works fine. There is something specific to your setup where it breaks. Can you please provide a repro of the issue? You can post it on http://snack.expo.io

**Comment by isnifer** [comment]
@satya164 removing zIndex produces an error. I can't tap on tab bar. It works only on iOS

**Comment by ikhsanalatsary** [comment]
Same here, it's not working on Android.

**Comment by satya164** [comment]
Please provide a repro with the issue, and if you get an error, post the error message. Just saying that I have the issue will not fix it, neither will help in any way.

**Comment by ikhsanalatsary** [comment]
Ok, I'm preparing it

**Comment by ikhsanalatsary** [comment]
Repo: https://github.com/ikhsanalatsary/project-rn
Demo App: https://i.diawi.com/BQEcFj

**Comment by huiming1313** [comment]
any update on this issue ?
In android i tap the tab is not giving me any response, IOS is working fine tough.

expo : "^25.0.0"
react-native-tab-view: "0.0.74"

**Comment by developer239** [comment]
I would like to apologize for the message that I wrote in this issue. However, I was quite frustrated because right now react-native ecosystem is extremely unpredictable. Many libraries don't work. Some of them work in older versions of react-native. The good ones work either on Android or on IOS. Finding cross-platform library is really hard.

I was working on two production-ready applications in my job for about 5-6 months. I liked it but whenever I had to present anything in react-native to my co-workers it was really hard. IOS guys were basically making fun of me and they had a right to do so.

I had to change this library to `react-native-scrollable-tab-view` in my first project.

I used `react-native-scrollable-tab-view` in my second project from the beginning.

If this library still does not work correctly on android then it should be labeled as IOS only library or it should be taken down from GitHub. Not because of me. But because it would improve the general health of the react-native community.

Edit: Haha look at the `react-native-scrollable-tab-view` github page. https://github.com/skv-headless/react-native-scrollable-tab-view Example images are not working. Example link to a demo is not working. That is what I am talking about. I appreciate the hard work that `react-native-community` and `skv-headless` put in their libraries but these are one of many examples that `react-native` is not production ready at least for another year.

**Comment by satya164** [comment]
It's not possible for me to debug this without a reduced repro case. @ikhsanalatsary thanks for the repro, but the app you linked to has a lot of things which doesn't make it easy for me to repro this.

@developer239 it's still unclear what exactly didn't work for you. we use it in production at our company and it has worked fine. it's not possible to debug an issue without any kind of info.

react-native is production ready, facebook and many other companies use it in production. many libraries available are not production ready, but that's a separate issue.

I'm closing this issue. Please open a new issue if you have a reduced test case and follow the issue template so we have enough information to debug the issue.

**Comment by ikhsanalatsary** [comment]
I Will Creating a new issue with simple repro. I faced this problem if Children components are textinput
