### ISSUE TITLE
Attempted to remove more RCT NativeAnimatedModule listeners than added

### ISSUE THREAD

**Issue by joncursi** [react-native-community/react-native-tab-view#319]
Hitting this issue after upgrading from `0.0.68` -> `0.0.69`. Only happens when navigating to a screen that contains a tab view from this library.

![screen shot 2017-08-03 at 3 26 17 am](https://user-images.githubusercontent.com/4974609/28910685-de15f9e2-77fb-11e7-8dbb-aa64c007a27c.png)

**Comment by satya164** [comment]
I don't use native animations yet. So seems like a React Native bug. Please post a repro.

**Comment by joncursi** [comment]
Alright. I also just upgraded from `0.47.0` RN to `0.47.1`. Odd thing happened. I removed the TabView component and rendered the screen successfully. Then restored TabView component and voila, the screen rendered with the tab view. Definitely feels like RN / upgrade internals.
