### ISSUE TITLE
Scrollable top bar

### ISSUE THREAD

**Issue by AvijitDutta95** [react-native-community/react-native-tab-view#324]
### Expected behavior
Can it possible to hide tab bar title and just display only tab bar icons/names when scrollable page horizontally as per WhatsApp tab bar??

### Actual behavior
Nothing 

### What have you tried
Confused

**Comment by txs** [comment]
Yes need this fix with changing the tabbar back to overflow:auto

**Comment by ixje** [comment]
Can you provide a screenshot of what you're trying to do? Don't assume everybody uses WhatsApp or knows what you're referring to.

**Comment by txs** [comment]
This is the overflow scroll
![image](https://user-images.githubusercontent.com/554329/29053562-65b7ce0e-7c23-11e7-8862-9c89a0ca67ac.png)
This is the overflow auto
![image](https://user-images.githubusercontent.com/554329/29053578-801b090a-7c23-11e7-8140-e75fe0a9ef7f.png)

Please approve the PR
https://github.com/react-native-community/react-native-tab-view/pull/325

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
