### ISSUE TITLE
Tab Indicator width without affecting tab itself

### ISSUE THREAD

**Issue by fxfactorial** [react-native-community/react-native-tab-view#333]
I'm able to get the indicator on top with this code: 

```
const footer_bar = p => {
  return (
    <TabBar
      {...p}
      indicatorStyle={{
        backgroundColor: TAB_SLIDER_COLOR,
        top: 0
      }}
      style={{
        backgroundColor: 'white'
      }}
      renderIcon={render_icon}
    />
  );
};
```

But I need the width of the indicator itself to be narrower. I've tried playing with width, padding, margin but it creates unequal offsets. 

What i want is something like this: 
<img width="108" alt="screen shot 2017-08-17 at 4 33 14 am" src="https://user-images.githubusercontent.com/3036816/29410342-f833069e-8304-11e7-9544-6e109ed9425d.png">

but have: 

<img width="119" alt="screen shot 2017-08-17 at 4 33 34 am" src="https://user-images.githubusercontent.com/3036816/29410363-069f40da-8305-11e7-845d-a99d016553b5.png">

**Comment by satya164** [comment]
You can use `renderIndicator` prop to render your own indicator with custom styles

**Comment by fxfactorial** [comment]
@satya164 I tried that previously, for example: 

      renderIndicator={indicator}


```
const indicator = e => {
  return (
    <View
      style={{
        width: 30,
        backgroundColor: TAB_SLIDER_COLOR,
        top: 0,
        height: 1
      }}
    />
  );
};
```

But with this code, I lose the sliding animation when switching tabs, it doesn't move.

**Comment by satya164** [comment]
You receive props to do the animation. Check the default implementation here https://github.com/react-native-community/react-native-tab-view/blob/master/src/TabBar.js#L171

**Comment by fxfactorial** [comment]
woof, this is digging deeper than initially expected. Okay thank you, this will keep me occupied

**Comment by rodrigoxavier** [comment]
@satya164 to keep the animation you must to put this view inside a <Animated.View> how shown in the docs.

The code follows:

```
return (
      <Animated.View style={[styles.container, { width, transform: [{ translateX }] }]}>
        <View
        style={{
          width: 30,
          backgroundColor: TAB_SLIDER_COLOR,
          top: 0,
          height: 1
        }}
      />
      </Animated.View>
    );
```

**Comment by nenjamin2405** [comment]
Hi @rodrigoxavier , based on your suggestion, how can I get the translateX in the props returned. I saw the source code only return these props:

{
            position,
            layout,
            navigationState,
            jumpTo,
            addListener,
            removeListener,
            width: tabWidth,
            style: indicatorStyle,
          }
