### ISSUE TITLE
How to show tab lebel in small Letter

### ISSUE THREAD

**Issue by ashusdn** [react-native-community/react-native-tab-view#334]
### Expected behaviour
How to change tab text from upper case to lower case: 'First','Second'

### Actual behaviour
Currently, All tabs appear in Upper case for ex: 'FIRST','SECOND'

### Code sample, screenshots
 routes: [
        { key: '1', title: 'Status' },
        { key: '2', title: 'Media' },
        { key: '3', title: 'Log' },
      ],

**Comment by hannahblair** [comment]
+1

**Comment by caiorios** [comment]
You can use the renderLabel prop like this:

```
state = {
    index: 0,
    routes: [
      { key: '1', title: 'Tab One', icon: 'tab-one-icon' },
      { key: '1', title: 'Tab Two', icon: 'tab-two-icon' }
    ]
  };

<TabBar
      renderLabel={this._renderLabel}
      ...
      {...props}
    />

_renderLabel = ({ route }) => (
    <Text style={s.tabBarLabel}>{route.title}</Text>
  );
```

**Comment by satya164** [comment]
Use `getLabelText`

**Comment by arnoldbird** [comment]
Here are two examples of a renderFooter callback, one with **renderLabel** and one with **getLabelText**.

Example with **renderLabel**:

```
_renderFooter(props) {

  _renderLabel = ({ route }) => (
    <Text style={styles.tablabel}>{route.title}</Text>
  );

  return (
    <TabBar 
      {...props} 
      style={styles.tabbar}
      tabStyle={styles.tab}
      renderLabel={this._renderLabel}
    />
  )
}
```

Example with **getLabelText**:

```
_renderFooter(props) {

  _getLabelText = ({ scene }) => (
    'you probably want to do something dynamic here'
  );

  return (
    <TabBar 
      {...props} 
      style={styles.tabbar}
      tabStyle={styles.tab}
      getLabelText={this._getLabelText}
    />
  )
  
}
```

**Comment by nicholasmarais1158** [comment]
The `renderLabel` example above worked for me, but the `getLabelText` did not.

`react-native-tab-view: v3.1.1`
