### ISSUE TITLE
HMR doesn't work 

### ISSUE THREAD

**Issue by vasyas** [react-native-community/react-native-tab-view#335]
I'm using
    "react": "16.0.0-alpha.12",
    "react-native": "^0.47.1",
    "react-native-tab-view": "^0.0.69",

HMR doesn't work when changing components nested in TabViewAnimated.
The same components get reloaded when put outside TabViewAnimated.

Module itself gets patched by HMR, and renderScene is executed.
But screen is not updated.

**Comment by alvinwoon** [comment]
confirmed with latest RN and Expo.

**Comment by alvinwoon** [comment]
Btw, this is more of a longstanding issue with HMR + PureComponent.

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
