### ISSUE TITLE
Bottom Tab Bar

### ISSUE THREAD

**Issue by ankitbisht143** [react-native-community/react-native-tab-view#336]
I am using react-native-tab-view. Working perfectly fine but I want that tab bar in bottom of my screen. I am trying to modify your stylesheet but not happening. Can you please help me in this?

I want like this..

![img_2239](https://user-images.githubusercontent.com/13850433/29612973-7bbeac0e-8821-11e7-8da4-0e2107d79273.PNG)

**Comment by mgwidmann** [comment]
does using `renderFooter` instead of `renderHeader` fix your issue?

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
