### ISSUE TITLE
How to add image in tabs?

### ISSUE THREAD

**Issue by rajsuvariya** [react-native-community/react-native-tab-view#338]
I want to have tabs with images is it possible with this library?

**Comment by rajsuvariya** [comment]
I found how to render label can be customized

**Comment by Ramaraju1992** [comment]
@rajsuvariya how you managed to add Custome image in a Tab???? can you explain with code????? thank you...........

**Comment by AlfaIrawan** [comment]
Hai @rajsuvariya can you share how to add Image or replace icon into Image in tabs here?
