### ISSUE TITLE
Why TabBarTop title is always uppercase?

### ISSUE THREAD

**Issue by sibelius** [react-native-community/react-native-tab-view#34]
https://github.com/react-native-community/react-native-tab-view/blob/master/src/TabBarTop.js#L44

shouldn't it be customizable?

**Comment by satya164** [comment]
@sibelius `TabBarTop` follows material design guidelines by default. You can use the `renderLabel` prop to pass text in any format you want.

**Comment by sibelius** [comment]
tks

**Comment by satya164** [comment]
@sibelius np. lemme know if it doesn't work for you.

**Comment by sibelius** [comment]
it did work here, tks

**Comment by wahidin32** [comment]
what format to make it not uppercase sir ?

getLabelText={{ ?????? }}
