### ISSUE TITLE
undefined is not an object (evaluating 'this.props.navigatiomState.index)

### ISSUE THREAD

**Issue by rishikarajeev** [react-native-community/react-native-tab-view#347]
### Actual behaviour
![screenshot_1505977671](https://user-images.githubusercontent.com/28704128/30683160-e5f33824-9ec9-11e7-9584-f0ac9a3ee7d2.png)

### What have you tried
![screenshot_1505977710](https://user-images.githubusercontent.com/28704128/30683184-030f1428-9eca-11e7-9fda-e55e6272c616.png)

**Comment by hashweer** [comment]
same issue!

**Comment by satya164** [comment]
Please follow the issue template. You didn't post your code, also you posted same error screen in "What have you tried" section. Seriously?
