### ISSUE TITLE
2nd view rendering under first view

### ISSUE THREAD

**Issue by kvieira90** [react-native-community/react-native-tab-view#35]
Added the same styling as the example shows and for some reason the views are rendering on their  respective views, and leaving a gap on the other. See attached. 
![screen shot 2016-10-04 at 10 29 46 pm](https://cloud.githubusercontent.com/assets/5322549/19099405/056b4620-8a84-11e6-9aed-7a2396c4a80a.png)
![screen shot 2016-10-04 at 10 29 43 pm](https://cloud.githubusercontent.com/assets/5322549/19099407/072d3220-8a84-11e6-9fa0-943ca4c130c1.png)

**Comment by satya164** [comment]
@kvieira90 Hmm... That's weird. Can you share some code sample?

**Comment by kvieira90** [comment]
Sure thing. You'll see the marginTop - that I added in to counteract this. 
![screen shot 2016-10-05 at 12 00 07 am](https://cloud.githubusercontent.com/assets/5322549/19100651/c0f81076-8a8e-11e6-9be1-6810d1037fc2.png)

**Comment by satya164** [comment]
@kvieira90 This code looks fine. Can you show me the full file please? Never seen this before.

**Comment by kvieira90** [comment]
@satya164 I'll send you a gist later today.

**Comment by satya164** [comment]
@kvieira90 Thanks a lot!

**Comment by satya164** [comment]
Hey @kvieira90 ! Any luck?

**Comment by kvieira90** [comment]
On it's way @satya164

**Comment by kvieira90** [comment]
@satya164 Any luck?

**Comment by satya164** [comment]
@kvieira90 Gimme a sample repro, or I won't be able to try.

**Comment by kvieira90** [comment]
@satya164 I sent you a gist, do you need to actually run the repo?

**Comment by satya164** [comment]
@kvieira90 Where? 😱

**Comment by satya164** [comment]
Hey @kvieira90 ! Still interested in taking a look at the issue.

**Comment by satya164** [comment]
ping @kvieira90

**Comment by satya164** [comment]
Closing since I don't have a repro.
