### ISSUE TITLE
Android: Tab scroll animation stops working after re-entering the screen

### ISSUE THREAD

**Issue by ywongweb** [react-native-community/react-native-tab-view#351]
Happens when using this lib with Wix's react native navigation router

### Expected behaviour  
Tab switching animation works everytime

### Actual behaviour  
Animation works the first time. But after coming back from another screen it no longer animates. Can still scroll by manually dragging the tabs.

### Code sample, screenshots
https://github.com/ywongweb/RnnTextiInputBug

1. Run repo on Android device or Simulator
2. Change tabs -> can see animation
3. Click on button to push new scene, then click back to go back to first scene
4. Change tabs -> no animation

### What have you tried
Also reported this issue on Wix's React Native Navigation issue board as this lib works on react-native-router-flux.
https://github.com/wix/react-native-navigation/issues/1909

**Comment by ywongweb** [comment]
solved

**Comment by DavidKuennen** [comment]
I'm having the same issue and using the latest version (0.0.70). What do I have to do to make this work?
