### ISSUE TITLE
After RN update, Initial index must always be 0 when using TabViewPagerScroll

### ISSUE THREAD

**Issue by Palisand** [react-native-community/react-native-tab-view#352]
**_After updating from react native 0.46 to 0.48_**

### Expected behaviour
Prior to updating, if I set my initial state as
```javascript
{
  index: 2,
  routes: ...
}
```
the component would mount with the 3rd tab active.

### Actual behaviour
After mounting, the 1st tab is active.

### What have you tried
- Setting the initial index to 0 and then setting it to the desired index on `componentDidMount` or with `setTimeout`. This delay in showing the desired tab is very unsightly and sometimes prone to failing if the content of a scene takes time to load.
- Using `TabViewPagerPan` on iOS. Solves active tab issue but does not provide smooth paging.

**Comment by Palisand** [comment]
Removing
```javascript
const initialLayout = {
  height: 0,
  width: Dimensions.get('window').width,
};
```
id the trick... guess I can't avoid that one frame delay in this case.

Closing since this is now a different issue.

**Comment by wangghon** [comment]
your post saved my life. How do you find it the initialLayout causes the issue? @Palisand 

Thanks a lot!

**Comment by Palisand** [comment]
@wangghon I don't recall, which means it probably was a lot of trial and error.

**Comment by anagar23** [comment]
I have tried removing initialLayout, but no luck. I am only facing this issue in Android. If I remove renderPager prop which has PagerScroll, it works fine. 

I am using "react-native": "0.59.9" and "react-native-tab-view": "^1.0.2".

Can we reopen this issue, so we have an exact solution?

**Comment by satya164** [comment]
@anagar23 upgrade
