### ISSUE TITLE
component re-rendering is not working   

### ISSUE THREAD

**Issue by 11et401012** [react-native-community/react-native-tab-view#357]
**here is  my  code :**

export default class TabViewExample extends PureComponent {
  static title = 'Scrollable top bar';
  
  state = {
    index: 3,
    routes: [
      { key: '1', title: 'Tasks' },
      { key: '2', title: 'Ongoing' },
      { key: '3', title: 'Approval' },
      { key: '4', title: 'Pending' },
      { key: '5', title: 'Accomplished' },

    ],
    loaded:false,
  };

  // C6426E
  _handleIndexChange = index => this.setState({ index });

  _renderHeader = props => <TabBar {...props} style={styles.tabbar} />;

  _renderScene = SceneMap({
    '1': List,
    '2': OngoingList,
    '3': ApprovalList,
    '4': PendingList,
    '5': AccomplishedList,

  });

  render() {
    return (
      <TabViewAnimated
        style={styles.container}
        navigationState={this.state}
        renderScene={this._renderScene}
        renderHeader={this._renderHeader}
        onIndexChange={this._handleIndexChange}
      />
    );
  }
}

**Comment by kikill95** [comment]
"If you are using the SceneMap helper, the scenes are already optimized with PureComponent and won't re-render if parent's state changes." from the docs
So, if you want to have updates, use this syntax instead:
```
renderScene = ({ route }) => {
  switch (route.key) {
  case 'home':
    return <HomeComponent />;
  default:
    return null;
  }
}

Basically, this isn't issue, just unclear docs (or we just lazy to read it fully), more info there: https://github.com/react-native-community/react-native-tab-view#optimization-tips

**Comment by pravesh-curefit** [comment]
I am facing the same issue with my code.
My renderScene method was

`
_renderScene = SceneMap({
        preBookedOrders: () => <PreBookedOrders pendingDelivery={this.state.pendingDelivery} delivered={this.state.delivered} navigate={this.props.navigation.navigate} />,
        newOrders: () => <View style={[styles.container, { backgroundColor: '#673ab7' }]} />,
    });
`

I changed it to 
`
_renderScene = ({ route }) => {
        switch (route.key) {
            case 'preBookedOrders':
                return <PreBookedOrders pendingDelivery={this.state.pendingDelivery} delivered={this.state.delivered} navigate={this.props.navigation.navigate} />
            case 'newOrders':
                return <View style={[styles.container, { backgroundColor: '#673ab7' }]} />
            default:
                return null;
        }
    }
`

But still, when my Main component re-renders, my PreBookedOrders component doesn't re-render. What should I do?

**Comment by LuisRizo** [comment]
I can confirm that `_renderScene` gets called on every `Main` component re-render. My problem was that the child component (in this case `PreBookOrders`) needed a logic update on the `shouldComponentUpdate` lifecycle method.

**Comment by satya164** [comment]
This is already documented https://github.com/react-native-community/react-native-tab-view#scenemap

> All the scenes rendered with `SceneMap` are optimized using `React.PureComponent` and don't re-render when parent's props or states change. If you don't want this behaviour, or want to pass additional props to your scene components, use `renderScene` directly instead of using `SceneMap`.

**Comment by kaushalvoza** [comment]
> I am facing the same issue with my code.
> My renderScene method was
> 
> ```
> _renderScene = SceneMap({
>         preBookedOrders: () => <PreBookedOrders pendingDelivery={this.state.pendingDelivery} delivered={this.state.delivered} navigate={this.props.navigation.navigate} />,
>         newOrders: () => <View style={[styles.container, { backgroundColor: '#673ab7' }]} />,
>     });
> ```
> 
> I changed it to
> 
> ```
> _renderScene = ({ route }) => {
>         switch (route.key) {
>             case 'preBookedOrders':
>                 return <PreBookedOrders pendingDelivery={this.state.pendingDelivery} delivered={this.state.delivered} navigate={this.props.navigation.navigate} />
>             case 'newOrders':
>                 return <View style={[styles.container, { backgroundColor: '#673ab7' }]} />
>             default:
>                 return null;
>         }
>     }
> ```
> 
> But still, when my Main component re-renders, my PreBookedOrders component doesn't re-render. What should I do?

I'm facing same issue. Do u have any updates on it ? if yes then please help me.
Thanks in advance.
