### ISSUE TITLE
Discussion about custom view for lazy loading

### ISSUE THREAD

**Issue by jouderianjr** [react-native-community/react-native-tab-view#358]
Hey everyone, I'm currently working on one app with 4 tabs and we've tried `lazy: true`, but basically we got an empty screen. What do you people think about adding a new option like `lazyView` or something related in order to be rendered until the view is loaded? Does it make sense?

**Comment by sospedra** [comment]
You mean like a placeholder? If so, I think the whole point of the lazy it's to not render anything. Tho, I like the idea.

cc @satya164

**Comment by jouderianjr** [comment]
Yeah, like a placeholder 😄 , I think could be a good addition for project that have heavy rendering. This feature could be added without cause any damage for other pieces.

I'll try your suggestion, but it's a bit hackish 🙊 

Thank you @sospedra ❤️

**Comment by satya164** [comment]
This can be done in the userland using `onPositionChange`. I don't think the library needs to have this feature inbuilt.
