### ISSUE TITLE
Expose `useForeground` prop in <TabBar />

### ISSUE THREAD

**Issue by Nickersoft** [react-native-community/react-native-tab-view#362]
Hi guys, awesome library! A small fix which I can add myself, but thought I'd ask about first, is exposing `useForeground` as a prop for TouchableNativeFeedback in TouchableItem.js and subsequently the TabBar component. By default, all material ripples appear in the background of the tab; however, my app uses a custom gradient tab background and as a result no ripples are shown on Android. Setting `useForeground` to true fixes this, yet there's no way to currently change its value. I'd like to open a PR adding this functionality and thought I'd start a discussion on the matter. 

More info on the original prop [can be found here](https://facebook.github.io/react-native/docs/touchablenativefeedback.html#useforeground).

### Expected behaviour
Material ripple should be able to be shown on tabs with custom backgrounds

### Actual behaviour
Material ripples don't appear on tabs with custom backgrounds due to `useForeground` being set to false by default with no way to change it

**Comment by satya164** [comment]
I'll work on it

**Comment by Nickersoft** [comment]
@satya164 any update on this?

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
