### ISSUE TITLE
Changing tab index programmatically to another tab index sub-screen.

### ISSUE THREAD

**Issue by Nasirilahi** [react-native-community/react-native-tab-view#363]
I am using this library with react-navigation. sometime i need to switch between screens programmatically.I have tab indexes and every tab in i can navigate to another screen within that tab, now suppose i am on a tab at index 1 and from there i want to go to a screen which will navigate from tab index 4 so i will reset my navigation action from screen at tab index 1.For this i am resetting my navigation action so after resetting this if i change the current index in state to show the selected tab so instead of staying to the screen where i navigated it, it will come to the initialRoute screen of that tab.

**Comment by thangvo9x** [comment]
This is a coflict  react-navigation to this lib, 
You can try with this lib react-native-scrollable-tab-view instead of.
I hope can help u improve them @@

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
