### ISSUE TITLE
How can  I change the color of text   and image of only selected tab. 

### ISSUE THREAD

**Issue by greenraze** [react-native-community/react-native-tab-view#364]
I have five bottom tabs which have different icons and text.I want to change the style of text and image of selected tab.How  is it possible in react-native-tab-view.
Now i m rendering the five image with text on different tabs they they are working fine on selection tab is highlighted.
<TabViewAnimated
        style={styles.container}
        navigationState={this.state}
        renderScene={this._renderScene}
        renderFooter={this._renderFooter}
        onIndexChange={this._handleIndexChange}

_renderFooter = props =>
  <TabBar {...props} renderIcon={this._renderIcon}
    labelStyle={{fontSize:7,fontFamily:MONTSERRAT_REGULAR,color:'black'}} style={{height:60}} tabStyle={{backgroundColor:GRAY_LIGHT_COLOR,height:
    60,}}   style={{backgroundColor:GRAY_LIGHT_COLOR}} />;

**Comment by katorres02** [comment]
Did you find a solution?

**Comment by shaikh-kamran** [comment]
You can Render your header like:
 _renderHeader = props => {
        const inputRange = props.navigationState.routes.map((key, i) => i);

        return (
          <View style={styles.tabBar}>
            {props.navigationState.routes.map((route, i) => {
                const tabcolor = props.position.interpolate({
                    inputRange,
                    outputRange: inputRange.map(
                        inputIndex => (inputIndex === i ? '#283891' : '#666666')
                    ),
                });
                const tabfontSize = props.position.interpolate({
                    inputRange,
                    outputRange: inputRange.map(
                        inputIndex => (inputIndex === i ? 14 : 10)
                    ),
                });
                const bcolor = props.position.interpolate({
                    inputRange,
                    outputRange: inputRange.map(
                        inputIndex => (inputIndex === i ? '#283891' : '#fff')
                    ),
                });
                return (
                    <TouchableOpacity
                        style={styles.tabItem}
                        onPress={() => this.setState({ index: i })}>
                        <Animated.View style={{justifyContent: 'center',height:40,alignItems: 'center',width:150,borderBottomWidth:2,borderBottomColor:bcolor}}>
                            <Animated.Text style={{ fontFamily:'Open Sans, Bold',color:tabcolor,fontSize: tabfontSize,}}>{route.title}</Animated.Text>
                        </Animated.View>
                    </TouchableOpacity>
                );
            })}
          </View>
        );
    };

TabViewAnimated will be like:

<TabViewAnimated
                        navigationState={this.state}
                        renderScene={this._renderScene}
                        renderHeader={this._renderHeader}
                        onIndexChange={this._handleIndexChange}
                        initialLayout={initialLayout}
                    />

Rest all will be same.

**Comment by TwinsOd** [comment]
My solution
  _renderTabBar(props) {
        let index = 0;
        return (
            <View style={{marginTop: 28,}}>
                <TabBar
                    {...props}
                    style={{backgroundColor: Colors.whiteApp, elevation: 0, height: 36}}
                    indicatorStyle={{backgroundColor: Colors.greenApp, height: 3}}
                    renderLabel={({ route }) => (
                        <View>
                            <Text style={{fontSize: 11, textAlign: 'center',
                                color: index === props.navigationState.index ? Colors.greenApp : Colors.blackApp}}>
                                {route.title}
                            </Text>
                            {console.log('Test', index += 1)}
                        </View>
                    )}
                />
            </View>
        );
    }

    render() {
        return (
            <TabView
                navigationState={this.state}
                renderScene={this._renderScene}
                renderTabBar={this._renderTabBar}
                onIndexChange={this._handleIndexChange}
            />
        )
    }

**Comment by ttdat2510** [comment]
> My solution
> 
> ```
> _renderTabBar(props) {
>        return (
>            <View style={{marginTop: 28,}}>
>                <TabBar
>                    {...props}
>                    style={{backgroundColor: Colors.whiteApp, elevation: 0, height: 36}}
>                    indicatorStyle={{backgroundColor: Colors.greenApp, height: 3}}
>                    renderLabel={({ route }) => (
>                        <View>
>                            <Text style={{fontSize: 11, textAlign: 'center',
>                               color: route.key === props.navigationState.routes[props.navigationState.index].key ?
> Colors.greenApp : Colors.blackApp}}>
>                                {route.title}
>                            </Text>
>                        </View>
>                    )}
>                />
>            </View>
>        );
>    }
> 
>    render() {
>        return (
>            <TabView
>                navigationState={this.state}
>                renderScene={this._renderScene}
>                renderTabBar={this._renderTabBar}
>                onIndexChange={this._handleIndexChange}
>            />
>        )
>    }
> ```
That's so great with me . many thanks

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
