### ISSUE TITLE
Indicator isn't updating correctly if we set custom TabWidth .

### ISSUE THREAD

**Issue by bijubijoy** [react-native-community/react-native-tab-view#366]
<TabBar
            indicatorStyle={{ height: 4, backgroundColor: '#14345A' }}
            labelStyle={{ color: '#14345A', fontFamily: 'Lato-Regular', fontSize: 12 }}
            style={{ backgroundColor: '#fff' }}
            tabStyle={{ width: 100 }}
            scrollEnabled={true} {...props} />;

if we set width in tabStyle indicator is not updating correctly, 
  
_trackPosition = (e: { value: number }) => {
    console.log(e.value);
    this._handlePositionChange(e.value);
    this._triggerEvent('position', e.value);
    this._lastPosition = e.value;
  };

i tried to print value from _trackPosition, it isn't printing the value if we set custom width, but printing correctly when we remove width.

**Comment by DaKaZ** [comment]
I am fairly certain PR #588 fixes this issue as I tested it with multiple tab widths

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
