### ISSUE TITLE
Slow transaction when there's a tab with list of images (Android(

### ISSUE THREAD

**Issue by 20matan** [react-native-community/react-native-tab-view#368]
### Expected behaviour
smoothly navigate between tabs when there's at least 1 tab which renders
a list of images

### Actual behaviour
Heavy fps drop when while it's animated

### Code sample, screenshots
![image](https://user-images.githubusercontent.com/10909504/31733125-661cc914-b443-11e7-8615-6d4490bdaf5e.png)

### What have you tried
Created 2 screens;
1. with texts and images (10~ items in the list)
2. a simple text
then when change tabs (from/to the "heavy" component) - it results in slow transaction

**Comment by alimek** [comment]
+1 I have similar problem,

I have 2 tab which heavy content (list, avatars, some text etc) min 20 elements at start, and when i change tab by clicking it animation is not smoothly, but swiping works fine.

iOS works ok, problem is only on Android.

**Comment by normdoow** [comment]
I am having this same issue as well

**Comment by 7laria** [comment]
same issue but with 4 of this type of screen

**Comment by WestFR** [comment]
Same for me with ten tables with images !

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.

**Comment by jiraiya103** [comment]
same issue, slow transaction in android example.
Have any solution ?
