### ISSUE TITLE
Shadow iOS

### ISSUE THREAD

**Issue by GCour** [react-native-community/react-native-tab-view#37]
Works great! Removed the other scroll tab component and replaced it with this one..

The only thing that bothers me a bit is that there's no shadow on iOS, only Android. Any way to fix this?

**Comment by satya164** [comment]
@GCour You can pass a `style` prop to the tab bar with box shadow

**Comment by satya164** [comment]
BTW I've more improvements coming - https://github.com/react-native-community/react-native-tab-view/pull/36 :D

**Comment by GCour** [comment]
@satya164 I have added following style but the shadow is not showing:

```
shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 2,
    shadowOffset: {
      height: 2
    }
```

**Comment by satya164** [comment]
@GCour thanks. I'll have a look at it in an hour.

**Comment by satya164** [comment]
@GCour Hey, just tried this. Shadow works fine when you set a `zIndex` to move the tab up :)

```js
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 2,
    shadowOffset: {
      height: 2,
    },
    zIndex: 1,
```

**Comment by satya164** [comment]
In next release there'll be a hairline shadow (like the navbar) below the tab bar by default. https://github.com/react-native-community/react-native-tab-view/commit/6c767ced7636302303922ee7332d0b5d841fe136

![image](https://cloud.githubusercontent.com/assets/1174278/19280619/5addc0a8-9004-11e6-9514-14d614a9cde8.png)

**Comment by satya164** [comment]
It's up - https://github.com/react-native-community/react-native-tab-view/releases/tag/v0.0.32

**Comment by WillyRamirez** [comment]
@satya164  how do I remove this default hairline shadow? Passing a style object with shadowOpacity: 0, to the tabBar does not seem to work..

**Comment by satya164** [comment]
@WillyRamirez passing style should work on iOS. do you have code/repro?

**Comment by WillyRamirez** [comment]
@satya164  I use android? Does that matter? 

```
 _renderHeader = (props) => {
    props = {...props, social: this.props.profile.social };
    return <TabBar style={{shadowOpacity: 0}}
                   indicatorStyle={{borderWidth: 0, height: 0}}
                   renderIndicator={this._renderIndicator}
                   renderLabel={this._renderLabel(props, this.props.profile.social)} {...props} />;
  };
```

**Comment by satya164** [comment]
@WillyRamirez this is only for iOS. On Android you need to pass `elevation: 0`

**Comment by tomasfrancisco** [comment]
I'm getting this behavior even with a high zIndex value

![screen shot 2017-05-11 at 17 03 38](https://cloud.githubusercontent.com/assets/4301103/25959573/f11f5c44-366b-11e7-9e68-0999b7949518.png)

I exaggerated on the shadow height and opacity so you can see better what I'm referring to.

Any thoughts?

**Comment by albinhubsch** [comment]
Having the same issue as @tomasfrancisco 
The only way I managed to get around it was to set content background to transparent, which works in some cases but when you have a list view with items with background different from main bg this gets problematic.
