### ISSUE TITLE
onIndexChange not called when i swipe to page at index 0 

### ISSUE THREAD

**Issue by mtr1012** [react-native-community/react-native-tab-view#370]
render() {
    if (!this.state.navigation) return <Text>Loading</Text>;

    return (
      <View style={{ flex: 1, backgroundColor: 'black' }}>
        {!this.state.isExpanded && this.renderToolBar()}
        <TabViewAnimated
          style={AppStyles.flex1}
          renderScene={this.renderScene}
          renderHeader={this.renderHeader}
          navigationState={this.state.navigation}
          onIndexChange={this.handleIndexChange}
        />
        {this.renderInfoView()}
      </View>
    );
  }

  handleIndexChange = index => {
    console.log(`index change ${index}`)
    this.setState({
      selectedIndex: index,
    })
  }

handleIndexChange not called when i swipe to page at index 0. Please help me. Many thanks !

**Comment by djalmaaraujo** [comment]
Just noticed this too.

**Comment by djalmaaraujo** [comment]
@mtr1012 A little bit late, but the workaround would be waiting a few milisecons and gettings from the ref tab instance:

```js
_onTabChange(index) {
    console.log(this.refs['tabs'].state.index) // this will print the old
    setTimeout(() => {
      console.log('Hey, changing. New index:', this.refs['tabs'].state.index) // this will print the next (actual) after the swipe
    }, 500);
}
```

**Comment by kpsroka** [comment]
I can't reproduce that issue. Can you provide a minimal/small example that illustrates the bug?

**Comment by djalmaaraujo** [comment]
@kpsroka The example is for the swipe event, not clicking, did you try specific swiping?

**Comment by kpsroka** [comment]
@djalmaaraujo Yes, I tried swiping. I used the example app from `react-native-tab-view` (running on Expo), which uses `TabViewAnimated` in a similar way to what @mtr1012 described. I suppose there's some interaction between `TabViewAnimated` and the parent `View` that's causing the problem, but without a piece of code that I can reproduce the issue with, I can't help.

**Comment by laogui** [comment]
I have the same problem, onIndexChange not called at index 0.

**Comment by limeyslimey** [comment]
I am also facing this issue. onIndexChange gets called for second and third tab but not for the first tab
`<TabView
          navigationState={this.state}
          renderScene={this.renderScene}
          onIndexChange={this.onChangeTab}
          renderTabBar={(props) => (
            <TabBar
              {...props}
              indicatorStyle={{ backgroundColor: '#6BAC1B' }}
              style={{ backgroundColor: 'white', height: 40 }}
              renderLabel={this.renderLabel}
              indicatorStyle={{ backgroundColor: '#6BAC1B' }}
            />
          )}
        />`
