### ISSUE TITLE
Re-render tabs when parent state changes

### ISSUE THREAD

**Issue by rajsuvariya1** [react-native-community/react-native-tab-view#371]
### Expected behavior
Tabs should re-render when parent state changes

### Actual behavior
Tabs not getting re-rendered when parent state changes

### What have you tried
Not sure what should I do as it is clearly mentioned in doc that scenemap is created from PureComponent which doesn't support re-rendering

**Comment by satya164** [comment]
https://github.com/react-native-community/react-native-tab-view#caveats

**Comment by rajsuvariya1** [comment]
Okay I have gone through it and now my code looks like this
```
_renderScene = SceneMap({
        '1': () => <Comp1 details={this.state.details}/>,
        '2': SecondRoute,
      });

```
```
state = {
      index: 0,
      routes: [
        { key: '1', title: 'Comp1' },
        { key: '2', title: 'Comp2' },
      ],
      details: null,
      loaded: false,
    };

```

But still, I am not able to access it from Comp1. I am getting undefined.

**Comment by satya164** [comment]
https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/TopBarTextExample.js#L50

**Comment by rajsuvariya1** [comment]
I am sorry but I don't have good exp in RN. I tried to make code like the one you provided but still, I am facing the same issue. If you could point out my mistake then it would be great

**Comment by rajsuvariya1** [comment]
Sorry for the trouble but not I am able to re render it

Thanks for the help :D
