### ISSUE TITLE
add right button to the top bar tab view

### ISSUE THREAD

**Issue by Elitebigboss90** [react-native-community/react-native-tab-view#373]
Hello, I want to add a button to the very right of the navigation bar. 
I feel like I can use a custom component in order to implement that. But it won't render it on the navigator bar, either above it or lower than it.

Please, someone can help me with that.

**Comment by alessandro-pianetta** [comment]
+1

Im having this issue as well. I want to place a custom button to the right of the final tab that opens a dropdown, but I'm having trouble figuring out how to implement it.

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.

**Comment by Beslinda** [comment]
Did anyone find a solution to this ?
