### ISSUE TITLE
How do dynamically change the color of the view added 

### ISSUE THREAD

**Issue by kalyanpkumar** [react-native-community/react-native-tab-view#374]
### Expected behaviour

I am working on an application where i need to show a rounded circle before the title of selected tab. I was able to override renderLabel method and add the view (rounded circle) before the tab title. I need to add this only for selected tab.

### Actual behaviour

But the rounded circle is being added to all the tabs. I need to dynamically change the color of other tabs when one of the tab is selected. OR i need to add the view (rounded circle) only for the selected tab.

### Code sample, screenshots

`_renderLabel = ({ route }) => (
    <View style={styles.tabBarlabelView}>
      <View style= {styles.tabBarLabelCircle}></View>

      <Text style={styles.tabBarlabel}>{route.title}</Text>
    </View>
  );`

`tabBarlabelView: {
    //textTransform: 'lowercase'
    backgroundColor:'transparent',
   marginTop :7,
   marginBottom : 9,
   marginLeft: 8,
   marginRight:8,
   flexDirection:'row',
   
  },
  tabBarLabelCircle:{
    backgroundColor:'orange',
   marginTop :5,
   marginLeft: 8,
   marginRight:8,
   width:10, 
   height:10, 
   borderRadius:5,
  }
tabBarlabel: {
   color:'black',
   fontWeight: "500",
   fontStyle :"normal",
   fontSize:15,
  }`

### What have you tried

Tried a lot.. in OnTabPress i tried to get the selected tab index and i tried to load the style based on the state. But it didn't worked out.

Expected design:

![screen shot 2017-10-29 at 12 01 59 am](https://user-images.githubusercontent.com/11042372/32137432-5c0f82ca-bc3d-11e7-9572-ca8e1b38b21d.png)

Current achieved design

![screen shot 2017-10-29 at 12 00 37 am](https://user-images.githubusercontent.com/11042372/32137435-77f48ba2-bc3d-11e7-8159-75f5bb668c7e.png)

**Comment by Weakky** [comment]
Just use `focused` param given to _renderLabel = ({ route, focused }) => ()`

**Comment by ikhsanalatsary** [comment]
try this [example](https://github.com/react-native-community/react-native-tab-view/blob/5c1771b29c8420abfb0348e27e6e42148a0367e2/example/src/ScrollViewsExample.js)

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
