### ISSUE TITLE
TabBar keyboardShouldPersistTaps should be a custom prop

### ISSUE THREAD

**Issue by danieloprado** [react-native-community/react-native-tab-view#375]
### Expected behaviour

TabBar should have a keyboardShouldPersistTaps to customize the behaviour  of touch.

###  Actual behaviour

You can't press any button inside a  TabBar with the Keyboard open.

### What have you tried

I added keyboardShouldPersistTaps={'handled'} to the ScrollView in TabBar.js and it fixes this issue.

**Comment by satya164** [comment]
Can you send a PR adding the prop? And set it to `handled` by default?

**Comment by danieloprado** [comment]
Sure!

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
