### ISSUE TITLE
Unable to 'Cancel' swipes properly

### ISSUE THREAD

**Issue by julienvincent** [react-native-community/react-native-tab-view#38]
Thanks for this very well written library. Very performant with a highly reusable API. One issue I did find with it is that its hard to cancel a swipe.

If you start a swipe in a direction, lets say `to the right`, and then attempt to cancel by reversing the swipe `to the left` - the left scene will still open (unless your swipe ends with no velocity and is past the threshold)

**Comment by julienvincent** [comment]
There should probably be some logic detecting if the current motion is in the opposite direction to the initial direction. I will take a look at the source and submit a PR when I get some time, but thought I'd open an issue incase someone wants to get to it sooner.

**Comment by satya164** [comment]
Thank you :)
Can you give a video of what's happening?

![tabs](https://cloud.githubusercontent.com/assets/1174278/19416937/1f591bac-93bc-11e6-9492-0b76ce9619da.gif)

**Comment by julienvincent** [comment]
Sure - how do you make these gif vids? :P

**Comment by satya164** [comment]
@julienvincent this - https://github.com/jclem/gifify

**Comment by julienvincent** [comment]
![swipe mov](https://cloud.githubusercontent.com/assets/8571121/19417028/eebfec9c-93a1-11e6-8e5e-13190ee93583.gif)

**Comment by julienvincent** [comment]
From looking at the source I think the [following line](https://github.com/react-native-community/react-native-tab-view/blob/master/src/TabViewPanResponder.js#L76) is what needs to change. This should contain some logic like `isMoving && !isMovingOppositeDirection`.

Will confirm once I get the example running locally

**Comment by satya164** [comment]
@julienvincent Thanks a lot. We'll probably need to keep track of the latest direction like in `respondToGesture` and then react accordingly.

**Comment by julienvincent** [comment]
@satya164 Agreed 👍
