### ISSUE TITLE
Center the tabs of a TabBar

### ISSUE THREAD

**Issue by QuentinBrosse** [react-native-community/react-native-tab-view#380]
Hi,

I use your `TabBar` component with `react-navigation` and I am trying to center my tabs in the tab bar. 

### Expected behaviour
<img width="355" alt="screen shot 2017-11-03 at 01 42 23 copy" src="https://user-images.githubusercontent.com/10938538/32357027-6119ca96-c039-11e7-8ce9-09affd4acb5c.png">

### Actual behaviour
<img width="355" alt="screen shot 2017-11-03 at 01 42 23" src="https://user-images.githubusercontent.com/10938538/32357030-66a2fef6-c039-11e7-97cc-555b926fd4a5.png">

### Code sample, screenshots
Here is my `TabBar` component call:
``` js
<TabBar
  {...props}
  onTabPress={this._handleOnPress}
  jumpToIndex={() => {}}
  renderIcon={this._renderIcon}
  renderIndicator={this._renderIndicator}
  style={styles.tabBar}
  tabStyle={styles.tabBarTab}
/>
```
with the corresponding styles:
``` js
tabBar: {
  backgroundColor: '#8FECC8',
  justifyContent: 'center',
},
tabBarTab: {
  borderRightWidth: 1,
  borderColor: 'white',
  width: 70,
},
```
### What have you tried
As you can see above, I tried to add a `justifyContent: 'center'` to the `style` property of the `TabBar` but their is no effect.
Am I obliged to create a custom `TabBar` to do this kind of thing ? If it is the case, what is the best way to do it ?

Thanks a lot for your help ! :)

**Comment by satya164** [comment]
Wrap the tab bar in a vote and add justify centre on the view.

**Comment by satya164** [comment]
view*

**Comment by QuentinBrosse** [comment]
Tanks a lot @satya164.
For those who would be interested, here is my solution:

I get this result:
<img width="388" alt="screen shot 2017-11-03 at 13 48 03" src="https://user-images.githubusercontent.com/10938538/32374374-a769ce42-c09d-11e7-8712-a3378bfef195.png">

with this code: 
``` js
const widthTabBar = TabBarTop.tabWidth * numberOfTabs;

return (
<View style={styles.tabBarContainer}>
  <TabBar
     [...]
     style={[styles.tabBar, {width: widthTabBar}]}
     tabStyle={styles.tabBarTab}
  />
</View>
);
```

and the corresponding style:

``` js
tabBar: {
  shadowColor: 'transparent',
  borderBottomWidth: StyleSheet.hairlineWidth,
  borderBottomColor: 'rgba(0,0,0,0.5)',
  backgroundColor: null,
},
tabBarTab: {
  borderWidth: 0,
  width: TabBarTop.tabWidth,
},
tabBarContainer: {
  flexDirection: 'row',
  justifyContent: 'center',
}
```

**Comment by arun1705** [comment]
Hello,
I want to achieve the above mentioned functionality using dynamic tabs for these i tried the mentioned solution by @QuentinBrosse  but i thing TobTabBar  component has been deprecated i am using     "react-native-tab-view": "^2.14.2", please provide me the solution

**Comment by khanhubgit** [comment]
<TabView
...
renderTabBar={props => (
     <View style={{flexDirection: 'row', justifyContent: 'center', backgroundColor: 'black'}}>
        <TabBar
          {...props}
          indicatorStyle={{ backgroundColor: 'white' }}
          tabStyle={{ width: 100}}
          scrollEnabled={true}
          style={{ backgroundColor: 'black'}}
          labelStyle={{color: 'green', fontWeight: '500'}}
          pressOpacity="0.7"
        />
     </View>
   )
/>
