### ISSUE TITLE
Warning PropTypes

### ISSUE THREAD

**Issue by dsah** [react-native-community/react-native-tab-view#384]
RN 0.48.1, react 16.0.0-alpha.12, react-native-tab-view-0.0.70
Getting warnings when using this module: 

### Expected behaviour
This modules need to be updated to make compatible with react native latest version.

### Actual behaviour
Warning: PropTypes has been moved to a separate package. 

Warning: checkPropTypes has been moved to a separate package. 

Warning: React.createClass is no longer supported. Use a plain JavaScript class instead.

Tried react-native-tab-view-0.0.59, still same error.

**Comment by satya164** [comment]
Are you sure it's from this module? It neither uses `React.createClass`, not `React.propTypes`. Please check other dependencies you are using.

**Comment by wanderSX** [comment]
Yeah, I'm also getting: 
> Warning: checkPropTypes has been moved to a separate package.

"react-native-tab-view": "0.0.73"

**Comment by satya164** [comment]
The error is unrelated to this library. Please check your dependencies.

**Comment by charleycesar** [comment]
I'm getting de same warning

**Comment by santhosh77h** [comment]
facing getting same error linking to this line [https://github.com/react-native-community/react-native-tab-view/blob/1e5975e3fc04884a6f69977f464a3932ceefdd55/src/TabViewAnimated.js#L6](on TabViewAnimated.js)

**Comment by snipter** [comment]
Looks like the problem in the version of the React Native that you're using. Working without warnings at `0.52.0`. But I have the same warnings at `0.47.0`. Looks like the problem in the Flow compiler. When React Native compiles js files, it uses `React.createClass` and `React.propTypes`, but a new version of the React shows errors about it. Try to update React Native to the new or to the latest version.
