### ISSUE TITLE
Unable to use within collapsible toolbar

### ISSUE THREAD

**Issue by prashantvv** [react-native-community/react-native-tab-view#389]
Hello, I'm using the slider inside  a collpasible toolbar, link : https://github.com/Agontuk/react-native-collapsible-toolbar  
& I tried a lot but unable to show the slider pages inside it. I;m new to RN and dont much musch about the styling. Can someone guide me on this thing. As the tab strip shows well but the tab pages are not visible even if I add height to them. The coding is simple as provided in the libs in both slider as well as in collpasible container. I need to know whether there are some chances of combining both libs by changing any styles in the tabview

* I manage to show pages only when I pass height to <TabViewAnimated> but it is not taking the whole height accordingly
Thanks

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
