### ISSUE TITLE
 renderScene not rendering the view when clicked on any of the tabs in the tabBar

### ISSUE THREAD

**Issue by imAnjithreddy** [react-native-community/react-native-tab-view#395]
I set the tabBar with two values and I'm calling renderScene to display component based on the route using switch 

Nothing is getting rendered whenever I click on any of the tabs

**Comment by imAnjithreddy** [comment]
<AnimatedTabBar /> just renders the header correctly

And nothing is getting displayed below that using renderScene when any of the tabs in the tabBar header is clicked.

**Comment by satya164** [comment]
Please follow the issue template when posting. Thanks.
