### ISSUE TITLE
When render to another page, then back to tab page the tab can't scroll with smoothly

### ISSUE THREAD

**Issue by azharprabudi** [react-native-community/react-native-tab-view#396]
hey everyone this first time i use react native tab view, and then i have a issue like that

[here video](https://youtu.be/6doEktRuz70)

when i move to another page, then back to the tab page. The tabbar can't scroll with smoothly, and function onIndexChange cannot call

Thanks

**Comment by azharprabudi** [comment]
I am so sorry to make this issue, but this issue already solved. Thanks so much

**Comment by Dielz98** [comment]
@azharprabudi i found similar problem. Care to share how you resolve this problem?

**Comment by jarvisluong** [comment]
I also encountered this problem. How can it be solved? @azharprabudi

**Comment by satya164** [comment]
Duplicate of https://github.com/react-native-community/react-native-tab-view/issues/225
