### ISSUE TITLE
tabbar.js can't change label and icon's color

### ISSUE THREAD

**Issue by wzy535** [react-native-community/react-native-tab-view#40]
Hi,
 In this example :https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/BottomBarIconTextExample.js
I can't change label's style and icon's color. 
I set icon color in color's style. but not work!
please help! Thanks in advance!!

**Comment by satya164** [comment]
@wzy535 Can you share your code?

**Comment by wzy535** [comment]
`export default class HomeView extends React.Component{

	state={
		index:0,
		routes:[
			{key:'site',title:'Top',icon:null,labelStyle:{color:'#222'}},
			{key:'collection',title:'User',icon:null,labelStyle:{color:'#222'}},
			{key:'user',title:null,icon:'user',labelStyle:{color:'#222'}}
		],
	}
	_handleChangeTab(index){
		this.setState({
			index,
		})
	}
	_renderScene({route}){
		switch(route.key){
			case 'site':
				return <SiteView />;
			case 'collection':
				return <CollectionView />;
			case 'user':
				return <UserView />;
			default:
				return null;
		}
	}

	_renderFooter(props){
		return (
			<TabBar
				{...props}
				renderIcon={this._renderIcon}
				renderBadge={this._renderBadge}
				style={styles.tabbar}
				tabStyle={styles.tab}
				labelStyle={styles.labelStyle}
			/>
		)
	}
	_renderIcon({route}){
		if(route.icon != null)
		return (
			<Icons 
				name={route.icon}
				size={26}
				style={{color:'black'}}
			/>
		)
	}
	render(){
		return (
			<TabViewAnimated
				style={[styles.container,View.propTypes.style]}
				navigationState={this.state}
				renderScene={this._renderScene}
				renderFooter={this._renderFooter}
				onRequestChangeTab={this._handleChangeTab.bind(this)}
			/>
		)
	}
}

const styles = StyleSheet.create({
	container:{
		flex:1,
	},
	tabbar:{
		backgroundColor:'#f7f7f7',

	},
	tab:{
		//opacity:1,
		padding:0,

	},
	icon:{
		backgroundColor:'transparent',
		color:'#222222'
	},
	labelStyle:{
		
	},
	tablabel: {
    backgroundColor: 'transparent',
    color: 'black',
    fontSize: 12,
    margin: 4,
  },

})`

**Comment by satya164** [comment]
You're not using the styles properly. You have to add the styles in the stylesheet at the bottom. For label you have an empty object in styles and added actual styles in state. Move it to the `labelStyle` object at the bottom.

For icon you're not using the icon style. Pass `style={styles.iconStyle}`

**Comment by MobileDev418** [comment]
How to set label color for selected and none selected item?
