### ISSUE TITLE
[Flow] Required module not found when trying to import react-native-tab-view

### ISSUE THREAD

**Issue by thibautguedou3** [react-native-community/react-native-tab-view#402]
### Expected behaviour
React native version: 0.49.3
React version: 16.0.0-beta.5
Flow version: 0.53.0
No error message from flow when trying to import react-native-tab-view

### Actual behaviour
Get the error message '[flow] react-native-tab-view (Required module not found)'

### Code sample, screenshots
<img width="475" alt="screen shot 2017-12-04 at 16 22 34" src="https://user-images.githubusercontent.com/31597701/33560349-ca20d72a-d90f-11e7-8182-ce4b6c32ee41.png">
<img width="556" alt="screen shot 2017-12-04 at 16 22 05" src="https://user-images.githubusercontent.com/31597701/33560359-ce4e34f0-d90f-11e7-9097-3a7cb2f5cf39.png">

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
