### ISSUE TITLE
Loop render in v0.0.73

### ISSUE THREAD

**Issue by moonjava2005** [react-native-community/react-native-tab-view#404]
I use the TabViewAnimated on my LightBox for photo page viewer
I found some problem
When I open and close the Lighbox fast and continuously, the render in TabViewAnimated was loop by "_handleLayout" trigger
The reason that I log to console is
In some how, the width = 0 and then the width = currentViewWidth. Therefore, the render is call again and again.
I work around by add this
`const { height, width } = e.nativeEvent.layout;
      console.log("++++++++++_handleLayout....: ",e.nativeEvent.layout);
    if(!width||!height)
    {
     return;
    }`
And everything is OK
Until now, I don't know why TabViewAnimated was layout width as 0 even every page, I return the view with fixed width = Screen Width.
I think may be for some other screens I don't want to render if their index out of current index. I return "null" as your document directions
Could you investigate this case?

**Comment by satya164** [comment]
Can you post your code? Are you using `initialLayout` property to pass a width?

**Comment by moonjava2005** [comment]
Dear @satya164 
This is my code
`
import {
    TabViewAnimated
} from 'react-native-tab-view';


constructor(props) {
        super(props);
        this.initialLayout = props.initialLayout;
        //Initialize layout if there's no from Props
        if (!this.initialLayout) {
            this.initialLayout = {
                width: Device.getCurrentScreenWidth(), height: Device.getCurrentScreenHeight()
            }
        }
        .......
    }

render() {
        return (<TabViewAnimated
            style={styles.fullFlex}
            navigationState={this.state}
            renderScene={this.renderMediaPage}
            onIndexChange={this.onTabIndexChange}
            initialLayout={this.initialLayout}/>);
    }

renderMediaPage({route}) {
        const {
            index,
            routes
        } = this.state;
        const renderIndex = routes.indexOf(route);
        if (Math.abs(index - renderIndex) > 1) {
            return null;
        }
        return (<View style={{width: Device.getCurrentScreenWidth(), height: Device.getCurrentScreenHeight()}}/>);
    }
`

**Comment by satya164** [comment]
Your code looks strange. What's `Device`? Can you post it on snack.expo.io?

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
