### ISSUE TITLE
 is onPositionChange gone in v0.73?

### ISSUE THREAD

**Issue by kdong007** [react-native-community/react-native-tab-view#405]
### Expected behaviour
onPositionChange exist as doc says

### Actual behaviour
onPositionChange is not found anywhere in source codes

### What have you tried
checked out older version v0.69 and onPositionChange exists

**Comment by satya164** [comment]
Sorry, I forgot to update the docs.

The library is going through a refactor to be able to provide smooth gestures and animations driven by the native driver, which means we no longer listen to events from native on JavaScript. Also there's no straightforward way to implement them with the new approach (React Native doesn't have APIs to add listeners on combined animation values).

I might work on implementing this feature in React Native in future and then I'll be able to re-add the prop. But I don't really have the time. Please stay on older version of the library if you need it.

**Comment by jgfidelis** [comment]
@satya164 we are on 0.0.70 and we want to upgrade because of a bug we found. I want to know if there is a workaround for this in the newest versions, because we use our own TabViewHeader (not TabBar) and our indicator animation depended on `onPositionChange`.

Thanks

**Comment by satya164** [comment]
Hard to say without knowing what you want to implement, but the included `TabBar` is nothing special. It receives the same props, so if the included tab bar can do something, you can do it with your custom tab bar too. Take a look at the implementation and the examples in the README.
