### ISSUE TITLE
Native Mode + wix/react-native-navigation =  Error

### ISSUE THREAD

**Issue by odesey** [react-native-community/react-native-tab-view#408]
I am trying to utilize the native driver as per the example here:
https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/NativeDriverExample.js

### Expected behaviour
Native driver should work and offer improved performance

### Actual behaviour
I receive the following error:
```
TypeError: Cannot read property 'PanGestureHandler' of undefined

This error is located at:
    in TabViewPagerExperimental (at UserProfileTabs.js:62)
    in RCTView (at View.js:113)
    in View (at TabViewAnimated.js:189)
    in TabViewAnimated (at UserProfileTabs.js:66)
    in NativeDriverExample (at Navigation.js:51)
    in _class (at renderApplication.js:35)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:126)
    in AppContainer (at renderApplication.js:34)
```

### Code sample, screenshots
See example here:
https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/NativeDriverExample.js

### What have you tried
Using `react navigation` instead of `react native navigation` seems to resolve the problem.

Are there additional steps required for `react native navigation` to work with native mode?

**Comment by odesey** [comment]
This was due to an installation issue with `react-native-gesture-handler`.

**Comment by benstokoe** [comment]
Hi @odesey, I am also having this issue, what was the installation issue you had and sorted?

Thanks!

**Comment by ikzjfr0** [comment]
I don't use `react-native link`, instead, i use `pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler/ios'`.

However, I still have the same issue as above.

![simulator screen shot - iphone x - 2018-05-23 at 06 51 19](https://user-images.githubusercontent.com/6456056/40389512-02cd13a6-5e56-11e8-8676-a310eec3ef7d.png)

**Comment by ikzjfr0** [comment]
@benstokoe appreciate if you can explains more about " manual installation method instead of running the react-native link command." and how to manually do that step by step?

**Comment by ikzjfr0** [comment]
I noticed in source code:
`
static defaultProps = {
    GestureHandler:
      global.__expo && global.__expo.DangerZone
        ? global.__expo.DangerZone.GestureHandler
        : undefined,
    canJumpToTab: () => true,
  };
`

What's `__expo` for? it's kind of `expo`? do i need to install other dependencis?
