### ISSUE TITLE
TabView sometime not working in modal

### ISSUE THREAD

**Issue by nhuthan** [react-native-community/react-native-tab-view#410]
### Expected behaviour
I want it working everytime
### Actual behaviour
[Android only]
When I use tab view in modal, sometimes the tabs did not finish rendering, the componentDidMount function did not call (until I close modal), only the tab header showing but the scenes not rendered, no animation translation running, no warning or error appear.
### Code sample, screenshots
See example I created https://snack.expo.io/@nhuthan/react-native-tab-view-issue, open and close modal some times you will see problem (on android)
### What have you tried
i tried not render header, return simple view and text for all scenes, return null for all scenes... i also downgrade to 0.0.70 but still not work

**Comment by nhuthan** [comment]
Hey, please confirm you knew this issue or read it. I submitted 21 days ago.

**Comment by ekeuus** [comment]
I have the same issue on Android. No problems on iOS.

**Comment by satya164** [comment]
Same bug as in https://github.com/react-native-community/react-native-tab-view/issues/474
