### ISSUE TITLE
Extremely Slow When Transitioning By Tapping Tab Bar

### ISSUE THREAD

**Issue by kingarawana** [react-native-community/react-native-tab-view#414]
I'm having an issue w/ TabViewAnimated and TabBar where it's extremely slow if a user taps on the tab instead of swiping left and right. The swiping feature is great. Super fast, no lag, but when tapping on the tabs in TabBar, there's a 1-2+ second delay.

I've tried setting the initialLayout prop. I've replaced my scenes with just <Text>Scene 1</Text>, <Text>Scene 2</Text>... etc, to ensure it wasn't a rerender problem but I'm still having the same issue. On the simulator it seems to work fine but with still a half second lag compared to swiping, but on a mobile device (iOS and Android), there's a significant lag. 

Here's my definition of TabViewAnimated

```javascript
<TabViewAnimated
              style={styles.container}
              navigationState={this.state}
              renderScene={this._renderScene}
              renderFooter={this._renderFooter}
              onIndexChange={this._handleChangeTab.bind(this)}
              initialLayout={initialLayout}
              useNativeDriver
            />
```

_renderScene
```javascript
_renderScene = ({ route }) => {
    switch (route.key) {
      case '1':
        return <Text>Hello 1</Text>
      case '2':
        return <Text>Hello 2</Text>
      case '3':
        return <Text>Hello 3</Text>
      case '4':
        return <Text>Hello 4</Text>
      case '5':
        return <Text>Hello 5</Text>
      default:
        return null;
    }
  };
```

_renderFooter
```javascript
_renderFooter = (props) => {
    return (<TabBar
      {...props}
      style={{backgroundColor: 'black'}}
      indicatorStyle={{backgroundColor: 'white'}}
      renderIcon={(x)=>{
        var iconSize = {width: 30, height:30, margin: 10};
        // switch(x.route.key){
        //   case "1":
        //     return <Image source={require('../../assets/clock_default.png')} style={iconSize}/>
        //     break;
        //   case "2":
        //     return <Image source={require('../../assets/transaction_default.png')} style={iconSize}/>
        //     break;
        //   case "3":
        //     return <Image source={require('../../assets/home_default.png')} style={iconSize}/>
        //     break;
        //   case "4":
        //     // return <Image source={require('../../assets/lightening_default.png')} style={iconSize}/>
        //     return <Image source={require('../../assets/bank_default.png')} style={iconSize}/>
        //     break;
        //   case "5":
        //     return <Image source={require('../../assets/list_default.png')} style={iconSize}/>
        //     break;
        // }
        switch(x.route.key){
          case "1":
            return <Text>1</Text>
            break;
          case "2":
            return <Text>1</Text>
            break;
          case "3":
            return <Text>1</Text>
            break;
          case "4":
            // return <Image source={require('../../assets/lightening_default.png')} style={iconSize}/>
            return <Text>1</Text>
            break;
          case "5":
            return <Text>1</Text>
            break;
        }
      }}
    />);
  };
```

Device: iPhone 6 - 11.0.3
react-native-tab-view@0.0.73

**Comment by wanderSX** [comment]
Had this problem only with debug build. Works fine with release build though

**Comment by kingarawana** [comment]
@wanderSX Turns out implementing shouldComponentUpdate made the biggest difference. The debug build seems to work fine as well.

I'll be closing this report.

**Comment by bradbumbalough** [comment]
@kingarawana I'm facing a similar issue -- where did you add the `shouldComponentUpdate`? In the component that is rendering the `<TabViewAnimated>`. I added a check there and didn't see it firing.. thank you!

**Comment by henricazottes** [comment]
@bradbumbalough any update ? I'm facing the same issue, very slow transition using the tabs but everything ok when swiping, can't figure out where it does come from. Even using simple <Text> components as scenes get slow transitions.

**Comment by malkio** [comment]
I faced similar issue, in my case it turns out that it was my IOS emulator. The "Slow Animations" debug was turned on.

Simulator->Debug->Slow Animations should be set to Off
or
CMD+T

**Comment by pribeh** [comment]
@kingarawana Where did you specify shouldComponentUpdate?

**Comment by ziyafenn** [comment]
Hey guys, same problem on iOS. Haven't tested on the release build. 

Is there any proper way to fix this?
