### ISSUE TITLE
FEATURE: Vertical Tabs / Calculating Position

### ISSUE THREAD

**Issue by DaKaZ** [react-native-community/react-native-tab-view#417]
### Overview

This is not a bug, but a feature request (that I am also working on) for vertical tabs. I am having a small issue in the implementation and hoping for some help.

As a user of react-native-tab-view both natively and with React Navigation, it would be useful to be able to render a vertical tab bar especially for tablet landscape views.  I have begun and mostly completed a branch that implements this feature for TabViewAnimated.  

I have run into a problem and I am hopeful someone from the core team can help me.  I am implementing the animations for the tab selector now and, unfortunately, my lack of experience with animating is tripping me up. I am trying to follow a similar design pattern to the existing code, but I cannot figure out where `position` gets updated with the currently selected tab index.  I only see position set in the constructor of TabViewAnimated.  I did instrument the code (through a series of console.logs and the private `__getValue()` method) and I can see Position is updated, but how?  I just need to better understand this section of the code so that I can implement it for the vertical view.

### Expected behaviour

When I pass in the `vertical` prop to TabViewAnnimated
```
      <TabViewAnimated
        style={[styles.container, this.props.style]}
        navigationState={this.state}
        renderScene={this._renderScene}
        renderHeader={this._renderHeader}
        onIndexChange={this._handleIndexChange}
        initialLayout={initialLayout}
        vertical
      />
```
I expect to see:

![simulator screen shot - ipad air 2 - 2017-12-28 at 11 54 15](https://user-images.githubusercontent.com/895892/34424121-627810d4-ebde-11e7-843c-d718b9e2c5ab.png)

### Actual behaviour

The code does not current provide vertical tabs

**Comment by satya164** [comment]
> where position gets updated with the currently selected tab index

`position` is a combination of 2 different animated values, `panX` and `offsetX`. Those values get updated inside the pagers, e.g.: https://github.com/react-native-community/react-native-tab-view/blob/master/src/TabViewPagerExperimental.js

**Comment by DaKaZ** [comment]
@satya164 thank you!  I guess I was a little confused - aren't the pager files just for animating the content section?

**Comment by satya164** [comment]
@DaKaZ pagers manage the gestures and the x-translation of the pages. the `position` animated value represents the current state of the x-translation.

**Comment by DaKaZ** [comment]
@satya164 I created pull request #418 with my initial attempt at adding the vertical tabs.  It still has one problem as noted in the PR comments.  It would be great if you could give this an initial review to let me know if there are any glaring issues or if you'd like to rearchitect in any way.  If you have a chance to help with the activity indicator issue I highlight in the PR comments that would be great too, but I understand if you have other commitments.

Thanks

**Comment by DaKaZ** [comment]
@satya164 I actually just found the problem.... will update the PR momentarily

**Comment by DaKaZ** [comment]
No reason to keep this issue open. Thanks
