### ISSUE TITLE
how to display the portion of left right element

### ISSUE THREAD

**Issue by usmanghani6** [react-native-community/react-native-tab-view#419]
is there any way to show the portion of right item and left item along current item i have tried padding and margins but no luck.
![f6yhc](https://user-images.githubusercontent.com/24776937/34466490-0af873d2-eef7-11e7-940d-9df39bb16f1f.png)

**Comment by satya164** [comment]
https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/CoverflowExample.js
