### ISSUE TITLE
Can't scroll FlatList inside TabViewAnimated 

### ISSUE THREAD

**Issue by mtr1012** [react-native-community/react-native-tab-view#420]
I'm using TabViewAnimated with 2 child views. Each view contain 1 FlatList. I can't scroll FlatList. Please help. Many thanks

**Comment by satya164** [comment]
Please use the issue template when creating an issue. I'm closing this issue since you haven't followed the issue template and it's impossible for me to help you without any useful information.

**Comment by yogeshR5** [comment]
@mtr1012  same issue Here. what you did

**Comment by jamessawyer** [comment]
+1 @satya164 does this library not support this feature?
