### ISSUE TITLE
Track swipe position

### ISSUE THREAD

**Issue by Druux** [react-native-community/react-native-tab-view#421]
### Expected behaviour
My `TabBarAnimated` has to have different backgroundColors and tint colors for some tabs. Therefore I would really like to animate my `TabBarAnimated` icons / labels based on the current swipe position of `TabViewAnimated`. If I don't interpolate the style based on the swipe position, it will result in a delayed re-render of the `TabBarAnimated` content and styles.

What I basically want to is this:
![nav](https://user-images.githubusercontent.com/9655723/34864714-eff82082-f775-11e7-8b25-3df1a545ae0b.gif)
Credits and copyright goes to https://dribbble.com/shots/3799265-Swipe-navigation, Steffen Nørgaard Andersen.

### Actual behaviour
Currently there is no possibility for me to perform animations during the swipe.

**Comment by satya164** [comment]
You receive the `position` animated value for every `renderX` callback. You can interpolate on it to do what you want.
