### ISSUE TITLE
TabBar disable in nested navigators

### ISSUE THREAD

**Issue by brzonsea** [react-native-community/react-native-tab-view#428]
Hi, I've been using react-native-tab-view together with react-navigation.

I have a quite complex tree of StackNavigators inside the root Tab View. 

And in some of these nested StackNavigators I would like to disable the Tab Bar. 

For now I am seeing the Tab Bar created by TabViewAnimated in all of my nested StackNavigators.

How can I disable the Tab Bar in some of my screens?

**Comment by satya164** [comment]
Please open React Navigation related issues in React Navigation repo from next time: https://reactnavigation.org/docs/navigators/tab#Screen-Navigation-Options
