### ISSUE TITLE
How to do this use tabbar?

### ISSUE THREAD

**Issue by TopGuo** [react-native-community/react-native-tab-view#429]
## I want to do that. eg: 

![like this](https://images2017.cnblogs.com/blog/1106982/201801/1106982-20180118225637365-779262551.gif)

## But i can't do it.

`Can you tell me how to do it .As shown in the figure`

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
