### ISSUE TITLE
RCTView: Shadow warnings

### ISSUE THREAD

**Issue by ou2s** [react-native-community/react-native-tab-view#433]
RCTView throws warnings when using TabBarAnimated with latest release (0.0.73)

### Expected behaviour
No warnings

### Actual behaviour
Warning thrown

### What have you tried
When commenting the shadow style tabBar in TabBar.js, the warning goes away.

Had this warning with several RN versions:
- 0.48.4
- 0.52.1

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
