### ISSUE TITLE
Using TabBar as a standalone view?

### ISSUE THREAD

**Issue by davidliu** [react-native-community/react-native-tab-view#434]
Is it possible to use TabBar as a standalone view rather than as a part of the TabView? It doesn't seem straightforward.

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
