### ISSUE TITLE
TextInput Loses focus on TebViewAnimated rendering

### ISSUE THREAD

**Issue by RavinderRikhi** [react-native-community/react-native-tab-view#437]
### Expected behaviour
The TextInput should remain focused on TabViewAnimated rendering. onTextChange function calls 2 functions to fetch data from the API calls which is further shown in TabViewAnimated's 2 tabs.

### Actual behaviour
As I hit the first letter the Tab view is rendered but TextInput loses focus and the keyboard closes. Which i have to tap again to type in further characters.

### Code sample, screenshots
`
_handleTextChange(text){

    this.setState({
      searchText: text.trim()
    },()=>{

      if(this.state.searchText.length){
        //this.refs.searchTextInput.focus();
        this._fetchCategories(this.state.searchText)
        this._fetchBusinessList(this.state.searchText)
      }

    })

  }

  _fetchCategories(text){

    const { dispatch } = this.props,
    payload = {
      searchData:text,
      flag:true,
      skip:0,
      limit: Number.MAX_SAFE_INTEGER
    };

    //Fetching voucher details of the current campaign
    const endPoint = "Users/searchBusinessOrCategories";

    RestClient.get(endPoint,payload).then((result) => {

      if(result.statusCode==200 || result.status=='success'){

        const { data } = result;

        this.setState({
          categoryList: data
        })

      }else
        dispatch(ToastActionsCreators.displayInfo(result.message));
    }).catch(error => {
      console.log(error);
      dispatch(ToastActionsCreators.displayInfo(error));
    });

  }

  _fetchBusinessList(searchText){
    const { dispatch } = this.props,
    payload = {
      searchData:searchText,
      flag:false,
      skip:0,
      limit: Number.MAX_SAFE_INTEGER
    };

    //Fetching voucher details of the current campaign
    const endPoint = "Users/searchBusinessOrCategories";

    RestClient.get(endPoint,payload).then((result) => {

      if(result.statusCode==200 || result.status=='success'){

        const { data } = result;

        this.setState({
          businessList: data
        })

      }else
        dispatch(ToastActionsCreators.displayInfo(result.message));
    }).catch(error => {
      console.log(error);
      dispatch(ToastActionsCreators.displayInfo(error));
    });
  }

_renderScene = ({ route }) => {

    const { categoryList, businessList } = this.state,
    { emptyCampaignList } = Constants.Content.labels;

    switch (route.key) {
      case 'category':
        return <View style={{flex:1}}>{
          (categoryList.length > 0 ) ? this._getCategoryListView(categoryList) : <View style={{flex:1,justifyContent:"center"}}>
            <Text style={{textAlign:"center",fontSize: Constants.Style.FONT_SIZE_4}}>
              {emptyCampaignList}
            </Text>
          </View>
        }
      </View>;
      case 'business':
        return <FlatListView data={businessList} onTapFunction={ this._goToCampaignDetails.bind(this) }/>
      default:
        return null;
    }
  };
`
this is my render function 

`
render(){

    //Page heading content
    const { search: PageHeading } = Constants.Content.screenHeadings,
    { trendingSearch: trendingSearchLabel, searchPlaceholder } = Constants.Content.labels,
    { default: keyboardType } = Constants.Content.keyboardTypes,
    {searchText, trendingSearches} = this.state;

    return (
      <View style={[styles.container]}>
        <AppHeader heading={PageHeading} leftButtons={this._getLeftButtonGroup()}/>
        <View style={[styles.searchBarContainer]}>
          <View style={{flex:1,alignItems:"center",justifyContent:"center"}}>
            <Icon name='search' size={Constants.Style.UNIT*1.4} color={Constants.Style.DarkGray}/>
          </View>
          <TextInput ref="searchInput" style={[styles.textInputStyle]} underlineColorAndroid='rgba(0,0,0,0)' keyboardType={keyboardType} onChangeText={this._handleTextChange.bind(this)} placeholder={searchPlaceholder} value={this.state.searchText}/>
        </View>
        <View style={[styles.bodyContainer]}>
          {
            (searchText.length > 0) ? <View><Text>This is my text</Text></View>
            : ( trendingSearches.length > 0 ) && <View style={[styles.trendingListContainer]}>
              <View style={[styles.labelContainer]}>
                <Text style={[styles.labelTextStyle]}>
                  {trendingSearchLabel}
                </Text>
              </View>
              <View style={[styles.listItemContainer]}>
                  {this._getCategoryListView(trendingSearches)}
              </View>
              <View style={{flex:4}}/>
            </View>
          }
        </View>
      </View>
    )
  }
`
![giphy](https://user-images.githubusercontent.com/15958016/35543140-7e8f89ae-0589-11e8-8ae4-bc4995686fb9.gif)

### What have you tried
I have tried to use refs to focus the text input again but it is giving a jaggy effect where the keyboard closes and then opens up again. 
Instead of TabViewAnimated when I simple view with some text the keyboard works fine.

**Comment by flotos** [comment]
I am having exactly the same problem. Did you come up with a solution ?

**Comment by ignivaravinderrikhi** [comment]
Updating the version from "0.0.74" to "0.0.77" and setting property keyboardDismissMode="none" does the job.

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
