### ISSUE TITLE
How I can disabled press on tabbar to jump?

### ISSUE THREAD

**Issue by toanhosss** [react-native-community/react-native-tab-view#440]
I want to jump from button in child component. So, how I can disable onpress in tabbar?

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.

**Comment by deepakSinghPapola** [comment]
@satya164   Thanks for new release, but is there any solution to disable press on Tab bar?
