### ISSUE TITLE
White space when scrolling inside a scene and swiping to the next one (with collapsible Header)

### ISSUE THREAD

**Issue by Crash--** [react-native-community/react-native-tab-view#441]
### Expected behaviour

If I scroll inside a scene, I expect that after swiping to an another one, the content is well displayed. With no white / blank space. 

### Actual behaviour

Use this project  : https://snack.expo.io/@satya164/collapsible-header-with-tabview 

Scroll inside the first scene then swipe right. See this space ? 

![ezgif-1-e5e37a27dd](https://user-images.githubusercontent.com/1107936/35625773-cbf22d72-0693-11e8-99c5-1f8f301ad299.gif)

### What have you tried
scrollTo with/without timeout() with no success.

**Comment by austenLacy** [comment]
@Crash-- I had a similar issue and solved it using the `onScroll` event listener

```javascript
```

**Comment by sircharleswatson** [comment]
@Crash-- Any luck with this yet? I'm facing the same issue at the moment. not sure how to resolve it.

**Comment by sircharleswatson** [comment]
@Crash-- I figured out a solution for this but it's not dynamic (have to set it up for each tab individually) I'm gunna try to do a repro on Expo soon but I'm super busy at the moment. I'll keep this thread up-to-date when I do it!

**Comment by fernandoantunes** [comment]
@sircharleswatson What solution did you find?

**Comment by harrie006** [comment]
@sircharleswatson What was the solution?

**Comment by sircharleswatson** [comment]
The solution I came up with was super convoluted and ridiculous (even though it worked) but I had to redesign away from using tabs on this particular page because it was causing too many other issues. In conclusion, I will try to avoid animated headers + tabs as much as possible in the future 🙈

**Comment by austenLacy** [comment]
@fernandoantunes @harrie006 @sircharleswatson I have a working (with some kinks) example that fixes this problem -- https://github.com/austenLacy/react-native-collapsible-header-with-tabs-demo

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.

**Comment by youngsaksham** [comment]
> @fernandoantunes @harrie006 @sircharleswatson I have a working (with some kinks) example that fixes this problem -- https://github.com/austenLacy/react-native-collapsible-header-with-tabs-demo

link not working
