### ISSUE TITLE
Breakdown of the module

### ISSUE THREAD

**Issue by Angelk90** [react-native-community/react-native-tab-view#443]
### Expected behaviour
Working module.

### Actual behaviour
Broken module.

### What have you tried
@satya164 : 
I put code example this: https://snack.expo.io/HyfQqMfLG
In a TabNavigator, that is, that is inside the individual tabs, it is not possible to see and move between the tabs.

If the code is tried without being put in the navigator tab it seems that it works.
How can I solve?

**Comment by Angelk90** [comment]
@satya164 : Are there any news?

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
