### ISSUE TITLE
Tablet - Badges away from the icon

### ISSUE THREAD

**Issue by Angelk90** [react-native-community/react-native-tab-view#444]
### Expected behaviour
In device mobile:
![screenshot](https://user-images.githubusercontent.com/20476002/35769472-c55d1d6c-090b-11e8-8a0b-88c3295b545c.png)

### Actual behaviour
In tablet:
![screenshot_20180203-172915](https://user-images.githubusercontent.com/20476002/35769478-d2f0fbba-090b-11e8-90e4-b066f66011e4.png)

### What have you tried
@satya164 : I tried it simply on the tablet, how can I make the badge not so far from the icon as it happens on the device phone.

**Comment by Angelk90** [comment]
@satya164 : Are there any news?

**Comment by Angelk90** [comment]
@satya164 : Are there any news?

**Comment by vhuytiki** [comment]
how do you fix it ?

**Comment by Angelk90** [comment]
@vhuytiki :   There is no solution, I can not find it. Ask the developers if there are any news.

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
