### ISSUE TITLE
Inside ScrollView Doesn't work

### ISSUE THREAD

**Issue by yogeshR5** [react-native-community/react-native-tab-view#445]
### Expected behavior
Scroll entire page along with Tab 

### Actual behavior
Giving ScrollView Doesn't render TabAnimated inside Tab Content

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
