### ISSUE TITLE
Strange behavior (overswipe) in Coverflow example

### ISSUE THREAD

**Issue by angly-cat** [react-native-community/react-native-tab-view#448]
Hi! This library is great, thanks for maintaining and improving it!

I was checking `Coverflow` example from [React Native Tab View Demos](https://expo.io/@satya164/react-native-tab-view-demos) on expo and noticed strange behavior.

### Expected behaviour
I expected the first and the last slides either to disallow further swipe at all, or to become smaller/semi-transparent and on touch end return to normal.

### Actual behaviour
I guess as long as spring animation hasn't fired "on completed" callback (I'm not sure if I understand the concept of it) or something, the first and the last slides allow overswipe with behavior, that doesn't seem intended.
Last slide reacted to overswipe by becoming larger instead of smaller.
First slide reacted to overswipe by moving in the opposite of expected direction.

### Code sample, screenshots
See [the video](https://youtu.be/AgOisy7Vy1c), pay attention to touch indicator. With the last slide spring animation ended after the first overswipe and hasn't reacted to it afterwards, but with the first slide with quick swipes I was able to trigger a lot of strange animations.

### What have you tried
To swipe here and there.

**Comment by zamotany** [comment]
I'd like to pick up this one
