### ISSUE TITLE
Bug not update renderScene runtime.

### ISSUE THREAD

**Issue by Angelk90** [react-native-community/react-native-tab-view#451]
### Expected behaviour
If the device is in Enable hot Reloading mode.
If the contents of a tab are changed, ie the renderScene, it should be updated immediately.

### Actual behaviour
If the device is in Enable hot Reloading mode.
If the contents of a tab are changed, it is not updated immediately.
We need to go back, and return to the view to see the changes.

### What have you tried
A possible solution would be to use:

```
componentWillReceiveProps (nextProps) {
 if (nextProps.renderScene! == this.props.renderScene) {
  ...Here enter what allows to edit the scene, the changes should be in nextProps.renderScene.
 }
}
```

@satya164 : it would be possible to solve this problem urgently.

**Comment by Ashi90** [comment]
Just Undefined an object before render tabViewAnimated, The following is worked for me

```
{this.props.classDetails != undefined &&
      <TabViewAnimated
      style={styles.container}
      navigationState={this.state}
      renderHeader={this._renderHeader}
      renderScene={this._renderScene}
      onIndexChange={this._handleIndexChange}/>
    }
```

**Comment by Angelk90** [comment]
@Ashi90 : 
I did not understand.
The problem is that if you edit a tab, we consider you have 3 tabs.
Change what is contained in tab0, do not see the change that has been made.
We need to go back, and return to the view.

**Comment by Ashi90** [comment]
@Angelk90 :  In my Code **this.props.classDetails**  is data that I'm render in tab0  Ok. Now as I can understand that you need to update the data without going to back screen right?

**Comment by Angelk90** [comment]
@Ashi90 : 
Set the device so that every time you make a change it updates:
The setting name is Enable Hot Reloading.

Consider this code:
```
import React, { Component } from 'react';
import { Text, StyleSheet, View } from 'react-native';
import { TabViewAnimated, TabBar } from 'react-native-tab-view'; // 0.0.74

export default class Home extends Component {
  constructor() {
    super();
    this.state = {
      index: 0,
      routes: [
        {
          key: '1',
          title: 'Movies',
        },
        {
          key: '2',
          title: 'Tv Series',
        },
        {
          key: '3',
          title: 'Actors',
        },
      ],
    };
  }

  _handleIndexChange = index =>
    this.setState({
      index,
    });

  _getLabelText = ({ route }) => route.title;

  _renderHeader = props => (
    <TabBar
      {...props}
      getLabelText={this._getLabelText}
      labelStyle={styles.label}
      tabStyle={styles.tab}
      style={styles.tabbar}
      indicatorStyle={styles.indicator}
    />
  );

  _renderScene = ({ route }) => {
    return <Text style={styles.itemName}>Route: {route.key}</Text>;
  };

  render() {
    return (
        <View style={{flex:1}}>
        <Text style={styles.itemName}>Name</Text>
        <TabViewAnimated
            //style={{ marginTop: 24 }}
            navigationState={this.state}
            renderScene={this._renderScene}
            renderHeader={this._renderHeader}
            onIndexChange={this._handleIndexChange}
        />
        </View>
    );
  }
}

const styles = StyleSheet.create({
  tabbar: {
    backgroundColor: '#205cb2',
  },
  tab: {
    padding: 0,
  },
  label: {
    fontSize: 12,
    marginTop: 2,
  },
  indicator: {
    backgroundColor: '#FFC107',
  },
});
```

Now edit, _renderScene and render ():
With this code:
```
 _renderScene = ({ route }) => {
    return <Text style={styles.itemName}>Route2: {route.key}</Text>;
  };

  render() {
    return (
        <View style={{flex:1}}>
        <Text style={styles.itemName}>Name2</Text>
        <TabViewAnimated
            //style={{ marginTop: 24 }}
            navigationState={this.state}
            renderScene={this._renderScene}
            renderHeader={this._renderHeader}
            onIndexChange={this._handleIndexChange}
        />
        </View>
    );
  }
```

Save and you'll see that:
Name will be updated with Name2
Instead the various "Route" n, will not update.

**Comment by satya164** [comment]
HMR is not reliable. This is mostly how HMR implementation are done rather than any React libraries.

I'm not exactly sure what are you changing and expecting HMR to update it, but if you change something in state, I don't think any HMR implementations handle it.

**Comment by Angelk90** [comment]
@satya164 : What would the HMR?
Did not I understand your speech?

**Comment by satya164** [comment]
HMR means Hot module reloading.

**Comment by Angelk90** [comment]
@satya164 : With all the modules I've used it seems like HMR, always update the content if a change is made.

This is the example you can try to see from your PC, (not to try on Expo):
https://github.com/react-native-community/react-native-tab-view/issues/451#issuecomment-366463221

**Comment by satya164** [comment]
> if a change is made

What exactly are you changing?

**Comment by Angelk90** [comment]
@satya164 : 
The steps are these:
1) HMR enable
2) Put the code that is provided.
3) Then put this code, You must edit: _renderScene and render ():
```
 _renderScene = ({ route }) => {
    return <Text style={styles.itemName}>Route2: {route.key}</Text>;
  };

  render() {
    return (
        <View style={{flex:1}}>
        <Text style={styles.itemName}>Name2</Text>
        <TabViewAnimated
            //style={{ marginTop: 24 }}
            navigationState={this.state}
            renderScene={this._renderScene}
            renderHeader={this._renderHeader}
            onIndexChange={this._handleIndexChange}
        />
        </View>
    );
  }
```

**Comment by satya164** [comment]
@Angelk90 no HMR implementation I have seen handles changing class properties, which is what `_renderScene` is. You can move it outside of the class to a separate component and try.

**Comment by Angelk90** [comment]
@satya164 : 
I did not understand, you're saying that nothing can be done, there is no solution?
The following function could not be used inside TabViewAnimated:
`componentWillReceiveProps (nextProps)
`

**Comment by satya164** [comment]
> The following function could not be used inside TabViewAnimated:

What exactly would you do in that function?

The component would already re-render if its props change. If `renderScene` prop changes, it'll update. But HMR implementations don't update class properties. That's an issue with the HMR implementations.
