### ISSUE TITLE
Tabs with FlatList Won't Swipe

### ISSUE THREAD

**Issue by jeprojects** [react-native-community/react-native-tab-view#454]
### Expected behaviour
Swiping tab bar view should change to next tab.

### Actual behaviour
Swiping disabled

### What have you tried
It works fine when the component isn't in a FlatList, but for some reason the FlatList is disabling the swipe for react-native-tab-view.

Also swiping the tab-bar works.

Any ideas?

**Comment by ghoshabhi** [comment]
@satya164 : I am facing this issue too. Can you please check #474 ? Thanks!
