### ISSUE TITLE
Swiping page instead of scrolling horizontal nested FlatList on Android

### ISSUE THREAD

**Issue by vpodolyan** [react-native-community/react-native-tab-view#455]
I have a friend list implemented as horizontally scrollable `FlatList` which is nested in one of the pages of `TabViewAnimated` component. `TabViewPagerExperimental` is used for `renderPager()` function.

I get different behavior on iOS and Android. 

### Expected behaviour

`FlatList` is scrolled horizontally on both iOS and Android.

### Actual behaviour

`FlatList` is scrolled well on iOS only while the tab page is swiping on Android most of time instead.

### Code sample, screenshots

*Scrolling on iOS*
![friend_list_scrolling_ios](https://user-images.githubusercontent.com/7989047/36385383-7b00a974-15a3-11e8-8a66-325b5b11c0b1.gif)

*Scrolling on Android*
![friend_list_scrolling_android](https://user-images.githubusercontent.com/7989047/36385394-837e7f5e-15a3-11e8-98f6-ed89c6f245c8.gif)

### What have you tried

I tried to change pager component to `TabViewPagerPan` that led to the working scroll on Android, but it got broken on iOS.

**Comment by vpodolyan** [comment]
Using `FlatList` from `react-native-gesture-handler` works for me

**Comment by yaronlevi** [comment]
Any solutions to the issue?

**Comment by vpodolyan** [comment]
@yaronlevi You can import `FlatList` from `react-native-gesture-handler` as workaround. It should fix the issue

**Comment by imansalhi** [comment]
@vpodolyan it will be helpful if you share your code with us ...i did what you said but nothing changed

**Comment by vpodolyan** [comment]
@imansalhi which version do you use? it's probably fixed in the current version. Sorry, I'm on vacations now, I'll get back next week and try to find that code :)

**Comment by vpodolyan** [comment]
@imansalhi I came back :) Here's the code. I don't put `ProfilePhotos` component's code here for simplicity
```js
class ProfileFriends extends PureComponent {
    render() {
            <FlatList
                 horizontal
                 contentContainerStyle={styles.flatlist}
                 showsHorizontalScrollIndicator={false}
                 keyExtractor={(item: RelationEntity) => item.user.id}
                 renderItem={({ item }) => (<FriendsItem user={item.user} />)}
                 ItemSeparatorComponent={() => (<View style={styles.friendListSeparator} />)}
                 renderScrollComponent={(props) => (<ScrollView {...props} />)}
                 data={this.props.friends}
              />
    }
}

class Profile extends PureComponent {
    state = {
        index: 0,
        routes: [
            { key: 'friends' },
            { key: 'photos' },
        ],
    };
    render() {
        return (
            <TabView
                navigationState={this.state}
                renderScene={SceneMap({
                     friends: ProfileFriends,
                     photos: ProfilePhotos,
                 })}
                onIndexChange={index => this.setState({ index })}
                initialLayout={{ width: Dimensions.get('window').width }}
          />
        );
    }
}
```
