### ISSUE TITLE
How to use react-native-tab-view alongside other routing modules, or is that even necessary?

### ISSUE THREAD

**Issue by arnoldbird** [react-native-community/react-native-tab-view#456]
If one is using react-native-tab-view for tabs, what might be the typical way to handle navigation to arbitrary routes that are not in the tabs?  How do I load a scene programmatically — for example, in response to a button press?

Would it be typical to use something like StackNavigator for defining routes and for handling arbitrary navigation to those routes?  Or does StackNavigator duplicate the behavior/features of react-native-tab-view?

**Comment by arnoldbird** [comment]
I am finding hard to judge whether to use this library, or whether I'm going down the wrong road by trying to use this.  I find it quite easy to use, in any of itself, and I like it.  However, I can't tell whether it is compatible with other popular ways to provide routing and navigation.  I don't know to what extent this library overlaps with React Navigation.  I don't know if I'm headed down a dead-end road.

In a programming sense, it's probably possible to make react-native-tab-view play well with React Navigation, but I'm not sure if it really makes sense to proceed this way, or if I'm going to end up with a badly organized app with duplicated functionality if I use both react-native-tab-view and React Navigation.  Part of this difficulty stems from my inability to understand what I get "for free" with React Navigation, and what requires customization.

**Comment by arnoldbird** [comment]
I think I have confirmed that react-native-tab-view is not compatible with React Navigation, or at least is not compatible with the "withNavigation" feature.  I posted a bug report with a demo at https://github.com/facebook/react-native/issues/18065

**Comment by satya164** [comment]
> If one is using react-native-tab-view for tabs, what might be the typical way to handle navigation to arbitrary routes that are not in the tabs? How do I load a scene programmatically — for example, in response to a button press?

The scenes are controlled by the state, so you can update the state any time to add new scenes.

> Or does StackNavigator duplicate the behavior/features of react-native-tab-view?

`StackNavigator` has a different navigation mechanism from tabs. The `TabNavigator` is the one which provides the same functionality.

> However, I can't tell whether it is compatible with other popular ways to provide routing and navigation.

It is just a React component, so it's compatible. The question is whether you want to integrate the navigation state of tabs with whatever library you are using. It depends on the API of navigation library.

> I don't know to what extent this library overlaps with React Navigation.
> it's probably possible to make react-native-tab-view play well with React Navigation

React Navigation uses `react-nativetab-view` internally to implement it's `TabNavigator`. However, React Navigation doesn't support dynamically changing the list of routes, hence that specific feature is unavailable in `TabNavigator` while supported by `react-native-tab-view`. So you would want to use `react-native-tab-view` directly if you need this feature. Otherwise, React Navigation should be enough.

>  think I have confirmed that react-native-tab-view is not compatible with React Navigation, or at least is not compatible with the "withNavigation" feature

It's definitely compatible. I replied to your comment on the linked issue.

**Comment by arnoldbird** [comment]
Thanks for your reply.  

> React Navigation doesn't support dynamically changing the list of routes

I don't quite know what this means.  Is there an example that shows what it means to dynamically change the list of routes?

**Comment by satya164** [comment]
@arnoldbird say you have 2 tabs, and sometime later you want to add a new tab.

**Comment by arnoldbird** [comment]
@satya164 
I don't need to do that at run time.  I think my navigation will be more stable than that.  I don't think I've ever worked on a project where I needed to add a new tab at run time.

**Comment by arnoldbird** [comment]
FWIW, I switched to a pure React Navigation approach, and made more progress in a half hour than I made in several hours trying to combine react-native-tab-view and React Navigation.  This is no fault of the libraries.  I think it's just because I have very little experience with React.  

It was very easy to get started with react-native-tab-view, and it provided very nice tabs, and I only got stuck when I tried to combine it with React Navigation.  A more advanced React developer probably would not get stuck on this.

**Comment by satya164** [comment]
> I don't think I've ever worked on a project where I needed to add a new tab at run time.

It depends on the project. Say you want to fetch a list of products from server and display them as tabs.

**Comment by hariDasu** [comment]
i am using react-native-navigation, and embed a stack navigator inside a tab within the parent tabNavigator. when I click on an item, it then navigates to this single items' detail screen, where I use react-native-tab-view to further organize this items contents as tehre is alot of information here. the problem I am having from here, is that I cannot push a new item onto the stack navigator, i can only present the next items' details view as a modal.

![simulator screen shot - iphone xr - 2019-01-16 at 16 39 21](https://user-images.githubusercontent.com/2300054/51280323-5b1a5600-19ad-11e9-9456-5ecdb4bf8e5b.png)
