### ISSUE TITLE
style set warning as of version 0.0.35

### ISSUE THREAD

**Issue by dannycochran** [react-native-community/react-native-tab-view#46]
I just upgraded to the new release (0.0.35) and now get this warning, appears to be coming from TabBarTop.js:

YellowBox.js:69 You are setting the style `{ position: ... }` as a prop. You should nest it in a style object. E.g. `{ style: { position: ... } }`

<img width="1192" alt="screen shot 2016-10-19 at 5 05 50 pm" src="https://cloud.githubusercontent.com/assets/1217178/19541830/571aa18c-961e-11e6-87c6-cf78a41e99a5.png">

**Comment by satya164** [comment]
@dannycohran oh, sorry for that. You can safely ignore it. It's because React thinking the normal position prop is a style prop. I was testing in production mode, so didn't catch it. Will do another release in a minute.

**Comment by satya164** [comment]
Published a new version. The warning should be gone now.

**Comment by dannycochran** [comment]
@satya164 thanks!
