### ISSUE TITLE
Want to show second tab by default

### ISSUE THREAD

**Issue by atitpatel** [react-native-community/react-native-tab-view#464]
I am following the same example shown in wiki which is working fine for me. But I have a requirement where I want to show the second tab by default instead of the first tab.

I tried setting index at componentDidMount, but it only changes the selected tab. It shows body of the first tab only.

OS : iOS

Hope this clarify the problem. Let me know if more details are required.

**Comment by amcvitty** [comment]
I have also experienced this, but it seems to be intermittent, so I guess some sort of race condition is going on.

**Comment by tuandt** [comment]
I got the same issue. Working fine on android but iOS.

React-native version 0.55.1

**Comment by shubhnik** [comment]
@satya164 Facing this issue too, any idea? Thanks.

**Comment by shubhnik** [comment]
Also , @atitpatel @amcvitty @tuandt anyone of you fixed it? Thanks.

**Comment by amcvitty** [comment]
I have not fixed it, or found any workaround. It's still intermittent in my app. 

I must admit - I was kind of selfishly hoping someone else would step up to tackle it. It's hard to reproduce consistently, so hard to debug

**Comment by anirudhramanan** [comment]
I have also experienced this, but it seems to be intermittent hence difficult to debug. Any luck ?

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.

**Comment by zigang93** [comment]
how to select second tab by default? I didn't saw any example
