### ISSUE TITLE
Add a `jumpToIndex` method with a deprecation message

### ISSUE THREAD

**Issue by satya164** [react-native-community/react-native-tab-view#467]
I [removed the `jumpToIndex` method](https://github.com/react-native-community/react-native-tab-view/commit/9d648a7333111750443eef0d50030a9ab9b22eb0) and replaced it with ` jumpTo` method. But we should keep the method with a deprecation message to let people upgrade in the meantime.

**Comment by Calsowah** [comment]
Guys, how do I actually implement these changes? I am a little new to git and I'm still getting this warning despite commenting out the jumptoIndex method in my node-modules folder. 

![react native warning](https://user-images.githubusercontent.com/32689867/40755348-1abef92e-644c-11e8-8074-6be54e2730d0.png)
