### ISSUE TITLE
TopTabBar with scrollEnabled causes indicator to render in wrong position on orientation

### ISSUE THREAD

**Issue by satya164** [react-native-community/react-native-tab-view#468]
https://github.com/react-navigation/react-navigation/issues/3534

**Comment by DaKaZ** [comment]
I am working on tracking this one down.  Its easy to see the problem without changing orientations if you make the tab width's larger, like 320.  Its even more exaggerated when the initial index is 2.  As seen here, the indicator SHOULD be under the `ALBUMS` but its rendered to the far right.  

![screen shot 2018-08-20 at 2 03 27 pm](https://user-images.githubusercontent.com/895892/44363688-1f24a880-a482-11e8-8563-72a01c67c9dc.png)

In calculating the indicator transform, we have to take into account the amount scrolled already.  Trying to figure that part out now, animated values are a little foreign to me :)

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
