### ISSUE TITLE
Setup infra for testing with detox

### ISSUE THREAD

**Issue by satya164** [react-native-community/react-native-tab-view#469]

**Comment by chakrihacker** [comment]
I would like to take this

**Comment by lanigga** [comment]
On this

**Comment by chakrihacker** [comment]
Update, expo detox is not working last time I checked

**Comment by chakrihacker** [comment]
I can help move to native example app or wait till expo detox is fixed

**Comment by satya164** [comment]
@chakrihacker thanks! we can try with native app
