### ISSUE TITLE
styling text label on a tab bar

### ISSUE THREAD

**Issue by ochanje210** [react-native-community/react-native-tab-view#47]
It seems the texts automatically becomes capital letters even if they were small letters..
How do u keep the text labels small letter?

**Comment by satya164** [comment]
@ochanje210 You can use the `renderLabel` prop to return a react element.

e.g. -  `renderLabel={route => <Text style={{ margin: 8 }}>{route.title}</Text>}`

**Comment by ochanje210** [comment]
@satya164 I appreciate your help!!

**Comment by AndroidDoctorr** [comment]
In the most recent version, it should be `route.route.title`

**Comment by eriegz** [comment]
> In the most recent version, it should be `{route.route.title}`

Bless you :)
