### ISSUE TITLE
Can't add box shadow to bottom tab bar

### ISSUE THREAD

**Issue by knightjdr** [react-native-community/react-native-tab-view#470]
I can't apply a box-shadow to the tab bar when placed at the bottom of my view.

Here's a code sample of the relevant bits:

```
const Style = {
   container: {
      flex: 1,
   },
   tabbar: {
      backgroundColor: '#0000ff',
      elevation: 5,
      shadowColor: '#000000',
      shadowOffset: { height: 5 }, # -5 does nothing either
      shadowOpacity: 0.75,
      shadowRadius: 5,
   },
};

renderFooter = props => (
    <TabBar
        {...props}
        renderIcon={this.renderIcon}
        style={Style.tabbar}
    />
)
render() {
    return (
      <TabViewAnimated
          initialLayout={initialLayout}
          navigationState={{
             index: this.state.index,
             routes: this.state.routes,
          }}
          onIndexChange={this.handleIndexChange}
          renderScene={SceneMap(scene)}
          renderFooter={this.renderFooter}
          style={Style.container}
      />
    );
  }
```

I also tried wrapping the TabBar component in a View component and apply the shadow to the view with no effect. I have confirmed that I can apply a shadow to other elements in my app using the above style syntax.

| software              | version
| --------------------- | -------
| android        | 8.1
| react-native          | 0.51.0
| react-native-tab-view | 0.0.74

**Comment by ravirajn22** [comment]
The shadow props like shadowOffset, shadowOpacity etc only work on iOS, not Android. For Android elevation is used, but from what I know elevation only applies shadow below the view not above. Hence applying elevation to the Tab at the bottom will create a shadow below the Tab not above, so it will not be visible. Try giving some bottom offset to the Tab and check.

**Comment by knightjdr** [comment]
Hoping this wasn't the case but thanks for the clarification.
