### ISSUE TITLE
error: package com.swmansion.gesturehandler.react

### ISSUE THREAD

**Issue by adirzoari** [react-native-community/react-native-tab-view#472]
Hello,
I installed this plugin, link it with command 'react-native link'
then I get error

> import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;
                                         ^
C:\Users\XXX\Documents\Projects\React Native\shelfmint_mobile\android\app\src\main\java\com\moonsite\shelfmint\MainApplication.java:44: error: cannot find symbol
            new RNGestureHandlerPackage(),
                ^

**Comment by ghoshabhi** [comment]
Did you install the `https://github.com/kmagiera/react-native-gesture-handler` package ?

**Comment by satya164** [comment]
Please open a new issue according to the issue template.

**Comment by HekmatFavid** [comment]
Thank you @jvandenaardweg  It works.
