### ISSUE TITLE
TabBar Indicator Under Wrong Category When Returning To Container Nested in TabNavigator

### ISSUE THREAD

**Issue by paul-hart** [react-native-community/react-native-tab-view#479]
### Current behaviour

Setup:

Using a TabNavigator with 5 screens where 3 of 5 five screens are using TabViewAnimated with TabBar from react-native-tab-view. 

Steps:
1. App launches and the first screen of the TabNavigator is a component which renders 5 sub-tabs using TabViewAnimated and TabBar from react-native-tab-view. These tabs appear on the top and the higher level TabNavigator tabs appear on the bottom.

2. Swipe to the right of the sub tabs so now the top tabs indicate that tab 2 is active of the 5 tabs.

3. Change the TabNavigator on the bottom to another category.

4. Return to the first TabNavigator tab on the bottom.

Result:

The top tabs driven by react-native-tab-view show tab 3 to be active. However the content still resembles tab 2. If you swipe a little but not enough to change to an adjacent tab, the top TabBar adjusts to the correct tab. This correction will not occur until you swipe a little.

On a side note, this also happens if you want to start on an index other than 0. Would love to just be able to pass index: 1+ and see the indicator under the correct tab. Again, in this case swiping a little fixes the indicators location and puts it under the correct tab.

Note: tapping an index seems to work, only when you change to a tab by swiping does the glitch seem to occur (at least in iOS).

### Expected behaviour

When I return to the screen that uses the react-native-tab-view TabBar and TabViewAnimated, the indicator remains under the correct tab.

Setting the index value in the state to something other than 0 should put the tab indicator in the right spot. 

### Code sample

NA

### Screenshots (if applicable)

NA

### What have you tried

Copying the code from GitHub and trying to fix the issue myself. 

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |  ios 11.2
| react-native          | 0.52.0
| react-native-tab-view | 0.0.74
| node                  | 9.4.0
| npm or yarn           | 5.6.0

**Comment by paul-hart** [comment]
Following up a little. Using the renderIndicator override property of the TabBar with nearly the same code as in the base TabBar class I was able to set a navigationState property which would force translateX to index * width. Using a timer I remove the property that forces my translateX and goes back using an Animation. This is clearly a hack, must be a better way?

I also noticed the labels are not the right fontWeights / colors. The labels also need an override to force them to be highlighted on the right tab.

**Comment by paul-hart** [comment]
Came up with a solution.

Step 1: Extend TabViewAnimated

`// @flow

import { TabViewAnimated } from 'react-native-tab-view';

// class

export default class TabViewAnimatedEx extends TabViewAnimated {
    constructor(props) {
        super(props);
    }

    resetOffsetWhenReady() {
        global.requestAnimationFrame(() => this.resetOffset());
    }

    resetOffset() {
        const { navigationState } = this.props;
        const { layout } = this.state;
        const index = navigationState.index;
        const offset = index * layout.width;
        const state = this.state;
        state.offsetX.setValue(-offset);
        state.panX.setValue(0);
    }
}
`

Step 2: In the component that uses TabViewAnimated, replace it with TabViewAnimatedEx like so:

`render() {
    return (
        <TabViewAnimatedEx
            props={this.props}
            ref={ref => (this._tabView = ref)}
            styles={commonStyles.innerTabView}
            navigationState={this.state.tabs}
            renderHeader={props => this._renderHeader(props)}
            renderScene={this._renderScene}
            onIndexChange={this._handleIndexChange}
            initialLayout={initialLayout}
        />
    );
}`

Step 3: At the end of your "_handleIndexChange" function, do this: 

`_handleIndexChange = index => {
    // ... your other code

    if (this._tabView) {
        this._tabView.resetOffsetWhenReady();
    }
};`

I was messing around with overriding props so that I could do that in my Ex class but it works well enough for me!

**Comment by paul-hart** [comment]
Came up with a solution:

`// @flow

import { TabViewAnimated } from 'react-native-tab-view';

// class

export default class TabViewAnimatedEx extends TabViewAnimated {
    constructor(props) {
        super(props);
    }

    componentDidUpdate(oldProps) {
        if (this.props.navigationState.index !== oldProps.navigationState.index) {
            if (this.state.panX._value !== 0) {
                global.cancelAnimationFrame(this._resetCallback);
                this._resetCallback = global.requestAnimationFrame(() => this.resetOffset());
            }
        }
    }

    resetOffset() {
        const { navigationState } = this.props;
        const index = navigationState.index;
        const { layout } = this.state;
        const offset = index * layout.width;
        this.state.offsetX.setValue(-offset);
        this.state.panX.setValue(0);
    }
}
`

**Comment by wildvalcom** [comment]
For me this `code fix` is still a little buggy, because I can see the jumping `indicator `. Apparently there animation issues inside of this library. I've seen a couple issues in the tracker which related to it.

**Comment by ghensley** [comment]
I am also seeing this issue when I click on containers within the tab view.

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
