### ISSUE TITLE
How to receive current route being rendered inside the `<TabBar .../>` component ?

### ISSUE THREAD

**Issue by ghoshabhi** [react-native-community/react-native-tab-view#480]
### Current behaviour
I am trying to render a custom background color for the tabbar which is being rendered and a different color for the inactive tabbar. Something like this:

<img width="383" alt="screen shot 2018-03-08 at 4 16 49 pm" src="https://user-images.githubusercontent.com/19292575/37222401-bba47e10-2381-11e8-92d2-1cc1ad7db653.png">

Somehow the `style` prop for the `TabBar` component doesn't have access to the current route being rendered or it is not exposed.

### Expected behaviour
To be able to dynamically load the style for each tabbar based on the current route being rendered

### Code sample
```js
class SomeContainerView extends Component<Props> {
  static navigatorStyle = defaultNavStyles;

  handleIndexChange = (index: number) => this.props.switchTab(index);

  renderHeader = (props: any) =>
    // console.log('props: ', props);
    (
      <TabBar
        {...props}
        indicatorStyle={styles.indicator}
        style={(props) => {
          console.log('props: ', props);
          return {
            backgroundColor: 'yellow',
          };
        }}
        tabStyle={styles.tab}
        labelStyle={styles.label}
      />
    )
  ;

  renderScene = ({ route }: Object) => {
    switch (route.key) {
      case 'key1': {
        return <Scene1 navigator={this.props.navigator} />;
      }
      case 'key2':
        return <Scene2 navigator={this.props.navigator} />;
      default:
        return null;
    }
  };

  renderPager = (props: any) => <TabViewPagerPan {...props} />;

  render() {
    return (
      <View style={{ flex: 1 }}>
        <TabViewAnimated
          initialLayout={initialLayout}
          navigationState={this.props.tabconfig}
          onIndexChange={this.handleIndexChange}
          renderHeader={this.renderHeader}
          renderPager={this.renderPager}
          renderScene={this.renderScene}
          style={{ flex: 1 }}
        />
      </View>
    );
  }
}

const mapStateToProps = (state: Object): Object => ({
  ...tabConfigSelector(state),
});

export default connect(mapStateToProps, { switchTab })(SomeContainerView);
```

### Screenshots (if applicable)
NA

### What have you tried

So what I did was store the `index` prop in my `routes` array like this:

```
routes: [
    { key: 'key1', title: 'Foo', index: 0 },
    { key: 'key2', title: 'Bar', index: 1 },
]
```

But within the `renderHeader` function I do not get the current route being rendered. I tried to use the `getLastPosition()` function to change the style as per the index received there. But I am not sure why after a couple renders I get the same value for tab switches. I am doing: `Math.floor(props.getLastPosition())`

<img width="176" alt="screen shot 2018-03-09 at 10 24 57 am" src="https://user-images.githubusercontent.com/19292575/37223200-a4c3c96e-2384-11e8-9f5f-723701c73b73.png">

I tried to access the `route` prop directly like in `renderLabel` or `renderIndicator`, but I think the style `prop` doesn't expose that. Example:

```js
style={({route}) => {
   let styles;
   if(route.index === props.navigationState.index) {
      styles = { backgroundColor: colors.DARK_RED };
   } else {
      syles = { backgroundColor: colors.LIGHT_GRAY };
   }
   return styles;
   }
})}
```

I am not sure if I am overcomplicating this. But I am not sure how to render styles for the `TabBar` dynamically based off the current route being rendered.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | both
| react-native          | 0.49.3
| react-native-tab-view | 0.0.70
| node                  | 8.2.1
| npm or yarn           | yarn v1.3.2

**Comment by satya164** [comment]
You need to render your own TabBar to do that. Check the examples on how to make a custom tab bar.

**Comment by ghoshabhi** [comment]
@satya164: Really sorry to bother you. I couldn't find a direct example of _creating_ a custom tab bar. Can you please point me to the correct link?

**Comment by satya164** [comment]
https://snack.expo.io/@satya164/custom-tabbar-example

**Comment by ghoshabhi** [comment]
You're the best! Thanks @satya164  :)
