### ISSUE TITLE
Do not run-ios when remove this lib

### ISSUE THREAD

**Issue by DanielLe232** [react-native-community/react-native-tab-view#484]
Hello all,
I have installed this lib, and i remove it.
After i run-ios again and it occur error:

=============================
ld: library not found for -lRNVectorIcons
clang: error: linker command failed with exit code 1 (use -v to see invocation)
=============================
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
This app could not be installed at this time.
Launching org.reactjs.native.example.DemoProject
org.reactjs.native.example.DemoProject: -1
An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
The request to open "org.reactjs.native.example.DemoProject" failed.
The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application "org.reactjs.native.example.DemoProject" is unknown to FrontBoard").

Could you explain why occur this error?
Thank.

**Comment by ghoshabhi** [comment]
Can you try running `react-native link` again ? Seems the `react-native-vector-icon` package is not linked. You can try to run the following steps:

```
rm -rf node_modules (or just delete the node_modules directory however you can)
yarn (or if you use npm: npm install)
react-native link
react-native run-ios
```

**Comment by satya164** [comment]
The error is unrelated to this library. Try what @ghoshabhi suggested!
