### ISSUE TITLE
Proposal: ID, waitFor and simultaneousHandlers props for Pager

### ISSUE THREAD

**Issue by jozan** [react-native-community/react-native-tab-view#486]
As I was playing around with `TabViewPagerExperimental` I noticed that it's missing some props which really make TabViewPagerExperimental and GestureHandler shine.

I wanted to build this:
```jsx
<GestureHandler.ScrollView horizontal pagingEnabled>
  <TabViewAnimated />
  <TabViewAnimated />
</GestureHandler.ScrollView>
```

`ScrollView` acts as a ViewPager and nested `TabViewAnimated` components have multiple tabs. When user swipes to the end of the first set of tabs parent scroll view would scroll to the right revealing second `TabViewAnimated `. I wanted this to be as fluid as possible and `TabViewPagerExperimental` was really handy along with `GestureHandler.ScrollView` but former was lacking some props I needed to build what I wanted so I had to build my own on top of current implementation.

I also needed to modify `TabViewPagerExperimental` a bit more to properly handle Android support in certain edge cases but was for my specific needs not general enough. I'm happy to have my own `ViewPager` at this point.

### New Props

```jsx
<TabViewPagerExperimental
  {...props}
  // new props
  id="pager"
  waitFor={['someButton']}
  simultaneousHandlers={['scrollView']}
/>
```

Would such PR be worth my time to make or not?

**Comment by satya164** [comment]
Hey, sorry I forgot about this. Can you send a PR?
