### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by PhanHoangTam** [react-native-community/react-native-tab-view#488]
I have component Home contains TabView.
2 child components : Showing & Coming are 2 Tab of component Home
Inside component Showing has a button
How to press this button, index of TabView in Home will change to 1 (move to Coming tab)

Thank you !

**Comment by ghoshabhi** [comment]
First - **please make sure you fill out the _issue template_** before you post an issue here. The maintainer is not likely going to entertain your question without it.

Secondly, if I am understanding your question correctly - you mean to ask how do you want to navigate from one screen to the other? If not, the solution below might not be relevant to you.

-------
The navigation object whose `index` property matches with `index`  in the _navigation state_ is rendered.

So for example, if your navigation state looks like this:

```js
state = {
  index: 0,
  routes: [
    { index: 0, text: 'Showing' },
    { index: 1, text: 'Coming' },
  ]
}
```
Then in both the views which have the button to navigate to/switch tabs you can just update the `index` prop like this: 

```
handleIndexChange = index => this.setState({ index });
```

and your button maybe something like this:

```
<TouchableOpacity onPress={() => this.handleIndexChange(2)}>
  <Text>Press to switch to tab 2</Text>
</TouchableOpacity>
```

Please refer to the example code [here](https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/TopBarTextExample.js#L40)!
