### ISSUE TITLE
Feature request: property to configure recognition of pan gestures in capture phase vs bubble phase

### ISSUE THREAD

**Issue by jh3141** [react-native-community/react-native-tab-view#489]
When using `TabViewPagerPan`, gesture recognition occurs in the capture phase, thus not allowing any components inside the scene opportunity to prevent the gesture being recognised.  It should be possible to configure whether the capture phase is used or not, e.g. using a property to be passed to the pager component.

In my current project, I've done this by copying the code for `TabViewPagerPan` into my own class and changing line 90 from:

```
       onMoveShouldSetPanResponderCapture: this._canMoveScreen,
```

to
```
       onMoveShouldSetPanResponderCapture: () => false,
```

which has worked nicely for my purposes, but I suspect others would benefit from being able to do so more easily in future.

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
