### ISSUE TITLE
How to change the color of underline in tabView?

### ISSUE THREAD

**Issue by ios-dev-newbie** [react-native-community/react-native-tab-view#498]
I want to change the color and width, Height of underline view? How to achieve the same.

### Current behaviour

Currently it shows a yellow underline below the current selected tab.

### Expected behaviour

Change the height and width and color of current selected tab.

**Comment by satya164** [comment]
https://github.com/react-native-community/react-native-tab-view#tabbar-

```js
indicatorStyle={{ backgroundColor: 'blue', height: 2 }}
```

**Comment by mucyomiller** [comment]
@satya164  your example for on touch in ios how to add always on indicator on current selected tab

**Comment by hammerstrike331** [comment]
https://github.com/satya164/react-native-tab-view#tabbar
  _renderTabBar = props => {
    return <TabBar
      {...props}
      inactiveColor={colors.text}
      activeColor={colors.text}
      indicatorStyle={{ backgroundColor: colors.text }}
      style={{ backgroundColor: colors.background }}
    />
    
  };
