### ISSUE TITLE
returning undefined for renderHeader results in strange behavior

### ISSUE THREAD

**Issue by dannycochran** [react-native-community/react-native-tab-view#50]
I have a TabViewAnimated component that switches between two routes, but does not show a TabBarTop until a state is triggered.

**Behavior**
1. upon first load, returns undefined for renderHeader, as I don't need a header, just the first page from my state.routes
2. once a certain state is changed to true, the header is then rendered, and a user can switch between both the routes with the header.
3. if a user hides the TabViewAnimated component (via changing the opacity, as it's an overlay within another component in my app), then returns to the TabViewAnimated component, neither page gets rendered, just the header. jumping between tabs does nothing except trigger the material animation.

**Current fix**

My current fix is to not return undefined, but a wrapper with some styling that hides TabBarTop given some state. This seems to fix the issue and is fine, but I'm curious why returning undefined seems to mess up the component lifecycle.

```
renderHeader(props) {
    // if (this.props.hideTab) {
    //   return;
    // }
    const viewProps = this.props.hideTab ? {
        style: {
          height: 0,
          opacity: 0
        },
        pointerEvents: 'none'
      } : {};

    return (
      <View {...viewProps}>
        <TabBarTop/>
      </View>
    );
  }

```

**Comment by satya164** [comment]
Hey. Can you provide a simple exponent project with an example? I'll try to debug this

**Comment by satya164** [comment]
Did you figure out? My first guess is `zIndex`. It has all sorts of weird behaviour. Could you try specifying `zIndex` as `0`?

**Comment by satya164** [comment]
Any updates on this?

**Comment by rstegg** [comment]
I have a problem with renderHeader as well, and it's so small I didn't want to open an issue:

when I have TabViewAnimated set lazy={true}, renderHeader loads after the scene.  Is this intended or a bug?  I want the scenes to lazy load, but I don't need the header to be lazy loaded.

**Comment by satya164** [comment]
Hey @rstegg . I don't think I understood the issue. lazy loading scenes shouldn't affect how header is loaded. If it's getting affected, it's bug. Do you have a demo somewhere I could take look?

**Comment by satya164** [comment]
Closing this due to no repro.
