### ISSUE TITLE
FlatList child is calling onEndReached on render

### ISSUE THREAD

**Issue by felippepuhle** [react-native-community/react-native-tab-view#501]
Something like this: https://github.com/facebook/react-native/issues/15473

### Current behaviour

`FlatList` is calling `onEndReached` just after rendering a tab.

### Expected behaviour

FlatList must call `onEndReached` just when we scroll it.

### Code sample

Home.js (main component)

```js
// ... more code here

  state = {
    tabs: Object.keys(CATEGORIES).map(category => ({
      key: category,
      title: CATEGORIES_TITLE[category],
    })),
    currentTab: 0,
  };

  renderTabScene = (props: SceneRendererProps<*> & Scene<*>) => {
    const active = this.state.currentTab === props.index;

    return <CourseListTab category={props.route.key} active={active} />;
  };

  render() {
    const { tabs, currentTab } = this.state;

    return (
      <HomeScreen statusBar={{ barStyle: 'light-content' }}>
        <TabViewAnimated
          navigationState={{ routes: tabs, index: currentTab }}
          onIndexChange={this.setCurrentTab}
          renderHeader={this.renderTabHeader}
          renderScene={this.renderTabScene}
        />
      </HomeScreen>
    );
  }

// .. more code here
```

CourseListTab.js

```js
// ... more code here

  render() {
    // from redux
    const { data } = this.props;

    console.log('rendering');

    return (
      <FlatList
        data={data}
        onEndReached={console.log}
        keyExtractor={this.keyExtractor}
        renderItem={this.renderItem}
      />
    );
  }

// ... more code here
```

### Screenshots

<img width="943" alt="screen shot 2018-04-04 at 11 16 17 am" src="https://user-images.githubusercontent.com/15961929/38313044-9f660ebc-37f9-11e8-8648-b20c1f9fac1b.png">

Any ideas?

**Comment by umaulana** [comment]
I also have this issue
@felippepuhle by any chance you already found the solution?

**Comment by felippepuhle** [comment]
@umaulana nope! tried another tab library that uses a `ScrollView` too and the bug still 😢

**Comment by umaulana** [comment]
@felippepuhle yeah I just realize that I have another `flatlist` inside react-native-tab-view in `onEndReached` works fine. I think it's not `react-native-tab-view fault` but `flatlist` inside `scrollview` fault because I only have this issue when flatlist inside `scrollview`

**Comment by imran1992** [comment]
If your flatlist calling onEndReached on render and also working scroll to the end then try this temporary fix:

Use State in constructor  let suppose `FirstTime`
 ```
constructor(props) {
    super(props);
    this.state = {
      FirstTime: true}
}
```

and at  `onEndReached`
```
onEndReached={() => {if (this.state.FirstTime) 
                          {this.setState({ FirstTime: !this.state.FirstTime });} 
                           else 
                           {alert("Calling For My Next Fetching Data");}
                      }
              }
```

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.

**Comment by moretti** [comment]
Hey @satya164, I found the same issue on `react-native-tab-view@2.10.0`.

I created a gist with a reproducible example:

https://gist.github.com/moretti/89c40ee23e54f8576ba3d87b937774c2

<img width="535" alt="react-native-tab-view scrollview bug" src="https://user-images.githubusercontent.com/1186409/62811268-5f50c100-bb01-11e9-92e6-3aefc3f5686a.png">

I realise that it's more of a bug with `ScrollView` + `FlatList`, but I'm wondering if you can think of an alternative solution.
I'm trying to include an infinite scroll list that uses `onEndReached` to fetch more items and I'd like to have the tab bar scrollable rather than fixed above the list.

**Comment by satya164** [comment]
@moretti https://github.com/react-native-community/react-native-tab-view#avoid-rendering-tabview-inside-scrollview
