### ISSUE TITLE
Unable to render Tab view

### ISSUE THREAD

**Issue by sja1n** [react-native-community/react-native-tab-view#502]
### Current behaviour
giving error 

### Expected behaviour
To render tabs 

This is the error I am getting - 

Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `SceneComponent`.
    in SceneComponent (at SceneMap.js:13) ...

### Code sample

Lists.js
```js
import React, { Component } from 'react'
import { View, Text, Dimensions } from 'react-native'
import { TabViewAnimated, TabBar, SceneMap } from 'react-native-tab-view'
import List from '../../Components/Lists/List'

class Lists extends Component {
  constructor(props) {
    super(props)
    this.state = {
      index: 0,
      routes: [
        { key: 'open', title: 'open' },
        { key: 'closed', title: 'closed' }
      ]
    }
  }

  initialLayout = {
    height: 0,
    width: Dimensions.get('window').width
  }

  indexChangeHandler = (index) => {
    this.setState({ index })
  }

  renderHeader = (props) => {
    return <TabBar {...props} />
  }

  renderScene = SceneMap({
    open: List,
    closed: List
  })

  render() {
    return (
      <View>
        <Text>Orderbook</Text>
        <TabViewAnimated
          navigationState={this.state}
          renderScene={this.renderScene}
          renderHeader={this.renderHeader}
          onIndexChange={this.indexChangeHandler}
          initialLayout={this.initialLayout}
        />
      </View>
    )
  }
}

export default Lists
```

List component

```js
import React from 'react'
import { View, Text, TouchableOpacity, StyleSheet } from 'react-native'

const List = (props) => {
  const { expanded, DetailsIcon, CancelIcon } = props
  const activeStyle = expanded ?
    { backgroundColor: colors.greyLight } :
    {}
  return (
    <View>
     <Text> ABCD</Text>
    </View>
  )
}

export default List
```

I tried to pass my List component as function as well still I am getting the same error.

### Your Environment

| software              | version
| ----------------------  | -------
| android                          | 6.0 
| react-native                  | 0.54  
| react-native-tab-view | 0.0.77
| node                              |  8.10.0
| npm                               | 4.6.1

**Comment by satya164** [comment]
You have `{ key: 'closed', title: 'closed' }` in your state, but no `closed` key in the object you pass to `SceneMap(...)`

**Comment by sja1n** [comment]
But reinstalling the app fixed the issue.
