### ISSUE TITLE
Unable to build project after installing react-native-tab-view

### ISSUE THREAD

**Issue by Louies89** [react-native-community/react-native-tab-view#504]
Hi @satya164 
I am using 
"dependencies": {
    "react": "16.3.0-alpha.1",
    "react-native": "0.54.2",
   "react-native-tab-view": "0.0.77",
}
  "devDependencies": {
    "babel-jest": "23.0.0-alpha.0",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.2",
    "react-test-renderer": "16.3.0-alpha.1"
  },

after installing "react-native-tab-view", the project is throwing below error.
![image](https://user-images.githubusercontent.com/30086899/38795418-d0b0a7c2-4175-11e8-9cff-2452c98af8fc.png)

even after down grading to "react-native-tab-view": "0.0.74" also same problem exist..

Please help....

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
