### ISSUE TITLE
how to render icon or image horizontally with text label?

### ISSUE THREAD

**Issue by karimkhamwani** [react-native-community/react-native-tab-view#505]
_renderIcon = ({ route }) => (
        <Icon name="heart" size={30} color="red"/>
    ); 

TabBar labelStyle={{color:'black'}} {...props} renderIcon={this._renderIcon} style={{backgroundColor:'white'}} indicatorStyle={{backgroundColor:'#f56231'}} />;

this works in vertical direction

**Comment by yuoppp** [comment]
`<TabBar tabStyle={{flexDirection: 'row'}}/>`

that works for me

**Comment by karimkhamwani** [comment]
omg thankyou so much.......

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
