### ISSUE TITLE
So how do I implement lazy loading in the current version?

### ISSUE THREAD

**Issue by NorthNothing** [react-native-community/react-native-tab-view#506]
| software              | version
| --------------------- | -------
| react-native          |0.54
| react-native-tab-view |0.77

I've looked at a lot of issues.
But I still don't know how to implement lazy this way?

**Comment by deecewan** [comment]
I'm currently looking at this. The way I'm doing it (and I only started like 15 minutes ago) is to just re-calculate the index + routes when I get new date, and pass that in as `navigationState`.

**Comment by NorthNothing** [comment]
Can you give me a thought?Because the page will call componentDidMount this component at the beginning.When and what do I judge?
To make an asynchronous network request.
thanks

**Comment by deecewan** [comment]
you could you `static getDerivedStateFromProps` (or `componentWillReceiveProps`) and update your state from there. I'm not maintaining any state for the actual pager - I calculate it fresh after ever page change because it's pretty cheap.

**Comment by NorthNothing** [comment]
Can you give me an example?I don't quite understand.
thanks

**Comment by Vi-jay** [comment]
lazy={true}

**Comment by Vi-jay** [comment]
oh no ,the current version has removed it

**Comment by pribeh** [comment]
I'm puzzled as well as to how to achieve this. It looks like the documented function no longer works.

**Comment by Palisand** [comment]
Justifications for removing `lazy` and an alternative approach are described [here](https://github.com/react-native-community/react-native-tab-view/releases/tag/v0.0.73).

You can also use the `focused` prop as mentioned [here](https://github.com/react-native-community/react-native-tab-view/issues/260#issuecomment-302991141) along with a property you set only once:

```javascript
...
renderScene = ({route, focused) => {
  ...
  return <Scene focused={focused} />;
  ...
}
...
class Scene extends Component {

  firstLoad = true;

  componentDidUpdate() {
    if (firstLoad && this.props.focused) {
      firstLoad = false;
      // do here what you used to do in componentWill/DidMount when lazy was available
    }
  }
}
```

**Comment by gianpaj** [comment]
Actually I found a way:

`Tabs.js`
```jsx
_renderScene = ({ route, navigationState }) => {
    switch (route.key) {
      case 'clothes':
        return (
          <ImageGrid
            focused={navigationState.index === 0}
          />
        );
      case 'shoes':
        return (
          <ImageGrid
            focused={navigationState.index === 1}
          />
        );
      case 'other':
        return (
          <ImageGrid
            focused={navigationState.index === 2}
          />
        );
      default:
        return null;
    }
};
```

`ImageGrid.js`
```jsx
export default class ImageGrid extends React.PureComponent<Props, State> {
  firstFocus = true;

  componentDidMount() {
    // for the first tab that will be in focused
    if (this.props.focused) {
      this.firstFocus = false;
      this.fetchItems(); // expensive method
    }
  }

  componentDidUpdate() {
    // when switching tabs, do this only the first time the tabs if focused to
    if (this.firstFocus && this.props.focused) {
      this.firstFocus = false;
      this.fetchItems(); // expensive method
    }
  }

  // ....
}
```

**Comment by leoyb** [comment]
Why is a basic function so complicated?

**Comment by itanhduy** [comment]
I didn't understand why we have to make it complicated while this is a very basic function for TabView.

**Comment by satya164** [comment]
Example: https://snack.expo.io/@satya164/react-native-tab-view-lazy-load

**Comment by venkatmithunk** [comment]
@satya164 lazy prop is removed?
