### ISSUE TITLE
how can i show loading indicator ?

### ISSUE THREAD

**Issue by eng0mustafa** [react-native-community/react-native-tab-view#508]
hello guys,,
i tried to view <ActivityIndicator/> while the scenes is render to avoid white page that appear

now i used 
_renderScene = ({ route }) => {

   switch (route.key) {
  case 'main':
    return <Main />;
    break;
  case 'amounts':
    return <Amounts />;
    break;
  case 'movements':
    return <Movements />;
    break;
  
  default:
    return null;
  }};
but it is delayed too 
how can i solve that please ?
thanks,,

**Comment by never00miss** [comment]
On will mount, Create a loading scene first, save it to your class state - let we call it homescreen.

On render, load the scene, it will show empty.

On did mount, call your stuff, Ajax, fetch or whatever and overide scene state

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
