### ISSUE TITLE
Custom TabViewHeader with different indicator

### ISSUE THREAD

**Issue by jgfidelis** [react-native-community/react-native-tab-view#509]
On our app, we are using tab-view 0.0.70. We had a bug and decided to update it. We noticed after 0.0.73 our indicator animation stopped happening, because the `onPositionChange` prop was removed.

Here is some code:
```
renderHeader = (tabViewConfig: any) => {
    return <TabViewHeader animatedValue={this.animatedChangingCurrentTab} tabViewConfig={tabViewConfig} />;
  };

<TabViewAnimated
            style={Layout.fullSize}
            navigationState={this.state.tabs}
            renderScene={this._renderTabScene}
            renderHeader={this.renderHeader}
            onPositionChange={this.onPositionChange}
            onIndexChange={this._handleChangeTab}
            renderPager={this._renderPager}
          />
```

And here is some code of the header:
```
class TabViewHeader extends React.Component<Props, State> {
  state = {
    labelsRect: [],
  };

  onLayoutLabelButton = (index: number) => (event: Event) => {
    const { labelsRect } = this.state;

    if (!labelsRect[index]) {
      labelsRect[index] = event.nativeEvent.layout;
      this.setState({ labelsRect });
      this.forceUpdate();
    }
  };

  getLabelActiveLineStyle() {
    const { animatedValue, tabViewConfig } = this.props;
    const { labelsRect } = this.state;

    return {
      left: animatedValue.interpolate({
        extrapolate: 'clamp',
        inputRange: tabViewConfig.navigationState.routes.map((_, index) => index),
        outputRange: tabViewConfig.navigationState.routes.map((_, index) => {
          if (!labelsRect[index]) {
            return 0;
          }

          return labelsRect[index].x;
        }),
      }),
      width: animatedValue.interpolate({
        extrapolate: 'clamp',
        inputRange: tabViewConfig.navigationState.routes.map((_, index) => index),
        outputRange: tabViewConfig.navigationState.routes.map((_, index) => {
          if (!labelsRect[index]) {
            return 0;
          }

          return labelsRect[index].width;
        }),
      }),
    };
  }

  render() {
    const { tabViewConfig, horizontalSpacing } = this.props;

    return (
      <Wrapper>
        <View horizontalSpacing={horizontalSpacing}>
          {!!tabViewConfig.navigationState &&
            !!tabViewConfig.navigationState.routes &&
            tabViewConfig.navigationState.routes.map((route, index) => (
              <TouchableOpacity
                key={route.key}
                onPress={() => tabViewConfig.jumpToIndex(index)}
                onLayout={this.onLayoutLabelButton(index)}
              >
                <Text>{route.title.toUpperCase()}</Text>
              </TouchableOpacity>
            ))}
        </View>
        <Animated.View style={this.getLabelActiveLineStyle()} />
      </Wrapper>
    );
  }
}
```

The pain is, our activity indicator should be a line only underneath the tab label.

We tried to update to 0.0.77 and use the `TabBar` as a header but we could not get this behavior appropriately.
How could we adapt our header to keep it working on the newest version? How can we substitute `onPositionChange`?
Thanks

**Comment by satya164** [comment]
I don't know what `this.animatedChangingCurrentTab` is. But `renderHeader` receives a `position` property in it's argument which you should use to interpolate on instead of a `onChangePosition` prop.

Also you shouldn't need to call `this.forceUpdate` after `setState`.

**Comment by jgfidelis** [comment]
Thank you.

I noticed position is of type `AnimatedMultiplication`. We will study on how to reimplement it because we want to keep up with the latest versions, when possible.

`animatedChangingCurrentTab = new Animated.Value(0);` if you want to know hehe.

Thanks for the feedback

**Comment by satya164** [comment]
You can interpolate on `AnimatedMultiplication`. As long as you don't need to add a listener, you don't need to change anything.

Also you should avoid animating `left` and `width`, and instead animate `translateX` and `scaleX` for better animation performance.

**Comment by jgfidelis** [comment]
Thanks, we changed to use the `position` prop and it worked. We will take a look into your `translateX` and `scaleX` tip as well. We will se the `TabBar` code to base ourselves in it.
