### ISSUE TITLE
Render TabBar separate from TabView

### ISSUE THREAD

**Issue by oopdafp** [react-native-community/react-native-tab-view#51]
Hey great & under-appreciated library! If I want my TabBar to overlay the tabview (Like I have a custom navigation and want to render the TabBar underneath it), I get it working with TabBarTop using absolute positioning, but only when scrollEnabled.  Anyone know the case, or a better approach?  (My custom navigation & content are not easily separated into separate components)

**Comment by satya164** [comment]
@oopdafp Hey. Thank you :D

absolute positioning should work without `scrollEnabled`. If it's not working, I'll check why.

You could always use the [Portal](https://joecritchley.svbtle.com/portals-in-reactjs) approach where you render the component somewhere else if your navigation and content aren't easily separated.

**Comment by satya164** [comment]
@oopdafp Hey. Thank you :D

absolute positioning should work without `scrollEnabled`. If it's not working, I'll check why.

You could always use the [Portal](https://joecritchley.svbtle.com/portals-in-reactjs) approach where you render the component somewhere else if your navigation and content aren't easily separated.

Also, the `renderHeader` function doesn't even have to be in the same component. You could define it in a parent and pass down as a prop.

**Comment by oopdafp** [comment]
When I tried absolute posiitioning with scrollEnabled=false, then it would position only the container & only the indicator would render (background color & label didn't render, for me at least)

Also, thanks I'll try the portal approach - my context is that my custom nav uses 'refs' many times to reference state of the components, so it would be harder to separate them.

**Comment by satya164** [comment]
@oopdafp Thank you. I'll debug this when I get some time. Do you have a example repo somewhere?

You could prevent switching to a tab with the `canJumpToTab` prop (check README), it didn't work properly when swipe is enabled though, do need to fix that.

**Comment by oopdafp** [comment]
@satya164 

Thanks so much! That worked for me - I'll close the issue.  

I do not have an example repo, but I know that it was

```
<TabBar
  {...props}
  swipeEnabled={false}
  style={{position: 'absolute'}} />
```

**Comment by mqtik** [comment]
I'm looking for this. I need to render the tabBar as the navigation header (not using absolute positioning, using navigation.setOptions or such)
