### ISSUE TITLE
Translucent background to tabbar

### ISSUE THREAD

**Issue by pribeh** [react-native-community/react-native-tab-view#513]
Thanks to everyone who's contributed to this incredible component!

Is it possible to set the background to the tabbar/view to translucent? I'm attempting to match the tabview with a header navigation that is translucent but no matter what part of the tabbar I attempt to apply #ffffff00 to there remains a white background. Is there a hidden view/layer behind the tab bar?

I found another issue seemingly about the issue but the suggested solution has no baring on the actual transparency of the tabview.

**Comment by amit2908** [comment]
@pribeh Actually the background color of the complete tabbar can be made translucent using rgba color scheme "rgba(255,255,255,0.5)" . But I too have a issue. I want to update the translucent color of the selected tab only. But when I try this I end up setting the background color of complete tab bar with all the elements as translucent color.

I am not able to access a particular tab for changing its bg color. Though in documentation it is written that 'tabStyle' property can be used to customize the individual tab. But its not working.

If somebody know how to customize an individual tab on selection and deselection event. Please let me know.

**Comment by pribeh** [comment]
@amit2908 Thanks !

**Comment by rgiles115** [comment]
Did you find a solution to this? I've done the same as @pribeh and tried making everything translucent with no luck.
