### ISSUE TITLE
Can't use scrollToOffset event of flatList which is inside _renderScene

### ISSUE THREAD

**Issue by kishanj918** [react-native-community/react-native-tab-view#517]
### Current behaviour

I have a flatList inside _renderScene which render cards of article, something like blog list.
& have a switch at bottom with absolute position (outside of TabViewAnimated component) now i have 3 things to show in article cards, 1. image, 2. Article Title, 3. Article Description.
on switch button change, i'm toggling article description component (hide & show toggle), and i want flatList to scroll to top.
however toggling working well, but i can't scrollToTop with flatList ref.
in sort, if i want to use ref of component which is inside _renderScene, then i can't use it.
is there any way to do so?

### Expected behaviour

It should make an reference of component (in my case flatList) and should able to handle event of that.

### Code sample
Whole code is really big, i made a sample of that to understand it easily.

__onChnageSwitch( value = !this.state.showArticleDescription ){
      ` this.setState({ showArticleDescription : value });`
       `this.GetArticleComponentRef.scrollToOffset({x: 0, y: 0, animated: true});`   //IT'S NOT WORKING.
}

_renderScene = ({route}) => {
     return (
        `<FlatList
            ref={(refs) => this.GetArticleComponentRef = refs }
            data={route.currentTabData}
            keyExtractor={(item, index) => index.toString()}
            renderItem={(item) => {
                    <ArticleCardComponent articleData={item.item} articleIndex={item.index} articleDescriptionShow={this.state.showArticleDescription} />
            }
       />`
     )
}

render(){
return (
`<View>`
`<Switch onValueChange = {(newState)=>  this.__onChnageSwitch()} value = {this.state.showArticleDescription}/>`
`<TabViewAnimated
    style={styles.container}
   navigationState={this.state}
   renderScene={this._renderScene}
   renderHeader={this._renderHeader}
   onIndexChange={this._handleIndexChange}
   scrollEnabled={true}
/>`
`</View>`
)}

### What have you tried

I tried various type of reference technics & events.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |  9
| react-native          |  0.53
| react-native-tab-view |  0.0.74
| node                  |  v8.7.0
| npm or yarn           |  npm : 5.5.1, yarn : 1.2.1

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
