### ISSUE TITLE
passing props

### ISSUE THREAD

**Issue by rogueturnip** [react-native-community/react-native-tab-view#518]
Hi!

I've gone through the issues and over the documentation and I'm trying to figure out how I can pass a prop from the <TabViewAnimated /> component all the way down to the Route.  What I'd like to do (and thought this is what happened) is
      <TabViewAnimated
        navigationState={this.state}
        renderScene={this._renderScene}
        renderHeader={this._renderHeader}
        onIndexChange={this._handleIndexChange}
        initialLayout={initialLayout}
        myprop={this.props.anotherprop}
      />

Then using renderScene pass it along to the actual route.
renderScene = ({ route }) => {
  switch (route.key) {
  case 'first':
    return <FirstRoute myprop={props.myprop} />;
  case 'second':
    return <SecondRoute />;
  default:
    return null;
  }

What am I missing in here?  I might be totally off track on how to do this so I thought I'd ask. 

Thanks!

**Comment by shubhnik** [comment]
You can do like this, if this is what you are looking for?
```js
renderScene = ({ route }) => {
  switch (route.key) {
    case 'first':
       return <ComponentA {...Aprops}/>;
    case 'second':
      return <ComponentB {...BProps}/>;
    default:
      return null;
}
```

**Comment by rogueturnip** [comment]
Thanks!  How do I get the props to renderScene from TabViewAnimated?  Was what I put above correct?

**Comment by shubhnik** [comment]
You can access this.props, this.state any other class variables in renderScene. renderScene is a class method.

**Comment by rogueturnip** [comment]
Got it.  I was mistaking what was going on.  Now I see how to use it.  Thanks!

**Comment by shubhnik** [comment]
@rogueturnip issue good to close now?

**Comment by rogueturnip** [comment]
Yes, works as you described.  Thanks!
