### ISSUE TITLE
swipe conflicts with PanResponder on iOS

### ISSUE THREAD

**Issue by deb0ch** [react-native-community/react-native-tab-view#521]
### Current behaviour

I am experiencing this issue when using the AnimatedTabView through react-navigation's TabNavigator, and tracked it down to the way AnimatedTabView handles the swiping gesture.

I am using a PanResponder inside my scene, and even when my PanResponder is handling the gesture, the AnimatedTabView's swiper handles it as well. This is undesirable as it makes the app unusable. 

This issue only happens on iOS.

### Expected behaviour

When my PanResponder has captured the gesture, the swiper should not handle it as well.

### What have you tried

I have dug into the code and found out that react-native-tab-view uses a ScrollView to handle the swipe on iOS, and found these issues that might be related:

https://github.com/facebook/react-native/issues/7444
https://github.com/facebook/react-native/issues/1046

According to the second one, the react-native team gave up on fixing this problem, so ScrollView and PanResponder might remain incompatible for a while.

Is the panResponder working with the swipe for other people ? Or is it a rare issue, related to my particular setup / set of versions ?

Is it such an unusual use case, to have a panResponder inside an AnimatedTabView, or ScrollView ?

### Your Environment

| software              | version
| --------------------- | -------
| ios        | 11.2 (15C107)
| react-native          | 0.54.3
| react-native-tab-view | 0.0.74
| node                  | v9.11.1
| yarn           | 1.5.1

**Comment by sridhard** [comment]
Any update on this issue?

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
