### ISSUE TITLE
disable press for specific tabs

### ISSUE THREAD

**Issue by jeffreymendez1993** [react-native-community/react-native-tab-view#530]
### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          |
| react-native-tab-view |
| node                  |
| npm or yarn           |

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.

**Comment by benhartouz** [comment]
@satya164 thanks for this interesting releases version , my question is can we add disable to a specific tab ?

**Comment by satya164** [comment]
@benhartouz with a custom tab bar, you could, but how will you prevent the user from swiping to the screen?

**Comment by benhartouz** [comment]
@satya164 i think there is a props to disable swiping, cause in my case i will put some buttons for users to navigating between tabs and before the user can switch up to a specific tab he must enter some mandatory informations. that's way i want to enable/disable tab's dynamically.

**Comment by a-eid** [comment]
@benhartouz have u found a solution to this issue?
