### ISSUE TITLE
Horizontal padding in Scrollable tabs

### ISSUE THREAD

**Issue by ButuzGOL** [react-native-community/react-native-tab-view#531]
Based on material design specification Scrollable tabs has horizontal padding
https://material.io/design/components/tabs.html#usage section => Scrollable tabs

**Comment by ButuzGOL** [comment]
no

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.

**Comment by renaekathleen** [comment]
@ButuzGOL did using 2.0 fix your issue? I have the same issue.
