### ISSUE TITLE
Individual Tab cannot be customized on selection and deselection only text color can be changed.

### ISSUE THREAD

**Issue by amit2908** [react-native-community/react-native-tab-view#538]
I am not able to access a particular tab for changing its bg color. Only text color can be changed using the Animated.Text component.  For example: 

`_renderTabBar = props => {`
       ` const inputRange = props.navigationState.routes.map((x, i) => i);`
       ` return (`
            `<View style={styles.tabBar}>`
             ` {props.navigationState.routes.map((route, i) => {`
                `const color = props.position.interpolate({`
                 ` inputRange,`
                 `outputRange: inputRange.map(`
                    `inputIndex => (inputIndex === i ? '#ffffff' : 'rgba(255,255,255,0.5)')`
                  `),`
                `});`
               ` return (`
                  `<TouchableOpacity`
                    `style={styles.tabItem}`
                    `onPress={() => this.setState({ index: i })}>`
                    `<View><Animated.Text style={{ color }}>{route.title}</Animated.Text></View>`
                  `</TouchableOpacity>`
                `);`
             ` })}`
           ` </View>`
         ` );`
       ` };`

Though in documentation it is written that 'tabStyle' property can be used to customize the individual tab. But its not working.  If somebody know how to customize an individual tab on selection and deselection event. Please let me know.

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
