### ISSUE TITLE
Invariant Violation: Element type is invalid: exprected string

### ISSUE THREAD

**Issue by munkhbaatar999** [react-native-community/react-native-tab-view#540]
Im using react-navigation (v2)

when i use createMaterialTopBarNavigator() -> it's not working properly. So slow and when only scrollEnabled properties true  it's working fine.

![screenshot_2018-06-12-19-54-20](https://user-images.githubusercontent.com/25764866/41289027-efdccfcc-6e7a-11e8-919a-9f4d279be143.png)

Then i use react native tab view throw me this error. 
__________________________________
![screenshot_2018-06-12-19-45-47](https://user-images.githubusercontent.com/25764866/41288568-5a32ed4a-6e79-11e8-81e6-502a9380e686.png)

AdsTopBarNav.js file
__________________________________________________
`import * as React from 'react';
import { View, StyleSheet, Dimensions } from 'react-native';
import { TabViewAnimated, TabBar, SceneMap } from 'react-native-tab-view';
import Ads from "../screens/Ads";
import { Colors } from '../themes/index';

const initialLayout = {
  height: 0,
  width: Dimensions.get('window').width,
};

export default class AdsTopBarNav extends React.Component {
  
  state = {
    index: 0,
    routes: [
      { key: 'first', title: 'FIRST' },
      { key: 'second', title: 'SECOND' },
      { key: 'third', title: 'THIRD' },
    ],
  };

  _handleIndexChange = index => this.setState({ index });

  _renderHeader = props => 
    <TabBar
        {...props}
        // scrollEnabled 
        indicatorStyle={styles.indicator}
        style={styles.tabbar}
        tabStyle={styles.tab}
        labelStyle={styles.label}
    />;

  _renderScene = SceneMap({
    first: <Ads navigation={this.props.navigation} tabId={1} />,
    second: <Ads navigation={this.props.navigation} tabId={0} />,
    third: <Ads navigation={this.props.navigation} tabId={-2} />,
  });

  render() {
    return (
      <TabViewAnimated
        style={[styles.container, this.props.style]}
        navigationState={this.state}
        renderScene={this._renderScene}
        renderHeader={this._renderHeader}
        onIndexChange={this._handleIndexChange}
        initialLayout={initialLayout}
      />
    );
  }
}

const styles = StyleSheet.create({
    container: {
      flex: 1,
    },
    tabbar: {
      backgroundColor: Colors.white,
    },
    tab: {
      height: 45,
    },
    indicator: {
      backgroundColor: Colors.skinColor,
    },
    label: {
      alignSelf: 'center',
      color: Colors.black,
      fontWeight: 'bold',
    },
});
`

CALLING FROM STACK NAVIGATION 
________________________________
`import AdsTopBarNav from './AdsTopBarNav';

export const AdsStack = StackNavigator({
    Ads: {
      screen: AdsTopBarNav,
      navigationOptions:({navigation}) => ({
        title: "INFO",
      })
    },
});`

**Comment by munkhbaatar999** [comment]
i said i use react navigation v2. Then i searching around from node-modules/react-native-tab-view/src finally fix this issue.

**Comment by shekharskamble** [comment]
hey @munkhbaatar999 how did you fix this issue? I am facing same problem

**Comment by munkhbaatar999** [comment]
@shekharskamble I saw sources from installed module named ''react-native-tab-view". Then there are different Components that i used for old version. Example TabViewAnimated => just TabView, SceneMap  key must string etc..
You should see difference between old and new version of 'react-native-tab-view' from node_modules.

**Comment by munkhbaatar999** [comment]
import { TabBar, TabView, PagerPan, SceneMap } from 'react-native-tab-view';
....

_renderTabBar = props => 
    <TabBar {...props} 
        indicatorStyle={styles.indicator}
        style={styles.tabbar}
        tabStyle={styles.tab}
        labelStyle={styles.label}
    />;
/// YOU SHOULD INCLUDE THIS LINE
 _renderPager = props => 
    <PagerPan {...props}  />;

..............



  _renderScene = SceneMap({
    // "home": () => {return <TabNavMain />},
    "first": () => { return <ChatStack />},
    "second": () => { return <ContactStack />},
    "third": () => { return <MeStack />},
  });

...............

render() {
    return (
      <TabView
        tabBarPosition={'bottom'}
        style={[styles.container, this.props.style]}
        navigationState={this.state}
        renderScene={this._renderScene}
        renderTabBar={this._renderTabBar}
        renderPager={this._renderPager}
        onIndexChange={this._handleIndexChange}
        initialLayout={initialLayout}
      />
    );
  }
