### ISSUE TITLE
How to hide or change tabBar visible after navigate subScreen like chat tab -> new Chat

### ISSUE THREAD

**Issue by munkhbaatar999** [react-native-community/react-native-tab-view#541]
### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | 4.4.2
| react-native          | 0.50.*
| react-native-tab-view | ^1.0.2
| react-navigation                  | 2.0.2
| npm or yarn           |

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
