### ISSUE TITLE
Changing selected tab bar's color is too slow when i use custom renderIcon & renderLabel function

### ISSUE THREAD

**Issue by RoysyLee** [react-native-community/react-native-tab-view#546]
### Current behaviour

I made a custom renderIcon & renderLabel function for setting selected tab's color.
original tab View's brightening effect is really fast.
and when i click tab bar changing color effect is fast.
but when i slide menu, setting tab's color(icon & label) is too slow....
seem like rendering tab bar is delayed.. 

### Expected behaviour

when i slide menu, setting selected tab's color takes same time to click tab menu.

### Code sample

_renderIcon = ({ route }) => {
    const color = (this.state.routes[this.state.index].key === route.key) ? '#fb5f26' : '#BBBBBB'
    return \<Icon
      name={route.icon}
      type={route.type}
      size={23}
      color={color}
    \/>
  }
  _renderLabel = ({ route, index }) => {
    const color = (this.state.index === index) ? '#fb5f26' : '#BBBBBB'
    return \<Text style={{color}}>{route.title}</Text>
  }

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | iOS
| react-native          | 0.55.4
| react-native-tab-view | 1.0.2
| node                  | 8.1.2
| npm or yarn           | yarn 1.7.0

**Comment by satya164** [comment]
You need to interpolate on the `position` prop

https://snack.expo.io/@satya164/custom-tabbar-example
https://facebook.github.io/react-native/docs/animations.html#interpolation
