### ISSUE TITLE
TabViewAnimated

### ISSUE THREAD

**Issue by zrone** [react-native-community/react-native-tab-view#547]
### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          |
| react-native-tab-view |
| node                  |
| npm or yarn           |

**Comment by cklinx** [comment]
Did you solve it?

Same here.

**Comment by cklinx** [comment]
Solved. Use TabView instead TabViewAnimated and renderTabBar instead renderHeader
