### ISSUE TITLE
Invariant violation error

### ISSUE THREAD

**Issue by boopathirbk** [react-native-community/react-native-tab-view#555]
It says I have to check render at login but I don't have that kind.

1) I included error and error part code.
2) please help me!

--------------This is the error showed in emulator--------

Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: number.

Check the render method of `login`.

This error is located at:
    in RCTView (at View.js:43)
    in login (at navigationStore.js:525)
    in Wrapped (at SceneView.js:17)
    in SceneView (at CardStack.js:455)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in AnimatedComponent (at Card.js:12)
    in Card (at PointerEventsContainer.js:39)
    in Container (at CardStack.js:498)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in CardStack (at CardStackTransitioner.js:67)
    in RCTView (at View.js:43)
    in Transitioner (at CardStackTransitioner.js:19)
    in CardStackTransitioner (at StackNavigator.js:41)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:226)
    in NavigationContainer (at Router.js:72)
    in App (at Router.js:93)
    in Router (at routes.js:14)
    in routes (at App.js:24)
    in RCTView (at View.js:43)
    in App (at renderApplication.js:32)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in AppContainer (at renderApplication.js:31)
getFiberTagFromObjectType
    ReactNativeRenderer-dev.js:5349:8
createFiberFromElement
    ReactNativeRenderer-dev.js:5300:45
createChild
    ReactNativeRenderer-dev.js:8495:12
reconcileChildrenArray
    ReactNativeRenderer-dev.js:8839:10
reconcileChildFibers
    ReactNativeRenderer-dev.js:9275:8
reconcileChildrenAtExpirationTime
    ReactNativeRenderer-dev.js:9723:6
reconcileChildren
    ReactNativeRenderer-dev.js:9704:4
updateHostComponent
    ReactNativeRenderer-dev.js:10129:20
beginWork
    ReactNativeRenderer-dev.js:10734:33
performUnitOfWork
    ReactNativeRenderer-dev.js:13126:21
workLoop
    ReactNativeRenderer-dev.js:13165:41
renderRoot
    ReactNativeRenderer-dev.js:13218:15
performWorkOnRoot
    ReactNativeRenderer-dev.js:13941:17
performWork
    ReactNativeRenderer-dev.js:13854:24
performSyncWork
    ReactNativeRenderer-dev.js:13814:14
requestWork
    ReactNativeRenderer-dev.js:13700:4
scheduleWork
    ReactNativeRenderer-dev.js:13537:22
scheduleRootUpdate
    ReactNativeRenderer-dev.js:14194:15
updateContainerAtExpirationTime
    ReactNativeRenderer-dev.js:14227:28
updateContainer
    ReactNativeRenderer-dev.js:14259:4
render
    ReactNativeRenderer-dev.js:14925:20
renderApplication
    renderApplication.js:54:34
run
    AppRegistry.js:101:10
runApplication
    AppRegistry.js:195:26
__callFunction
    MessageQueue.js:344:47
<unknown>
    MessageQueue.js:107:26
__guard
    MessageQueue.js:291:8
callFunctionReturnFlushedQueue
    MessageQueue.js:106:17

-------------This is my login.js---------------

import React, { Component } from 'react';
import {
  StyleSheet,
  Text,
  View,
  TouchableOpacity
} from 'react-native';

import Logo from '../img/logo.png';
import Form from '../components/form.js';

import { Actions} from 'react-native-router-flux';

export default class login extends Component {

    signup(){
        Actions.signup()
    }
    render() {
        return (
            <View style={styles.container}>
                <Logo/>
                <Form type='Login'/>
                <View style={styles.signupTextCont}>
                    <Text style={styles.signupText}>Don't have an account yet?</Text>
                    <TouchableOpacity onPress={this.signup}><Text style={styles.signupButton}>SignUp</Text></TouchableOpacity>
                </View>
            </View>
        )
    }
}
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#63b4f4',
    alignItems: 'center',
    justifyContent: 'center'
  },
  signupTextCont:{
    flexGrow: 1,
    alignItems: 'flex-end',
    justifyContent: 'center',
    paddingVertical: 16,
    flexDirection: 'row'
  },
  signupText:{
      color:'#ffffff',
      fontSize: 16
  },
  signupButton:{
      color:'#ffffff',
      fontSize: 16,
      fontWeight: '500'
  }

});

Help me please!!!

**Comment by alainib** [comment]
get the same error after update from v0.70.0 to v1.0.2. 
did you fix it ?

**Comment by satya164** [comment]
@boopathirbk I don't see tab view in your stack trace.

@alainib please check the release notes: https://github.com/react-native-community/react-native-tab-view/releases/tag/v1.0.0
