### ISSUE TITLE
How can I add a fixed header above the tab view?

### ISSUE THREAD

**Issue by Garvita-hike** [react-native-community/react-native-tab-view#557]
I am trying to add a fixed header above my tab view. 

Currently, The tab bar occupies the whole screen.

**Comment by merbin2012** [comment]
I have the same problem

**Comment by chenhuaxian** [comment]
I have the same problem

**Comment by maxgfr** [comment]
+1

**Comment by winardis** [comment]
i having the same issue where i need to render some other content on top of the tab bar
but i do that the tab bar seems to have some sort height issue? cmiiw
