### ISSUE TITLE
[ios] Top tabbar bouncing when press

### ISSUE THREAD

**Issue by umaulana** [react-native-community/react-native-tab-view#558]
### Current behaviour
tab screen will be bouncing when top tab bar is pressed. This only happens in ios but not in android.

### Expected behaviour
tab bar change smoothly

### Code sample

```
import { TabViewAnimated, TabBar, TabViewPagerScroll } from 'react-native-tab-view';

 this.state = {
      index: 0,
      routes: [
        { key: '1', title: '1' },
        { key: '2', title: '2' },
        { key: '3', title: '3' },
        { key: '4', title: '4' }
      ]
}

 _handleIndexChange = index =>
    this.setState({
      index
    });

_renderScene = ({ route }) => {
    switch (route.key) {
      case '1':
        return (
          <View style={{ backgroundColor: 'red', flex: 1 }} />
        );
      case '2':
        return (
          <View style={{ backgroundColor: 'green', flex: 1  }} />
        );
      case '3':
        return (
          <View style={{ backgroundColor: 'blue', flex: 1  }} />
        );
      case '4':
        return (
          <View style={{ backgroundColor: 'yellow', flex: 1  }} />
        );
      default:
        return null;
    }
  };

_renderTabBar = props => (
    <TabBar
      {...props}
      scrollEnabled
      indicatorStyle={styles.tabBarIndicator}
      style={styles.tabbar}
      tabStyle={styles.tab}
      labelStyle={styles.tabBarLabel}
    />
  );

render () {
return (
....
 <TabViewAnimated
          style={[styles.container, this.props.style]}
          navigationState={this.state}
          renderScene={this._renderScene}
          renderHeader={this._renderTabBar}
          onIndexChange={this._handleIndexChange}
          initialLayout={initialLayout}
          renderPager={(props) => <TabViewPagerScroll {...props} />}
          useNativeDriver
        />
)
}
```

### Screenshots (if applicable)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9917335/42515023-f66af718-8484-11e8-8eff-d364b2f2ac5e.gif)

### What have you tried
Changing pager to use PagerPan or PagerScroll seems not the answer

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios only
| react-native          |  0.50.4
| react-native-tab-view | ^0.0.73
| node                  | 8.9.1
| npm or yarn           | yarn 1.3.2
| react-navigation |^1.0.0-beta.15

**Comment by umaulana** [comment]
ah sorry here's the gif https://i.imgur.com/Qtvh5AH.gif

**Comment by umaulana** [comment]
this not react-native-tab-view bug. It happens because of high cpu in react-native-maps
https://github.com/react-community/react-native-maps/issues/1031

can someone close this issue

**Comment by mlympix-prabhav** [comment]
Can you please show your styles code ?
