### ISSUE TITLE
Provide Better Documentation on TabView Animation Requirements

### ISSUE THREAD

**Issue by solomonhawk** [react-native-community/react-native-tab-view#559]
**NOTE** The issue described here may be resolved via https://github.com/react-native-community/react-native-tab-view/commit/f5756e95bd1beeee02ecfbc26f98ee2acae8b83e which as of me writing this is the most recent commit in `master` which hasn't been released yet.

Perhaps an action item after that's been released is to update the documentation to describe the behavior (e.g. "When `navigationState.routes` changes size, we cannot reliably animate the Pager so we change slides without animating.")

### Current behaviour

If you create a `<TabView />` and you inadvertently pass it a new `routes` object as part of the `navigationState` prop - you will not see any animations when interacting with the `TabBar`. This is not documented and not terribly expected either.

### Expected behaviour

I did not disable animation (e.g. via `animationEnabled={false}`), therefore I expect to see animations when changing tabs.

### Code sample

I don't have time at this moment to put together a complete example, but the scenario is fairly simple:

```
// In some component, render method
render() {
  let key = .. get the current route key ..
  let index = .. get the current route index ..

  let navigationState = {
    index,
    routes: { ...ROUTES } // CONTRIVED, I've demonstrated the notion that this field is a new object on every `render`. Imagine this is a function call that returns the routes, but will return a new object every time. This is obviously bad, but fairly easy to accidentally do.
  }

  return (
    <TabView
      navigationState={navigationState}
      renderScene={this._renderScene} // not important for the example
      initialLayout={INITIAL_LAYOUT} // not important for the example, correctly configured
    />
  )
}
```

### What have you tried

Several different things, but to no avail. Finally I recognized that I was passing in a new object on each render after I inspected this library's source code and found the equality check on `navigationState.routes`.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | both
| react-native          | 0.55.4
| react-native-tab-view | ^1.0.2
| node                  | 8.11.3
| npm or yarn           | yarn 1.7.0

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
