### ISSUE TITLE
UX is inappropriate if one of the tabs contains ScrollView

### ISSUE THREAD

**Issue by anton-aleksandrov** [react-native-community/react-native-tab-view#56]
Swiping between tabs feels not good if one of tabs contains scrollview: scrollview prevail on swiping too much, so it's hard to swipe between tabs instead of scrolling up and down.

Try to apply this piece of code to this library:

```
onPanResponderMove: (_, {dx, dy, x0, y0}) => {
  if (!this._axis) {
    const dx2 = dx * dx;
    const dy2 = dy * dy;
    if (dx2 + dy2 > 10) {
      this._axis = dx2 > dy2 ? 'x' : 'y';
    }
  }
}
```
This feels way better.

**Comment by satya164** [comment]
I'm not sure about this. In the app we were working on, I found the swipe was triggering a lot when scrolling.

**Comment by satya164** [comment]
The default pager now uses native primitives. So this is no longer relevant.

**Comment by kulikalov** [comment]
@satya164 is there a convenient way to increase swipe angel now?
