### ISSUE TITLE
how to pass props to rendered view 

### ISSUE THREAD

**Issue by imansalhi** [react-native-community/react-native-tab-view#563]
I created a tab view used [this guide ](https://snack.expo.io/@satya164/custom-tabbar-example) and every thing worked correctly but i cant use props.navigation in rendered views...how can i pass props to the components i render them in tab-view?
i need some thing like this:
` <Hotest navigation={this.props.navigation}/>  `

how its possible?

**Comment by satya164** [comment]
https://github.com/react-native-community/react-native-tab-view#scenemap

> to pass additional props to your scene components, use renderScene directly instead of using SceneMap
