### ISSUE TITLE
Props inactiveBackgroundColor & activeBackgroundColor for TabBar 

### ISSUE THREAD

**Issue by Donhv** [react-native-community/react-native-tab-view#566]
Hello everyone! I have question about TabBar .
have it support change background color when tab focused or unFocused?
If it not support how i can make it by tabBarComponent?
thanks all!
My Environment:
react-navigation | ^2.6.2
react-native | ~0.55.4
node |
npm

**Comment by pavithra2110** [comment]
Any solution?

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
