### ISSUE TITLE
how to use it in ScrollView?

### ISSUE THREAD

**Issue by imansalhi** [react-native-community/react-native-tab-view#567]
I  want to use tab view inside `<ScrollView> `but it doesn't render!...and every one has this problem.. 
how to render tabview inside ScrollView!...is there any  solution for that ? or its impossible ?

**Comment by acollazomayer** [comment]
Having the same problem also!, is there a way to do so? Can someone answer please

**Comment by binoalien** [comment]
https://github.com/react-native-community/react-native-tab-view/issues/537

**Comment by tmtung144** [comment]
me too

**Comment by firashamila33** [comment]
same problem here !!!
I reprduced the problem [here](https://snack.expo.io/@plazma33/tab-bar-nested-in-scrollview-problem),,, any solutions ??

**Comment by firashamila33** [comment]
**Solved**  following [this](https://github.com/react-native-community/react-native-tab-view/issues/537#issuecomment-395359494)

**Comment by Faolain** [comment]
Amazing work @satya164 I was wondering if one wants to render a <ScrollView> within a route what do you suggest? Currently it renders blank on android when you nest any route within ScrollView. I want to keep the TabBar on top where it is currently and only have the child view scroll. Is this possible?

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.

**Comment by hamsddxn** [comment]
helo everyone, is this problem solved?
i have same issue
