### ISSUE TITLE
Before leaving the route, renderTabBar did it again.

### ISSUE THREAD

**Issue by ghost** [react-native-community/react-native-tab-view#569]
## Current behaviour
RenderTabBar has done it again when I leave the page with tabview.The execution of renderTabBar before leaving will cause the error of the tabbar text color animation in the next time you come in.
## Expected behaviour
I want to leave renderTabBar no longer before I leave
## Code sample
```javascript
       <TabView
            style={[{flex: 1}, this.props.style]}
            navigationState={this.state}
            renderScene={this._renderScene}
            renderTabBar={this._renderTabBar}
            tabBarPosition="top"
            onIndexChange={this._handleIndexChange}
            animationEnabled={false}
            swipeEnabled={true}
          />
```
renderTabBar
```javascript

  _renderTabBar = props => (
    <View style={styles.tabbar}>
      {props.navigationState.routes.map((route, index) => {
        return (
          <TouchableOpacity
            key={route.key}
            style={{flex: 1}}
            onPress={() => props.jumpTo(route.key)}>
            <Animated.View style={styles.tab}>
              {this._renderLabel(props)({route, index})}
            </Animated.View>
          </TouchableOpacity>
        )
      })}
    </View>
  )
```
renderLabel
```javascript
  _renderLabel = ({position, navigationState}) => ({route, index}) => {
    const inputRange = navigationState.routes.map((x, i) => i)
    const outputRange = inputRange.map(
      inputIndex => (inputIndex === index ? '#ffffff' : '#9B9B9B')
    )
    const color = position.interpolate({
      inputRange,
      outputRange,
    })
    console.log(JSON.stringify(color))
    return (
      <Animated.Text style={[styles.label, {color}]}>
        {route.title}
      </Animated.Text>
    )
  }
```
## Your Environment
| software | version |
| ------ | ------ | 
| react-native | 0.56 | 
| react-native-tab-view | 1.0.2 | 
| ios | 11.4 |

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
