### ISSUE TITLE
Android Swipe Tabs incorrect / double / twice navigates

### ISSUE THREAD

**Issue by lixaotec** [react-native-community/react-native-tab-view#570]
### Current behaviour
Dear fellows, 

I´m facing an issue with react-native-tab-view. When I swipe from android, the navigation seem to get messy and do not switch tavs correctly. Everytime it advances two tabs (seems to be calling twice the _renderScene).

The same behavior doesn´t occur at iOS.

How to fix it please?

### Your Environment

    "expo": "^27.0.1",
    "react": "16.3.1",
    "react-native": "~0.55.2",
    "react-native-paper": "^1.11.0",
    "react-native-tab-view": "^1.0.2",
    "react-navigation": "^2.8.0"

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
