### ISSUE TITLE
TabView in TabNavigation

### ISSUE THREAD

**Issue by Toshihiro2010** [react-native-community/react-native-tab-view#571]
I want Tabview in TabNavigator Screen.but subTab S1-S3 No Display and No Slide.

![image](https://user-images.githubusercontent.com/19641939/43180080-4e2a51d4-9000-11e8-8a21-b010302e76b0.png)

but subTab Display and slide normally

![image](https://user-images.githubusercontent.com/19641939/43180147-a5f99f8c-9000-11e8-9bee-eaa652facb85.png)

### Your Environment

| software              | version
| react-native         0.54.0 |
| react-native-tab-view 1.0.2 |

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
