### ISSUE TITLE
Dynamic SceneMap re-renders on each tab switch

### ISSUE THREAD

**Issue by vuckookv3** [react-native-community/react-native-tab-view#572]
### Current behaviour

So I have dynamic tab render (depending on number of players) and dynamic SceneMap.

```
        state = {
            index: 0,
            routes: new Array(this.players_count).fill().map((e, i) => ({ key: 'player' + i, title: this.props.players_names['player' + i].toUpperCase() }))
        };

    makeRoute = (player) => (
        <View style={{ flex: 1 }}>
        
            <ScrollView>

                <View style={{ flex: 1 }}>
                    {this.renderInputs(player)}
                </View>

            </ScrollView>
        </View>
    )

    makeSceneMap = () => {
        const all = {};

        for (let i = 0; i < this.players_count; i++) {
            all['player' + i] = this.makeRoute.bind(this, 'player' + i)
        }

        return all;
    }

    render() {
        return (
            <View style={styles.mainContainer}>

                <TabView
                    navigationState={this.state}
                    renderScene={SceneMap(this.makeSceneMap())}
                    onIndexChange={index => this.setState({ index })}
                    initialLayout={{ width: Dimensions.get('window').width, height: Dimensions.get('window').height }}
                />

            </View>
        )
    }
```
This renders fine, but on tab switch, it all rerenders, and makeSceneMap() gets called again, and resets each tab.

### Expected behaviour

I want to keep the previous entered words of previous tabs.

### Screenshots (if applicable)

http://recordit.co/sKzjJ8N1fo

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | 23.0.1
| react-native          | 0.55.4
| react-native-tab-view | 1.0.2
| node                  | 9.9.0
| npm or yarn           | 5.6.0

**Comment by vuckookv3** [comment]
Solved this by calling makeSceneMap() inside constructor and putting it in one variable, and giving real SceneMap(this.sceneMap)

**Comment by msafayasar** [comment]
@satya164 As I tried what you wrote: `all['player' + i] = <MakeRoute player={player} />`
But there is an error that says it needs to be string. What is the problem?
