### ISSUE TITLE
Instead of routes in state how to pass header data to TabViewAnimated 

### ISSUE THREAD

**Issue by sajidsajj** [react-native-community/react-native-tab-view#574]
HI all,

Currently we are setting the header array/data in react native state routes array ( as show below ) .

this.state = {
routes: [
        { key: '1', title: 'cars'},
        { key: '2', title: 'bikes' },
      ],
}

Instead of above how to pass the header data through props or renderHeader function to TabViewAnimated ?

TabViewAnimated
          style={styles.container}
          navigationState={this.state}
          renderScene={this._renderScene(data)}
          renderHeader={this._renderHeader}
          onIndexChange={this._handleIndexChange}

Already i am passing tab render data through renderScene  ??? please suggest any solution for header

**Comment by DaKaZ** [comment]
What version of the library are you using? `renderHeader` and `renderFooter` were changed to just `renderTabBar` and a new prop `tabBarPosition` was added (which defaults to 'top')

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
