### ISSUE TITLE
unable to resolve module 'react-native-tab-view '

### ISSUE THREAD

**Issue by Anujmoglix** [react-native-community/react-native-tab-view#577]
Hi ,
   I am getting unable to resolve module when i am importing it .Module doesn't exist in module map ... bla bla,
I checked package.json it is already there , "react-native-tab-view": "^1.0.2",

**Comment by areeb111** [comment]
Check node_modules directory and see if it's already there or not ?

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
