### ISSUE TITLE
Example app is broken

### ISSUE THREAD

**Issue by sbefort** [react-native-community/react-native-tab-view#581]
Example app linked from the ReadMe.md is broken:
https://expo.io/@satya164/react-native-tab-view-demos

**Comment by DaKaZ** [comment]
Looks like someone just submitted a PR #582 to fix this...

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
