### ISSUE TITLE
How to customize active and inactive label color?

### ISSUE THREAD

**Issue by jungleyu** [react-native-community/react-native-tab-view#583]
Currently I can just set label color, when I change the tab, it just change the opacity. But what can I do if I want to set different label color for active and inactive label.
What I do now is just using renderLabel to decide active label and inactive label style.

**Comment by DaKaZ** [comment]
That is how this library works.  If you want something besides the default, you would need to create a custom `renderLabel` method and pass that in.  In order to help determine which label is active, I just submitted this PR (for a different issue) but it should help on this issue too: https://github.com/react-native-community/react-native-tab-view/pull/589

**Comment by C0dekid** [comment]
Would be really helpfull if you can add these in a prop like

`activeColor={'Your color'}` and `inactiveColor={'custom label'}`

**Comment by DaKaZ** [comment]
@t3chnoboy I think we can solve this in #589 - I am engaging with @satya164 to ensure that the approach is to his liking so that it can be merged when complete.  Please jump on that thread if you have input.

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.

**Comment by Base29** [comment]
Hello guys the activeColor and inactiveColor props are not working for me.
RN version = 0.59.10
RN Tab View version = 2.10.0

what could be the issue ?

**Comment by LaszloDev** [comment]
Same issue as @Base29.
`<TabBar inactiveColor='green' />` does have no effect.

react-native-tab-view@2.10.0
react-native > expo v34

**Comment by obiwankenoobi** [comment]
same here. `activeColor` have no effect.  Any updates on this issue? (:

**Comment by flikQ** [comment]
this still appears to be an issue.

**Comment by Dreamfullstacker** [comment]
<TabBar {...props} 
                        activeColor={'#007AFF'}
                        indicatorStyle={{ backgroundColor: '#007AFF' }}
                        style={{ backgroundColor: '#F2F2F7'}}
                        renderLabel={({ route, focused, color }) => {
                            if(focused)
                            return(
                                <View style={{flexDirection : 'row', justifyContent : 'center'}}>
                                    <Text style={[{ color : '#007AFF'}, styles.TabViewBarItemText]}>
                                    {route.title}
                                    </Text>
                                </View>
                            )
                            else
                            return(
                                <View style={{flexDirection : 'row', justifyContent : 'center', alignItems : 'center'}}>
                                    <Text style={styles.TabViewBarItemText}>
                                    {route.title}
                                    </Text>
                                </View>
                            )
                        }}
                        />

Have solved problem by customize TabBar code
