### ISSUE TITLE
Cannot disable swipe in Tab View Animated

### ISSUE THREAD

**Issue by emmajam** [react-native-community/react-native-tab-view#59]
My component and it's props:
```
<TabViewAnimated
    style={styles.navBar}
    navigationState={this.state}
    renderScene={this._renderScene}
    renderHeader={this._renderHeader}
    onRequestChangeTab={this._handleChangeTab} />
```
This is my header bar:
```
_renderHeader = (props) => {
    return (
      <TabBarTop
        {...props}
        style={styles.tabBar}
        indicatorStyle={styles.indicator}
        labelStyle={styles.label}  />
    );
  }
```

No prop to disable swipe gestures...?

**Comment by satya164** [comment]
Please check the docs - https://github.com/react-native-community/react-native-tab-view#tabviewpagerpan-
And examples - https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/NoAnimationExample.js#L126

**Comment by Randy808** [comment]
I think he was referring to the fact that you don't have a swipeEnabled option for TabViewAnimated, which you don't. The link you referred to is TabViewPagerPan which wouldn't be used for the same tasks as TabViewAnimated.

**Comment by satya164** [comment]
How does having the option on TabViewAnimated make a difference?
