### ISSUE TITLE
How to reload the tab?

### ISSUE THREAD

**Issue by oguzkaganeren** [react-native-community/react-native-tab-view#592]
### Current behaviour

There is a no problem with the tab view. It's work.

### Expected behaviour

I want to reload the tab(or tabs) when changing the tab index.

### Your Environment

| software              | version
| --------------------- | -------
| react-native          | 55.4

**Comment by sumitjr** [comment]
@oguzkaganeren did you find the solution?

**Comment by witalobenicio** [comment]
@sumitjr just use SceneMap and it will do the job.
