### ISSUE TITLE
Update height to focused scene height

### ISSUE THREAD

**Issue by jjenzz** [react-native-community/react-native-tab-view#594]
I haven't followed the template as this is a feature request.

It would be really handy if there was an option to make the focused scene as tall as its content. Currently, scenes with hardly any content will be as tall as the tallest scene.

If you can point me in the right direction then I'd be happy to submit a PR for this.

**Comment by bpolonia** [comment]
I'm running into this situation myself. Came here to see if anyone else had run into it and figured it out. Any luck with this @jjenzz ?

**Comment by yangnana11** [comment]
Refer here #290

**Comment by e11i0t** [comment]
Depending on what you want to do, it may be better to handle a "isFocused" on each tab. This will also prevent to load all tabs on the init state. And for your case you can add a condition to your FlatList with a `{ this.state.focused ?`

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.

**Comment by cassianomon** [comment]
version 2.10 and it doesn't work, all tabs have height equals to the higher.

**Comment by soqt** [comment]
any solution / plan for this feature?

**Comment by tomsupertramp** [comment]
version 2.14.0 and it still doesn't work
