### ISSUE TITLE
Tab Bar Indicator is missing for custom tab bar

### ISSUE THREAD

**Issue by selvananbu** [react-native-community/react-native-tab-view#595]
### Code sample
    _renderTabBar = props => {
    const inputRange = props.navigationState.routes.map((x, i) => i);

    return (
      <View style={styles.tabBar}>
        {props.navigationState.routes.map((route, i) => {
          const color = props.position.interpolate({
            inputRange,
            outputRange: inputRange.map(
              inputIndex => (inputIndex === i ? '#fff' : '#222')
            ),
          });
          return (
            <TouchableOpacity
              key={i}
              style={styles.tabItem}
              onPress={() => this.setState({ index: i })}>
              <Animated.Text style={{ color,fontSize: 20}}>{route.title}</Animated.Text>
            </TouchableOpacity>
          );
        })}
        indicatorStyle={{ backgroundColor: '#f6de6c' }}
      </View>
    );
  };
  render() {

    return (
      <TabView
         navigationState={this.state}
         renderScene={SceneMap({
           report: Report,
           chart: Chart,
           pivot: Pivot,
         })}
         onIndexChange={index => this.setState({ index })}
         initialLayout={{ width: Dimensions.get('window').width ,height:height(10)}}
         tabStyle={{backgroundColor: '#A32453'}}
         labelStyle={{backgroundColor: '#A32453'}}
         renderTabBar={this._renderTabBar}
         onIndexChange={this._handleIndexChange}

       />
     );
  }
}

![untitled](https://user-images.githubusercontent.com/5378843/44766605-4c9ce080-ab6b-11e8-904a-9e77979b3e29.png)

### What have you tried

I used the docs to create a custom tab bar now my question is how to add indicator.

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
