### ISSUE TITLE
Navigation within page

### ISSUE THREAD

**Issue by mrjcka** [react-native-community/react-native-tab-view#60]
Hi there, thank you for this amazing plugin, I found it so much easy to implement quality navigator.

I run into a situation that need to navigate to different page within a page content instead of TabBar icons. I had a look through and did not find the solution, I hope that there is a way to do that

Cheers!

**Comment by satya164** [comment]
@mrjcka You can do `this.setState({ index: 3 })` to navigate to the 3rd page and so on.

**Comment by mrjcka** [comment]
Thanks for the answer Satyajit! I wasn't explain well my case but I have found way to work around from your answer.

For anyone who run into the issue, the case is instead of return a <View> directly through _renderScene (see from repository example), I rendered a view component from different file.
To navigate to different tab, I passed _handleChangeTab into the view component as below and called from inside the View component

```javascript
import Home from './home'
import Settings from './settings'

_renderScene = ({ route }) => {

    switch (route.key) {
    case '1':
      return <Home changeTab={this._handleChangeTab} />;
    case '2':
      return <Settings changeTab={this._handleChangeTab} />;
    case '3':
      return <View style={[ styles.page, { backgroundColor: '#4caf50' } ]} />;
    default:
      return null;
    }
  };
```

Then inside the View component, when we need to navigate to different tab/view 
```javascript
this.props.changeTab(3)
```

**Comment by satya164** [comment]
@mrjcka Yes, that's the correct solution.
