### ISSUE TITLE
Solution to change icon color of the selected tab

### ISSUE THREAD

**Issue by flashkiller58rus** [react-native-community/react-native-tab-view#600]
Is the any working solution to change icon (i use only icon in a tab withoun label) color of the active tab?

I tried following to implement needed behaviour, but it doesn't work for me. All icons still in one color and not changed when tab activated.

`_renderIcon = ({ route,index }) => (
    <Icon name={route.icon} size={24} color={this.state.index == index ? "#1308FE" : "#8A8A8F"} />
  );`

My complete task is: 
    -always white tabbar background, 
    -grey inactive icons,
    -blue active one.

Need help to realize this if it possible with this tabview component.

**Comment by flashkiller58rus** [comment]
@andreiguzga Thanks a lot! It works great!
Can u clarify why my code do nothing for my understanding?

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
