### ISSUE TITLE
create github page to docs

### ISSUE THREAD

**Issue by nicholasess** [react-native-community/react-native-tab-view#608]
Hi everyone!
I'm member of the core team [docz](https://github.com/pedronauck/docz) and i will send a PR with docs to react-native-tab-view. Before that, i need that you create in settings the github page in branch master the folder ```docs```. 

After tell me when the github page created.

Thanks

**Comment by nicholasess** [comment]
@satya164 thanks 💯

**Comment by nicholasess** [comment]
@satya164 are there someone update?

**Comment by satya164** [comment]
so? :)
