### ISSUE TITLE
When I click on the tab header the content of tab does not animation (swipe)

### ISSUE THREAD

**Issue by GerardCasadevall** [react-native-community/react-native-tab-view#609]
In the demonstration of the documentation by clicking on the tab header the content of the tab changes making the animation (swipe), I tried to reproduce this scenario and it is impossible for me.

https://github.com/react-native-community/react-native-tab-view/blob/master/demo/demo.gif

How do the same effect of changing the tab with my finger when I click on the header of the tab? Now when I click on the tab header the content is loaded without any animation.

**Comment by UsmanAkmal01** [comment]
can you show your code? its most likely you have two state. make sure you defined keys like this in constructor: ```constructor(props) {
  super(props);
  this.state = {


    index: 0,
    routes: [
      { key: 'a', title: 'a' },
      { key: 'b', title: 'b' },
      { key: 'c', title: 'c' },
    ],}}```

**Comment by GerardCasadevall** [comment]
Hi UsmanAkmal01,

My code:

var tabs = {
	twitter: <View style={{ flexGrow: 1 }}>{this.twitterTab}</View>,
	quote: <View style={{ flexGrow: 1 }}>{this.contractSheetTab}</View>,
	dom: <View style={{ flexGrow: 1 }}>{this.booksTab}</View>,
	chart: <View style={{ flexGrow: 1 }}>{this.chartTab}</View>
}; 
var routes = [
	{ key: 'twitter', title: I18n.t('Twitter') },
	{ key: 'quote', title: I18n.t('Quote') },
	{ key: 'dom', title: I18n.t('Dom') },
	{ key: 'chart', title: I18n.t('Chart') }
];

<TabView
	navigationState={{
		index: this.state.currentTab,
		routes: routes
	}}
	style={{ flex: 1 }}
	renderTabBar={props => (
		<TabBar
			{...props}
			indicatorStyle={{
				backgroundColor:
					Theme.topTabBarActiveTextColor,
				height: 3
			}}
			style={{
				backgroundColor: Theme.tabDefaultBg
			}}
			renderLabel={({ route }) => (
				<View style={GlobalStyles.tabBarItem}>
					<Text
						style={[
							GlobalStyles.tabBarItemText,
							{
								color:
									Theme.topTabBarActiveTextColor
							}
						]}>
						{route.title}
					</Text>
				</View>
			)}
		/>
	)}
	renderScene={route => {
		const scenes = tabs;
		return scenes[route.route.key];
	}}
	onIndexChange={this.handleOnChangeTab}
	initialLayout={{
		width: Dimensions.get('window').width,
		height: 0
	}}
/>

As you can see in the gif, the last two transitions that are made by clicking on the header of the tab do not make any animation:

![untitled](https://user-images.githubusercontent.com/13941090/45492821-97bf1200-b76d-11e8-9fec-7c74f3bce9cf.gif)

regards!

**Comment by satya164** [comment]
can you post the full code? your code isn't clear. you can wrap the code in 3 backticks so it's properly formatted:


    ```js
    your code here
    ``|

**Comment by GerardCasadevall** [comment]
Someone has a code that when click the header of tab the content of the tab changes making the animation (swipe)?

**Comment by ManigandanRaamanathan** [comment]
Any solution for this problem?

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
