### ISSUE TITLE
Empty space under tabulation

### ISSUE THREAD

**Issue by 7fantasy7** [react-native-community/react-native-tab-view#610]
### Current behaviour
Empty space under tabulation

### Expected behavior
Appearing header 

### Code sample
https://snack.expo.io/@satya164/collapsible-header-with-tabview

### Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/10965264/45928296-f3e21d00-bf49-11e8-953b-fc4f15dfb95f.png)

I tried to make my own view based on example.
And after changing tab it looks like this:
![image](https://user-images.githubusercontent.com/10965264/45928313-3ad01280-bf4a-11e8-9568-3c4788528b2e.png)

And after scrolling even for a pixel header appears again:
![image](https://user-images.githubusercontent.com/10965264/45928319-51766980-bf4a-11e8-87f9-7f49157353de.png)

My code:
https://pastebin.com/rYwwMtzG

**Comment by 7fantasy7** [comment]
Created snack on expo with cutted logic from app to show behavior
https://snack.expo.io/ryxqr7HYX

To reproduce: scroll page down, then change tab

**Comment by nbhaohao** [comment]
same problem

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
