### ISSUE TITLE
get height of tab view?

### ISSUE THREAD

**Issue by hsunami10** [react-native-community/react-native-tab-view#612]
How do I get the height of the tab view / tab bar? I've tried using an `onLayout` callback like normal elements, but it doesn't work.

**Comment by jerearaujo03** [comment]
Did you solve this?

**Comment by BharathBunty** [comment]
How can i Adjust height With the content in each tab..  i unable to wrap the data. empty space produced after data popping from server , please help me. to set the height for each tab view , i m getting the height of highest tab
