### ISSUE TITLE
Nesting TabView within renderScene of parent TabView

### ISSUE THREAD

**Issue by Faolain** [react-native-community/react-native-tab-view#614]
### Current behaviour
When I try to nest a TabView within a route of a parent TabView nothing renders other than the parent and child tab bars.

### Expected behaviour

I should be able to render and switch between the tabs of a nested child component which should then bubble up to swipe to the parent component if there are no longer any tabs left to swipe within the child view.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.57
| react-native-tab-view | 1.0.2
| node                  | 10.2.1
| npm or yarn           | 6.4.0

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
