### ISSUE TITLE
change the amount the indicator scrolls when switching tabs?

### ISSUE THREAD

**Issue by hsunami10** [react-native-community/react-native-tab-view#616]
How do I change the amount the indicator moves when switching tabs? I decreased the width of the tab view, and now the indicator starts in the correct position, but then switching to the other tab, is completely offset from where it's supposed to be. Something like this: 
<img width="373" alt="screen shot 2018-10-02 at 3 46 12 pm" src="https://user-images.githubusercontent.com/22967267/46375932-55953c00-c65a-11e8-9f8a-2dad76994b5d.png">
<img width="372" alt="screen shot 2018-10-02 at 3 46 06 pm" src="https://user-images.githubusercontent.com/22967267/46375934-575eff80-c65a-11e8-8bde-d652c4d2aabc.png">

**Comment by satya164** [comment]
Currently, you can override the `layout` prop passed to the tab bar. We should make it automatic in future.

**Comment by hsunami10** [comment]
@satya164 how do you override the `layout` prop? Can you give me a quick example?

**Comment by satya164** [comment]
```js
renderTabBar = props => <TabBar {...props} layout={{ ...props.layout, width: CUSTOM_WIDTH }} />
```

**Comment by hsunami10** [comment]
that works perfectly, thanks!
