### ISSUE TITLE
We don't know what to do with this node type. We were previously a Statement but we can't fit in here?

### ISSUE THREAD

**Issue by kdawgwilk** [react-native-community/react-native-tab-view#617]
### Current behaviour

Failing to bundle the jsbundle to embed in react-native app with the error:
```
/path/to/project/node_modules/react-native-tab-view/src/TabView.js: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
```

### Expected behaviour

That the lib can bundle just fine

### What have you tried

Tried adding `@babel/plugin-transform-flow-strip-types` plugin to babel config

### Your Environment

| software              | version
| --------------------- | -------
| ios | 11
| react-native | 0.56
| react-native-tab-view | 1.2.0
| node | 10.8.0
| yarn | 1.9.4

`.babelrc`

```
{
  "presets": [
    "babel-preset-react-native"
  ],
  "retainLines": true,
  "passPerPreset": true,
  "plugins": [
    ["relay", {"schema": "./schema.json"}],

    "@babel/plugin-transform-flow-strip-types",

    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-transform-runtime", {
      "helpers": true,
      "polyfill": false,
      "regenerator": false
    }],
    ["./app/babel-plugin-proposal-class-properties", { "loose": true }],

    "lodash",
    ["react-intl", {
      "messagesDir": "./extracted-messages/",
      "enforceDescriptions": false
    }]
  ]
}
```

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
