### ISSUE TITLE
React-native-tab-view tab navigation issue

### ISSUE THREAD

**Issue by BhoomiJani** [react-native-community/react-native-tab-view#620]
### Current behaviour
I have used react-native-tab-view for tab navigation. but (_handleIndexChange) this function not working in tab view child component.
### Expected behaviour
Navigate tab on button click

### Code sample
handleIndexChange = index => this.setState({ index });
<TouchableOpacity onPress={() => this.handleIndexChange(2)}><Text>Press to switch to tab 2</Text></TouchableOpacity>

**Comment by dravya88** [comment]
You can use the jumpTo function passed as prop by scene object. It expects route key as parameter.
[SceneMap](https://github.com/react-native-community/react-native-tab-view#scenemap) Then in tab view child component, call this function from props.

Example:

`_onButtonPress = () => {
  this.props.jumpTo(<routeKey>);
}
<TouchableOpacity onPress={() => this._onButtonPress}>
`

**Comment by BhoomiJani** [comment]
Hey Thanks for replying ,
Yes i can use this but its showing syntax error.
Can you please write this whole process here?
So i can understand this process very well.

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
