### ISSUE TITLE
jumpTo(key)

### ISSUE THREAD

**Issue by alainib** [react-native-community/react-native-tab-view#621]
I want to open a `<TabView/>` on a given tab pragmatically.  

### Current behaviour

 i cannot make it work with `jumpTo={"third"}` props, it open always the first not the third tabs for example

 

 

### Code sample
 

		import * as React from "react";
		import { View, StyleSheet, Dimensions } from "react-native";
		import { TabView, TabBar, SceneMap } from "react-native-tab-view";

		const FirstRoute = () => <View style={[styles.container, { backgroundColor: "#ff4081" }]} />;
		const SecondRoute = () => <View style={[styles.container, { backgroundColor: "#673ab7" }]} />;

		const ThirdRoute = () => <View style={[styles.container, { backgroundColor: "#ff4081" }]} />;
		const FourthRoute = () => <View style={[styles.container, { backgroundColor: "#673ab7" }]} />;

		export default class TabViewExample extends React.Component {
		  state = {
			index: 0,
			routes: [
			  { key: "first", title: "First" },
			  { key: "second", title: "Second" },
			  { key: "third", title: "third" },
			  { key: "fourth", title: "fourth" }
			]
		  };

		  render() {
			return (
			  <TabView
				navigationState={this.state}
				renderScene={SceneMap({
				  first: FirstRoute,
				  second: SecondRoute,
				  third: ThirdRoute,
				  fourth: FourthRoute
				})}
				onIndexChange={index => this.setState({ index })}
				initialLayout={{ width: Dimensions.get("window").width }}
				jumpTo="third"
			  />
			);
		  }
		}

		const styles = StyleSheet.create({
		  container: {
			flex: 1
		  },
		  tabBar: {
			flexDirection: "row",
			paddingTop: 45
		  },
		  tabItem: {
			flex: 1,
			alignItems: "center",
			padding: 16
		  }
		});

 
 
 

### What have you tried

I tried jumpTo={"third"} or jumpTo={3} 

 

### Your Environment

| software              | version
| --------------------- | -------
| android             |    6
| react-native          | 0.55.4
| react-native-tab-view | 1.0.2  (1.2.0 version work very very slowly)

**Comment by satya164** [comment]
`jumpTo` is a method passed to components such as `TabBar` and the routes. It's not for initial route. To change the initial route, change the `index` property in the `state` to the desired index.

**Comment by Nurul26** [comment]
answer please??
