### ISSUE TITLE
TabView disappear when wrapped inside a View

### ISSUE THREAD

**Issue by jerinho** [react-native-community/react-native-tab-view#622]
### Current behaviour

Disappear when wrapped inside a View

### Expected behaviour

Should be able to be wrapped inside a View without a problem

### Code sample

```
render() {
	return (
		<View>
			<TabView/>
			{/*TabView's props is same to the sample source code*/}
		</View>
	);
}
```

### What have you tried

The package itself need to be fixed first regardless of whether there is any workaround or hack to solve the issue

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.55.4
| react-native-tab-view | 1.2.0
| node                  | 8.11.4
| npm or yarn           | 6.4.0

**Comment by jerinho** [comment]
Explicitly set the wrapper's height solve this. But I still don't think zero height as default should be considered as a good idea

**Comment by satya164** [comment]
> But I still don't think zero height as default should be considered as a good idea

The `TabView` will fill the available space. It's not zero-height. Your wrapper `View` doesn't have something like `flex: 1`, so there's no space available for the `TabView` to render.
