### ISSUE TITLE
disable rendering all scenes automatically?

### ISSUE THREAD

**Issue by hsunami10** [react-native-community/react-native-tab-view#623]
Is it possible to disable the rendering of all scenes automatically? Or do we have to handle this ourselves?

**Comment by pavel-zlotarenchuk** [comment]
Great question
Or how you can update the render when you open the screen

**Comment by ShinsukeWatanabe** [comment]
@hsunami10 
@pavel-zlotarenchuk 
https://snack.expo.io/@satya164/react-native-tab-view-lazy-load

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
