### ISSUE TITLE
React.createElement: type is invalid

### ISSUE THREAD

**Issue by zhllucky** [react-native-community/react-native-tab-view#628]
:\GitHub\newS\employees\node_modules\react-native\Libraries\Core\ExceptionsManager.js:84 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

An error has also occurred using the official example.

### Code sample

![image](https://user-images.githubusercontent.com/25603886/47414942-cedd0600-d7a4-11e8-95fd-93c4fa7815a2.png)

![image](https://user-images.githubusercontent.com/25603886/47414967-de5c4f00-d7a4-11e8-837d-3cc8a049bb3d.png)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |  android
| react-native          | 0.57.3
| react-native-tab-view |  0.0.74
| node                  |
| npm or yarn           | npm

**Comment by RGump** [comment]
+ I have the same problem

**Comment by annpt1** [comment]
me too, when adding 
`        renderPager = {this.renderPager}
`

**Comment by empy92** [comment]
I have this problem after update react version from 0.56.
I fixed updating this library version.

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
