### ISSUE TITLE
how to keep tab view on bottom while executing a card navigation transition?

### ISSUE THREAD

**Issue by hsunami10** [react-native-community/react-native-tab-view#629]
I am using react-navigation with react-native-tab-view, since the tab view is in one React component, how do I navigate to another screen, keeping the tab view stationary at the bottom?

**Comment by satya164** [comment]
Wrap `StackNavigator` inside `TabNavigator` instead of `TabNavigator` inside `StackNavigator`

**Comment by hsunami10** [comment]
@satya164 I tried that in `renderScene`, but it says `Failed prop type: Invalid prop `children` supplied to `PagerScroll`, expected a ReactNode`
<img width="732" alt="screen shot 2018-10-24 at 3 40 20 pm" src="https://user-images.githubusercontent.com/22967267/47459998-22e6eb00-d7a3-11e8-942f-2fe5b55a0606.png">

**Comment by hsunami10** [comment]
Here is the code for my `renderScene`, I pass this to the `TabView` prop `renderScene`

`renderScene = ({ route }) => {
    switch (route.key) {
      case 'feed':
        return createStackNavigator(
          {
            Feed: FeedScreen
          },
          {
            initialRouteName: 'Feed',
            headerMode: 'none'
          }
        );
      case 'discover':
        if (this.state.mounted.discover) {
          return createStackNavigator(
            {
              Discover: DiscoverScreen
            },
            {
              initialRouteName: 'Discover',
              headerMode: 'none'
            }
          );
        }
        break;
default:
        return;`

**Comment by hsunami10** [comment]
I got it, thanks!
