### ISSUE TITLE
Is possible set swipeDistanceThreshold to PagerExperimental before start onSwipeStart?

### ISSUE THREAD

**Issue by cklinx** [react-native-community/react-native-tab-view#633]
Hi, 
i use PagerExperimental component and it has a scrollview inside my tab; when i scroll the scrollview verticatly, onSwipeStart event is triggered even i dont swipe.

Is there a way to choose the min distance before the event start?

Thanks in advance.

**Comment by satya164** [comment]
Do you use `ScrollView` from `react-native-gesture-handler`?

**Comment by cklinx** [comment]
I use `Animated.ScrollView` from `react-native`

**Comment by satya164** [comment]
You need to use the `ScrollView` from gesture handler is you want to use pager experimental

**Comment by cklinx** [comment]
I need `Animated.ScrollView` cuz must use ` onScroll={Animated.event(
           [{nativeEvent: {contentOffset: {y: this.animatedValue}}}],
           {useNativeDriver: true}
          )}` do you know how can i do it?

Thanks.

**Comment by cklinx** [comment]
Anyway: i tried with `ScrollView` from `react-native-gesture-handler` and `onSwipeStart` starts as normal the normal one.

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
