### ISSUE TITLE
SafeAreaView not working with TabBar

### ISSUE THREAD

**Issue by steoo** [react-native-community/react-native-tab-view#635]
To support iPhone X I should use `SafeAreaView` ( https://reactnavigation.org/docs/en/handling-iphonex.html ) but when used with `TabBar` it doesn't work

    render() {
        return (
         <SafeAreaView>
            <TabView
                style={this.props.style}
                navigationState={this.state}
                renderScene={this._renderScene}
                renderTabBar={this._renderTabBar}
                tabBarPosition="bottom"
                onIndexChange={this._handleIndexChange}
                swipeEnabled={false}
            />
         </SafeAreaView>
        );
    }

if used like this nothing is shown on video

**Comment by satya164** [comment]
You probably need `flex: 1` on the `SafeAreaView`. Anyway, you should wrap the individual scenes and `TabBar` in `SafeAreaView` instead of the whole `TabView`.

**Comment by steoo** [comment]
Going to try it. The problem is that the TabView goes under the "software" button


![screenshot 2018-11-08 at 18 31 53](https://user-images.githubusercontent.com/3333573/48216302-9d5b6180-e384-11e8-8644-4f2fd0ddc8ca.png)

**Comment by steoo** [comment]
Setting `flex: 1` on `SafeAreaView` did the trick, thank you :)

**Comment by ishigamii** [comment]
@steoo  close the issue if it is resolved

**Comment by originalix** [comment]
thanks! `flex: 1` resolved my problem 👍

**Comment by Champkinz** [comment]
@steoo this fixed the issue `flex: 1`, long live steoooo ✅

**Comment by hemantbavle1** [comment]
flex: 1 not working!!!
