### ISSUE TITLE
Ability to set renderUnfocusedScenes

### ISSUE THREAD

**Issue by balbirsng** [react-native-community/react-native-tab-view#637]
### Current behaviour
TabView renders all the scenes, for unfocused scenes there is a delay added.

### Expected behaviour
It should be configurable to set if unfocused scenes can be rendered automatically or it renders only when focused (atleast once)

### Code sample
`renderUnfocusedScenes  = false`

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          |
| react-native-tab-view |
| node                  |
| npm or yarn           |

**Comment by satya164** [comment]
Why do you need this to be configurable?

**Comment by satya164** [comment]
It won't work properly with swipe gesture. If you don't want to render all tabs, render style kind of placeholder by default and then update our to actual content when the index changes.

**Comment by satya164** [comment]
Check this snack for an example: https://snack.expo.io/@satya164/react-native-tab-view-lazy-load
