### ISSUE TITLE
Change selected tab color on change of tab?

### ISSUE THREAD

**Issue by pavithra2110** [react-native-community/react-native-tab-view#638]
is there any method to change the tab color itself on change of tab? There is a props that has been mentioned in few solution as `activeTabStyle`. But it's not showing for me.

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
