### ISSUE TITLE
Requires react-native >=0.36?

### ISSUE THREAD

**Issue by jankalfus** [react-native-community/react-native-tab-view#64]
It would be nice to state somewhere that this requires react-native version at least 0.36 (or whenever was overflow: "scroll" introduced). On react-native 0.32, you get the infamous red box screen stating that View doesn't support overflow: "scroll", only "visible" or "hidden".

**Comment by jankalfus** [comment]
Replacing "scroll" by "hidden" in TabBar.js on line 20 fixes the issue. But, I'm guessing this'll have some side effects?

**Comment by satya164** [comment]
@jankalfus Hey, yeah, this is noted in release notes, but I should add to README too. PR welcome.

**Comment by jankalfus** [comment]
@satya164 Where are the release notes located?

**Comment by satya164** [comment]
https://github.com/react-native-community/react-native-tab-view/releases

**Comment by jankalfus** [comment]
Ah, right. Sorry, it's late :D Here's the PR: #67
