### ISSUE TITLE
nextRoute.key undefined is not an object PagerAndroid

### ISSUE THREAD

**Issue by sibelius** [react-native-community/react-native-tab-view#644]
### Current behaviour

It is crashing and changing tabs

### Expected behaviour

it should not crash

### Code sample
![image](https://user-images.githubusercontent.com/2005841/48920176-83d71100-ee7e-11e8-9f22-d2ba53e05334.png)

https://github.com/react-native-community/react-native-tab-view/blob/master/src/PagerAndroid.js#L98

### What have you tried

My workaround would be to use another Pager
Another workaround would be implement `canJumpToTab`, so it won't `jump` to a wrong tab https://github.com/react-native-community/react-native-tab-view/blob/master/src/PagerAndroid.js#L25

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 57.5
| react-native-tab-view | 1.3.0
| node                  | 10.12.0
| npm or yarn           | 1.12.3

**Comment by satya164** [comment]
Can you post a repro?

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
