### ISSUE TITLE
Expose accessibility props from 'PagerAndroid'

### ISSUE THREAD

**Issue by rimzici** [react-native-community/react-native-tab-view#645]
I am using react-navigation and the issue is stemming from the tab-view, so mentioning it here.

### Current behaviour

`ViewPagerAndroid` is capturing the focus, every time clicking a new component.(the second press gives focus to the desired component though)
This happens even when I have moved away/navigated to a new screen/stack navigator, from
then tab navigator(that uses `ViewPagerAndroid`)
**NOTE: custom transition**

### Expected behaviour

- If the tab navigator is active, and any accessible component is touched, it should gain focus,
and not `ViewPagerAndroid`.(Seem to work most time)

- Once navigated away from the tab navigator(custom transition), `ViewPagerAndroid` should
not gain focus at all.

### Code sample
NULL
### Screenshots (if applicable)
**NOTE: arrow is where I am pressing**

- Tab navigator is active, but when I press on an element on which I have set `accessible: true`
it is not getting focused at all.
![screenshot_20181123-131824](https://user-images.githubusercontent.com/16771765/48932763-90617500-ef23-11e8-8a6b-4d6072c5ee26.png)

- Here I have navigated to a new stack navigator(custom navigation transition), still from beneath
the `ViewPagerAndroid` inside the tab navigator is capturing the focus, and announces the default message.
![screenshot_20181123-131838](https://user-images.githubusercontent.com/16771765/48932764-90617500-ef23-11e8-8052-a00dee599752.png)

### What have you tried

Explained with the screenshot

### Your Environment

| software              | version
| --------------------- | -------
| react-native          | 0.55.4
| react-native-tab-view | 1.3.0
| react-navigation         | 2.5.5

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
