### ISSUE TITLE
How to change default blue tab bar background and default yellow active tab underline?

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [react-native-community/react-native-tab-view#647]
### Current behaviour

How to change default blue tab bar background and default yellow active tab underline?

### Code sample

Following sample from readme

**Comment by raedhellal** [comment]
To change the default tab bar you need to custumize a tabBar and pass it to the prop renderTabbar.

An example to explain more is as follow i prefer to do it in seperate function : 

renderTabBar(props) {
        return (<TabBar
                style={{backgroundColor: '#FFFFFF', elevation: 0, borderColor: '#000000', borderBottomWidth: 1, height:50}}
                labelStyle={{color: 'black', fontSize: 18, fontWeight: 'bold'}}
                {...props}
                indicatorStyle={{backgroundColor: '#e65970', height: 2.5}}
            />
        );
    }

Then pass it to the TabView:

 <TabView renderTabBar={this.renderTabBar}/>

And about the Indicator Style in the renderTabBar you can find a prop called indicatorStyle do what you want to that indicator.

Good Luck :) .

**Comment by ManigandanRaamanathan** [comment]
Thanks. Found solution already from the example in repo.

**Comment by alisherakb** [comment]
> how to set title tabs to normal without uppercase ?

`textTransform: 'capitalize'`

**Comment by simonasdev** [comment]
it's funny because `textTransform: 'none'` is the single one that doesn't work :D

**Comment by Nurul26** [comment]
how to change active tab fontcolor to black and inactive tab fontcolor to grey?

**Comment by AliShan3810** [comment]
> Thanks. Found solution already from the example in repo.

can you send me the solution
