### ISSUE TITLE
Lazy rendering of scenes

### ISSUE THREAD

**Issue by zabojad** [react-native-community/react-native-tab-view#649]
### Current behaviour

When we have a large number of routes and each scene is expensive to render, the `TabView` component becomes really slow at initial render.

That's a pity because this performance leak comes from the fact that all scenes are rendered at initial render even if most of them won't be displayed.

The suggested way to improve it is is this one : https://github.com/react-native-community/react-native-tab-view#optimize-large-number-of-routes

However, it is far from being ideal:
- You cannot use `SceneMap` with this workaround
- It will re-render all scenes that included in your test condition even when they already have been rendered.

### Expected behaviour

We need a way to lazy render scenes that will not re-render them when changing scene.

### Code sample

n/a

### Screenshots (if applicable)

n/a

### What have you tried

For now, nothing in particular, but suggestions are welcome.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.57.0
| react-native-tab-view | 1.3.0
| node                  | v8.11.3
| npm or yarn           | yarn version v1.10.1

**Comment by satya164** [comment]
https://github.com/react-native-community/react-native-tab-view#more-examples-on-snack

![image](https://user-images.githubusercontent.com/1174278/49323637-d8cdf380-f51e-11e8-8eb0-2f946aae2222.png)

**Comment by zabojad** [comment]
@satya164 can you please re-open this issue.

The "Lazy Load" snack example doesn't lazy load the scenes at all.

Here is a modified snack with console.logs which shows that: https://snack.expo.io/r1sSXaykE

**Comment by zabojad** [comment]
@satya164 You are right. Thank you for you answers...

**Comment by tiyunchen** [comment]
PureComponet  is not working

**Comment by zabojad** [comment]
@tiyunchen it is working. You might have another issue if it is not. Share a snack if you want any help...

**Comment by kyle-ssg** [comment]
Small note on this, if you want to improve performance a bit more you can defer rendering other tabs in the component themselves

e.g tab 2:
```
  <Delay>
              <View/>
              <View>{...expensiveContent}</View>
     </Delay>
```

Where Delay is
```
import React, { Component } from 'react';
import propTypes from 'prop-types';

export default class Delay extends Component {

    static displayName = 'Delay';

    static propTypes = {
        children: propTypes.node,
        delay: propTypes.number,
    };

    static defaultProps = {
        delay: 500,
    };

    constructor(props, context) {
        super(props, context);
        this.state = {};
        this.timeout = setTimeout(() => this.setState({ ready: true }), props.delay);
    }

    componentWillUnmount() {
        clearTimeout(this.timeout);
    }

    render() {
        return this.props.children[this.state.ready ? 1 : 0];
    }
}
```
