### ISSUE TITLE
First tab is mounted twice

### ISSUE THREAD

**Issue by mukesh-rbsl** [react-native-community/react-native-tab-view#650]
### Current behaviour
The first screen in tab view mounted twice

### Expected behaviour

Expected behavior as screen must be mounted one time in tab view

### Code sample

You can easily reproduce with:

"react-native": "^0.57.4"
"react-native-tab-view": "^1.3.1"
"react-navigation": "^3.0.0"
Platform: android

### What have you tried
I have tried "npm i react-native-tab-view" and used "Quick Start example"

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.57.4
| react-native-tab-view | 1.3.1
| node                  | v10.4.1
| npm or yarn           | 6.1.0 (npm)

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
