### ISSUE TITLE
how to set the dynamic key and title using react native tab view 

### ISSUE THREAD

**Issue by dharagosai** [react-native-community/react-native-tab-view#652]
state = {
    index: 0, 
    routes: [
      { key: 'first', title: 'First' }
    ],
  };

  <TabView
        navigationState={this.state}
        renderScene={SceneMap({
          category_get: FirstRoute,
        })}
        onIndexChange={index => this.setState({ index })}
        initialLayout={{ width: Dimensions.get('window').width,height: Dimensions.get('window').height }}
      />

**Comment by omeileo** [comment]
**Generate Scenes**
```
const getScenes = colors => {
  let scenes = []

  colors.forEach((color, index) => {
    scenes.push(
      () => <View style={[styles.scene, { backgroundColor: color }]} key={index} />
      // This is causing re-rendering of tabview :( 
      // HELP
    )
  })

  return scenes
}
```

**Generate Routes**
```
const getRoutes = titles => {
  let routes = []

  titles.forEach(title => {
    routes.push({
      key: title,
      title: title
    })
  })

  return routes
}
```

**Generate SceneMap**
```
const getSceneMap = (routes, scenes) => {
  let sceneMap = {}

  routes.forEach((route, index) => {
    sceneMap[route.key] = scenes[index]
  })

  return sceneMap
}
```

**Define Class**
```
export default class YourClass extends Component {
  state = {
    index: 0,
    routes: getRoutes([ 'First', 'Second', 'Third', 'Fourth', 'Fifth', 'Sixth', 'Seventh' ]),
  }

  renderTabBar = props => {
    const inputRange = props.navigationState.routes.map((x, i) => i)

    return (
      <View style={styles.tabBar}>
        <ScrollView
          horizontal
          showsHorizontalScrollIndicator={false}
          contentContainerStyle={styles.tabBarScrollView}
        >
          {
            props.navigationState.routes.map((route, i) => {
              return (
                <TouchableOpacity
                  style={styles.tabItem}
                  onPress={() => this.setState({ index: i })}
                  activeOpacity={0.85}
                >
                  <Text style={styles.tabBarText}>
                    {route.title}
                  </Text>
                </TouchableOpacity>
              )
            })
          }
        </ScrollView>
      </View>
    )
  }

  scenes = getScenes([ 'transparent', 'yellow', 'green', 'purple', 'orange', 'black', 'white' ])
  sceneMap = getSceneMap( this.state.routes, this.scenes )

  render() {

    return (
      <TabView
        navigationState={this.state}
        renderScene={SceneMap(this.sceneMap)}
        renderTabBar={this.renderTabBar}
        onIndexChange={index => this.setState({ index })}
        initialLayout={{ width: screen.width, height: screen.height }}
      />
    )
  }
}
```

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.

**Comment by alihbk** [comment]
> **Generate Scenes**
> 
> ```
> const getScenes = colors => {
>   let scenes = []
> 
>   colors.forEach((color, index) => {
>     scenes.push(
>       () => <View style={[styles.scene, { backgroundColor: color }]} key={index} />
>       // This is causing re-rendering of tabview :( 
>       // HELP
>     )
>   })
> 
>   return scenes
> }
> ```
> 
> **Generate Routes**
> 
> ```
> const getRoutes = titles => {
>   let routes = []
> 
>   titles.forEach(title => {
>     routes.push({
>       key: title,
>       title: title
>     })
>   })
> 
>   return routes
> }
> ```
> 
> **Generate SceneMap**
> 
> ```
> const getSceneMap = (routes, scenes) => {
>   let sceneMap = {}
> 
>   routes.forEach((route, index) => {
>     sceneMap[route.key] = scenes[index]
>   })
> 
>   return sceneMap
> }
> ```
> 
> **Define Class**
> 
> ```
> export default class YourClass extends Component {
>   state = {
>     index: 0,
>     routes: getRoutes([ 'First', 'Second', 'Third', 'Fourth', 'Fifth', 'Sixth', 'Seventh' ]),
>   }
> 
>   renderTabBar = props => {
>     const inputRange = props.navigationState.routes.map((x, i) => i)
> 
>     return (
>       <View style={styles.tabBar}>
>         <ScrollView
>           horizontal
>           showsHorizontalScrollIndicator={false}
>           contentContainerStyle={styles.tabBarScrollView}
>         >
>           {
>             props.navigationState.routes.map((route, i) => {
>               return (
>                 <TouchableOpacity
>                   style={styles.tabItem}
>                   onPress={() => this.setState({ index: i })}
>                   activeOpacity={0.85}
>                 >
>                   <Text style={styles.tabBarText}>
>                     {route.title}
>                   </Text>
>                 </TouchableOpacity>
>               )
>             })
>           }
>         </ScrollView>
>       </View>
>     )
>   }
> 
>   scenes = getScenes([ 'transparent', 'yellow', 'green', 'purple', 'orange', 'black', 'white' ])
>   sceneMap = getSceneMap( this.state.routes, this.scenes )
> 
>   render() {
> 
>     return (
>       <TabView
>         navigationState={this.state}
>         renderScene={SceneMap(this.sceneMap)}
>         renderTabBar={this.renderTabBar}
>         onIndexChange={index => this.setState({ index })}
>         initialLayout={{ width: screen.width, height: screen.height }}
>       />
>     )
>   }
> }
> ```

perfect

**Comment by duytamdev** [comment]
> 
 change `scenes = getScenes([ 'transparent', 'yellow', 'green', 'purple', 'orange', 'black', 'white' ])` to 
` const scenes = useMemo(() => getScenes(data), [data]);`

this will avoid the scenes variable to be re-initialized
