### ISSUE TITLE
Overlapping scenes [feature]

### ISSUE THREAD

**Issue by ionush** [react-native-community/react-native-tab-view#653]
### Current behaviour

Normal tabview behaviour. It's working fine

### Expected behaviour

Is it possible to have tabs overlap? I know most of the time this functionality wouldn't be desirable, but I'm trying to implement something similar to the app store on ios
![image](https://user-images.githubusercontent.com/26359601/49499088-1aa4c400-f8a8-11e8-93b4-6003aa8da6dc.png)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios
| react-native          | 0.56
| react-native-tab-view | 1.2.0
| node                  | 10.6.0
| npm or yarn           | 6.1.0

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
