### ISSUE TITLE
Thumbnail gives error 

### ISSUE THREAD

**Issue by dharagosai** [react-native-community/react-native-tab-view#656]
i have use thumbnail in myproject that give me this error 

### Current behaviour
![screenshot_2018-12-11-11-31-12-974_host exp exponent](https://user-images.githubusercontent.com/45596590/49781459-b4d29500-fd0a-11e8-8898-695425427b9b.png)

### Code sample
this is my full screen code 

import React from 'react'
import { StyleSheet, Text, View, Image,WebView } from 'react-native'
import Thumbnail from 'react-native-thumbnail-video';

export default class Screen3 extends React.Component {
  static navigationOptions = {
    drawerLabel: 'Screen Three',
    drawerIcon: () => (
      <Image
        source={{uri: `https://dummyimage.com/60x60/000/fff.jpg&text=3`}}
        style={{width: 30, height: 30, borderRadius: 15}}
      />
    )
  }

  render() {
    return (
      <View style={styles.container}>
         <Thumbnail url="https://www.youtube.com/watch?v=lgj3D5-jJ74" />
      </View>
    )
  }
}
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
})

**Comment by corasan** [comment]
I'm having the same problem

**Comment by dharagosai** [comment]
why you have closed my issue.

**Comment by satya164** [comment]
How is this issue related to this library?

**Comment by dharagosai** [comment]
@satya164  Thank You
