### ISSUE TITLE
Initial entry page, default selection of tablabel 5, tablabel need to scroll, Indicator can not accurately locate

### ISSUE THREAD

**Issue by kxcy001123** [react-native-community/react-native-tab-view#657]
### Current behaviour

There are 6 tabs in total. When I enter the page and choose the fifth by default, label can scroll normally, but Indicator can't locate accurately.

### Expected behaviour

There are 6 tabs in total. When I enter the page and choose the fifth by default, label can scroll normally and Indicator can locate normally.

### Code sample
```
this.state = {
      index: 0,
      routes: [
        { key:BoughtOrderStatus.PENDING_PAYMENT.id,title:BoughtOrderStatus.PENDING_PAYMENT.name},
        { key: BoughtOrderStatus.TO_BE_DELIVERED.id, title: BoughtOrderStatus.TO_BE_DELIVERED.name},
        { key: BoughtOrderStatus.PENDING_RECEIVE.id, title: BoughtOrderStatus.PENDING_RECEIVE.name},
        { key: BoughtOrderStatus.PENDING_RECEIPT.id, title: BoughtOrderStatus.PENDING_RECEIPT.name},
        { key: BoughtOrderStatus.COMPLETED.id, title: BoughtOrderStatus.COMPLETED.name},
        { key: BoughtOrderStatus.CANCELLED.id, title: BoughtOrderStatus.CANCELLED.name},
      ],
    };
render() {
    return (<TabView
      navigationState={this.state}
      ref={ref=>this.tabView = ref}
      tabBarPosition={"top"}
      renderScene={this._renderScene}
      renderTabBar={this._renderTabBar}
      onIndexChange={index => this.setState({ index })}
      initialLayout={{ width: Dimensions.get('window').width, height: 64 }}
      useNativeDriver
    />)
  }
```
### What have you tried

 TabBar.js    

this.state = {
      visibility: new Animated.Value(initialVisibility),
      scrollAmount: new Animated.Value(0),
      initialOffset,
    };
change to

this.state = {
      visibility: new Animated.Value(initialVisibility),
      scrollAmount: new Animated.Value(initialOffset.x),
      initialOffset,
};

can resolve my issue

### Your Environment

| software              | version
| --------------------- | -------
| ios         |  iphone5
| react-native          |   0.57
| react-native-tab-view |  1.3.1
| node                  |    8.12.0
| npm or yarn           |   yran

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
