### ISSUE TITLE
Rendering an a bottom border on inactive tabs

### ISSUE THREAD

**Issue by alextes** [react-native-community/react-native-tab-view#658]
### Current behaviour

I'm using the following styles in order to have an gray inactive indicator for the inactive tabs. It appears that since the indicator is rendered _before_ of the individual tabs giving the tabs a border means the border is rendered over the indicator.

How could I get the indicator to be visible on top of the tabs having a border indicating they are inactive.

### Code sample

```js
          indicatorStyle={{
            borderColor: colors.turquoise,
            backgroundColor: colors.turquoise,
          }}
          tabStyle={{ borderBottomWidth: 2, borderColor: colors.gray1 }}
```

### Screenshots (if applicable)

What is currently happening:

<img width="317" alt="screen shot 2018-12-18 at 15 20 04" src="https://user-images.githubusercontent.com/2011351/50160252-1a112200-02d9-11e9-8903-356520274086.png">

What I'd like:

<img width="560" alt="screen shot 2018-12-18 at 15 25 24" src="https://user-images.githubusercontent.com/2011351/50160306-3614c380-02d9-11e9-94e7-060934c0c42c.png">

**Comment by alextes** [comment]
For my use-case, it turned out easier to write a light, view-only version of this component. Since I don't need the navigation side of things.

**Comment by alextes** [comment]
Someone asked me the following on another channel:
>Could you please give me an idea on how you ended up implementing it?
>That would be extremely helpful. Like you, I am trying to play with tabStyle={{ borderBottomWidth: 2, borderColor: ‘gray' }} but every time the border covers the indicator.

I ended up writing a light version that doesn't manage any sibling views and still needs a parent to tie the tabs together with the visual changes they produce. I quite like the result.

Here's the implementation since I was asked about this directly.
```tsx
import * as React from 'react';
import { TouchableOpacity, View } from 'react-native';

import { colors } from '../styles/theme';
import { RText } from './r-text';

type FC<T> = React.FunctionComponent<T>;

interface TabProps {
  label: string;
  isActive: boolean;
  onPress: () => void;
}
const Tab: FC<TabProps> = ({ isActive, label, onPress }) => {
  const borderColor = isActive ? colors.turquoise : colors.superLightGray;
  const textColor = isActive ? 'turquoise' : 'lightGray';
  return (
    <TouchableOpacity onPress={onPress} style={{ flex: 1 }}>
      <View
        style={{
          borderColor,
          borderBottomWidth: 2,
          paddingVertical: 10,
        }}
      >
        <RText textAlign="center" color={textColor}>
          {label}
        </RText>
      </View>
    </TouchableOpacity>
  );
};

interface TabsProps {
  activeIndex: number;
  onSetIndex: (index: number) => void;
  tabs: Array<{ label: string }>;
}
export const Tabs: FC<TabsProps> = ({ activeIndex, onSetIndex, tabs }) => (
  <View style={{ flexDirection: 'row' }}>
    {tabs.map((tab, index) => {
      return (
        <Tab
          key={tab.label}
          isActive={activeIndex === index}
          onPress={onSetIndex.bind(null, index)}
          label={tab.label}
        />
      );
    })}
  </View>
);
```

**Comment by samipshah100** [comment]
You can also use a custom renderTab bar with <TabBar renderLabel = {({route, focused, color})=>( ...code)} and use the focused prop of renderlabel callback for this.
