### ISSUE TITLE
How to implement an infinite loop, eg. swip right to the last page will scroll to the first page

### ISSUE THREAD

**Issue by robert1202** [react-native-community/react-native-tab-view#659]
How to implement an infinite loop,
eg. swip right to the last page will scroll to the first page

**Comment by amber-pli** [comment]
@robert1202  did not find a solution?

**Comment by ElfenLiedGH** [comment]
> @robert1202 did not find a solution?

I resolved it by adding fake screen at first and last position and handle it in onIndexChange like this


`  const goNext = useCallback(
    () => setIndex(i => (i + 1 >= realRoutes.length + 1 ? 1 : i + 1)),
    [realRoutes.length],
  );
  const goPrevious = useCallback(
    () => setIndex(i => (i === 1 ? realRoutes.length : i - 1)),
    [realRoutes.length],
  );`
