### ISSUE TITLE
Can I make a tabView inside another tabView?

### ISSUE THREAD

**Issue by HurryHarryV** [react-native-community/react-native-tab-view#661]
I want to make a react-native program which uses double layered tabView.

![image](https://user-images.githubusercontent.com/46097147/50405078-6a611600-07ea-11e9-9511-94cec39e5122.png)

But the subTab doesn't work and I can't do anything with it.

import React from 'react';
import { View, Image, Text, StyleSheet, Dimensions } from 'react-native';

import { TabView, TabBar, SceneMap } from 'react-native-tab-view';

export default class MainView extends React.Component {
    
	static navigationOptions = {
		title: 'MainView',
		header: null
    }

    state = {
        mainTab: {
            index: 0,
            routes: [
                { key: 'mainFirst', title: 'First' },
                { key: 'mainSecond', title: 'Second' },
            ],
        },
        subTab: {
            index: 1,
            routes: [
                { key: 'subFirst', title: 'First1' },
                { key: 'subSecond', title: 'Second1' },
            ],
        },
    };

    subIndexChange = (index) => {
        this.setState({
            ...this.state,
            subTab: {
                ...this.state.subTab,
                index: index
            } 
        });
    }
        
    FirstRoute = () => (
        <TabView
            navigationState={this.state.subTab}
            renderScene={SceneMap({
                subFirst: this.SubFirstRoute,
                subSecond: this.SubSecondRoute,
            })}
            onIndexChange={index => this.subIndexChange(index)}
            initialLayout={{ width: Dimensions.get('window').width }}
            tabBarPosition='bottom'
        />
    );

    SecondRoute = () => (
        <View style={[styles.scene, { backgroundColor: '#673ab7' }]} >
            <Text>Second</Text>
        </View>
    );

    SubFirstRoute = () => (
        <View style={[styles.scene, { backgroundColor: '#ff4081' }]} >
            <Text>Sub First</Text>
        </View>
    );

    SubSecondRoute = () => (
        <View style={[styles.scene, { backgroundColor: '#673ab7' }]} >
            <Text>Sub Second</Text>
        </View>
    );

    mainIndexChange = (index) => {
        this.setState({ 
            ...this.state,
            mainTab: { 
                ...this.state.mainTab, 
                index: index 
            } 
        });
    }

    render() {
        return (
            <TabView
                navigationState={this.state.mainTab}
                renderScene={SceneMap({
                    mainFirst: this.FirstRoute,
                    mainSecond: this.SecondRoute,
                })}
                onIndexChange={index => this.mainIndexChange(index)}
                initialLayout={{ width: Dimensions.get('window').width }}
                tabBarPosition='top'
            />
        )
    }
}

var styles = StyleSheet.create({
    scene: {
        flex: 1,
    },
    container: {
        flex: 1,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center'
    },
    tabs: {
        flex: 0.5,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center'
    },
    subTabs: {
        flex: 0.5,
    }
})

Please help me. And I'm sorry that the code is so untidy.

**Comment by satya164** [comment]
https://github.com/react-native-community/react-native-tab-view#known-issues
