### ISSUE TITLE
How to change TabView Height ?

### ISSUE THREAD

**Issue by HRCJ7** [react-native-community/react-native-tab-view#663]
### Current behaviour

TabView height cannot be changed. Below I have attached screenshot of it.

### Expected behaviour

TabView height need to same with  renderScene view height size

### Code sample

 ```
     <TabView
          navigationState={this.state}
          renderScene={SceneMap({
            new_arrivals: FirstRoute,
            featured: SecondRoute,
            best_sellers: FirstRoute,
            trending: SecondRoute
          })}
          renderTabBar={this._renderTabBar}
          onIndexChange={index => this.setState({ index })}
          useNativeDriver
        />
```

### Screenshots (if applicable)

<img width="315" alt="screen shot 2019-01-01 at 10 06 32 pm" src="https://user-images.githubusercontent.com/9447556/50574641-45842880-0e12-11e9-9c41-76d224c3edc8.png">

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |11
| react-native          |0.55.4
| react-native-tab-view |1.3.1
| node                  |6.11.4
| npm or yarn           |3.10.10

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.

**Comment by cassianomon** [comment]
version 2.10 and it doesn't work, all tabs have height equals to the higher.

**Comment by ClementLevesque** [comment]
I run version 2.5.0 and the tabs height seem to be updated when navigating through the different tabs when the height is higher but it never updates back when the height is lower.

**Comment by aamirl** [comment]
Has this issue been solved? Still struggling with this one.

**Comment by sikeeoh** [comment]
Has this issue been solved?  :(

**Comment by guibas741** [comment]
Has this issue been solved?

**Comment by juanjsebgarcia** [comment]
I'm still seeing this on the latest, anyone know a workaround?

**Comment by yarapolana** [comment]
+1 on this one any insight?

**Comment by VictorioMolina** [comment]
Any workaround?

**Comment by guibas741** [comment]
I gave up on react-native-tab-view and create my own tab component using `lazy` and `Animation`

**Comment by VictorioMolina** [comment]
I have implemented my own tab view and having the same problem. It seems that I am doing something wrong in the nested FlatList. Maybe this is happening to someone else... I am having the same behaviour in both tabs.

https://snack.expo.io/@victoriomolina/my-tabview 

If someone knows how to solve it please contact me at: victoriomolina17@gmail.com

Sorry for the inconvenience.
