### ISSUE TITLE
Is there any way to change the tab manually or jump to a particualr tab using a callback without performing tap or swipe.

### ISSUE THREAD

**Issue by amrit-sahoo** [react-native-community/react-native-tab-view#664]
### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          |
| react-native-tab-view |
| node                  |
| npm or yarn           |

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
