### ISSUE TITLE
Is there a way to use this tab for a single page?

### ISSUE THREAD

**Issue by SaiOduri** [react-native-community/react-native-tab-view#665]
I just want to use the top bar as an animated slider and don't really want it to change the page. If not, i'll have to make my own. Thanks in advance.

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
