### ISSUE TITLE
where I can use the  indicatorStyle props

### ISSUE THREAD

**Issue by renishdeveloper** [react-native-community/react-native-tab-view#666]
I have to change the tab bar label's color in the Tab view

There is no error, but I can't able to change the color of Tab view.
Actually, I can't know where the indicatorStyle has to use to change the label color.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android version : 7.0
| react-native          | 0.57.1
| react-native-tab-view | 1.2.2
| node                  | 8.12.0
| npm or yarn           | 6.4.1

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
