### ISSUE TITLE
Tab View with swipeEnabled={true} but disabled on one scene

### ISSUE THREAD

**Issue by JohnnyDevX** [react-native-community/react-native-tab-view#673]
So I have a scrollable tab view and I want to make it swipeable in three screens/scenes, but disable scrolling on one screen/scene. 

Is it somehow possible?

I'm using TabView with PagerExperimental for the best performance.

**Comment by JohnnyDevX** [comment]
That's easy, you just have to conditionally set the swipeEnabled props, based on for example this.state.index:

     <Tabs swipeEnabled={this.state.index == 2 ? false : true}

**Comment by robizzt** [comment]
If you want to disable swipe only on first screen and you have lazy loading enabled, this will not work, since `this.state` will be unidentified.
