### ISSUE TITLE
How to use React navigation inside react-native-tab-view?

### ISSUE THREAD

**Issue by devvlop** [react-native-community/react-native-tab-view#676]
How can I use react navigation in react-native-tab-view to jump to another screen?
I have this error : Error: undefined is not an object (evaluating '_this3.props.navigation.navigate')
And to fix that I should give access to view by navigation={this.props.navigation} .
In normal screen working fine but in tabs not working.
How can I add access to this View:
`const HomeTab = () => (
<View><Text>Hello!</Text></View>
)
`

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.

**Comment by gamingumar** [comment]
@satya164 the tabs are not visible if i navigate from current tab to new react navigation screen and come back
