### ISSUE TITLE
Inconsistent response from canJumpToTab

### ISSUE THREAD

**Issue by patrickngohonestbee** [react-native-community/react-native-tab-view#677]
Hi, thanks for your work on this awesome lib.

I'm experiencing a bit of an inconsistency when using `canJumpToTab` prop.
I noticed that sometimes it receives an object with a route key and the route object as value `{ route: actualRoute }`,

https://github.com/react-native-community/react-native-tab-view/blob/93edc9e130a63d16cd10b8c5b635e16fade8e7c5/src/PagerScroll.js#L105

 and sometimes it receives the route object directly.

https://github.com/react-native-community/react-native-tab-view/blob/93edc9e130a63d16cd10b8c5b635e16fade8e7c5/src/TabView.js#L164

Is this the intended behavior? It makes it a bit difficult to use the `canJumpToTab` prop

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
