### ISSUE TITLE
scrollEnabled={false} does not work

### ISSUE THREAD

**Issue by wildQueequeg** [react-native-community/react-native-tab-view#68]
react-native-tab-view: 0.0.34
react-native: ^0.35.0

With scrollEnabled={false}, tabs still scroll

**Comment by satya164** [comment]
@wildQueequeg That's weird. Can you post some example code?

**Comment by wildQueequeg** [comment]
@satya164 

Is this usage correct?

<TabBar scrollEnabled={false}
                  {...props}
                  renderIcon={this._renderIcon}
                  renderBadge={this._renderBadge}
                  style={styles.tabbar}
      />;

**Comment by wildQueequeg** [comment]
I tried it using renderPager and that successfully disables tab scrolling. 
```
_renderPager = (props) => {
    return <TabViewPagerPan {...props} swipeEnabled={false} />;
  };

<TabViewAnimated
        ...
        renderPager={this._renderPager}
      />

```

What is the difference between `swipeEnabled={false}` in renderPager and `scrollEnabled={false}` in TabBar ?

**Comment by satya164** [comment]
`swipeEnabled={false}` disables swipe gesture in the tab view.
`scrollEnabled={false}` (default) disables scrollable tabs in the tab bar.
