### ISSUE TITLE
ViewPagerAndroid will be removed in a future release.

### ISSUE THREAD

**Issue by diruuu** [react-native-community/react-native-tab-view#682]
### Current behaviour

I got warning after upgrading to latest react native release candidate. `ViewPagerAndroid has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/viewpager' instead of 'react-native'`. Any plan to adjust this?

| software              | version
| --------------------- | -------
| ios or android        | both
| react-native          | 0.59.0-rc.1
| react-native-tab-view | ^1.3.1

**Comment by satya164** [comment]
We're soon going to remove the use of `ViewPagerAndroid` entirely. https://github.com/react-native-community/react-native-tab-view/pull/681

Meanwhile, you can suppress the warning with `YellowBox.ignoreWarnings(['ViewPagerAndroid'])`

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
