### ISSUE TITLE
"react-native-tab-view": "2.0.0-alpha.3" onIndexChange not call immediately after swiping

### ISSUE THREAD

**Issue by tamirrab** [react-native-community/react-native-tab-view#685]
### Current behaviour

"react-native-tab-view": "2.0.0-alpha.3" onIndexChange not call immediately after swiping
This is damage the Lazy loading of the components

### Expected behaviour

onIndexChange call immediately after swiping like version "react-native-tab-view": "1.3.2"
### Code sample

I put the indexes on the screen so you can see when is change index (only after swipe. on click it's great)

@https://github.com/tamirrab/TabViewTesting

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | both iOS and Android
| react-native          | "0.58.5"
| react-native-tab-view | "2.0.0-alpha.3"
| node                  |v8.11.4
| npm or yarn           |yarn

**Comment by satya164** [comment]
It was never called immediately after swiping, at least not always. There's a new experimental `addListener` prop passed to `renderScene` so it's possible to detect when you are entering another screen (e.g. if the value is `> 0`, then you're going to index `1`, if the value is `< 3` then you're going to index `2` etc. It should make implementing lazy loading significantly easier and will be more reliable. However, keep in mind that this API may change before stable release.

**Comment by nicodelpiano** [comment]
Hi @satya164, can you explain how this `addListener` prop could be used? Because I'm not really following your suggestion, what do you mean with `the value is > 0`? My current use case is that I'd like to fetch some data before rendering the next tab (switching tabs from the topbar is fast, but swiping is super slow).

Thank you!

**Comment by satya164** [comment]
You get an `addListener` prop in `renderScene` which you can pass to your component. For how it's used, you can check the [SceneView](https://github.com/react-native-community/react-native-tab-view/blob/master/src/SceneView.js#L41 ) component in the library.

But in your case it seems like you should just use `lazy` prop and fetch data in `componentDidMount`
