### ISSUE TITLE
Tab Bar Color

### ISSUE THREAD

**Issue by lutakyn** [react-native-community/react-native-tab-view#686]
### Current behaviour

I have the default blue header color and the yellow underline color.

### Expected behaviour

I want to add styles to the tab title and style it like a button 

### Code sample

 `import * as React from 'react';
   import { View, StyleSheet, Dimensions } from 'react-native';
  import { TabView, SceneMap } from 'react-native-tab-view';

  const FirstRoute = () => (
   <View style={[styles.scene, { backgroundColor: '#ff4081' }]} />
  );
   const SecondRoute = () => (
     <View style={[styles.scene, { backgroundColor: '#673ab7' }]} />
   );
   const ThirdRoute = () => (
    <View style={[styles.scene, { backgroundColor: 'red' }]} />
   );
   export default class TabViewExample extends React.Component {
   state = {
    index: 0,
    routes: [
      { key: 'first', title: 'First' },
      { key: 'second', title: 'Second' },
        { key: 'third', title: 'Third' },
    ],
   };

  render() {
    return (
      <TabView
        navigationState={this.state}
        renderScene={SceneMap({
          first: FirstRoute,
          second: SecondRoute,
          third:ThirdRoute
        })}
        onIndexChange={index => this.setState({ index })}
        initialLayout={{ width: Dimensions.get('window').width }}
      />
    );
  }
}

const styles = StyleSheet.create({
  scene: {
    flex: 1,
  },
});`

### What have you tried

I am stuck at this point since the documentation didn't we can do that.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | oreo
| react-native          | 0.57
| react-native-tab-view | 1.3.2
| node                  |
| npm or yarn           |

**Comment by satya164** [comment]
`TabBar` accepts a `style` prop to change styles such as background color, `tabStyle` to style individual tabs, and `indicatorStyle` for indicator. If these props aren't enough for you, you can also make a custom tab bar https://snack.expo.io/@satya164/react-native-tab-view-custom-tabbar

**Comment by lutakyn** [comment]
<TabView
navigationState={this.state}
renderScene={SceneMap({
first: FirstRoute,
second: SecondRoute,
third:ThirdRoute
})}
onIndexChange={index => this.setState({ index })}
initialLayout={{ width: Dimensions.get('window').width }}
 style={{backgroundColor:'#333333'}}
/>

check this code, I used TabView and adding a style to the TabView still changes nothing here.The color is still blue.Assist

**Comment by lutakyn** [comment]
TabView style doesn't work as expected,I just need to change the backgroud color for the TabView

**Comment by robertogl23** [comment]
como se cambia el color, tengo que usar tabBar??
