### ISSUE TITLE
Unable to build project after updating to version 2.0.0-alpha.3

### ISSUE THREAD

**Issue by chukkalasandeep** [react-native-community/react-native-tab-view#688]
Hi,
I am using the below dependencies
"dependencies": {
    "moment": "^2.24.0",
    "react": "^16.6.3",
    "react-native": "^0.58.4",
    "react-native-animatable": "^1.3.1",
    "react-native-config": "^0.11.7",
    "react-native-elements": "^1.0.0",
    "react-native-gesture-handler": "^1.0.16",
    "react-native-modal": "^7.0.2",
    "react-native-paper": "^2.11.1",
    "react-native-ratings": "^6.3.0",
    "react-native-reanimated": "^1.0.0-alpha.12",
    "react-native-root-toast": "^3.0.2",
    "react-native-router-flux": "^4.0.6",
    "react-native-status-bar-height": "^2.2.0",
    "react-native-tab-view": "^2.0.0-alpha.3",
    "react-native-vector-icons": "^6.3.0",
    "react-navigation": "^3.2.3",
    "react-navigation-material-bottom-tabs": "^1.0.0"
  },
  "devDependencies": {
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "24.0.0",
    "jest": "24.0.0",
    "metro-react-native-babel-preset": "0.51.1",
    "react-test-renderer": "16.6.3"
  },

below is the build error 

![image](https://user-images.githubusercontent.com/9654621/53288181-82402080-37c0-11e9-9d0e-222e1b95c8d1.png)

Earlier version of react-native-tab-view is working, the error is only coming after upgrading. Please help

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | v0.58.4
| react-native-tab-view | v2.0.0-alpha.3
| node                  | v11.9.0
| npm or yarn           | npm

**Comment by satya164** [comment]
Looks like your `node_modules` is messed up. Delete your `node_modules` folder and try again.

Also, I recommend using `yarn` to avoid such issues in the future.

**Comment by christophior** [comment]
I am also getting the same error even after wiping out and reinstalling my node dependencies. I'm using npm, not yarn.

**Comment by satya164** [comment]
NPM is buggy. Please use Yarn and report if it doesn't work. As you can see, the published package has no such import: https://unpkg.com/react-native-tab-view@2.0.0-alpha.3/src/index.js
