### ISSUE TITLE
TabView style props doesn't work as expected

### ISSUE THREAD

**Issue by lutakyn** [react-native-community/react-native-tab-view#692]
### Current behaviour
I have the default blue header color and the yellow underline color.

### Expected behaviour
I want to add styles to the tab title and style it like a button in a TabView

### Code sample
` import * as React from 'react';
   import { View, StyleSheet, Dimensions } from 'react-native';
  import { TabView, SceneMap } from 'react-native-tab-view';

   const FirstRoute = () => (
   <View style={[styles.scene, { backgroundColor: '#ff4081' }]} />
   );
   const SecondRoute = () => (
   <View style={[styles.scene, { backgroundColor: '#673ab7' }]} />
   );
   const ThirdRoute = () => (
   <View style={[styles.scene, { backgroundColor: 'red' }]} />
   );
   export default class TabViewExample extends React.Component {
   state = {
   index: 0,
   routes: [
   { key: 'first', title: 'First' },
   { key: 'second', title: 'Second' },
   { key: 'third', title: 'Third' },
   ],
   };

  render() {
    return (
    <TabView
   navigationState={this.state}
   renderScene={SceneMap({
   first: FirstRoute,
   second: SecondRoute,
  third:ThirdRoute
   })}
   onIndexChange={index => this.setState({ index })}
   initialLayout={{ width: Dimensions.get('window').width }}
   />
   );
   }
    }

   const styles = StyleSheet.create({
   scene: {
   flex: 1,
   },
    });`

### What have you tried
I am stuck at this point since the documentation didn't we can do that.

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |
| react-native                 |
| react-native-tab-view        |
| react-native-gesture-handler |
| react-native-reanimated      |
| node                         |
| npm or yarn                  |

**Comment by satya164** [comment]
Please pass `style` prop to `TabBar`, not `TabView`

https://github.com/react-native-community/react-native-tab-view#rendertabbar
https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/ScrollableTabBarExample.js#L41
