### ISSUE TITLE
Tab bar button press wait for scenes to fully render even though there is lazyload placeholder

### ISSUE THREAD

**Issue by oguzhanali** [react-native-community/react-native-tab-view#693]
### Current behaviour

Version 2.0.0-alpha.4 works like a charm,  when swiping, tab's indicator slide with same with swiping scenes no delay, evertyhing is ok. I am using tab war with "scrollenabled", when sliding tab's indicator slide out of the screen, tab bar is focused to the active position with a long delay. It is same when navigate throught the tab bar (on press). I figured out, tab bar wait for scenes didCompenentMount, and then sliding animation and focus begins, that makes the delay, no lazy load place holder, goes directly (after the delay) to rendered scene. 

### Expected behaviour

Swiping scenes and navigation through tab bar should both work with lazy load, with same transition speed. I am not sure if it is tab bar's expected behaviour. Is there any way to work it synchronous with swiping? 

### Code sample

https://github.com/oguzhanali/LaggyTabBarView/blob/master/index.js

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |
| react-native                 | 
| react-native-tab-view        | 2.0.0-alpha.4
| react-native-gesture-handler | 1.0.16
| react-native-reanimated      | 1.0.0-alpha.12
| node                         |
| npm or yarn                  |

**Comment by satya164** [comment]
Are you on iOS or Android?

**Comment by oguzhanali** [comment]
@satya164 sorry for not mentioning, issue is on Android.

**Comment by satya164** [comment]
I can only see a minor delay (probably because I'm on a high-end device), but it's expected because your screens aren't optimized. Please see https://github.com/react-native-community/react-native-tab-view#avoid-unnecessary-re-renders on how to prevent-unnecessary re-renders to speed up tab switching.

**Comment by oguzhanali** [comment]
@satya164 I am actually asking, is this possible to use a lazy load placeholder with tab bar on press jumpto method? https://snack.expo.io/@satya164/react-native-tab-view-lazy-load pressing the tab do not load lazy load place holder, just swiping does. Can you give me a advice or trick ?

**Comment by satya164** [comment]
> pressing the tab do not load lazy load place holder

state update happens first with tab press. why do you want to show placeholder? surely faster the user sees the screen the better?

**Comment by vasilich6107** [comment]
In current scenario there is two differences
When I swipe to the next tab - I see the loader(placeholder) and have a feeling that something is 'loading'.
When I press on the next tab - everything freezes(I do not understand whether application working or stuck) and after several seconds my tab appears.

**Comment by ankitjaiswal1994** [comment]
@vasilich6107 Any solution worked for you.. because it is happening in the latest update also ?

**Comment by vasilich6107** [comment]
@ankitjaiswal1994 I switched to flutter cause RN is to painful to work with ;-)

**Comment by ankitjaiswal1994** [comment]
@vasilich6107 ROFL... Good Mate :)
