### ISSUE TITLE
swipe enabled ={true} not swipe between tabs

### ISSUE THREAD

**Issue by adirzoari** [react-native-community/react-native-tab-view#695]
### Current behaviour
I set swipeEnabled to true and when I try to swipe between tabs, nothing happened

### Expected behaviour
to swipe between tabs (without press on tab bar buttons)

### Code sample
 
```
  _handleIndexChange = index =>
    this.setState({
      index,
    });




  renderLabel = ({ route, focused, color }) => {
    console.log('route', route, focused, color)
    return (
      <View style={style.view_label}>
        <Text
          style={[
            style.tab_label_text,
            focused ? style.selected_tab_label : {}
          ]}
        >
          {route.title}
        </Text>
      </View>
    )
  }


  _renderTabBar = props => (
    <TabBar
      {...props}
      renderLabel={this.renderLabel}
      activeColor={Colors.pink}
      inactiveColor={Colors.black}
      indicatorStyle={style.indicator_tab}
      style={style.content_tabs}
      tabStyle={style.tab_style}
    />
  );




  _renderScene = SceneMap({
    contacts: FirstRoute,
    albums: SecondRoute,
  });

 <TabView
          style={this.props.style}
          navigationState={this.state}
          renderScene={this._renderScene}
          renderTabBar={this._renderTabBar}
          tabBarPosition="top"
          onIndexChange={this._handleIndexChange}
          swipeEnabled={true}


        />


```

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |android 
| react-native                 |0.57.8
| react-native-tab-view        |^2.0.0-alpha.5
| react-native-gesture-handler |^1.0.12
| react-native-reanimated      |^1.0.0-alpha.12
| node                         | v9.10.0
| npm or yarn                  | yarn

**Comment by satya164** [comment]
Did you finish the additional steps for linking gesture handler as mentioned here? https://github.com/react-native-community/react-native-tab-view#installation

**Comment by adirzoari** [comment]
@satya164  sorry, I didn't see. after follow these steps, it's working. thanks
