### ISSUE TITLE
Can you post an example with TabBar and Icon,Thanks

### ISSUE THREAD

**Issue by SongZhuhai** [react-native-community/react-native-tab-view#697]
### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |
| react-native                 |
| react-native-tab-view        |
| react-native-gesture-handler |
| react-native-reanimated      |
| node                         |
| npm or yarn                  |

**Comment by satya164** [comment]
https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/TabBarIconExample.js
