### ISSUE TITLE
Tab style width auto

### ISSUE THREAD

**Issue by rochapablo** [react-native-community/react-native-tab-view#698]
### Current behaviour

When using `tabStyle={{ width: 'auto' }}`, indicator does not assume the same width as each tab.

### Expected behaviour

There's no error. I just expect the indicator tab follow each tab size (when `width: 'auto' `)

### Code sample

https://github.com/rochapablo/react-native-tab-view

### Screenshots (if applicable)

![Imgur](https://i.imgur.com/teqFAUY.png)

### What have you tried

I've tried this https://github.com/react-native-community/react-native-tab-view/issues/323#issuecomment-408330801, the indicator works but the scroll gets mess-up letting a huge space at the and of the tabs container.

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | iOS 10
| react-native                 | 0.58.6
| react-native-tab-view        | 2.0.1
| react-native-gesture-handler | 1.0.17
| react-native-reanimated      | 1.0.0-alpha.12
| node                         | 10.15.0
| npm or yarn                  | npm 6.4.1

**Comment by satya164** [comment]
It's not supported. PR welcome.

**Comment by popcornAC** [comment]
Also trying to tackle this problem.

**Comment by glennvgastel** [comment]
The indicator would also have to resize when switching between tabs, so you'd need to determine a state that holds the size of each button. Using `onLayout` on the children, you could report the tab's height to their parent and calculate from there.

**Comment by popcornAC** [comment]
Is anyone working on it? If not, I'll attempt a PR...

**Comment by rochapablo** [comment]
@popcornAC, news?

**Comment by popcornAC** [comment]
@rochapablo  Got caught up with work, was going to start working on it again soon

**Comment by danigm87** [comment]
@rochapablo @popcornAC, news?

**Comment by rochapablo** [comment]
@danigm87, noop

**Comment by gowtham6797** [comment]
+1

**Comment by salhotra** [comment]
+1

**Comment by sato-daiki** [comment]
+1

**Comment by satya164** [comment]
https://github.com/react-native-community/react-native-tab-view/pull/751

**Comment by satya164** [comment]
This was implemented in b889782a5fd30ce0c6636546bb7225700b90424e
