### ISSUE TITLE
Library not working

### ISSUE THREAD

**Issue by academy-codex** [react-native-community/react-native-tab-view#699]
### Current behaviour

Failed to load bundle(http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(Unable to resolve module `react-native-reanimated` from `/Users/siddhantchadha/Desktop/Plootus/plootusreactapp/node_modules/react-native-tab-view/src/TabBar.js`: Module `react-native-reanimated` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`. (null))

__38-[RCTCxxBridge loadSource:onProgress:]_block_invoke.226
    RCTCxxBridge.mm:412
___ZL36attemptAsynchronousLoadOfBundleAtURLP5NSURLU13block_pointerFvP18RCTLoadingProgressEU13block_pointerFvP7NSErrorP9RCTSourceE_block_invoke.118
__80-[RCTMultipartDataTask URLSession:streamTask:didBecomeInputStream:outputStream:]_block_invoke
-[RCTMultipartStreamReader emitChunk:headers:callback:done:]
-[RCTMultipartStreamReader readAllPartsWithCompletionCallback:progressCallback:]
-[RCTMultipartDataTask URLSession:streamTask:didBecomeInputStream:outputStream:]
__88-[NSURLSession delegate_streamTask:didBecomeInputStream:outputStream:completionHandler:]_block_invoke
__NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
-[NSBlockOperation main]
-[__NSOperationInternal _start:]
__NSOQSchedule_f
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_continuation_pop
_dispatch_async_redirect_invoke
_dispatch_root_queue_drain
_dispatch_worker_thread2
_pthread_wqthread
start_wqthread

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |
| react-native                 |
| react-native-tab-view        |
| react-native-gesture-handler |
| react-native-reanimated      |
| node                         |
| npm or yarn                  |

**Comment by glennvgastel** [comment]
You should read the installation section on the front page.
Also, don't ignore issue templates.

**Comment by satya164** [comment]
Please follow the README and if it's still not working, open a new issue with the issue template.

**Comment by alainib** [comment]
same issues for me. 
does the version 2.0.1 work with  "react 16.5.2" and "react-native 0.55.4" ?

**Comment by herarya** [comment]
+1 same

**Comment by yasirwahid** [comment]
doesnt work same

**Comment by akinncar** [comment]
try `npm install react-native-reanimated`
