### ISSUE TITLE
Vertical TabViewAnimated

### ISSUE THREAD

**Issue by Kottidev** [react-native-community/react-native-tab-view#70]
can you add for example param "horizontal" type bool in TabViewAnimated 

If true, the Animated view's children are arranged horizontally in a row instead of vertically.

**Comment by satya164** [comment]
@Kottidev It's not possible right now, but shouldn't be very difficult to add. PR welcome.

**Comment by Kottidev** [comment]
@satya164 can you help me , how can i added it ?

**Comment by julesmoretti** [comment]
Plus one with this request please 👍

**Comment by satya164** [comment]
@Kottidev Check `TabViewPanPager` code

**Comment by satya164** [comment]
I'm not planning to work on vertical tab view anytime soon. If someone figures out a nice way to do it, feel free to send a PR. Closing this issue.
