### ISSUE TITLE
Cant enable react-native-tab-view in my app

### ISSUE THREAD

**Issue by kobimilan995** [react-native-community/react-native-tab-view#702]
### Current behaviour

My brand new react-native app crashes when i introduced react-native-tab-view

### Expected behaviour

I wish to use this library without any problems, but i cant get around this error.

### Screenshots (if applicable)
<img width="416" alt="screenshot 2019-03-04 at 20 39 22" src="https://user-images.githubusercontent.com/31390546/53758443-0c257300-3ebe-11e9-808d-2ca68aee1254.png">

### What have you tried

I have tried literallly everything
### Your Environment

| software                     | version
| ---------------------------- | -------
| ios              |
| react-native                 | 0.58.5
| react-native-tab-view        | latest
| react-native-gesture-handler | latest
| react-native-reanimated      | latest

**Comment by satya164** [comment]
try `react-native start --reset-cache`

**Comment by kobimilan995** [comment]
Didnt fix it. Now i m getting this: 
<img width="416" alt="screenshot 2019-03-04 at 20 50 23" src="https://user-images.githubusercontent.com/31390546/53758861-36c3fb80-3ebf-11e9-81be-f6a8fbfff311.png">

And i have succesfully linked everything

**Comment by satya164** [comment]
@kobimilan995 have you reinstalled pods and everything accordingly? from your error it looks like reanimated isn't linked
