### ISSUE TITLE
Tab bar does not respond to taps

### ISSUE THREAD

**Issue by gmaclennan** [react-native-community/react-native-tab-view#703]
### Current behaviour

I add the example from the README to a minimal RN project (v0.58.5) on Android and when pressing a tab it does not reliably switch tabs. It only works about 10% of the time. The ripples show on the tab but it is not triggering a tag switch. In `adb logcat` I see this every time I tap a tab:

```
03-04 20:45:23.641  1101  1101 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 4, app_layer_count: 3, gpu_target_index: 3, display type: 0
03-04 20:45:23.703  1127  1159 E ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
```

Swiping between tabs does work.

### Expected behaviour

I expect to tap a tab and the tab view to switch to that tab.

### Code sample

https://github.com/gmaclennan/mapeo-nodejs-mobile/tree/react-native-tab-view

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | android SDK 28.0.3
| react-native                 | v0.58.5
| react-native-tab-view        | v2.0.1
| react-native-gesture-handler | v1.1.0
| react-native-reanimated      | v1.0.0-alpha.12
| node                         | v8.15.0
| npm or yarn                  | npm 6.7.0

**Comment by satya164** [comment]
Are you connected to the debugger?

**Comment by gmaclennan** [comment]
Yes, I was. Disconnecting does fix this! Still occasionally seems to miss a press, but this is likely because I've got __DEV__ true. I'll test a production build.

**Comment by gmaclennan** [comment]
With `__DEV__=false` this is much better. Very occasionally a tap is not working, but I cannot reproduce reliably.

**Comment by wbercx** [comment]
Taps do seem to not fire beyond showing a ripple sometimes. I don't find switching between them very responsive in v2 either, even when I render `null` as my scenes, and in release mode.

**Comment by satya164** [comment]
The tab press literally only updates the state. The code for tab bar in v2 is also largely the same as the code in v2. There's not a lot of failure points there.

If `onPress` is not firing properly, make sure you're not connected to debugger and test on real device. And follow the optimization tips: https://github.com/react-native-community/react-native-tab-view#optimization-tips

If you have a consistent repro, please open a new issue with a demo on https://snack.expo.io/ or a GitHub repo and I'll check it out.

**Comment by camel113** [comment]
Don't you think we should add a note to the README about this issue?
