### ISSUE TITLE
Doesn't build with BundlePhobia.com

### ISSUE THREAD

**Issue by Eyesonly88** [react-native-community/react-native-tab-view#705]
### Current behaviour

It does not build with Bundlephobia.com

### Expected behaviour

It should build with Bundlephobia in order to get stats about the package.

```
/tmp/tmp-build/packages/build-react-native-tab-view@2.0.1-AV4/node_modules/react-native-tab-view/src/index.js 7:7 Module parse failed: Unexpected token (7:7) You may need an appropriate loader to handle this file type. | export { default as SceneMap } from './SceneMap'; | > export type { Route } from './types'; | export type { NavigationState } from './types'; | export type { SceneRendererProps } from './types'; @ /tmp/tmp-build/packages/build-react-native-tab-view@2.0.1-AV4/index.js 1:10-42
```

### Your Environment

Built with Bundlephobia.com

https://bundlephobia.com/result?p=react-native-tab-view

https://github.com/pastelsky/bundlephobia

**Comment by satya164** [comment]
Most react native libraries won't bundle with bundlephobia.
