### ISSUE TITLE
`animationEnabled` option not working in 2.0.1

### ISSUE THREAD

**Issue by wuchangming** [react-native-community/react-native-tab-view#707]
### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |
| react-native                 |
| react-native-tab-view        |2.0.1
| react-native-gesture-handler |
| react-native-reanimated      |
| node                         |
| npm or yarn                  |

**Comment by dsznajder** [comment]
@wuchangming It was removed in `2.0.1` version. See other breaking changes [here](https://github.com/react-native-community/react-native-tab-view/releases/tag/v2.0.1)

**Comment by wuchangming** [comment]
@dsznajder it’s there any way to disable the animation between the switch of the Tabs?

**Comment by dsznajder** [comment]
@wuchangming I would go for downgrade of a module and lock it to some previous version. As you can see in release changes, this library will keep current behaviour with animating tabs.

**Comment by satya164** [comment]
@wuchangming consider migrating to a different library if you don't want animations.

**Comment by Jyrno42** [comment]
@satya164 Would you accept a PR that re-enables animationEnabled? 

Context: I am dynamically adding/removing tabs in some conditions (while preserving the active view) the view animates if I if the previous index of the active page is now different from the old index of that particular page (e.g if I add more items before the previously active page).

**Comment by HessiPard** [comment]
I could remove animation with `timingConfig `props:
`timingConfig={{
						duration: 1,
					}}`

**Comment by Bardiamist** [comment]
Vote for that feature
https://react-navigation.canny.io/feature-requests/p/allow-to-disable-animation-for-tabnavigator
