### ISSUE TITLE
[v2.0.1] Tab is Still Sliding/Swiping Even If Index is Not Updated

### ISSUE THREAD

**Issue by diruuu** [react-native-community/react-native-tab-view#708]
### Current behaviour

Tab is still sliding/swiping even if index is not updated. I tried to not update the state on `onIndexChange`, but I am still able to slide through  the tabs. It just disabled the tabbar onpress action. Isn't it brake the concept of controlled component?

### Expected behaviour

Tabview unable to swipe if index hasn't changed

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | both
| react-native-tab-view        | v2.0.1]

**Comment by satya164** [comment]
Closing since this shouldn't happen in latest versions.
