### ISSUE TITLE
Native module cannot be null?

### ISSUE THREAD

**Issue by galuh1300d** [react-native-community/react-native-tab-view#709]
Why this error happen?

<img width="390" alt="screen shot 2019-03-08 at 13 23 54" src="https://user-images.githubusercontent.com/43464041/54011602-aaa72200-41a5-11e9-9d56-2b4417f7dea3.png">

**Comment by thanhtuttm** [comment]
I have the same issue on iOS.

**Comment by galuh1300d** [comment]
> I have the same issue on iOS.

exactly, can you solve this?

**Comment by satya164** [comment]
Please link `react-native-reanimated` as mentioned in the installation instructions, and fill the issue template when reporting issues.

**Comment by galuh1300d** [comment]
> Please link `react-native-reanimated` as mentioned in the installation instructions, and fill the issue template when reporting issues.

But i've link react-native-reanimated?

**Comment by satya164** [comment]
If linking is not working properly, report the issue in react-native-reanimated repo with a proper repro since the error is coming from that library

**Comment by pmadruga** [comment]
Just ran into this problem and I have this problem every time because react-native link has never worked for me. So adding this to your Podfile 

`pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'` 
 and then `pod install` will do the trick.

I had previously installed RN gesture handler but if you are facing that issue, than solve it in the same way: 

`pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'`

**Comment by c6thomas** [comment]
Any updates to this? None of the suggested ideas worked

**Comment by c6thomas** [comment]
Idk if its because I'm a noob, but doing what @pmadruga recommended caused serious collisions with my node_modules & podfile.  I had to completely override my local branch with my remote & clear my cache to fix the issue

**Comment by nlabofa** [comment]
The issue is that react-native link react-native-reanimated is not properly linking the react-native-reanimated library. You have to link it manually in Xcode. i.e add RNReanimated.xcodeproj to the libraries folder, then add libReanimated.a to the link binary with libraries

**Comment by Luktm** [comment]
if you using react-native-firebase on ios please check the podfile similar. SEE SEE THE  COMMENT  OF "### CHECK THIS POD [NAME] ###" 

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TGus' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for TGus

  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies

 ### CHECK THIS POD REACT!!! ###
  pod 'React', :path => '../node_modules/react-native', subspecs: [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
  
 ### CHECK THIS POD YOGA###, ### RNReanimated### , ### RNGestureHandler!!!###
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

### PLEASE CHECK POD FOLLY ###
  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'Firebase/Core'
  # pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Functions'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'

### PLEASE CHECK TARGET ###
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end

      targets_to_ignore = %w(React yoga)
      if targets_to_ignore.include? target.name
        target.remove_from_project
      end

      # rnfirebase = installer.pods_project.targets.find { |target| target.name == 'RNFirebase' }
      # rnfirebase.build_configurations.each do |config|
        # config.build_settings['HEADER_SEARCH_PATHS'] = '$(inherited) ${PODS_ROOT}/Headers/Public/**'
      # end
    end
  end
end
```
