### ISSUE TITLE
Tab Content goes Blank after Route is Pushed then Popped

### ISSUE THREAD

**Issue by joncursi** [react-native-community/react-native-tab-view#71]
Hi! I have used `react-native-tab-view` to set up a four-pane system and ran into this bug. All of my panes have "filter" buttons which push a new route onto the stack. Within the filter scene, when the user is finished, they click "Done" and it will pop that route off the stack and return to the pane being managed by `react-native-tab-view`.

I noticed that when a route is pushed, and then subsequently popped, the tab content of the other 3 __non-active tabs__ (which do have content to show, and originally showed that content before pushing and popping) now show up completely blank:

![img_3121](https://cloud.githubusercontent.com/assets/4974609/20519559/62c8106a-b071-11e6-9d7b-cc38f7d2fee3.PNG)

In this blank area, there is a <ListView> with, as I mentioned, a lot of rows rendered. It should not be blank. I also noticed that if you simply *nudge* this ListView component (a small swipe up or down in that blank area), the ListView content pop back up (re-render?).

I'm not sure where the bug with this lies, but my hunch is that it's in this library, so I figured I would start here!

Any help appreciated! Thanks!

**Comment by satya164** [comment]
Is a React Native bug https://github.com/facebook/react-native/issues/1831

Set `removeClippedSubViews` as a workaround.

**Comment by joncursi** [comment]
Thank you!

**Comment by mayconmesquita** [comment]
This works, Thanks!
