### ISSUE TITLE
Android only -> E/ReactNativeJS: undefined is not an object (evaluating '_ReanimatedModule.default.configureProps') 

### ISSUE THREAD

**Issue by jatin-mohindra** [react-native-community/react-native-tab-view#710]
### Screenshots (if applicable)

Getting this error in logcat only on android:
<img width="1326" alt="screenshot 2019-03-08 at 17 39 36 10" src="https://user-images.githubusercontent.com/47021089/54027953-54e47100-41c9-11e9-87ca-e639c76d6854.png">

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |
| react-native                 |
| react-native-tab-view        |2.0.1
| react-native-gesture-handler |
| react-native-reanimated      |
| node                         |
| npm or yarn                  |

**Comment by weikilla** [comment]
i meet the same issue,  i get the error message: null is not an object(evaluating '_ReanimatedModule.deafult.configureProps'), is there anyone who can help with me?

**Comment by satya164** [comment]
@weikilla please link reanimated as mentioned in README

Closing issue due to incomplete issue template.

**Comment by jatin-mohindra** [comment]
@satya164 I have updated the template above. pls let me know if more info is required. also I linked reanimated as mentioned in the README but it does not work. the issue is only for android

**Comment by AmitM30** [comment]
Same issue. Android only. please help !

**Comment by alshirokov81** [comment]
Same issue ((

**Comment by Ilphrin** [comment]
I had the same issue, changed form using `SceneMap` to a custom `renderScene` method, rebuilt via Android Studio, and restarted metro bundler. Now it is working! I don't know which step fixed this issue though :/

**Comment by Nextt1** [comment]
Using renderScene props. Still facing the same issue.

**Comment by AHStudyBank** [comment]
SAME ISSUE!!!!!

**Comment by AHStudyBank** [comment]
Hello!!

**Comment by muhammad-nauman** [comment]
@weikilla have you found any solution?

**Comment by muhammad-nauman** [comment]
@weikilla and others, here is the solution:
Make sure that you've added
new ReanimatedPackage(),in MainApplication.java under getPackages

Import from: import com.swmansion.reanimated.ReanimatedPackage;

**Comment by jayrajkachariya** [comment]
@muhammad-nauman we don't need to do it, if we are using React-Native v0.6 or greater. **react-naitve link** command will do it for us and don't need to override the package-list in **MainApplication.java**.

I had similar issue, For me just reinstalling node_modules worked fine.

**Comment by AndroidDoctorr** [comment]
He's referring to this step, for React 0.59 or lower:
`react-native link react-native-reanimated`
`react-native link react-native-gesture-handler`
Took me a while to figure out because I thought I was using the latest react-native

**Comment by mdoubah87** [comment]
Thanks @muhammad-nauman  
Make sure that you've added
new ReanimatedPackage(),in MainApplication.java under getPackages
new RNGestureHandlerPackage(), in MainApplication.java under getPackages

Import from: import com.swmansion.reanimated.ReanimatedPackage; and
Import from: import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;

**Comment by Shirley-Liz** [comment]
I have done all the above but the error still persists, i am running react  native 0.61.2 ,  react-navigation 4.0.10, react-native-tabs 2.5.6

**Comment by sanjayradadiya** [comment]
I am having same issue that has @Shirley-Liz

**Comment by kojongDev** [comment]
In android my case I just got an error with install and link. If you sync later, it will be solved.

**Comment by alidiepuit** [comment]
I still have this issue (android). Any suggest for this?

**Comment by rdodda527** [comment]
<img width="389" alt="Screen Shot 2020-02-05 at 5 44 39 PM" src="https://user-images.githubusercontent.com/39780944/73898763-38204580-483f-11ea-8a72-d8369b9444ef.png">
Mine just says "n.default.ConfigProps" - Any idea how to resolve this?

**Comment by mayank-budhiraja** [comment]
Facing the same issue. Couldn't resolve it. Any help?
