### ISSUE TITLE
Flickering/Delayed behaviour when only one tab route

### ISSUE THREAD

**Issue by RyanForsdick** [react-native-community/react-native-tab-view#713]
### Current behaviour

When using a TabView with only one route, there is flickering behaviour and a delay in render updates.

### Expected behaviour

No flickering or delay.

### Code sample

Example with two tabs with no issues:
https://snack.expo.io/r1slwnwv4

Example with one tab experiencing issue:
https://snack.expo.io/H1nmv2wPV

### What have you tried

Made sure that all the components are PureComponents and no unnecessary re-renders are ocurring, and recreated issue in a very simplistic snack to make sure that using a single tab is the cause.

### Your Environment

Using expo.

| software                     | version
| ---------------------------- | -------
| ios or android               | android 8.0.0
| react-native                 | 32.0.0
| react-native-tab-view        | 2.0.2
| react-native-gesture-handler | 1.0.14
| react-native-reanimated      | 1.0.0-alpha.11
| node                         | 10.13.0
| npm or yarn                  | yarn 1.12.3

**Comment by satya164** [comment]
I can't repro the issue in the provided snacks.

**Comment by RyanForsdick** [comment]
I think maybe as with issue #715 it is only a problem for certain devices
On samsung galaxy s7 Edge, running android version 8.0.0 the issue is visible in the snacks

**Comment by satya164** [comment]
Behaviour with a single route should be improved with latest version. I'm closing the issue. Let me know if you're still facing the issue.
