### ISSUE TITLE
If I swipe over the text input while swiping, it focuses on the text input 

### ISSUE THREAD

**Issue by Frekansapp** [react-native-community/react-native-tab-view#717]
### Current behaviour

I tested it in versions 2.0.1 and 2.0.2. I'm experiencing this issue. If I swipe over the text input while swiping, it focuses on the text input and turns on the keyboard and swipe does not work . Version 1.3.2 did not have this problem.

### Expected behaviour

should not focus on text input when swiping

### Screenshots (if applicable)

<img src="https://media.giphy.com/media/claGqOcmuoqUpYeTAM/giphy.gif" width="240">

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |Android 5.1
| react-native                 | 0.59.0
| react-native-tab-view        |2.0.2
| react-native-gesture-handler |1.1.0
| react-native-reanimated      |1.0.0-alpha.12
| node                         |11.11.0
| npm or yarn                  |NPM 6.8.0

**Comment by linddominic** [comment]
I think this has to do with the with to `react-native-gesture-handler` for the pager.

I'm seeing the same problem, where touches are being fired while swiping the tab view.

**Comment by Frekansapp** [comment]
Is there any development?

**Comment by satya164** [comment]
Yeah, it'll be great if you can open an issue in gesture handler repo https://github.com/kmagiera/react-native-gesture-handler

**Comment by satya164** [comment]
Closing since it's an issue with gesture handler.
