### ISSUE TITLE
Simply touching view causes huge bounce on Android RN 0.59.0. Version 2.0.2

### ISSUE THREAD

**Issue by wizebin** [react-native-community/react-native-tab-view#719]
### Current behaviour

When using gestures, the leftover velocity of the previous swipe seems to be applied when touching down on the tab view. Only in android, only on the recently stable release 0.59.0

### Expected behaviour

After a gesture is complete, the next touch down should be isolated and not affect the view in any way.

### Code sample

https://github.com/wizebin/TabViewVelocityIssue

### Screenshots (if applicable)

Video showing the core of the issue:
https://streamable.com/ybyc1

### What have you tried

Started on the react-native-gesture-handler docs, may try out some solutions myself

### Your Environment

| software                     | version
| ---------------------------- | -------
| android               | 9
| react-native                 | 0.59.0
| react-native-tab-view        | 2.0.3
| react-native-gesture-handler | 1.1.0
| react-native-reanimated      | 1.0.0-alpha.12
| node                         | 11.0.0
| npm                  | 6.4.1

**Comment by wizebin** [comment]
Some more information:
Manually tapping a tab will stop the second issue (where the view to the left will show up while scrolling) until another swipe has occurred

**Comment by gamingumar** [comment]
I am also facing similar issue in React Native 0.59 on android. Manually tapping a tab works first time but it doesn't work after that. Swipe still works though.
