### ISSUE TITLE
cannot swipe in ios simulator

### ISSUE THREAD

**Issue by chirag04** [react-native-community/react-native-tab-view#72]
i think the default example should be good enough to replicate. I haven't tried tho. Our app is using the having the same setup as default example.

cc @satya164

**Comment by satya164** [comment]
@chirag04 I'll check this soon. thanks for the reminder

**Comment by leechance** [comment]
@chirag04  the demo component must use as root component !! if used as chirld component ,maybe cannot scroll

**Comment by satya164** [comment]
I cannot reproduce this issue with the example app. Do you have a repro for me @chirag04 ?

**Comment by chirag04** [comment]
don't have a repo atm. going to close this since the new defaults in .42 works really nicely.
