### ISSUE TITLE
tabview without tabbar

### ISSUE THREAD

**Issue by bakaa99** [react-native-community/react-native-tab-view#725]
I want just the tab view without tabbar, i already have a tabbar but it's in another animated component, it's too much work to change the whole animated calculations just so that i can have both of these together.

Is it possible to pass null to renderTabBar so that i can only have the tabview

**Comment by satya164** [comment]
Pass `renderTabBar={() => null` to `TabView`

**Comment by bittu1028** [comment]
@satya164  @horodnicdragos  if there is no tab bar how did manage navigation between tabs using a custom button ?
