### ISSUE TITLE
Integration with stackNavigator

### ISSUE THREAD

**Issue by phonegap20** [react-native-community/react-native-tab-view#726]
Hi,

How can i implement stack navigator in SceneMap instead of passing react component name.

In SceneMap it only accepts the react component not the stack navigator which is causing this.props.navigation undefined in nested component.

like i want to pass it in similar way.

const HomeNavigator = createStackNavigator(
{
Home: HomeScreen,
Details: DetailsScreen
},
{
initialRouteName: "Home"
}
);

_renderScene = SceneMap({
'1': HomeNavigator,
'2': Screen2,
'3': Screen3,
'4': Screen4,
'5': Screen5,
'6': Screen6
});

It only accepts the react class component not the StackNavigator.

**Comment by Taylor123** [comment]
I would suggest using `react-navigation` or a similar library Tab Navigator rather than this library if you're trying to save navigation state for specific tabs

**Comment by phonegap20** [comment]
Dear Taylor,
Thanks for your suggestion, i really appreciate it.
Let's consider one simple use case for apps.

Let's say i have below scenes
'1': Screen1,
'2': Screen2,
'3': Screen3

User wants to navigate from Screen2 to ====> some nested screen let's name it "Settings"

Now from settings screen user wants to navigate Screen1.

Can you suggest the way to achieve it using this library please ?

I will appreciate if you can suggest a way to implement using this library.

**Comment by satya164** [comment]
Please use `createMaterialTopTabNavigator` from https://github.com/react-navigation/react-navigation-tabs. It provides integration for this library with React Navigation.

**Comment by phonegap20** [comment]
Thanks satya164,
I know createMaterialTopTabNavigator library..sorry may be you did not get my question.

**Comment by satya164** [comment]
All screens in `react-native-tab-view` receive a `jumpTo` prop. You'll need to pass it down to your screen somehow, perhaps using `screenProps` or React Context. Then you can call `jumpTo('Screen1')`

**Comment by phonegap20** [comment]
i am really sorry if you did not get my question.
Please refer below use case.

<Screen1 jumpTo={jumpTo} />
<Screen2 jumpTo={jumpTo} />
from Screen1 i am navigating to "Settings" screen.
Now from "Settings" screen i want to navigate "Screen2".

I understand that you can pass this.props.navigation as props from Screen1 to "Settings" but you can't navigate from "Settings" screen to "Screen2".

Please try to do it from your end and you will face same issue.
