### ISSUE TITLE
TabView not rendering if sibling components are present or it has a parent

### ISSUE THREAD

**Issue by onstash** [react-native-community/react-native-tab-view#728]
### Current behaviour
TabView is not getting rendered when there are sibling components or if it's rendered like this - <View><View><TabComponent /></View></View>.

Currently, I have a component that's like this <Text>Hello</Text><TabComponent /><Text>World</Text>.

TabView is not getting rendered. Only Hello & World are getting rendered.

### Expected behaviour

The following must be the rendered components - Hello <TabComponent> World

I expect the TabView to render with sibling components.

### Code sample

```
import React from "react";

import { View, StyleSheet, Dimensions, Text } from 'react-native';
import { TabView, SceneMap } from 'react-native-tab-view';

const FirstRoute = () => (
  <View style={styles.scene}><Text>First</Text></View>
);
const SecondRoute = () => (
  <View style={styles.scene}><Text>Second</Text></View>
);
const ThirdRoute = () => (
  <View style={styles.scene}><Text>Third</Text></View>
);


export default class TabViewExample extends React.Component {
  state = {
    index: 0,
    routes: [
      { key: 'first', title: 'First' },
      { key: 'second', title: 'Second' },
      { key: 'third', title: 'Third' },
    ],
  };

  render() {
    return (
      <View>
        <Text>Hello</Text>
        <TabView
            navigationState={this.state}
            renderScene={SceneMap({
                first: FirstRoute,
                second: SecondRoute,
                third: ThirdRoute,
            })}
            onIndexChange={index => this.setState({ index })}
            initialLayout={{ width: Dimensions.get('window').width }}
          />
        <Text>World</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  scene: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center"
  },
});
```

### Screenshots (if applicable)

![Screenshot_20190325-151428](https://user-images.githubusercontent.com/4272832/54910164-c9c9e180-4f11-11e9-9324-ba13890d5fc2.jpg)

### What have you tried

I wrapped TabComponent inside another component called TabWrapper. Tried <Text>Hello</Text><TabWrapper /><Text>World</Text>. Didn't work.

### Your Environment

| software                     | version
| ---------------------------- | -------
| android               | 9.0.4 OxygenOS on OnePlus 5
| react-native                 | 0.57.2
| react-native-tab-view        | 2.0.3
| react-native-gesture-handler | 1.1.0
| react-native-reanimated      | 1.0.0-alpha.12
| node                         | 8.12.0
| npm or yarn                  | yarn

**Comment by satya164** [comment]
Add `style={{ flex: 1 }}` to your wrapper view

**Comment by onstash** [comment]
Thank you, @satya164.
