### ISSUE TITLE
Custom tabs

### ISSUE THREAD

**Issue by DenisDov** [react-native-community/react-native-tab-view#729]
How to create this curved lines and smooth change between them?

<img width="374" alt="Screen Shot 2019-02-25 at 19 42 36" src="https://user-images.githubusercontent.com/13405393/54939312-ee818180-4f30-11e9-90b3-0762e1541144.png">

https://snack.expo.io/@denisdov/issue-tabs

How to solve that?

**Comment by satya164** [comment]
You probably need a third party library which can animate between such curves. Closing since it's not in the scope of this library.
