### ISSUE TITLE
Extra page without inserting the icon for TabBar

### ISSUE THREAD

**Issue by mrjcka** [react-native-community/react-native-tab-view#73]
Howdy,

I have recently run into situation that I need an extra page/view that not include the icon into the TabBar, my current solution is adding an extra if as below

Line 303 in src/TabBar.js
```javascript
{routes.map((route, i) => {
    const focused = index === i;
    const outputRange = inputRange.map(inputIndex => inputIndex === i ? 1 : 0.7);
```

Replace with
```javascript
{routes.map((route, i) => {
   
    // skip if not required to display icon
    if (i.hideIcon) return;

    const focused = index === i;
    const outputRange = inputRange.map(inputIndex => inputIndex === i ? 1 : 0.7);
```

Then in the state setup

```javascript
state = {
    index: 0,
    routes: [
        { key: '1', icon: 'home' },
        { key: '2', icon: 'magnify' },
        { key: '3', hideIcon: true }
    ]
};
```

Also setup as normal for 3 keys (as above example)
```javascript
_renderScene = ({route}) => {
    switch (route.key) {
        ...
    }
}
```

Happy to do a PR if this sounds good.
Cheer!

**Comment by satya164** [comment]
I think you can achieve it by following too,

```js
_renderHeader = (props) => {
  const navigationState = props.navigationState(route => !route.hide);
  const jumpToIndex = index => props.jumpToIndex(props.navigationState.indexOf(navigationState[index]));
  return <TabBarTop {...props} navigationState={navigationState} jumpToIndex={jumpToIndex} />;
};
```

Same for `renderFooter`.

I've not tried it though. Try and lemme know if it works for you.

**Comment by mrjcka** [comment]
There might be a miss understanding,
I believe solution you provided was trying to hide all icons (which your code works as I tried).

The situation I ran into was having 6 routes but only need to display icon of 4 in the TabBar

**Comment by satya164** [comment]
@mrjcka Hmm... no, it wasn't to hide all icons

**Comment by mrjcka** [comment]
I tried again, it does works!
Cheers!

**Comment by teddyteh** [comment]
How do I make it so that if I go to a hidden tab, the underline below the selected tab is not the last visible tab?
