### ISSUE TITLE
Newbie's doubt 

### ISSUE THREAD

**Issue by renanBicudo** [react-native-community/react-native-tab-view#732]
### Current behaviour

When I click on a tab, I get an error saying

_this.setState is not a function. (In '_this.setState ({
index: index}) ',' _ this.setState 'is undefined

### Expected behaviour

i follow the example, so i don't understand why i getting this message

### Code sample

`import React from 'react';
import { View, Text } from 'react-native';
import { TabView, SceneMap } from 'react-native-tab-view'

renderScene = SceneMap({
    faturamento: RotaFaturamento,
    financeiro: RotaFinanceiro,
    estoque: RotaEstoque,
  });  

const RotaFaturamento = () => (
            <Text>ABA1</Text>
);

const RotaFinanceiro = () =>  (
        <Text>ABA2</Text>
);

const RotaEstoque = () =>  (
        <Text>ABA3</Text>
);

const relatorios = () => {

    state ={
        index: 0,
        routes: [
            { key: 'faturamento', title: 'Faturamento'},
            { key: 'financeiro', title: 'Financeiro'},
            { key: 'estoque', title: 'Estoque'},
        ]
    }

   
    renderScene = ({ route, jumpTo }) => {
        switch (route.key) {
          case 'faturamento':
            return <RotaFaturamento jumpTo={jumpTo} />;
          case 'financeiro':
            return <RotaFinanceiro jumpTo={jumpTo} />;
          case 'estoque':
            return <RotaEstoque jumpTo={jumpTo} />;
        }
      };

    return(
        <TabView
            navigationState={this.state}
            onIndexChange={index => this.setState({ index })}
            renderScene={SceneMap({
                faturamento: RotaFaturamento,
                financeiro: RotaFinanceiro,
                estoque: RotaEstoque
            })}
        />        
    );
}

export default relatorios;
`

**Comment by satya164** [comment]
You can't use `this.setState` in a function component. Either use a class component like in the example or refactor to use a function component with `useState` hook: https://reactjs.org/docs/hooks-state.html
