### ISSUE TITLE
evaluating e.nativeEvent.pageScrollState on android

### ISSUE THREAD

**Issue by bernardakl** [react-native-community/react-native-tab-view#733]
Hello, 
I am using   
{
   "react-native": "0.55.2",
   "react-native-tab-view": "^1.3.3"
}
On IOS working good.
On android, 
on switch tab, I get this error: undefined is not an object (evaluating 'e.nativeEvent.pageScrollState')
_handlePageScrollStateChanged
    PagerAndroid.js:96:33
_onPageScrollStateChanged
    ViewPagerAndroid.android.js:200:42
...

**Comment by satya164** [comment]
Please update to 1.3.4
