### ISSUE TITLE
Center active Tab only

### ISSUE THREAD

**Issue by vohoangankhanh** [react-native-community/react-native-tab-view#736]
How can only the active tab be center like this, I have 3 tab in tabbar,the requirement is the active tab always be center of the screen, if tab 1 and 3 is actived they will be center and the next tab still appear partially on the screen. And can tabs scroll infinitely like a circle?
![image](https://user-images.githubusercontent.com/13093106/55521557-6aa36400-56ab-11e9-8995-b142049c2846.png)
![image](https://user-images.githubusercontent.com/13093106/55521579-83ac1500-56ab-11e9-8a99-255847c97fd2.png)

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |
| react-native                 |
| react-native-tab-view        |
| react-native-gesture-handler |
| react-native-reanimated      |
| node                         |
| npm or yarn                  |

**Comment by satya164** [comment]
This is not possible with the default tab bar. You can provide a custom one for your use case.

**Comment by mirajwebclues** [comment]
@vohoangankhanh  you got any solution for this ?

**Comment by vohoangankhanh** [comment]
> @vohoangankhanh you got any solution for this ?

not yet @mirajwebclues
