### ISSUE TITLE
Active label in tab bar is cropped if it's size is bigger than the inactive

### ISSUE THREAD

**Issue by ajubin** [react-native-community/react-native-tab-view#737]
### Current behaviour

If active label rendering size is bigger than inactive label size, active label is being cropped.

### Expected behaviour

Active label shouldn't be cropped

### Code sample

https://snack.expo.io/@ajubin/react-native-tab-view-custom-tabbar

### Screenshots (if applicable)
On the screenshot, the second label (which is actived) is cropped to the size of the inactive label
![image](https://user-images.githubusercontent.com/14874974/55546603-f7601900-56cf-11e9-9a60-d86a2db65982.png)
![image](https://user-images.githubusercontent.com/14874974/55546839-60e02780-56d0-11e9-9b44-b22839fbe289.png)

### What have you tried

in file `TabBarItem.js` the activeLabel view with the style  `StyleSheet.absoluteFill` seems to be the origin of this issue.

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios  and android            |  IPhone X - 11.4 + Nexus 5 Android 9
| react-native                 | 0.59.1
| react-native-tab-view        | ^2.0.3
| react-native-gesture-handler | ^1.1.0
| react-native-reanimated      | 1.0.0-alpha.12
| node                         | 8.12.0
| npm or yarn                  | yarn

**Comment by satya164** [comment]
I don't think it's possible to fix this. We need to overlay the active and inactive labels on top of each other to cross-fade them and one of them needs to be absolutely positioned.
