### ISSUE TITLE
Only renders the initial tab in IOS Or Android 

### ISSUE THREAD

**Issue by saharjedidi** [react-native-community/react-native-tab-view#739]
i have a problem 
i install this library and i implement it 
i have 3 tabs but only the informations in the initial tab renders but in the second and the third one is empty (didn't display data in the second and the third tabs )

**Comment by satya164** [comment]
repro please

**Comment by satya164** [comment]
Closing due to incomplete issue template.

**Comment by Amenocy** [comment]
i have same problem, it is related to RTL and i18nManager.isRTL checks inside tabview code.
