### ISSUE TITLE
A onChange method?

### ISSUE THREAD

**Issue by skeie** [react-native-community/react-native-tab-view#74]
First off, thanks @satya164! This project is amazing!

I had one question. I would like to have a callback that gets called before a scene is changed. My use case is that I have a header with an icon. And the source of that icon depends on which route my `TabView` is on.

As of now, I use the `onRequestChangeTab` callback, but then the image is not updated until the transition is finished. 
I could potentially hacked it together by using `onChangePosition`. But I rather not. 

So what do you think? Would you accept a PR for this?

**Comment by satya164** [comment]
`onChangePosition` sounds like the good way to go for your use case. Something like,

```
_handleChangePosition = position => {
  if (Number.isInteger(position) {
    // handle your stuff
  }
}
```

Doesn't look very hacky :)

**Comment by skeie** [comment]
Aha, I hadn't thought this through :-). Thanks for the detailed answer.
