### ISSUE TITLE
ViewPagerAndroid has been extracted from react-native core

### ISSUE THREAD

**Issue by naorzr** [react-native-community/react-native-tab-view#741]
Reopening #682

### Current behaviour

Getting warning that ViewPagerAndroid has been extracted from react-native core and will be removed in a future release.

### Expected behaviour

React-native-tab-view to import the ViewPager from the community module instead of rn-core module.

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |
| react-native                 | 0.59.4
| react-native-tab-view        | 2.0.3
| react-native-gesture-handler | 1
| react-native-reanimated      | 1
| node                         | 11.8.0
| npm or yarn                  | 6.9.0

**Comment by satya164** [comment]
The 2.0.3 version doesn't use `ViewPagerAndroid`. try resetting metro cache with `react-native start --reset-cache`
