### ISSUE TITLE
Jumping to tab programmatically not working in iOS

### ISSUE THREAD

**Issue by anirudhramanan** [react-native-community/react-native-tab-view#743]
### Current behaviour

On changing the tab index programmatically, it only changes the tab indicator but not the scene below. The scene still renders the first screen, but the tab indicator points to the current index.

### Expected behaviour

The scene should be updated as well.

### Screenshots (if applicable)

<img width="238" alt="Screenshot 2019-04-13 at 1 34 14 PM" src="https://user-images.githubusercontent.com/16556984/56076591-eb233c80-5df0-11e9-8deb-dbcbff7e2651.png">

### Your Environment

iOS

**Comment by wizebin** [comment]
I can't seem to recreate your issue, the code in this branch works:

https://github.com/wizebin/TabViewVelocityIssue/tree/programmatic-jumping

You could try forking this repo and demonstrating your issue.

**Comment by Buddikazz** [comment]
i also canot move tab programitically with using index in IOS.android work fine.

**Comment by manurana** [comment]
I am also seeing a weird issue with the component not respecting a programmatic tab change only on a iOS device. An iOS emulator, and android (device/emulator) work fine.
Don't know if its related. Will try to set up an example to demonstrate

**Comment by gamingumar** [comment]
Are you using the onIndexChange callback to change your index?

**Comment by anirudhramanan** [comment]
To repro the issue, set the index in the initialState (in the constructor) to second or third tab. The onIndexChange callback is working though.

**Comment by sienkashing** [comment]
I had this issue when the version of react-native-tab-view I was using was v1.3.2.

Upgrading it to v2.2.0 manage to fix the issue for me. (You will need to install [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) for this update.)

**Comment by satya164** [comment]
Closing due to incomplete issue template
