### ISSUE TITLE
tab is not rendered in rtl mode

### ISSUE THREAD

**Issue by elirangoshen** [react-native-community/react-native-tab-view#746]
### Current behaviour
When using rtl, when selecting tabs other then the first one, its not being rendered

### Expected behaviour

When selecting any tab, it should render its view

### Code sample

Thats my tab navigator component: 

```
export const TabStack = createMaterialTopTabNavigator({
  moneyTransfer: { screen: MoneyTransferScreen },
  withdrawal: { screen: WithdrawalScreen },
  pendingRequests: { screen: PendingRequestsScreen },

},
  {
    defaultNavigationOptions: {
      drawerLabel: translate("operations.label"),
    },
    lazy: true,
    tabBarOptions: {
      activeTintColor: color.palette.lightGrey,
      inactiveTintColor: color.palette.lightGrey,
      scrollEnabled: false,
      animationEnabled: false,
      swipeEnabled:false,
      style: {
        backgroundColor: "#212121"
      },
      indicatorStyle: {
        backgroundColor: color.palette.green,
      },
      labelStyle: {
        width: 200,
        color: color.palette.lightGrey,
      },

    },
  })
```

### Screenshots (if applicable)

<img width="383" alt="Screen Shot 2019-04-18 at 11 11 10 AM" src="https://user-images.githubusercontent.com/9560116/56350735-bd147280-61cb-11e9-8025-42136b6a8701.png">

### What have you tried

I tried to set animationEnabled, gestureEnabled and swipeEnabled to false as i read in different issue. 

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios              |    12.2
| react-native                 | 0.59.2
| react-native-tab-view        | 1.3.4
| react-native-gesture-handler | 1.1.0
| react-native-reanimated      | 1.0.0
| node                         | 11.14.0
| npm or yarn                  | 1.15.2

**Comment by elirangoshen** [comment]
by the way, i see there is fix related to rtl in tab view 2.1.0, but im using react navigation tabs and tab view version its still 1.3.4 there

**Comment by elirangoshen** [comment]
Hi, I'd glad if I could get updates on this.

**Comment by satya164** [comment]
Please upgrade to latest `react-navigation-tabs` which uses the new version of `react-native-tab-view`.

**Comment by elirangoshen** [comment]
issue is still occurring, as latest version of the lib uses react-native-tab-view 2.0.3, wheres the fix only added in react-native-tab-view version [2.1.0](https://github.com/react-native-community/react-native-tab-view/releases/tag/v2.1.0)

could you update tab-view to latest version ?

**Comment by satya164** [comment]
I will update soon, but you can use yarn resolutions to force the version https://yarnpkg.com/lang/en/docs/selective-version-resolutions/

**Comment by Abdo-zayed** [comment]
in TabBar.js 
modify this function 
        _this.resetScroll = function (value) {
            const tabLength=this.props.navigationState.routes.length-1;

            const target=I18nManager.isRTL?tabLength-value:value;
            console.log(tabLength+' '+target)
            if (_this.props.scrollEnabled) {
                _this.scrollView && _this.scrollView.scrollTo({
                    x: _this.getScrollAmount(_this.props, _this.state,target),
                    animated: true
                });
            }
        };
