### ISSUE TITLE
tabbar width problem when have many tabbar

### ISSUE THREAD

**Issue by YanYuanFE** [react-native-community/react-native-tab-view#749]
### Current behaviour

I have many tabbar，and tabbar width is not adaptive。 

### Expected behaviour

I expect that the width of the tabbar can be adapted to the content, and that the tabbar beyond the screen width can be hidden and appear when sliding.

### Code sample

`
const { index, routes, languages, loading } = this.state;
    const map = {};
    languages.forEach((language) => {
      const LanguageRoute = () => <PopularTab tabLabel={language.name} />;
      map[language.name] = LanguageRoute;
    });
    return (
      <View style={styles.container}>
        <NavigationBar
          style={{backgroundColor: "#2196F3"}}
          title={'最热'}
          statusBar={{backgroundColor: '#2196F3'}}
        />
        {
          loading ? <ActivityIndicator /> :
            <TabView
              navigationState={{index, routes}}
              renderScene={SceneMap(map)}
              onIndexChange={index => this.setState({ index })}
              initialLayout={{ width: Dimensions.get('window').width }}
              renderTabBar={(props) =>
                <TabBar
                  {...props}
                  indicatorStyle={{ backgroundColor: 'white' }}
                  style={{ backgroundColor: '#2196F3' }}
                  renderLabel={({ route, focused, color }) => (
                    <Text style={{ color: focused ? "#F5F5F5" : color, margin: 0 }}>
                      {route.key}
                    </Text>
                  )}
                />
              }
            />
        }
      </View>
    )
`

### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/17774285/56455443-fe09b400-6390-11e9-968a-e8178cfdacfb.png)

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | ios
| react-native                 | 0.59.3
| react-native-tab-view        | 2.03
| react-native-gesture-handler | 1.1.0
| react-native-reanimated      | 1.0.0
| node                         |  10.13.0
| npm or yarn                  | 6.4.1

**Comment by satya164** [comment]
https://github.com/react-native-community/react-native-tab-view#scrollenabled

**Comment by MuhammadUsman786786** [comment]
you can use 'scrollEnabled' property of TabBar

**Comment by YanYuanFE** [comment]
thanks, good.
