### ISSUE TITLE
How To: Horizontal swipes inside TabViewAnimated

### ISSUE THREAD

**Issue by polmoneys** [react-native-community/react-native-tab-view#75]
Thank you for this component <3 

Trying to solve one problem my guess it's very common without any luck. App has 3 screens, on two of them I'd like to be able to swipe horizontally without changing the screen. On isolation work,but when mixing it with TabViewAnimated both fail.

![screenshot](https://cloud.githubusercontent.com/assets/7026863/20764147/2a355a06-b72d-11e6-926f-b70b7dd64119.png)

(Colored 'squares' at the bottom are inside a horizontal ListView)

![screenshot](https://cloud.githubusercontent.com/assets/7026863/20764146/2a34927e-b72d-11e6-8ec8-97172f98e540.png)

(Each item list should reveal a button on swiping left)

Should I be looking at TabViewPagerPan ? 

Current iteration https://gist.github.com/polmoneys/26cfc57287e9529e098b83e62eb2c93c

**Comment by satya164** [comment]
@polmoneys You probably just want to disable horizontal swiping on tabs? That'd work for you I think

https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/NoAnimationExample.js#L132

**Comment by satya164** [comment]
You could probably conditionally set it like `swipeEnabled={this.state.index === 2}` (if you want swipe to be enabled only on second tab)

**Comment by polmoneys** [comment]
my hope was not to lose horizontal swiping to switch tabs, some sort of checking for the distance of the swipe and decide if 'greater than'. 
thanks for swipeEnabled={this.state.index === 2} this might be the answer, let me try it and get back to you. GRACIAS !

**Comment by satya164** [comment]
@polmoneys 

> my hope was not to lose horizontal swiping to switch tabs, some sort of checking for the distance of the swipe and decide if 'greater than'.

`TabViewPagerPan` does accept a `swipeDistanceThreshold` prop, I'm not sure if it will work with another swipeable element, but worth a try. Though I think this behaviour might be a bit confusing for the user.
