### ISSUE TITLE
Title in navigation bar doesnt change when switching from a tab to another

### ISSUE THREAD

**Issue by edoantonioco** [react-native-community/react-native-tab-view#753]
### Current behaviour

if you have 4 (or any amount) of option in the tab, you can switch between them but the title in the navigation bar wont change

### Expected behaviour

when you select another option into the tab bar (bottom mode), it should also change the text of the navigation bar to the name of the title you set in the routes.
Or at least to have the option.

### Screenshots (if applicable)

this is a screenshot from the example project that is part of this library.

Notice how I selected "Article", but the top bar still says "Custom tab bar"

![WhatsApp Image 2019-04-23 at 10 46 37 PM](https://user-images.githubusercontent.com/5560824/56633170-48ea2c80-661a-11e9-8f00-974c11a710e7.jpeg)

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |android
| react-native                 |expo 32
| react-native-tab-view        |latest
| react-native-gesture-handler |
| react-native-reanimated      |
| node                         |11
| npm or yarn                  |

**Comment by satya164** [comment]
This how the example is written. If you want to change the title, you can do so on `onIndexChange` listener.

**Comment by edoantonioco** [comment]
@satya164 It does works, except when the tab window is the first window you see when you open the app. Once you access another unrelated window and return to the tab view, it is now able to update the title. Before that, it stays with the title you gave it it originally.

(at least when using rnrf)
