### ISSUE TITLE
Use a png image for Icon in Tab bar not Working?

### ISSUE THREAD

**Issue by abhi06991** [react-native-community/react-native-tab-view#756]
### Current behaviour

I am looking to add a png image as icon for individual tabs, but the images are not appearing

### Expected behaviour
 
I would want the images to appear before the text.

I have tried using with Image tag as well as without it, but its not displaying the image
### Code sample
```
detailsIcon: require('../Navigation/images/details-icon.png'),
flightIcon: require('../Navigation/images/flight-icon.png'),
stayIcon: require('../Navigation/images/stay-icon.png'),

  state = {
    index: 0,
    routes: [
      { key: 'first', title: 'Details', icon: <Image source={detailsIcon} /> },
      { key: 'second', title: 'Flights', icon: <Image source={flightIcon} /> },
      { key: 'third', title: 'Stay', icon: <Image source={stayIcon} /> },

    ],
  };

```
Also, without using the Image Tag

```
  state = {
    index: 0,
    routes: [
      { key: 'first', title: 'Details', icon: {detailsIcon}  },
      { key: 'second', title: 'Flights', icon: {flightIcon}  },
      { key: 'third', title: 'Stay', icon: {stayIcon}  },

    ],
  };
```

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | Android
| react-native                 | 0.57.8
| react-native-tab-view        | 2.2.0
| react-native-gesture-handler | 1.1.0
| react-native-reanimated      | 1.0.1
| node                         | v8.9.4
| npm or yarn                  | npm

**Comment by satya164** [comment]
You need to provide a `renderIcon` prop to `TabBar`
https://github.com/react-native-community/react-native-tab-view#rendericon
https://github.com/react-native-community/react-native-tab-view/blob/9fc4ba8cdf18c48899fcf9e7882ba9265b7479f1/example/src/TabBarIconExample.js#L40
