### ISSUE TITLE
onIndexChange has delay

### ISSUE THREAD

**Issue by aliazizi** [react-native-community/react-native-tab-view#758]
### Current behaviour

`onIndexChange` has delay on animation, for example I want to call api to load item when index changed and onIndexChange called after a dely I think this is because of the spring animation.

### Expected behaviour

`onIndexChange` called shortly after index of tab changed.

**Comment by wizebin** [comment]
https://github.com/react-native-community/react-native-tab-view/pull/718

Changes this behavior, but there is some mild controversy about it [here](https://github.com/react-native-community/react-native-tab-view/issues/716#issuecomment-475359336)

**Comment by satya164** [comment]
Duplicate of #716
