### ISSUE TITLE
Please upgrade flow version. There are errors in flow 0.98.o

### ISSUE THREAD

**Issue by vasilich6107** [react-native-community/react-native-tab-view#759]
### Current behaviour

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/react-native-tab-view/src/TabBarItem.js:134:18

Cannot assign renderLabel !== undefined ? renderLabel : (...) => { ... } to renderLabel because in the return value:
 • Either null or undefined [1] is incompatible with null [2].
 • Or property @@iterator is missing in null or undefined [1] but exists in $Iterable [3].

```

### Expected behaviour

No flow errors.

### Your Environment

| software                     | version
| ---------------------------- | -------
| flow-bin               |0.98.0

**Comment by satya164** [comment]
Ideally I want to migrate the library to use TypeScript since Flow keeps breaking every release of React Native, so I don't want to spend energy fixing issues with Flow.

**Comment by satya164** [comment]
Just [migrated the lib to TypeScript](https://github.com/react-native-community/react-native-tab-view/commit/01ba66e244882ce98ac624e82f71f9c43e810378). Closing since I don't use Flow anymore.
