### ISSUE TITLE
error when link react-native-reanimated

### ISSUE THREAD

**Issue by rahultatvasoft** [react-native-community/react-native-tab-view#765]
@satya164  ERR! Something went wrong while linking. Error: ENOENT: no such file or directory, open 'D:\Projects\wamp\www\Reactnative-projects\Quesst\Quesst_Git\ios\quesst.xcodeproj\project.pbxproj'

**Comment by satya164** [comment]
Closing since this doesn't look like a bug in the library. Please open an issue in the https://github.com/react-native-community/react-native-cli repo for issues with linking.
