### ISSUE TITLE
android take to long to switch tab

### ISSUE THREAD

**Issue by cani1see** [react-native-community/react-native-tab-view#769]
### Current behaviour
the ripple effect take to long 

### Expected behaviour
shorter ripple time
### Code sample
`<View style={{width: '100%', flex: 1}}>
                <TabView
                    renderTabBar={this.renderTabBar}
                    navigationState={this.state}
                    renderScene={({route}) => {
                      switch (route.key) {
                        case 'all':
                          return this.renderTab('ALL');
                        case 'send':
                          return this.renderTab('SEND');
                        case 'receive':
                          return this.renderTab('RECEIVE');
                        case 'resource':
                          return this.renderTab('RESOURCE');
                      }
                    }}
                    onIndexChange={index => this.setState({index})}
                    initialLayout={{width: deviceWidth}}
                    swipeEnabled={false}
                    lazy={true}
                >
                </TabView>
              </View>

  renderTabBar = props =>
      <TabBar
          {...props}
          activeColor={'black'}
          inactiveColor={'grey'}
          indicatorStyle={{
            backgroundColor: "#5829DB',
            marginLeft:18,
            width: 20
          }}
          pressColor={'grey'}
          style={{backgroundColor: 'white'}}
          tabStyle={{width: 60}}
      />
`

### Screenshots (if applicable)

https://www.youtube.com/watch?v=H55-V7FdwZ8

### What have you tried
setting timingConfig

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | android
| react-native                 | 0.59.2
| react-native-tab-view        | 2.2.0
| react-native-gesture-handler | 1.1.0
| react-native-reanimated      | 1.0.0
| node                         | 11.6.0
| npm or yarn                  | 1.15.2

**Comment by xaviershay** [comment]
it's probably https://github.com/react-native-community/react-native-tab-view/issues/720

**Comment by satya164** [comment]
can you provide some runnable code? have you followed the tips in https://github.com/react-native-community/react-native-tab-view#optimization-tips ? are you running in production mode or development mode?

also give the latest version a try and let me know if this still happens.

**Comment by cani1see** [comment]
@satya164 I didn't reproduce in dummy project, with almost the same code. I tried to simplify that page to only contain the tabview, problem remains. also I did update react-native to 0.59.8 , and react-native-tab-view to 2.3.0.

**Comment by satya164** [comment]
you didn't answer any of my questions

**Comment by cani1see** [comment]
@satya164 
production mode and development mode both have this problem. 
production mode do have normal ripple time most time, but tab change is after the animation and do have long ripple time once a while.
I still have long ripple time in development mode, while I cannot reproduce it in new project. I will look into it some other time.

**Comment by cani1see** [comment]
@satya164  https://github.com/cani1see/TabViewExample 
It was ok even in development mode, I rerun it today, the problem is back in  development mode, without any code modify. 
production mode mostly ok, but sometimes do have the long ripple time.

**Comment by Frekansapp** [comment]
i have same problem too

**Comment by satya164** [comment]
You haven't followed any instructions from the [Optimization Tips section](https://github.com/react-native-community/react-native-tab-view#optimization-tips). You at least need to make sure your components extend `PureComponent` or implement a `shouldComponentUpdate`. I have already mentioned this link in my comment.
