### ISSUE TITLE
scene opacity animation

### ISSUE THREAD

**Issue by ethicalvats** [react-native-community/react-native-tab-view#770]
### Current behaviour

I am not sure how to track the pan positionX and animate the opacity of the next scene.

### Expected behaviour

I want to achieve an animation on the opacity of the next scene view to fade in with the swipe gesture. The value of opacity must be corresponding to the swipe distance.

### What have you tried
 
Since Tabview uses react-native-gesture-handler and onSwipeStart and onSwipeEnd gives the Gesture events, there must be some way to track the translateX from PanGestureHandler but I am not sure about it, any direction about how to achieve it would be great.

The plugin is awesome <3

**Comment by ethicalvats** [comment]
anyone!!

**Comment by satya164** [comment]
You can interpolate on the `position` prop that you receive in `renderScene`. Example: https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/CoverflowExample.js#L67
