### ISSUE TITLE
Why did you remove addListener on version 2.2.1?

### ISSUE THREAD

**Issue by tamirrab** [react-native-community/react-native-tab-view#775]
Why did you remove addListener on version 2.2.1?
Now we can't listener to position anymore

**Comment by satya164** [comment]
> Why did you remove addListener on version 2.2.1?

The position listener can overload the bridge which I would like to avoid in a built-in API.

> Now we can't listener to position anymore

You still can using `Animated.Code`, it's also more flexible because you can add conditionals etc. to optimize the listener:

```js
<Animated.Code
  exec={Animated.onChange(
    this.props.position,
    Animated.call([this.props.position], ([value]) =>
      console.log('position is', value)
    )
  )}
/>
```

**Comment by tamirrab** [comment]
Do you have any example where to set Animated.Code?
I can't find any syntax for it

**Comment by satya164** [comment]
@tamirrab put it in your `render` in the component where you need to listen to the value

```js
render() {
  return (
    <React.Fragment>
      <Animated.Code ... />
      <RestOfYourStuff />
    </React.Fragment>
  );
}
```

**Comment by satya164** [comment]
Lemme know if this works for you or if you need any help :)

**Comment by tamirrab** [comment]
Sorry but the syntax is really a mess
the console.log not fire when I write your example
it's to bad because I use allot on tab-view and the listener really help

**Comment by satya164** [comment]
> Sorry but the syntax is really a mess

Reanimated syntax is different, but you don't have to manually add and remove listeners in `componentDidMount` and `componentWillUnmount`, and it's much more flexible (for example if you want to throttle the listener, [it's possible now](https://github.com/react-native-community/react-native-tab-view/issues/700#issuecomment-484033080)).

> the console.log not fire when I write your example
> it's to bad because I use allot on tab-view and the listener really help

Here is a snack demonstrating usage of the listener: https://snack.expo.io/H1LrhOF2V

**Comment by tamirrab** [comment]
The demonstrating is on one tab and not on all the tabView
The listener has a full view on the position on each tab as a full container

**Comment by satya164** [comment]
Not sure what you mean by all the tabview, but you can use this snippet as many times as you want. The `position` prop is passed to the same components where you had access to `addListener`, so you can use this snippet in all of the same components.

**Comment by tamirrab** [comment]
It work :)
thank you
