### ISSUE TITLE
Scene componentDidMount call when switching tabs

### ISSUE THREAD

**Issue by Stjng** [react-native-community/react-native-tab-view#777]
Currently componentDidMount is my scene called very time i switching, this will cause my view will add multiple time ( native module ). How to make Scene componentDidMount call once.

**Comment by satya164** [comment]
Please provide code

**Comment by satya164** [comment]
Closing because the library doesn't remount screens, so it's a bug in the user code, and the issue template wasn't filled.

**Comment by Stjng** [comment]
Sorry for late reply, my code is:
```
<TabView 
              navigationState={this.state}
              renderTabBar={this._renderTabBar}
              renderScene={
                SceneMap({
                  call: () => (
                    <CallScreen />
                  ),
                  chat: () => (
                    <ChatScreen messages={this.state.messages}/>
                  ),
                  problem: () => (
                    <ProblemScreen/>
                  )
                })
              }
              onIndexChange={index => this.setState({index})}/>
```
**CallScreen.js**
```
class CallScreen extends React.PureComponent {
  componentDidMount() {
      console.log("Mount)
   }

  componentWillUnmount() {
      console.log("Unmount")
   }
   render () {
      return (
        <View>... </View>
     )
  }
}
```

Everytime im switching to another tabs, componentDidMount and componentWillUnmount inside CallScreen got called. How to prevent this :(

**Comment by Stjng** [comment]
Issue fixed, just read the following note 

> Always define your components elsewhere in the top level of the file. If you pass inline functions, it'll re-create the component every render, which will cause the entire route to unmount and remount every change. It's very bad for performance and will also cause any local state to be lost.

Thanks :D

**Comment by JuanCamilo0809** [comment]
> Issue fixed, just read the following note. My fault.
> 
> > Always define your components elsewhere in the top level of the file. If you pass inline functions, it'll re-create the component every render, which will cause the entire route to unmount and remount every change. It's very bad for performance and will also cause any local state to be lost.
> 
> Thanks :D


Hi, But if you want pass a params from the state, Who do it?

For Example 

`

const Calls = (Calls=[])=> <CallScreen calls={Calls} />

const Chats = (Chats=[])=> <CallScreen chats={Chats} />

export default class PedidoNuevo extends Component<Props> {
state={
Calls:[1,2,3,4,5],
Chats:[43,67]
}

render(){

return (<TabView 
  navigationState={this.state}
  renderTabBar={this._renderTabBar}
  renderScene={
     SceneMap({
           call:Calls,
           chat: Chats,
           problem: () => (
                <ProblemScreen/>
           )
     })
  }
  onIndexChange={index => this.setState({index})}/>)

}





}
`

How to pass this params?

Thanks

**Comment by Stjng** [comment]
Hi @JuanCamilo0809 
If you need to pass additional props, use a custom renderScene function:
Ex:
`renderScene = ({ route }) => {
  switch (route.key) {
    case 'first':
      return <FirstRoute foo={this.props.foo} />;
    case 'second':
      return <SecondRoute />;
    default:
      return null;
  }
};`
