### ISSUE TITLE
How to move item in to center of tabbar when click item 

### ISSUE THREAD

**Issue by nambd-1242** [react-native-community/react-native-tab-view#784]
When I have many item , and I add property  ` scrollEnabled={true}` in `TabBar`
Can you give me property help me move an item into center of `TabBar` when clicking item .
As image , I want move item "First2" into center of  `TabBar`
<img width="247" alt="Screen Shot 2019-05-22 at 5 58 07 PM" src="https://user-images.githubusercontent.com/34257742/58169535-2f8cdc80-7cbb-11e9-8901-9e5c7fed0beb.png">

**Comment by satya164** [comment]
This should happen automatically. Do you have a repro where it doesn't happen?

**Comment by satya164** [comment]
Closing due to no repro
