### ISSUE TITLE
how do I change the default color of the tab, the color blue?

### ISSUE THREAD

**Issue by BrunoLagoa** [react-native-community/react-native-tab-view#787]
how do I change the default color of the tab, the color blue?

```
<TabView
      navigationState={this.state}
      renderScene={SceneMap({
        agenda: this.AgendaRoute,
        detalhes: this.DetalhesRoute
      })}
      onIndexChange={index => this.setState({ index })}
      initialLayout={{ width: Dimensions.get("window").width }}
    />
```

**Comment by Sanjaya94** [comment]
Use **TabBar** Tag,Like this 


     <TabView
                             
                                  tabStyle={[{height: hp(40),}]}
                                  scrollEnabled={true}
                                    navigationState={this.state}
                                    renderScene={SceneMap({
                                        Details: this.FirstRoute,
                                        Schedule: this.SecondRoute,
                                    })}
                                    renderTabBar={props =>
                                        <TabBar
                                          {...props}
                                          indicatorStyle={{ backgroundColor: '#00887A'}}
                                          style={{ backgroundColor: '#ECECEC' }}
                                          labelStyle={{color:'#000000' }}
                                        
                                   
                                        />
                                      }
                                    onIndexChange={index => this.setState({ index })}
                                    initialLayout={{ width: Dimensions.get('window').width,backgroundColor:'#ffffff' }}
                                />

**Comment by pascal-mormin** [comment]
As written in the documentation, styles you can apply to the tabBar are :
**tabStyle**
Style to apply to the individual tab items in the tab bar.

**indicatorStyle**
Style to apply to the active indicator.

**labelStyle**
Style to apply to the tab item label.

**contentContainerStyle**
Style to apply to the inner container for tabs.

**style**
Style to apply to the tab bar container.
