### ISSUE TITLE
scroll view inside the tab view is not working

### ISSUE THREAD

**Issue by karthikeyansundaram2** [react-native-community/react-native-tab-view#789]
# Bug

 the scroll view inside the react-native-tab-view is not working 
I tried both react-native scroll view and react-native-gesture-handler scroll view
But scroll is not working

## Environment info

react-native:0.56
react-native-tab-view:2.3.0
react-native-gesture-handler:1.0.5

React native info output:

Library version: 2.3.0

## Steps To Reproduce

Just create a tab view and inside the tab view create a scroll view and check-->

Describe what you expected to happen:

1. Scroll must work

2. Refresh control must work

**Comment by satya164** [comment]
Closing due to incomplete issue template

**Comment by karthikeyansundaram2** [comment]
<TabView
style={[{ flex: 1 }]}
navigationState={this.state}
renderScene={(route) => this._renderScene(route, this.props)}
renderTabBar={this._renderTabBar}
swipeEnabled={true}
onIndexChange={(index) => this.setState({ index })}
initialLayout={{ width: Dimensions.get('window').width }}
useNativeDriver

  />
inside the route:
<ScrollView
style={styles.leaguesList}
showsVerticalScrollIndicator={false}
refreshControl={<RefreshControl
style={{ backgroundColor: 'transparent' }}
refreshing={this.state.isFetching}
onRefresh={() => { this.onRefresh(); }} />}
>
....
....
</ScrollView>

**Comment by karthikeyansundaram2** [comment]
This is the sample code

I cannot be able to use scroll view inside the tab view 
if used only scroll works or refresh works

**Comment by satya164** [comment]
Please provide runnable code. As you can check in the example that scrollviews work fine https://github.com/react-native-community/react-native-tab-view/tree/master/example

**Comment by karthikeyansundaram2** [comment]
The scroll is working but refresh control is not working

**Comment by satya164** [comment]
Please open a new issue with the issue template + runnable code on https://snack.expo.io so it's easy to debug
