### ISSUE TITLE
Does this work with a large ListView inside each tab view?

### ISSUE THREAD

**Issue by adremalin** [react-native-community/react-native-tab-view#79]
Hi!

I need to have one ListView inside each tabbed view. These will be very big with images etc. Is this compatible with react-native-tab-view? If so, how to add content like a ListView? 

Thanks!

**Comment by satya164** [comment]
It works with any kind of content. Please check the examples folder which includes an example for ListView.

**Comment by adremalin** [comment]
I found it! Wow, you have done some great coding. Very good code. Will definitely recommend this to more people. Thanks!

**Comment by satya164** [comment]
@adremalin Thank you 😁
