### ISSUE TITLE
How to add a collapsible header

### ISSUE THREAD

**Issue by chenhuaxian** [react-native-community/react-native-tab-view#791]

**Comment by tyuwan** [comment]
Please let me know if you found a solution.

**Comment by satya164** [comment]
closing the issue since it's not a bug in the library. feel free to continue discussing.

**Comment by zyslife** [comment]
@chenhuaxian @tyuwan 
You can try the [react-native-head-tab-view.](https://github.com/zyslife/react-native-head-tab-view)
(tabs with collapsible header)
