### ISSUE TITLE
Keep footer fixed at the bottom of the screen when keyboard opens in android

### ISSUE THREAD

**Issue by imrahulpatel** [react-native-community/react-native-tab-view#794]
Is there any way this can be accomplished? I tried setting position: absolute; but it seems like the tabs keep wanting to move upwards with keyboard
![image](https://user-images.githubusercontent.com/9443277/58966903-c3d56400-87d0-11e9-9876-a74fa2a016d6.png)

**Comment by satya164** [comment]
You need to listen to keyboard events and hide the tab bar manually.

https://facebook.github.io/react-native/docs/keyboard#methods
