### ISSUE TITLE
Tab indicator only moves on double tap

### ISSUE THREAD

**Issue by ozgepoundandgrain** [react-native-community/react-native-tab-view#798]
# Tab indicator only moves on double tap
http://g.recordit.co/jve9Xh2rdm.gif

The indicator for the active tab does not move when I tap on a tab once. It only moves when I tap on a tab twice.

## Environment info

react-native-cli: 2.0.1
react-native: 0.57.1
"react-native-tab-view": "^2.5.0"

#Code

```
class Home extends React.Component {
  constructor(props){
    super(props);

    this.state = {
   .........

      routes: [
        { key: 'first', title: 'Vision Board' },
        { key: 'second', title: 'Affirm' },
      ],
    }

    // this.pressTab = this.pressTab.bind(this)
  }

  render() {
    console.log(this.state)
    return (
      <DrawerComponent {...this.props}>
      <TabView
        renderTabBar={props =>
          <TabBar
            labelStyle={{color: 'black'}}
            bounces
            {...props}
            indicatorStyle={{ backgroundColor: 'black' }}
            style={styles.tabStyle}
            renderLabel={SceneMap({
              'first': () => <Text>Vision board</Text>,
              'second': () => <Text>Affirm</Text>
            })
            }
          />
        }
        navigationState={this.state}
        renderScene={SceneMap({
          'first': () => <ScrollView style={styles.scrollView}>
          {this.state.visions ?
          <FlatList
            keyExtractor={(item, index) => index}
            numColumns={2}
            data={this.state.visions}
            renderItem={this._renderVision}
        />
        :
        <Text>nothing</Text>
          }
        </ScrollView>,
          'second': () =>   <ScrollView style={styles.scrollView}>
          <View style={styles.innerScroll}>
          <FlatList
            keyExtractor={(item, index) => index.toString()}
            numColumns={1}
            data={this.state.mantras}
            renderItem={this._renderData}
            />
          </View>
        </ScrollView>,
        })}
        onIndexChange={index => this.setState({ index })}
        initialLayout={{ width: Dimensions.get('window').width }}
      />
      </DrawerComponent>
    )
  }
}
```

**Comment by satya164** [comment]
Please provide a runnable repro on https://snack.expo.io

Also please avoid inline components as mentioned in the README

![image](https://user-images.githubusercontent.com/1174278/59151772-39dc0400-8a39-11e9-9f53-a1891cbc3b48.png)

**Comment by ozgecokyasar** [comment]
@satya164 
https://snack.expo.io/@git/github.com/ozgecokyasar/mani-react
the code doesn't seem to compile because of an error related to react-native-tab-view

**Comment by winrox** [comment]
For what it's worth, I am seeing something similar. I have forms in my tabs, and when a form has focus, only swipe works for me to change tabs, and touch and double touch have no effect. Once the form no longer has focus, all of touch events work again.

**Comment by anhnh27** [comment]
Did you solve this?

**Comment by ozgepoundandgrain** [comment]
@anhnh27 take a look at this other issue opened by someone else 
https://github.com/react-native-community/react-native-tab-view/issues/809

**Comment by ozgepoundandgrain** [comment]
@winrox  take a look at this issue opened by someone else:
https://github.com/react-native-community/react-native-tab-view/issues/809

**Comment by ozgepoundandgrain** [comment]
@anhnh27 still trying to figure it out unfortunately

**Comment by satya164** [comment]
Closing since no repro was provided.
