### ISSUE TITLE
Android, swipe left-right not triggering tab change.

### ISSUE THREAD

**Issue by AndriiUhryn** [react-native-community/react-native-tab-view#799]
Android, swipe left-right not triggering tab change.
Each Tab item is a ScrollView. I guess it's because of that. Is there a chance to force it work same as on IOS (that is working fine even with Scroll View as a child).

**Comment by wazave** [comment]
I am having the same issue.

**Comment by AndriiUhryn** [comment]
I figure it out, You need to follow steps described here: https://reactnavigation.org/docs/en/getting-started.html
![Screenshot (13)](https://user-images.githubusercontent.com/22635238/59307704-c8ee5380-8ca7-11e9-9ac6-690007d9e95c.png)

**Comment by wazave** [comment]
> I figure it out, You need to follow steps described here: https://reactnavigation.org/docs/en/getting-started.html
> ![Screenshot (13)](https://user-images.githubusercontent.com/22635238/59307704-c8ee5380-8ca7-11e9-9ac6-690007d9e95c.png)

Thank you so much! (:
