### ISSUE TITLE
How to do optimization with renderScene?

### ISSUE THREAD

**Issue by viettranme** [react-native-community/react-native-tab-view#80]
Hello,

In the [optimization tips](https://github.com/react-native-community/react-native-tab-view#optimization-tips), there's the instruction to move the renderScene to a separate component and apply  shouldComponentUpdate to prevent unnecessary re-renders. I have tried with different codes but they still not working. The UI is not updated as the function shouldComponentUpdate returns false.

My code is as below:

```
class TabViewExample extends React.Component {
  constructor(props, context) {
    super(props, context);
    
    this.state = {
      index: 0,
      routes: [
        { key: 'FooScreen', title: 'Foo'},
        { key: 'BarScreen', title: 'Bar'},
      ],      
    };
  }

  _handleChangeTab = (index) => {
    this.setState({
      index,
    });
  };
  
  render() {
    return (
      <View style={styles.container}>
        <MySeparateComponent
          style={{ flex: 1 }}
          navigationState={this.state}
          onRequestChangeTab={this._handleChangeTab}
        />        
      </View>
    );
  }
}

//////////////////////////////////

class MySeparateComponent extends React.Component {
  constructor(props, context) {
    super(props, context);
  }

  shouldComponentUpdate(nextProps, nextState) {
    return false;
  }
  
  _renderScene = ({route}) => {
    let ComponentClass = RouteHelper.resolveComponentClass(route.key);
    return <ComponentClass/>;
  };

  render() {
    return (
      <View style={styles.container}>
        <TabViewAnimated
          style={{ flex: 1 }}
          navigationState={this.props.navigationState}
          renderScene={this._renderScene}
          onRequestChangeTab={this.props.onRequestChangeTab}
        />        
      </View>
    );
  }
}
```

I am not sure if this code correctly follows the optimization instruction. Please help! 

Thanks

**Comment by satya164** [comment]
I meant that instead of inlining the view logic for each route in `renderScene`, separate each route into a `PureComponent`. In your code, `ComponentClass` should be a pure component. No need for a separate `MySeparateComponent` component.

**Comment by viettranme** [comment]
Thanks for your feedback. It seems that the problem is still there. The function renderScene is called many times when the tab index is changed, and leads to multiple expensive view re-rendering. Could you please give a code sample to clarify your optimization instruction? Thanks

**Comment by viettranme** [comment]
I have solved this. Code for reference as below:

`
class TabViewExample extends React.Component {
...
 _renderScene = ({route}) => {
    // Resolve to a component, for example like the MyPureComponent below
    let ComponentClass = RouteHelper.resolveComponentClass(route.key);
    return <ComponentClass/>;
  };
...
}

class MyPureComponent extends React.Component {
  shouldComponentUpdate(nextProps, nextState) {
    return false;
  }
  
  render() {
    return (
      <View style={{flex: 1}}>
        <Text>A sample view</Text>
      </View>
    );
  }
}
`

**Comment by satya164** [comment]
Glad you figured it out! Any suggestions what I should write so its more obvious?

**Comment by sun2rise** [comment]
I'm sorry @satya164 what do you mean exactly for `PureComponent` it has to be stateless?

**Comment by wellingtondessuy** [comment]
I have a similar problem. Every time that a state is updated all tabs are rebuilt, renderScene is called once for each tab. Any help??

**Comment by sun2rise** [comment]
@wellingtondessuy  I figured it out.. my previous snippet was wrong!
I had to use `PureComponent` just form the react library or shouldComponentUpdate function will never be fired!
the correct example:

```js
import React, { PureComponent } from 'react';

class MyComponent extends PureComponent {
  shouldComponentUpdate(nextProps, nextState) {
    // use some logic here to prevent updates
    // for example here, with the help of lodash library i can detect a real change
    // in the props object and prevent the update if nothing really changed inside
    // the object
    // return !_.isEqual(this.props.data, nextProps.data);

    return false;
  }

  render () {
    return <div>PureComponent: it updates only when i say</div>;
  }
}

**Comment by satya164** [comment]
@sun2rise you should avoid doing deep equality checks (e.g. - `_.isEqual`) and prefer shallow equality checks (like `PureComponent` does, or this library [shallowequal](https://www.npmjs.com/package/shallowequal)). Deep equality checks can hurt performance when the content actually needs to re-render.

As of latest version, you can use `SceneMap` which automatically does this optimization so that you don't have to think about it.

```js
  _renderScene = SceneMap({
    'first': FirstRoute,
    'second': SecondRoute,
  });
```

**Comment by sun2rise** [comment]
thank you @satya164 , I think you're right, I will follow your advice!
