### ISSUE TITLE
How i do remove the transition effect ?

### ISSUE THREAD

**Issue by Wilson-Lim** [react-native-community/react-native-tab-view#801]
# Question

How i do remove the transition effect ? 
currently using ^2.5.0

**Comment by satya164** [comment]
https://github.com/react-native-community/react-native-tab-view#timingconfig

```js
timingConfig={{ duration: 0 }}
```

**Comment by z252383898** [comment]
> https://github.com/react-native-community/react-native-tab-view#timingconfig
> 
> ```js
> timingConfig = {{duration ： 0 }}
> ```

but i still see transition effect, although very brief
