### ISSUE TITLE
Nested TabView inside a Scene of a TabView, TabBar press of the parent doesnt work.

### ISSUE THREAD

**Issue by mgcostaParedes** [react-native-community/react-native-tab-view#807]
# Bug

Once i create a tabview inside a scene of another tabview(parent), when i jump to the nested tabview and modify the scene, the parent tabBar press doesnt work anymore, however the swipe stills working, this only happens when i modify the scene of this nested tabview.

## Environment info

react = 16.8.3
react-native = 0.59.9
expo = 33.0.6

## Steps To Reproduce

![tabview](https://user-images.githubusercontent.com/16031444/59671219-35d88080-91b5-11e9-9ccb-240d80a8a5c6.gif)

## Reproducible sample code

Parent TabView =
```javascript 
  <TabView
   navigationState={this.state}
   renderTabBar={props =>
       <TabMenu props={props} renderIcon={this._renderIcon} />
   }
   renderScene={this._renderScene}
   onIndexChange={index => this.setState({ index })}
   initialLayout={{ width: Dimensions.get('window').width, height: Dimensions.get('window').height }}
   useNativeDriver removeClippedSubviews={true} lazy={true}
   renderPager={(props) => <PagerScroll {...props}/>}  />
```

Nested TabView =
```javascript 
  <TabView navigationState={this.state}
   renderTabBar={props =>
         <SubTabMenu props={props} renderIcon={this._renderIcon} />
    }
   renderScene={this._renderScene}
   onIndexChange={index => this.setState({ index })}
   initialLayout={{ width: Dimensions.get('window').width, height: Dimensions.get('window').height }} />
```

**Comment by satya164** [comment]
Hey! What's your version of `react-native-tab-view`?

**Comment by jian-leopoldo** [comment]
I have the same problem, in my case, I'm not using nested tabs but still not working.

**Comment by satya164** [comment]
closing due to incomplete info about environment and no runnable repro.
