### ISSUE TITLE
Lazy load working wrong.

### ISSUE THREAD

**Issue by Donhv** [react-native-community/react-native-tab-view#813]
I have a tab with 3 screen. i set lazy loading for it.
when i from screen 1 -> 3 screen 2 auto render. (or when i from 1->2 then 2->1 screen 3 auto render). 
I think when stand in screen index then navigate to any screen it auto call screen index+1( although nerver focus screen index+1)
My Tab view: 
 `<TabView
                                navigationState={this.state}
                                renderScene={this.renderStepView}
                                lazy={true}
                                swipeEnabled={false}
                                onIndexChange={index => this.setState({ index })}
                                // renderTabBar={() => <View style={{ height: 0 }} />}
                                initialLayout={{ width: Dimensions.get('window').width }} />`
    "react-native-tab-view": "^2.6.0",
    "react-native": "0.59.5",

**Comment by satya164** [comment]
I can't repro this issue. Please open a new issue with a runnable repro if you believe there's a bug in the library.

**Comment by wenkangzhou** [comment]
same issue,any progress?
