### ISSUE TITLE
IOS App crashes : unable to use the package 

### ISSUE THREAD

**Issue by c-ancia** [react-native-community/react-native-tab-view#814]
### Current behaviour

The app works properly on Android but crashes on IOS when I try to open it. I installed the package and followed all the installation steps. 

### Expected behaviour

I would like to use this library, especially that it works properly on android.

### Screenshots

![Screenshot 2019-06-20 at 17 14 43](https://user-images.githubusercontent.com/8183242/59864602-155c2200-937f-11e9-94e1-fdcf52bbc252.png)

### What have you tried

I tried to unlink the 2 dependencies and uninstall the package and then reinstalled it and relinked the 2 dependencies (react-native-reanimated & react-native-gesture-handler) but still the same error occurs. I am not using expo.

### Your Environment

| software                     | version
| ---------------------------- | -------
| react-native                 | 0.59.9
| react-native-tab-view        | 2.5.0
| react-native-gesture-handler | 1.3.0
| react-native-reanimated      | 1.1.0
| node                         | 12.4.0

**Comment by satya164** [comment]
looks like an issue with metro, unrelated to the library

**Comment by c-ancia** [comment]
Sure, but still it happens once I install the library, otherwise it works fine...

**Comment by sushilbansal** [comment]
getting similar issue with this package.
