### ISSUE TITLE
Tab View scroll enabled not working

### ISSUE THREAD

**Issue by nileshmean** [react-native-community/react-native-tab-view#815]
### Current behaviour
I have 7 tab view items and the screen work fine just the tab view items are not scrolling horizontally all my test breaks in multiple lines instead scrolling. 

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |
| react-native                 |
| react-native-tab-view        |
| react-native-gesture-handler |
| react-native-reanimated      |
| node                         |
| npm or yarn                  |

**Comment by satya164** [comment]
Please refer to the documentation and examples in the repo.

Closing due to incomplete issue template.
