### ISSUE TITLE
Any way to hide tab bar?

### ISSUE THREAD

**Issue by wildQueequeg** [react-native-community/react-native-tab-view#82]
Is there any way to hide tab bar in child views? For example if I go to a camera view, is there anyway I can hide it there?

I have an app with three tabs A, B, C. In tab C's root view navigates to a camera view which is where I want to hide the tab bar.

**Comment by satya164** [comment]
@wildQueequeg can you describe a bit more? if you don't want a tab bar, you can just avoid passing a `renderHeader` prop.

**Comment by wildQueequeg** [comment]
I added a state to the TabView hideTabBar and passed a callback to other views to toggle it. Is this the best approach?

**Comment by satya164** [comment]
@wildQueequeg sounds good to me

**Comment by TheCodeTalker** [comment]
@wildQueequeg is it working for you. i am wanted do the same thing. can post that approach how to do that.

**Comment by wildQueequeg** [comment]
@TheCodeTalker In your component that renders the TabBar, you can add a state `hideTabBar` and use this to determine whether or not the renderHeader is displayed. Add a function to toggle that state and pass it to your views.

**Comment by furysheep** [comment]
@administerspice Doesn't it cause the tab scenes to rerender? The whole component is being reloaded.
