### ISSUE TITLE
Remove default bottom border?

### ISSUE THREAD

**Issue by karanpratapsingh** [react-native-community/react-native-tab-view#828]
Hey, can somebody help me to remove the bottom border on the tab view?

![Screenshot 2019-07-01 at 1 13 54 PM](https://user-images.githubusercontent.com/29705703/60419154-3dab1280-9c02-11e9-8ebd-00d44598f2a7.png)

**Comment by karanpratapsingh** [comment]
It's not border, it's acutally shadow,

You can remove using this: 

```
<Tabview
...
style={{
 shadowOffset: { height: 0, width: 0 }, 
shadowColor: 'transparent',
 shadowOpacity: 0,
 elevation: 0 
}}
/>

```

**Comment by springkjw** [comment]
If you use renderTabbar Props, Default Bottom Style is in TabBar Component. So you should pass pass props style in TabBarComponent.

`
<TabView
...
  renderTabBar={props =>
   <TabBar
     style={{
       shadowOffset: { height: 0, width: 0 }, 
       shadowColor: 'transparent',
       shadowOpacity: 0,
       elevation: 0 
     }}
   />
 }
/>
`

**Comment by VSV6** [comment]
@springkjw thanks man it really worked for me. I was been looking for a whole day just for this. Now it has been solved. Thank you so much! And I think just ` elevation: 0 ` this one is enough to take out the tab bar shadow.

**Comment by nhanpdnguyen** [comment]
Was finding a solution for Android version and `elevation: 0` has worked ✅
