### ISSUE TITLE
can't dynamic change Tablabel fonsize

### ISSUE THREAD

**Issue by chen504554911** [react-native-community/react-native-tab-view#829]
dynamic change Tablabel fonsize and it will incomplete display.

<TabView
        navigationState={tabRoute}
        renderScene={SceneMap({
          troubleTicket: () => (<WaitDoneInfo />),
          requestSupport: () => (<WaitDoneInfo />),
          commandMission: () => (<WaitDoneInfo />),
          onSiteAcceptance: () => (<WaitDoneInfo />),
          riskOperation: () => (<WaitDoneInfo />),
          onSiteCooperation: () => (<WaitDoneInfo />),
          businessOpening: () => (<WaitDoneInfo />),
          resourceChange: () => (<WaitDoneInfo />),
          jobPlan: () => (<WaitDoneInfo />),
        })}
        renderTabBar={props =>
          <TabBar
            {...props}
            style={styles.tabViewStyle}
            tabStyle={styles.tabBarStyle}
            scrollEnabled={true}
            renderIndicator={() => (null)}
            renderLabel={({ route, focused, color }) => {
              if (focused)
                return (
                  <Text style={{ color, fontSize: 17 }}>
                    {route.title}
                  </Text>
                )
              return (
                <Text style={{ color, fontSize: 14 }}>
                  {route.title}
                </Text>
              )
            }}
          />
        }
        onIndexChange={this.onTabChange}
        initialLayout={{ width: Dimensions.get('window').width }}
        lazy
      />

**Comment by chakrihacker** [comment]
The code you have written is wrong, you have to close Text tag
Closing as it's not an issue

**Comment by chen504554911** [comment]
`<TabView
        navigationState={tabRoute}
        renderScene={SceneMap({
          troubleTicket: () => (<WaitDoneInfo />),
          requestSupport: () => (<WaitDoneInfo />),
          commandMission: () => (<WaitDoneInfo />),
          onSiteAcceptance: () => (<WaitDoneInfo />),
          riskOperation: () => (<WaitDoneInfo />),
          onSiteCooperation: () => (<WaitDoneInfo />),
          businessOpening: () => (<WaitDoneInfo />),
          resourceChange: () => (<WaitDoneInfo />),
          jobPlan: () => (<WaitDoneInfo />),
        })}
        renderTabBar={props =>
          <TabBar
            {...props}
            style={styles.tabViewStyle}
            tabStyle={styles.tabBarStyle}
            scrollEnabled={true}
            renderIndicator={() => (null)}
            renderLabel={({ route, focused, color }) => {
              if (focused)
                return (
                  <Text style={{ color, fontSize: 15 }}>
                    {route.title}
                  </Text>
                )
              return (
                <Text style={{ color, fontSize: 15 }}>
                  {route.title}
                </Text>
              )
            }}
          />
        }
        onIndexChange={this.onTabChange}
        initialLayout={{ width: Dimensions.get('window').width }}
        lazy
      />`

it is wrong? i mean how can i dynamic change Tab label fonsize

**Comment by chakrihacker** [comment]
fontSize is same for both focused and non focused elements!!

**Comment by chen504554911** [comment]
`renderTabBar={props =>
          <TabBar
            {...props}
            style={styles.tabViewStyle}
            tabStyle={styles.tabBarStyle}
            scrollEnabled={true}
            renderIndicator={() => (null)}
            labelStyle={{ fontSize: 17 }}
            renderLabel={({ route, focused, color }) => {
              if (!focused)
                return (
                  <Text style={{ color, fontSize: 14 }}>
                    {route.title}
                  </Text>
                )
              return (
                <Text style={{ color, fontSize: 17 }}>
                  {route.title}
                </Text>
              )
            }}
          />
        }
        onIndexChange={this.onTabChange}
        initialLayout={{ width: Dimensions.get('window').width }}
        lazy
      />`
sorry,my code ，In fact, this is the case。so fontSize can change? i changed and Showing a bit of a problem

**Comment by chen504554911** [comment]
![IMG_20190701_211845](https://user-images.githubusercontent.com/24787299/60439867-2726aa80-9c46-11e9-8308-8abf66877419.jpg)

**Comment by satya164** [comment]
You can set custom height and width in `tabStyle` to make sure your text fits.

**Comment by chen504554911** [comment]
I set custom height and width,but i does't work.

**Comment by chen504554911** [comment]
`tabBarStyle: {
    width: Dimensions.get('window').width / 2,
    height: 100
  },`
![IMG_20190701_213522](https://user-images.githubusercontent.com/24787299/60441160-014ed500-9c49-11e9-87f4-804b5b433179.jpg)

**Comment by 349989153** [comment]
```
renderLabel={({ route, focused, color }) => {
  if (focused){
    return <Text style={{ color, fontSize: 15, minWidth: 100, textAlign: 'center' }}> {route.title} </Text>;
  }
  return <Text style={{ color, fontSize: 15, minWidth: 100, textAlign: 'center' }}> {route.title} </Text>;
}}
```
Try to give a minWidth to the Text element. @chen504554911

**Comment by whereiscode** [comment]
@chakrihacker Your answer doesn't mean anything to solve the problem. You can't solve the problem. By closing the problem, you close the opportunity for others to solve the problem

**Comment by ajithes1** [comment]
`<TabBar
       {...props}
       renderLabel={this._renderLabel}
 />   
`

`_renderLabel = ({ route, focused }) => {
        if (focused) {
            return <Text style={{ fontSize: 15 }}> {route.title} </Text>;
        }
        return <Text style={{ fontSize: 18 }}> {route.title} </Text>;
    }`
