### ISSUE TITLE
Transition is not optimal when jumping multiple tabs

### ISSUE THREAD

**Issue by bevkoski** [react-native-community/react-native-tab-view#83]
When tapping on a tab located multiple tabs farther away from the current one, the transition is not very smooth. It hops once or twice before settling in the correct position.

It can be reproduced using one of the examples provided (https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/TopBarTextExample.js). I also made a GIF in order to illustrate this more clearly.

![jumping-tabs](https://cloud.githubusercontent.com/assets/6344196/21051504/e24ad1b2-be20-11e6-9967-e2ed2964214e.gif)

**Comment by bevkoski** [comment]
Isn't the following a simple fix for this issue?

In TabBar.js:
```
<TouchableItem
  borderless
  key={route.key}
  style={styles.tab}
  pressColor={this.props.pressColor}
  activeOpacity={this.props.activeOpacity}
  delayPressIn={0}
  onPress={() => { // eslint-disable-line react/jsx-no-bind
    const { onTabPress, jumpToIndex } = this.props;
    this._resetScrollOffset(this.props); // FIX
    jumpToIndex(i);
    if (onTabPress) {
      onTabPress(routes[i]);
    }
  }}
>
```

This is the result:

![issue-83-possible-fix](https://cloud.githubusercontent.com/assets/6344196/21081716/ba974ec2-bfcc-11e6-9802-cc7868f420ed.gif)

@satya164, please let me know if you have some better ideas or if I should submit a pull request.

**Comment by satya164** [comment]
Hmm... Seems my comment didn't go through.

In your fix it kinda looks weird. It doesn't jump, but I can't follow the animation. It goes to left then transitions back to right (?)

Probably because `this._resetScrollOffset(this.props);` resets the offset with current navigation state, when we actually want it to be the next navigation state.

Though I don't get why it jumps in the first place, we're not doing anything to scrollview when you press. And the second jump is just a `scrollTo` on the scrollview, and for some reason it's not animated. I think we need to figure out why not.

**Comment by bevkoski** [comment]
I slowed down the animation so that we can see the difference more clearly.

Without the fix:
- The position that it transitions to includes the ```this._scrollOffset```
- It then resets the offset in order to settle in the correct location, which results in a sudden hop

![fix-no](https://cloud.githubusercontent.com/assets/6344196/21095067/1f3b61e6-c05a-11e6-87c2-73547bed9524.gif)

With the fix:
- The ```this._scrollOffset``` is first reset
- The animation then starts from the previously selected tab
- The animation ends at the currently selected tab, which results in a smoother experience, with no hops

![fix-yes](https://cloud.githubusercontent.com/assets/6344196/21095252/e593aff6-c05a-11e6-83bd-3184b9969139.gif)

I know that it's not perfect. Ideally, ```this._scrollOffset``` should be reset without affecting the position of the scroll view and then the animation should start from that position and end at the newly selected tab. I'll try to implement a better solution, based on this idea. Any help would be appreciated.

**Comment by satya164** [comment]
With the changes, it still jumps, except it's not very noticeable. I think the first step in fixing this would be to figure out why the jumps occur, and then figure out how to fix them.

**Comment by lingard** [comment]
I solved this by adding a listener to the animated position prop instead of using this.props.subscribe, eg:

TabBar.js

```javascript
  componentDidMount() {
    this._adjustScroll(this.props.navigationState.index)
    this._positionListener = this.props.position.addListener(this._adjustScroll)
  }
```

instead of:

```javascript
  componentDidMount() {
    this._adjustScroll(this.props.navigationState.index)
    this._positionListener = this.props.subscribe('position', this._adjustScroll)
  }
```

Maybe it's not optimal but it works for me.

**Comment by satya164** [comment]
Hmm... That's weird

**Comment by CharlesMangwa** [comment]
I'm pretty sure this will be solved when we'll merge this branch https://github.com/react-native-community/react-native-tab-view/tree/native-animation 😏…
