### ISSUE TITLE
swipe enabled ={true} not swipe between tabs

### ISSUE THREAD

**Issue by yrjwcharm** [react-native-community/react-native-tab-view#835]
![image](https://user-images.githubusercontent.com/34397383/61016661-fcb1bb80-a3c2-11e9-9a08-8a3a4e9289bd.png)

**Comment by sfshine** [comment]
IMPORTANT: There are additional steps required for react-native-gesture-handler on Android after linking. Check the this guide to complete the installation.

**Comment by yrjwcharm** [comment]
![image](https://user-images.githubusercontent.com/34397383/61181676-17eb2800-a65c-11e9-9dc3-af53595c33f0.png)

**Comment by yrjwcharm** [comment]
Just  Add the Above .
@sfshine  You are the best!!  I solve it.
