### ISSUE TITLE
TabPage always create when changing page

### ISSUE THREAD

**Issue by sfshine** [react-native-community/react-native-tab-view#838]
### Current behaviour

TabPage(Pages in TabView) always create when changing page  ,and even recreate when it is invisiable

### Expected behaviour

TabPage only create when it first show to user, and cache next time

### Code sample

class HomeScreen extends React.Component {
    state = {
        index: 0,
        routes: [
            {key: 'timeline', title: '关注'},
            {key: 'public', title: '广场'},
        ],
    };

    componentWillMount() {
        console.log('HomeScreen componentWillMount', this.props);
    }

    render() {
        const {theme} = this.props;
        let statusBar = {
            backgroundColor: theme.themeColor,
            barStyle: 'light-content',
        };
        let navigationBar = <NavigationBar//app标题栏
            title={'主页'}
            statusBar={statusBar}//状态栏配置
            style={theme.styles.navBar}//颜色遵循主题的
        />;

        const TimeLineRoute = () => <TimelinePage tabLabel="timeline" type="timeline"/>;
        const PublicRoute = () => <PublicPage tabLabel="public" type="public"/>;

        return <View style={styles.container}>
            {navigationBar}
            <TabView
                swipeEnabled={true}
                lazy={true}
                // lazyPreloadDistance={2}
                removeClippedSubviews={false}
                navigationState={this.state}
                renderScene={SceneMap({
                    timeline: TimeLineRoute,
                    public: PublicRoute,
                })}

                onIndexChange={index => this.setState({index})}
                initialLayout={{width: Dimensions.get('window').width}}
                renderTabBar={(props) =>
                    <TabBar
                        {...props}
                        indicatorStyle={{backgroundColor: 'white'}}
                        style={{backgroundColor: theme.styles.selectedTitleStyle.color}}
                        renderLabel={({route, focused, color}) => (
                            <Text style={{fontSize: 14, height: 17, color: focused ? 'white' : color, margin: 0}}>
                                {route.title}
                            </Text>
                        )}
                    />
                }
            >
            </TabView>
        </View>
    }
}
### Screenshots (if applicable)
when changine to next tab, the construstor of the first tab was invoked!

![image](https://user-images.githubusercontent.com/3046831/61170522-173f8c80-a59d-11e9-83ef-6233e849261f.png)

### What have you tried

Too many searches

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | android 
| react-native                 | 0.58.0-rc.1
| react-native-tab-view        | "2.8.0",
| react-native-gesture-handler | "1.3.0",
| react-native-reanimated      | "1.0.0-alpha.12",
| node                         |  10
| npm or yarn                  | yarn

**Comment by satya164** [comment]
Don't create components in render. In the README we explicitly mention this.
