### ISSUE TITLE
Unknown named module: 'react-native-tab-view'

### ISSUE THREAD

**Issue by PuYart** [react-native-community/react-native-tab-view#84]
I just copy the Example code in README, but it doesn't work... Please help me.

react-native: 0.39.1

<img width="476" alt="2016-12-10 16 51 59" src="https://cloud.githubusercontent.com/assets/13675762/21072322/0199b596-bef9-11e6-9055-ac2965760f64.png">

**Comment by satya164** [comment]
Did you install it first? `npm install -S react-native-tab-view react-addons-shallow-compare`?

**Comment by PuYart** [comment]
sure... I have installed them and checked them in node_modules...
it seems that something happens on my React Native. any modules I installed throw this error.

**Comment by Duhonghao** [comment]
how to solve this problem . When i import socket.io in my node ,it occoured the same problem.
