### ISSUE TITLE
Dynamic Width auto not working

### ISSUE THREAD

**Issue by vikramkh** [react-native-community/react-native-tab-view#840]
At first, when I updated it yesterday, it was working fine, but all of a sudden it started to have bugs even though I did not change anything. This is the code:
![image](https://user-images.githubusercontent.com/22332387/61177073-5d472100-a59a-11e9-9b35-ec06270b43e6.png)
![image](https://user-images.githubusercontent.com/22332387/61177099-fb3aeb80-a59a-11e9-9838-3c2665b3f978.png)
![image](https://user-images.githubusercontent.com/22332387/61177106-23c2e580-a59b-11e9-8667-60815b793ade.png)
The indicator is not adjusting to the width of the tabs, and is overlapping between two different tabs

**Comment by satya164** [comment]
Can you post a runnable repro as per the issue template?

**Comment by vikramkh** [comment]
Very sorry, I'm a bit unfamiliar with those terms.  You mean like a video recording of the app running?

**Comment by vikramkh** [comment]
Also this is the dependency:
![image](https://user-images.githubusercontent.com/22332387/61177130-a5b30e80-a59b-11e9-8823-d76ef58271db.png)

**Comment by satya164** [comment]
Minimal code which I can run to see the issue. Ideally on https://snack.expo.io or in a GitHub repo.

**Comment by vikramkh** [comment]
What is super strange is that, I ran an npm update for ^2.9.0 and it stopped now.

**Comment by quicksilverr** [comment]
It's still persisting for me.
