### ISSUE TITLE
Whether the indicator width can be set to a shorter centered property？

### ISSUE THREAD

**Issue by yrjwcharm** [react-native-community/react-native-tab-view#841]
![image](https://user-images.githubusercontent.com/34397383/61181759-ef176280-a65c-11e9-942f-e7da2d4b38cc.png)

**Comment by yrjwcharm** [comment]
It is now spread across the entire width

**Comment by yrjwcharm** [comment]
what ?No One can solve it?

**Comment by yrjwcharm** [comment]
Fuck !!!!

**Comment by BunHouth** [comment]
> what ?No One can solve it?
Do you want to display like this?
<img width="479" alt="Screen Shot 2019-07-24 at 2 59 15 PM" src="https://user-images.githubusercontent.com/8031851/61775732-acefdd00-ae23-11e9-82c8-a2d410674c97.png">

**Comment by yrjwcharm** [comment]
@BunHouth  是的

**Comment by yrjwcharm** [comment]
@BunHouth  auto center

**Comment by BunHouth** [comment]
> @BunHouth auto center

you can check here.  
https://github.com/BunHouth/RNTabExample

**Comment by yrjwcharm** [comment]
![image](https://user-images.githubusercontent.com/34397383/62289717-fe3a4500-b491-11e9-8a74-9b8df1ce21b4.png)

**Comment by BunHouth** [comment]
@yrjwcharm please kindly show me your code snippet.  
The issue is you are trying to using Hooks methods inside class component.

**Comment by bookjan** [comment]
Hi, I share an example of the indicator width wrap the content width.

![Aug-08-2019 11-42-07](https://user-images.githubusercontent.com/1734406/62674985-70051800-b9d7-11e9-92c7-141b46423d68.gif)

The example code you can get it from [here](https://gist.github.com/bookjan/412d88ebd6b98f8ed49900be946668bf)

**Comment by Joltik** [comment]
> > @BunHouth auto center
> 
> you can check here.
> https://github.com/BunHouth/RNTabExample/blob/master/Home.js#L75

success
