### ISSUE TITLE
v2  embed horizontal scroll view can't scroll.

### ISSUE THREAD

**Issue by gaodeng** [react-native-community/react-native-tab-view#842]
### Current behaviour

v2 horizontal scroll view can't scroll.
![IMG_0635](https://user-images.githubusercontent.com/1118249/61191970-0ac54c00-a6e3-11e9-9036-6362d35bf65f.PNG)

### Expected behaviour

it should scroll normaly like v1

**Comment by chakrihacker** [comment]
Any repro code??

**Comment by Trancever** [comment]
@gaodeng Use ScrollView from `react-native-gesture-handler` and it should be working fine again.

**Comment by gaodeng** [comment]
@Trancever  It's still not working on iOS. android is fine.

**Comment by pribeh** [comment]
Experiencing this on a Samsung S9 plus but only in production.

**Comment by gaodeng** [comment]
?
