### ISSUE TITLE
null is not an object (evaluating '_ReanimatedModule.default.configureProps')

### ISSUE THREAD

**Issue by muhammad-nauman** [react-native-community/react-native-tab-view#843]
### Current behaviour
Importing is getting failed with an error while running the example code
"null is not an object (evaluating '_ReanimatedModule.default.configureProps')"

### Expected behaviour

It should run the example code and render the screen

### Code sample

```
import * as React from 'react';
import { View, StyleSheet, Dimensions, StatusBar } from 'react-native';
import { TabView, SceneMap } from 'react-native-tab-view';

const FirstRoute = () => (
  <View style={[styles.scene, { backgroundColor: '#ff4081' }]} />
);
const SecondRoute = () => (
  <View style={[styles.scene, { backgroundColor: '#673ab7' }]} />
);

export default class Tab extends React.Component {
  state = {
    index: 0,
    routes: [
      { key: 'first', title: 'First' },
      { key: 'second', title: 'Second' },
    ],
  };

  render() {
    return (
      <View>
        <TabView
          navigationState={this.state}
          renderScene={SceneMap({
            first: FirstRoute,
            second: SecondRoute,
          })}
          onIndexChange={index => this.setState({ index })}
          initialLayout={{ width: Dimensions.get('window').width }}
          style={styles.container}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    marginTop: StatusBar.currentHeight
  },
  scene: {
    flex: 1,
  },
});
```

### What have you tried

Nothing, I don't know what to do now.

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | Android
| react-native                 | 0.59.8
| react-native-tab-view        | ^2.9.0
| react-native-gesture-handler | ^1.3.0
| react-native-reanimated      | ^1.1.0
| node                         | 10.15.13
| npm or yarn                  | yarn

**Comment by satya164** [comment]
Please read the docs.

**Comment by muhammad-nauman** [comment]
> Please read the docs.

Obviously, I have read the docs and followed all the steps. Can you please at least reference to where I'm doing wrong?

**Comment by IronTony** [comment]
I have the same problem, and I have read the documentation.
So would you be so kind to help us please?

**Comment by chakrihacker** [comment]
which version of tab view are you using

**Comment by AndroidDoctorr** [comment]
If you haven't gotten it already, the step you skipped is:
react-native link react-native-reanimated
react-native link react-native-gesture-handler
(Unless you're using react-native 0.6 and above)

**Comment by 123dma** [comment]
Hello Iron. 
I restart the App.
 react-native start --reset-cache &&
 react-native run-android 

and solve my problem.

**Comment by dart200** [comment]
i had to do the linking despite using 0.61.1, the docs don't seem to be correct.

**Comment by jiyouliang** [comment]
I had solved the problem by:
react-native link react-native-reanimated

![image](https://user-images.githubusercontent.com/19160100/68942338-55ff8080-07e3-11ea-809b-9340b02e9064.png)

**Comment by alexstoyanov** [comment]
I am getting the same problem using react-native 0.61.5

**Comment by shoaib2527** [comment]
@alexstoyanov 
Did you resolved??
Getting same error with react-native 0.61.5

**Comment by DenisSokoloff** [comment]
I try

`react-native link react-native-reanimated`

and then

```
react-native start --reset-cache
react-native run-android
```

Works for me, good luck

**Comment by alexstoyanov** [comment]
@shoaib2527 although I am using react-native 0.61.5 - I tried react-native link react-native-reanimated and it worked

**Comment by plockxng** [comment]
> @shoaib2527 although I am using react-native 0.61.5 - I tried react-native link react-native-reanimated and it worked

Thanks, this actually worked strangely...

I'm confused why we have to do this since like @alexstoyanov and @shoaib2527,  I am also using react-native 0.61.5 and there should be automatic linking.

**Comment by jaldesigner** [comment]
> > @ shoaib2527 embora eu esteja usando o react-native 0.61.5 - tentei o link react-native react-native-reanimated e funcionou
> 
> Obrigado, isso realmente funcionou estranhamente ...
> 
> Estou confuso por que temos que fazer isso, pois, como @alexstoyanov e @ shoaib2527 , também estou usando o react-native 0.61.5 e deve haver ligação automática.

Não funcionou comigo. uso o React Native 0.61.5

**Comment by nate-whil** [comment]
if you're on react-native 60 or above, instead of running link, just add  
`implementation project(':react-native-reanimated')
implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02'`
to the dependencies section of your app/build.gradle

**Comment by SumitThinktanker** [comment]
Finally, I came to the conclusion to go for native development instead of wasting time solving errors.

**Comment by ricardocosta21** [comment]
@SumitThinktanker  This is ridiculous. I'm tired of this crap.

**Comment by udaisshekhawat** [comment]
If you are using react native versions greater than 0.60,

For android you can use the solution provided here:
https://stackoverflow.com/questions/57878353/i-have-an-error-in-react-native-null-is-not-an-object-evaluating-reanimatedmo

This worked for me.

**Comment by Jaffarraza12** [comment]
I don't why people sharing ideas "react-native-link" as RN @0.60 linking is automatic .
i have by updating my pod file in IOS
 pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

and run pod install after . 
Thats worked for me.

**Comment by RamonaVint** [comment]
Same issue react native 0.63.2

**Comment by karlsoft** [comment]
u can try add modules like this

![image](https://user-images.githubusercontent.com/9859238/101315892-6bd05f80-3896-11eb-8bee-5eb9d392dcd6.png)

 modules.add(new ReanimatedModule(reactContext));

**Comment by patrice4github** [comment]
LOL. "Read the doc", like that's going to help your open source project.
I'm just trying to get my app to display so I can convert it to Fluke.

**Comment by PAAPII10** [comment]
My version is above 0.61 still I tried this
npx react-native link react-native-reanimated
npx react-native run-android
It worked for me... If it helps leave a like, Thank you

**Comment by juanbomfim22** [comment]
@PAAPII10  For me it worked!! At least the error is another one 🔥🔥

**Comment by Nacho-source** [comment]
> If you haven't gotten it already, the step you skipped is: react-native link react-native-reanimated react-native link react-native-gesture-handler (Unless you're using react-native 0.6 or above)

In my case, I was encountering this error using react native `0.68.2` in an iOS simulator and this solution + `pod install` + `npm run ios` worked for me.

**Comment by sheriffjimoh** [comment]
Please I am facing this error currently, is there anyone that can help please, I just upgrade our app to expo / SDK 46.0.0, React native 0.69.6, and I was forced to upgrade to reanimated   2.9.1. thereby bringing this error every time I run npm start ---clear, I have imported it in barbel.config.js as mentioned in the documentation. thank you.

**Comment by AdnanAshraf-gol** [comment]
module.exports = {
    presets: [
      ...
    ],
    plugins: [
      ...
      'react-native-reanimated/plugin',
    ],
  };
  
  
  update your babel.config.js and then expo start -c

**Comment by sheriffjimoh** [comment]
Already did that
