### ISSUE TITLE
<animated.text   style {{color}} > error 

### ISSUE THREAD

**Issue by Ghiffary** [react-native-community/react-native-tab-view#844]
What should i do?? please i need help buddy

### Code sample

https://github.com/Ghiffary/React-Native-Top-Slider

### Screenshots (if applicable)

<img width="885" alt="Screenshot 2019-07-16 at 18 39 34" src="https://user-images.githubusercontent.com/9641295/61291663-4e11de80-a7f9-11e9-92bc-179120a70d0b.png">
<img width="579" alt="Screenshot 2019-07-16 at 18 39 50" src="https://user-images.githubusercontent.com/9641295/61291665-4e11de80-a7f9-11e9-8f48-0d24fc444228.png">

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | pie
| react-native                 | newest
| react-native-tab-view        | newest
| react-native-gesture-handler | newest
| react-native-reanimated      | newest
| node                         | newest
| npm or yarn                  |newest

**Comment by satya164** [comment]
Closing since this doesn't seem like a bug in the library and the repro provided doesn't even use the library.

**Comment by Ghiffary** [comment]
but i just install the library, but the color eror cannot be run..

**Comment by satya164** [comment]
Please provide a repro that shows the issue. Your repro doesn't then use this library.
