### ISSUE TITLE
Is it possible to use new feature "tab style width auto" with lazy tabview?

### ISSUE THREAD

**Issue by oguzhanali** [react-native-community/react-native-tab-view#846]
### Current behaviour

New feature tabstyle= {width:auto} works very well with scrollenabled tabbar. But when you use it with lazy feature, indicator wait for scenes to be fully rendered and then transform next selected tab's width, even though next selected scenes' place holder began to seen, causes an lagged experience (even though it is minimal). Issue is on android.

### Expected behaviour

Tabstyle width auto should work with lazy feature. Should not wait for scenes to be fully rendered, because we know tabs' widths and should work with lazy load placeholder as well.

### What have you tried

Is this a limitation for "tab style width auto"? I couldn't figure out a solution, is it something that can be done?

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |
| react-native                 | 0.59.8
| react-native-tab-view        | 2.9.0
| react-native-gesture-handler | 
| react-native-reanimated      |
| node                         |
| npm or yarn                  |

**Comment by satya164** [comment]
Lazy load is independent from the tab bar. `width: 'auto'` works fine with lazy for me. Please provide a video/gif and a runnable repro of the issue you're having.

**Comment by oguzhanali** [comment]
@satya164 a video/gif only for now. It looks like that:
![tabStyleWithAuto](https://user-images.githubusercontent.com/47118973/61596479-e8fd2500-ac0c-11e9-9651-19651498cb03.gif)

**Comment by sinazeini** [comment]
this is my same problem,anybody can help us ?
