### ISSUE TITLE
UI stuck when switching tabs by tapping on Android and Expo.

### ISSUE THREAD

**Issue by oriharel** [react-native-community/react-native-tab-view#851]
### Current behaviour

I have 7-10 tabs, each one contains SectionList with 50-100 items.
Sometimes, when I switch back and forth between 2 adjacent tabs, the UI is frozen for 2-4 seconds before the switch takes place. It's not only upon first render.
Swiping between these 2 tabs is smooth, however the TabBar takes this amount of time to update.

### Expected behaviour

Render should be a lot faster, specially when it's not the first visit to the tabs

### Code sample

I can't give a runnable code, as it involves the amount of the data in order to reproduce. But here's how I use <TabView>:
```
<TabView
	navigationState={{ index: this.index, routes: this.routes }}
	renderTabBar={props => (
		<TabBar
			{...props}
			inactiveColor={'rgb(129, 167, 227)'}
			activeColor={'rgb(27, 125, 225)'}
			indicatorStyle={styles.indicator}
			style={styles.tabBar}
			scrollEnabled={true}
			renderLabel={renderLabel}
		/>
	)}
	renderScene={this.renderScene}
	onIndexChange={index => (this.index = index)}
	lazy={true}
	lazyPreloadDistance={1}
/>

renderScene = ({ route }) => {
		let items: any = route.items;
		return (
			<SectionList
				sections={items}
				renderItem={this.renderItem}
				renderSectionHeader={this.renderSectionHeader as any}
				ItemSeparatorComponent={this.itemSeparator}
				keyExtractor={keyExtractor}
				nestedScrollEnabled={true}
				stickySectionHeadersEnabled={true}
				contentContainerStyle={styles.tabList}
				scrollEventThrottle={5}
				showsVerticalScrollIndicator={false}
			/>
		);
	};

renderItem = ({ item }: { item: MFindingGroup }) => (
		<GenericItem
			item={item}
			goToDV={this.goToDV}
			goToPathView={this.goToPathView}
			style={commonStyles.flexOne}
		/>
	);

const GenericItem = ({
	item,
	goToDV,
	goToPathView,
	style
}: {
	item: MFindingGroup;
	goToDV: (item: MFindingGroup) => void;
	goToPathView: (item: MFindingGroup) => void;
	style: any;
}) => {
	const goToPV = () => goToPathView(item);
	switch (item.type) {
		case FindingGroupType.OPEN_DISTRIBUTION:
			return withPathsDrillDown(
				<Distribution item={item} goToDV={goToDV} style={style} />,
				goToPV
			);
		case FindingGroupType.CLOSED_DISTRIBUTION:
			return withPathsDrillDown(
				<ClosedDistribution item={item} goToDV={goToDV} style={style} />,
				goToPV
			);

		case FindingGroupType.PREVALENCE:
			return withPathsDrillDown(
				<PrevelanceGroup item={item} goToDV={goToDV} style={style} />,
				goToPV
			);

		case FindingGroupType.LABTEST_GROUP:
			return withPathsDrillDown(
				<LabTestGroup item={item} goToDV={goToDV} style={style} />,
				goToPV
			);
		case FindingGroupType.MULTI_LEVEL_GROUP:
			return (
				<MultiLevelGroup
					item={item}
					goToDV={goToDV}
					style={style}
					goToPathView={goToPathView}
				/>
			);
		default:
			return withPathsDrillDown(
				<LeafItem item={item} goToDV={goToDV} style={style} />,
				goToPV
			);
	}
};
```

### What have you tried

I've tried to profile the scenario (more reproducible on a real device then on an emulator) and in the Chrome profiler, the React FlameChart looks like most of the period has a grey duration with no data (probably native code). the React part, where I can see my components hierarchy - the duration looks fine. 

### Your Environment

| software                     | version
| ---------------------------- | -------
| android               | 9
| react-native                 | Expo 33 (Managed Workflow)
| react-native-tab-view        | 2.6.2
| react-native-gesture-handler | 1.2.1
| react-native-reanimated      | The default included in Expo 33
| node                         | 10.15.1
| npm or yarn                  | 1.17.3

**Comment by satya164** [comment]
> I can't give a runnable code, as it involves the amount of the data in order to reproduce. But here's how I use

It's impossible to know what's happening without code. You need to at least post your `renderScene` function.

Have you followed optimization tips? https://github.com/react-native-community/react-native-tab-view#avoid-unnecessary-re-renders

**Comment by oriharel** [comment]
thanks @satya164 - I've added more code.

**Comment by satya164** [comment]
Doesn't look like you have followed the optimization tips. Please follow the README to implement `shouldComponentUpdate`/`PureComponent`/`React.memo` to prevent unnecessary re-renders.

**Comment by oriharel** [comment]
I have.
As you can see, renderScene() returns a SectionList which is a PureComponent.

**Comment by oriharel** [comment]
Anything else that comes in mind?

**Comment by satya164** [comment]
> SectionList which is a PureComponent

Can't say without code which I can run and debug. Your example is also storing state in class property which I'm not sure is going to behave correctly.

**Comment by oriharel** [comment]
So from what I've read, it's exactly the same as described in #720 .
I'm running version 2.6.2 so it's after your changes. There is also a report in #778 that this is still not fixed. I'm aware that @xaviershay said that it has fixed his issue - I wonder, are you sure?

**Comment by xaviershay** [comment]
it definitely made an improvement on the isolated test case I had, but haven't had a chance to incorporate into our main app yet.

**Comment by barmola** [comment]
I am still facing this UI stuck issue in version `^3.1.1` on Android only. Can anyone please help me with this?
