### ISSUE TITLE
calling class components from renderScene not working

### ISSUE THREAD

**Issue by leslielyj** [react-native-community/react-native-tab-view#852]
### Current behaviour

I have an array passed to the tab-view page via getparams from 'react-navigation'. I would like to display the data in the routes. I've read through all the documentation and can't find a way to use SceneMap as I cant pass data in the routes there. Thus I am trying to pass them to a separate class component instead (as I would also need to do a componentdidmount for fetch purpose).   

### Expected behaviour

in <TabView renderScene={this.renderScene}/>I expected the renderScene function declared outside the return would work but it says route: route, renderScene is undefined

### Code sample
        export default class ViewOrganization extends Component {
          state = {
            index: 0,
            routes: [
              { key: 'albums', title: 'Albums' },
              { key: 'members', title: 'Members'}
            ],
          };

          render() {
            const { navigation } = this.props;
            const organization = navigation.getParam("organization"); 

            renderScene = ({ route, jumpTo }) => {
              switch (route.key) {
                case 'media':
                  return <CommunityMedia jumpTo={jumpTo} foo={organization}/>;
                case 'members':
                  return <CommunityMembers jumpTo={jumpTo} foo={organization}/>;
                default:
                  return null;
              }
            };
            
            return (
              <TabView
                navigationState={this.state}
                renderScene={this.renderScene}
                onIndexChange={index => this.setState({ index })}
                initialLayout={{ width: width }}
                style={{ backgroundColor: 'white', color: 'black' }}
                tabStyle={{ backgroundColor: 'white'}}
                indicatorStyle={{ backgroundColor: 'black' }}
              />
            )
          }
        }

### Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/17871490/61759280-9a14e280-adfa-11e9-97f3-285a69e2e5c5.png)

### Your Environment

| software                     | version
| ---------------------------- | -------
| android               | 9.0
| react-native                 | 60.4
| react-native-tab-view        | 2.7.3
| react-native-gesture-handler | 
| react-native-reanimated      |
| node                         | 
| npm                  |

**Comment by satya164** [comment]
You don't have a `renderScene` method on your class. It's defined as a global variable inside render

![image](https://user-images.githubusercontent.com/1174278/61759823-b187a780-adc9-11e9-9d0c-8251de420895.png)

**Comment by leslielyj** [comment]
Hello, 

Thank you for your response. I tried putting it outside render and inside the class and it works. However any idea how to pass data to a separate class component? 

Code:
![image](https://user-images.githubusercontent.com/17871490/61760461-34c2f080-adfe-11e9-93c9-4b1b51cc51f7.png)

Error: 
![image](https://user-images.githubusercontent.com/17871490/61760490-4efcce80-adfe-11e9-897c-6cffe2c25bd8.png)

Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: %s.%s%s, undefined,  You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by leslielyj** [comment]
Nevermind me, found out the issue, it was on my end on my line of code that didn't have anything to do with the dependency :D Cheers~

**Comment by lander854** [comment]
What was the solution? having the same problem here

**Comment by chrise86** [comment]
I'm facing this error now and can't figure out where/why it's happening, what did you do to fix it @leslielyj ?
