### ISSUE TITLE
More text will be displayed like this

### ISSUE THREAD

**Issue by yrjwcharm** [react-native-community/react-native-tab-view#858]
![image](https://user-images.githubusercontent.com/34397383/62264301-f5c21a00-b451-11e9-8fc7-c9202a360a74.png)

**Comment by chakrihacker** [comment]
are you using `width: 'auto'`

**Comment by yrjwcharm** [comment]
@chakrihacker Whose properties?

**Comment by yrjwcharm** [comment]
@chakrihacker  I solve it .Thank you
