### ISSUE TITLE
With this property, the layout is no longer centered

### ISSUE THREAD

**Issue by yrjwcharm** [react-native-community/react-native-tab-view#859]
![image](https://user-images.githubusercontent.com/34397383/62289207-acdd8600-b490-11e9-85a7-00e6767d2d4f.png)

**Comment by chakrihacker** [comment]
Any reproducible code??

**Comment by yrjwcharm** [comment]
<TabView
                    navigationState={this.state}
                    renderScene={SceneMap({
                        first: () => <FirstRoute {...this.props} CI={this}/>,
                        second: () => <SecondRoute {...this.props} CI={this}/>,
                    })}
                    onIndexChange={index => this.setState({index})}
                    initialLayout={{width: Dimensions.get('window').width}}
                    renderTabBar={props =>
                        <TabBar
                            {...props}
                            style={{
                                backgroundColor: "#f5f5f5",
                                shadowColor: "#d4d4d4",
                                shadowOffset: {
                                    width: 0,
                                    height: verticalScale(1)
                                },
                                shadowRadius: 0,
                                shadowOpacity: moderateScale(1),
                            }}
                            getLabelText={({route}) => route.title}
                            labelStyle={{
                                fontFamily: "PingFangSC-Regular",
                                fontSize: moderateScale(15),
                            }}
                            tabStyle={{height: verticalScale(44),width:'auto'}}
                            indicatorStyle={{backgroundColor: '#118fb8',width: scale(26),
                                height: verticalScale(2),
                              }}
                            activeColor={'#118fb8'}
                            inactiveColor={'#666666'}

                        />
                    }
                />
