### ISSUE TITLE
I want to build custom tab with react navigation

### ISSUE THREAD

**Issue by tariqsidd** [react-native-community/react-native-tab-view#861]
export default createMaterialTopTabNavigator ({
    feed: {
        screen: ProductRoutes,
    },
    profile: {
        screen: StoreRoutes,
    },
    inbox: {
        screen: BrandRoutes,
    }
}, {
    tabBarComponent: TabNavigator
})

import * as React from 'react';
import { View, Text, StyleSheet, I18nManager } from 'react-native';
import {
    TabView,
    TabBar,
    SceneMap,
} from 'react-native-tab-view';
import Animated from 'react-native-reanimated';

import ProductRoutes from '../product.routes';
import StoreRoutes from '../store.routes';
import BrandRoutes from '../brand.routes';

export default class TabNavigator extends React.Component {

    state = {
        index: 0,
        routes: [
            {
                key: 'productRoutes',
                icon: 'ios-paper',
                color: [244, 67, 54],
                title: 'Products'
            },
            {
                key: 'storeRoutes',
                icon: 'ios-people',
                color: [0, 132, 255],
                title: 'Stores'
            },
            {
                key: 'brandRoutes',
                icon: 'ios-albums',
                color: [76, 175, 80],
                title: 'Brands'

            },
        ],
    };

    handleIndexChange = (index) => this.setState({
        index,
    });
    renderIndicator = (props) => {
        const { position, navigationState, getTabWidth } = props;
        const inputRange = [
            0,
            0.48,
            0.49,
            0.51,
            0.52,
            1,
            1.48,
            1.49,
            1.51,
            1.52,
            2,
        ];
        const scale = Animated.interpolate(position, {
            inputRange,
            outputRange: inputRange.map(x => (Math.trunc(x) === x ? 2 : 0.1)),
        });
        const opacity = Animated.interpolate(position, {
            inputRange,
            outputRange: inputRange.map(x => {
                const d = x - Math.trunc(x);
                return d === 0.49 || d === 0.51 ? 0 : 1;
            }),
        });
        const translateX = Animated.interpolate(position, {
            inputRange: inputRange,
            outputRange: inputRange.map(x => {
                const i = Math.round(x);
                return i * getTabWidth(i) * (I18nManager.isRTL ? -1 : 1);
            }),
        });
        return (
            <Animated.View
                style={[
                    styles.container,
                    {
                        width: `${100 / navigationState.routes.length}%`,
                        transform: [{ translateX }] ,
                    },
                ]}
            >
                <Animated.Image
                    source={require('../../assets/images/line.png')}
                    style={[
                        styles.indicator,
                        { opacity, transform: [{ scale }]},
                    ]}
                />
            </Animated.View>
        );
    };

    renderLabel =({ route, focused }) => (
        <Text style={{ color: focused? '#028090' : '#aaaaaa', margin: 8 }}>
            {route.title}
        </Text>
    );

    renderTabBar = (props) => (
        <TabBar
            {...props}
            renderLabel={this.renderLabel}
            renderIndicator={this.renderIndicator}
            style={styles.tabbar}
        />
    );

    renderScene = SceneMap({
        productRoutes: ProductRoutes,
        storeRoutes: StoreRoutes,
        brandRoutes: BrandRoutes,
    });

    render() {
        return (
            <TabBar
                {...this.props}
                renderLabel={this.renderLabel}
                renderIndicator={this.renderIndicator}
                style={styles.tabbar}
            />
        );
    }
}

const styles = StyleSheet.create({
    tabbar: {
        backgroundColor: '#fff',
        overflow: 'hidden',
        height:60,
        justifyContent:'center'
    },
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    indicator: {
        width: 40,
        height: 20,
        marginTop:30
    },
});

**Comment by soroushm** [comment]
so use https://www.npmjs.com/package/react-navigation-tabs
