### ISSUE TITLE
Navigation listeners like didFocus, willFocus not working in child views.

### ISSUE THREAD

**Issue by peddireddykishore** [react-native-community/react-native-tab-view#862]
here is my code Sample 

componentDidMount() {
  this._sub = this.props.route.navigation.addListener(
       'didFocus',
       this._componentFocused
     );  
}

**Comment by Schildkroete23** [comment]
I have the same problem. @peddireddykishore did you find a workaround?

**Comment by satya164** [comment]
This is not related to this library. The library doesn't and cannot prevent React Navigation listeners from being called.

**Comment by mtalhagaoglu** [comment]
same problem here. i need a function everytime page focused and i am doing that with listener function but with this lib it didn't work. did you guys any find any solution for this?
