### ISSUE TITLE
I can't switch tab to other routes

### ISSUE THREAD

**Issue by vokespeaks** [react-native-community/react-native-tab-view#863]
Hi,

When I switch to the other route, I get the below error
_this.setState is not a function. (In '_this.setState({idex: index}),  ','_this.setState is undefined)

my code snippet can be found here https://gist.github.com/vokespeaks/573b0406f44e24eb42f628e011e51afa

**Comment by satya164** [comment]
That's not correct syntax for a React Component. Please refer React documentation on how to write components and the project's README on an example component using the library.
