### ISSUE TITLE
Tab indicator in incorrect place

### ISSUE THREAD

**Issue by itzsaga** [react-native-community/react-native-tab-view#866]
### Current behaviour

Tab indicator is not lining up with non-index 0 tab items.

### Expected behaviour

The tab indicator to be properly positioned.

### Code sample

I tried but couldn't get the example working on Snack. Key piece of info is if the tab bar has to scroll horizontally to get to the initial index the indicator is in the incorrect place. It ends up where the tab item would be before scrolling to the center. This code produces the screenshot below on load.
```javascript
state = {
    index: 2,
    routes: [
      { key: "stepOne", title: "Step One" },
      { key: "stepTwo", title: "Step Two" },
      { key: "stepThree", title: "Step Three" },
      { key: "stepFour", title: "Step Four" }
    ],
};
```
I'm using auto width as well.

### Screenshots (if applicable)

![Screen Shot 2019-08-12 at 15 46 55](https://user-images.githubusercontent.com/11750061/62897528-15dabe80-bd19-11e9-8f1d-64290c522afc.png)

### What have you tried

I've tried setting the index dynamically based on a prop, I've tried different Tab components chosen and rendered at runtime like the [docs](https://reactjs.org/docs/jsx-in-depth.html#choosing-the-type-at-runtime) describe. I've tried just hardcoding it like I'm doing in this example.

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |12.4
| react-native                 |0.59.9
| react-native-tab-view        |2.10.0
| react-native-gesture-handler |1.1.0
| react-native-reanimated      |1.0.1
| node                         |12.2.0
| npm or yarn                  |yarn

**Comment by matias91** [comment]
I'm experiencing the same issue in **version: 2.14.0**.
I tried with the defaults TabBar and indicator, instead of using my customs, but the result is the same.
Looks like this issue should be open.
Is there anyone who can help with this?

<img width="437" alt="Screen Shot 2020-04-28 at 17 02 31" src="https://user-images.githubusercontent.com/2778383/80532167-192edc80-8972-11ea-93f7-e7197b4ebfc4.png">

**Comment by PedroBern** [comment]
Same problem here.

**Comment by Batstone** [comment]
Also experiencing the same issue. Has anyone figured this out?

**Comment by theMasix** [comment]
Same here on `v3.1.1`
