### ISSUE TITLE
Activetab is not in center when scrollEnabled is true and tabStyle width is set to 'auto'.

### ISSUE THREAD

**Issue by earlyCloud** [react-native-community/react-native-tab-view#867]
### Current behaviour
Active tab is not in center when scrollEnabled is true and tabStyle width is set to 'auto'.
### Expected behaviour
Active tab scrolls to center of view.
### Environment
| software                     | version
| ---------------------------- | -------
| ios or android               | android
| react-native                 | 0.57.8
|react-native-tab-view   | 1.4.1
| node                         | 8.11.4
| npm                 | 5.6.0

**Comment by satya164** [comment]
`react-native-tab-view` 1.x doesn't support `width: 'auto'`. Please upgrade to latest version

**Comment by earlyCloud** [comment]
> 
> 
> `react-native-tab-view` 1.x doesn't support `width: 'auto'`. Please upgrade to latest version
Thanks for the reply. 
Actually I come here from react-navigation. The newest react-navigation relies on this version, sorry to trouble you but I don't know how to deal with it.
