### ISSUE TITLE
No way to customize animation speed

### ISSUE THREAD

**Issue by scottmas** [react-native-community/react-native-tab-view#869]
This isn't a bug but a feature request. Currently there is no way to customize the speed of the animation. We would like to make the animation far faster. We don't necessarily need super fine grained control over the animation, just the speed at which it executes.

**Comment by satya164** [comment]
https://github.com/react-native-community/react-native-tab-view/blob/master/README.md#timingconfig

**Comment by satya164** [comment]
It's not a tab bar option. Pass it in navigation config
