### ISSUE TITLE
Tab bar shouldn't scroll when there aren't enough items

### ISSUE THREAD

**Issue by satya164** [react-native-community/react-native-tab-view#87]

**Comment by CharlesMangwa** [comment]
@satya164 This issue seems to have been solved?

**Comment by satya164** [comment]
I'm not sure. Need to test.

**Comment by CharlesMangwa** [comment]
My bad, it does scroll indeed: https://sketch.expo.io/ByHoRr2ol.

**Comment by karanjthakkar** [comment]
@CharlesMangwa I can't reproduce on iOS using the example you posted. @satya164 can you give it a shot on android? The android simulator on Snack also doesnt seem to exhibit any kind of scrolling.

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.
