### ISSUE TITLE
how to remove the bottom line in tabBar

### ISSUE THREAD

**Issue by wowtrxqn** [react-native-community/react-native-tab-view#870]
![QQ图片20190826094507](https://user-images.githubusercontent.com/24369118/63659831-3bba9580-c7e6-11e9-9106-e5c107585207.png)

How can I remove the tabbar bottom line

**Comment by wowtrxqn** [comment]
I got it.

**Comment by garrottkai** [comment]
What was the solution?

**Comment by garrottkai** [comment]
for reference, the line is a box shadow. Setting shadowOpacity and elevation to 0 on TabBar gets rid of it.

**Comment by shahabrauf18** [comment]
In my case, 

<TabBar
            {...props}
            indicatorStyle={{ backgroundColor: Colors.blue.alt2 }}
            style={{ backgroundColor: Colors.white.default, shadowOpacity: 0 }}
            activeColor={Colors.blue.alt2}
            inactiveColor={Colors.grey.default}
        />

**Comment by mgpepe** [comment]
@shahabrauf18  not in `TabBar` though, in the `TabView`!
