### ISSUE TITLE
how to add icon in the tabView area？

### ISSUE THREAD

**Issue by wowtrxqn** [react-native-community/react-native-tab-view#871]
for example ，i want to add some function buttons on the right side of the tabView，i tryed adding Text Component but doesn't work

`renderTabBar = props => (
        <View>
        <TabBar
            {...props}
            renderIcon={this.renderIcon}
            style={styles.tabbar}
            labelStyle={styles.labelStyle}
            tabStyle={styles.tabStyle}
            indicatorStyle={styles.indicatorStyle}
            renderIndicator={this.renderIndicator}
        />
        <Text style={{position:'absolute',right:0,top:0,color:'black',width:100,height:50,justifyContent:'center',alignItems:'center'}}></Text>
        </View>
    );`

![QQ12224](https://user-images.githubusercontent.com/24369118/63748469-ff696100-c8db-11e9-9fa0-9bcbc93179c4.png)

**Comment by Thebarda** [comment]
You can use `renderLabel` property from `TabBar` then :
```javascript
<View>
    // Your icon here
    <Text numberOfLines={1}>
        {props.route.title}
    </Text>
</View>
```

**Comment by wowtrxqn** [comment]
> You can use `renderLabel` property from `TabBar` then :
> 
> ```js
> <View>
>     // Your icon here
>     <Text numberOfLines={1}>
>         {props.route.title}
>     </Text>
> </View>
> ```


I want to add some function  buttons on the right side of the tabView base on absolute position ，Red box as shown above

**Comment by Thebarda** [comment]
I did not understand that, sorry.
Maybe try to customize tab bar (Example here : https://snack.expo.io/@satya164/react-native-tab-view-custom-tabbar)
