### ISSUE TITLE
Navigating to end of tab list breaks lazy logic

### ISSUE THREAD

**Issue by viventus** [react-native-community/react-native-tab-view#874]
### Current behaviour

I have a large list of tabs:
```
<TabView
                lazy
                lazyPreloadDistance={1}
                key={this.key}
                navigationState={this.state}
                tabBarPosition="bottom"
                renderScene={this.handleRenderScene}
                onIndexChange={this.navigateToTab}
                renderTabBar={this.handleRenderTabBar}
                initialLayout={INITIAL_LAYOUT}
                onSwipeEnd={this.handleSwipe}
            />
```
Navigating to the end of tab list renders all scenes

### Expected behaviour

Navigating to the end of tab list renders two last scenes

### What have you tried

I created local patch disabling handleEnter 
https://github.com/react-native-community/react-native-tab-view/blob/master/src/SceneView.tsx#L76

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | iOS
| react-native                 | 0.60.5
| react-native-tab-view        | 2.10.0
| react-native-gesture-handler |
| react-native-reanimated      |
| node                         | 12.6.0
| npm or yarn                  | npm

**Comment by DuranMoodley** [comment]
Has this issue been resolved ? Is there a fix ?

**Comment by Trancever** [comment]
@viventus That's how this library works from the beginning. I don't think it's gonna be changed to work as you expect anytime soon, because it requires a lot of effort and probably core logic redesign and reimplementation.
