### ISSUE TITLE
Error after installing and importing both TabView and SceneMap

### ISSUE THREAD

**Issue by ismaelbarry** [react-native-community/react-native-tab-view#875]
### Current behavior

After following the directions for Expo installation
- npm install react-native-tab-view
- expo install react-native-gesture-handler react-native-reanimated

Then integrating the QuickStart code in my project, I get the following error in Terminal as the Javascript Bundle does not build successfully:
- Unable to resolve "react-native/Libraries/Components/View/ViewStylePropTypes" from "node_modules/react-native-reanimated/src/createAnimatedComponent.js"

Now, from the Expo app on my phone:

![error screen](https://user-images.githubusercontent.com/13290756/64292180-c5313c80-cf37-11e9-8564-65d568ef69c8.jpg)

### Expected behaviour

I expect the code to run successfully. However, there seems to be an issue with my node_modules after the following installation: expo install react-native-gesture-handler react-native-reanimated.

### Code sample

To reproduce this error, make sure are running Expo version 33.0.0 with react Native Version 59.8. Next, follow the installation guide:
- npm install react-native-tab-view
- expo install react-native-gesture-handler react-native-reanimated

Then, follow the quickstart guide.

### What have you tried

I attempted the follow the instructions from the error code; however, I'm still experiencing the problem. I've also tried using rm -rf node_modules && npm install, but this also did not work. Interestingly, when I remove the following import statement 
- import { TabView, SceneMap } from 'react-native-tab-view' 

the error goes away. Therefore, the issue must be with this library.

### Your Environment

Currently running: 
- Expo Version 33.0.0
- React Native Version 59.8

After installation of the following command: expo install react-native-gesture-handler react-native-reanimated, I get the following log:

![Screenshot 2019-09-04 17 33 50(2)](https://user-images.githubusercontent.com/13290756/64293340-63be9d00-cf3a-11e9-9b10-ac6b0b88b58e.png)

I'm also using npm. 

Thanks everyone!

**Comment by snaksa** [comment]
Same here.

**Comment by snaksa** [comment]
The same happens when I try too.

**Comment by chakrihacker** [comment]
Expo already ships **react-native-gesture-handler react-native-reanimated** you don't have to install it

**Comment by jantongiovanni** [comment]
Issue is with the expo install command installing "react-native-reanimated": "^1.2.0",
Change version to ^1.3.0 and npm install and it should fix it
