### ISSUE TITLE
 TextInput in tabs, does not work and when using onChangeText for service errors, when typing does not display

### ISSUE THREAD

**Issue by drezza544** [react-native-community/react-native-tab-view#876]
### Current behaviour

###My Code, Please Help
![image](https://user-images.githubusercontent.com/50728257/64489578-372ebc00-d27f-11e9-9299-c15acd3bbe47.png)

### Code sample

For Syntax Highlighting check this [link](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |
| react-native                 | 0.59.9
| react-native-tab-view        | 2.10.0
| react-native-gesture-handler | 1.4.1
| react-native-reanimated      | 1.2.0
| node                         |
| npm or yarn                  |

**Comment by talha-hameed** [comment]
get any solution??

**Comment by martppa** [comment]
Hi there! This issue appears when you try to share the same state between tabs. Creating a specific component with its own state for each tab will solve the problem.
