### ISSUE TITLE
 "Invariant Vilation:[8, { "type":"value","value":<<NAN>>}] is not usables as a native method argument

### ISSUE THREAD

**Issue by viet97** [react-native-community/react-native-tab-view#878]
### Current behaviour

After seting up done , I'm geting error : "Invariant Vilation:[8, { "type":"value","value":<<NaN>>}] is not usables as a native method argument

### Expected behaviour

it should be run correctly without error...
### Code sample

```
@withTheme
export default class TabChannel extends BaseScreen {

    state = {
        routes: [
            { key: 'first', title: 'First' },
            { key: 'second', title: 'Second' },
        ],
    }


    render() {
        return (
            <View>
                <TabView
                    navigationState={this.state}
                    renderScene={SceneMap({
                        first: FirstRoute,
                        second: SecondRoute,
                    })}
                    onIndexChange={index => this.setState({ index })}
                    initialLayout={{ width: dimensions.width }}
                />
            </View>

        );
    }
}

```
### Screenshots (if applicable)

![Screenshot from 2019-09-10 14-25-47](https://user-images.githubusercontent.com/24263655/64593554-7ae90900-d3d8-11e9-9a25-a9bc5551b5ec.png)
9-09-10 14-25-47.png…]()

### Your Environment

| software                     | version
| ---------------------------- | -------
| android               | 27
| react-native                 | 0.59.1
| react-native-tab-view        | 2.10.0
| react-native-gesture-handler | ^1.4.1
| react-native-reanimated      | ^1.2.0
| node                         | 8.10.0
|  yarn                  | 1.17.3
| react-native-navigation  |^3.1.2

**Comment by jordangrant** [comment]
```
state = {
        index: 0,
        routes: [
            { key: 'first', title: 'First' },
            { key: 'second', title: 'Second' },
        ],
    }
```

**Comment by SimonPotier** [comment]
Had the same error, for me it was because I set a percentage value as width in initialLayout props, when I stick to the initial example it works: `initialLayout={{width: '100%'}}` -> `initialLayout={{width: Dimensions.get('window').width}}`

**Comment by briantical** [comment]
I am currently experiencing this error. Any solution as the one mentioned by @SimonPotier didn't work for me. I am actually using the example given.

**Comment by diegoprates** [comment]
@briantical make sure that you initialize index state with 0.

**Comment by shubhamtakode** [comment]
Still exists

**Comment by bracketsberlin** [comment]
I had the same problem and the following addition did the trick:

**Example was**:
`navigationState={{ index, routes }}`

**Solution was**:
`navigationState={{ "index": tabIndex, routes }}`

As @jordangrant correctly pointed out, there must be an **index** key in the navigation state. I don't know how the example is supposed to work?!
