### ISSUE TITLE
React-native 0.61.0-rc.3 Can't swipe between tabs

### ISSUE THREAD

**Issue by Ludus-Team** [react-native-community/react-native-tab-view#879]
### Current behaviour
On Android only
On react-native 0.61.0-rc.3
can't swipe between tabs

### Expected behaviour
On Android with react-native 0.61.0-rc.3
Will swipe between tabs when I set "swipeEnabled"

### Code sample
```
import * as React from 'react';
import { View, StyleSheet, Dimensions } from 'react-native';
import { TabView, SceneMap } from 'react-native-tab-view';

const FirstRoute = () => (
  <View style={[styles.scene, { backgroundColor: '#ff4081' }]} />
);

const SecondRoute = () => (
  <View style={[styles.scene, { backgroundColor: '#673ab7' }]} />
);

export default class TabViewExample extends React.Component {
  state = {
    index: 0,
    routes: [
      { key: 'first', title: 'First' },
      { key: 'second', title: 'Second' },
    ],
  };

  render() {
    return (
      <TabView
        navigationState={this.state}
        renderScene={SceneMap({
          first: FirstRoute,
          second: SecondRoute,
        })}
        onIndexChange={index => this.setState({ index })}
        initialLayout={{ width: Dimensions.get('window').width }}
      />
    );
  }
}

const styles = StyleSheet.create({
  scene: {
    flex: 1,
  },
});
```

### What have you tried
react native 0.60.5 Same code

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | android
| react-native                 | 0.61.0-rc.3
| react-native-tab-view        |2.10.0
| react-native-gesture-handler |1.4.1
| react-native-reanimated      |1.2.0
| node                         |11.10.0
| npm or yarn                  |yarn

**Comment by satya164** [comment]
Can you provide a repro?

**Comment by kyungjoongo** [comment]
same issue in React-native 0.61.0-rc.3

**Comment by DomiR** [comment]
You can test it here: https://github.com/DomiR/react-navigation5-swipe-problem. I've just verified this on android.

**Comment by DomiR** [comment]
Seems to be related to this problem: https://github.com/kmagiera/react-native-gesture-handler/issues/745

**Comment by hussainahmad** [comment]
is there anyone found workaround for this, getting the same issue on android.

**Comment by peksi** [comment]
I have the same issue with react-native 0.61.1 on android

**Comment by Divya-A** [comment]
I have the same issue with react-native 0.61.2 ,react-native-reanimated: 1.3.0, react-native-gesture-handler:1.4.1, react-native-tab-view : 2.10.0 on android

**Comment by dalvtor** [comment]
The previous comment fixes it for me on Debug mode, but makes the app crash in release mode.

**Comment by b1ngx** [comment]
Android app crash in release when swipe tab but debug is ok.

```json
"react-native": "0.61.2",
"react-native-gesture-handler": "^1.4.1",
"react-native-reanimated": "^1.3.0",
```

**Comment by franjorub** [comment]
same problem ios release 

extractEvents@94:13054
<unknown>@94:13845
_e@94:88659
Ne@94:13582
Ue@94:13755
receiveEvent@94:14164
value@24:3685
<unknown>@24:841
value@24:2939
value@24:813
value@<null>:<null>
'
*** First throw call stack:
(0x18ea05c30 0x18e7200c8 0x10496ccd0 0x1049de9a8 0x18ea0c724 0x18e8d5280 0x18e8d5e90 0x10499f680 0x1049a1790 0x1049a14f4 0x105915e48 0x1059172a8 0x10591e938 0x10591f528 0x10592a4e8 0x18e712aa0 0x18e718c78)
libc++abi.dylib: terminating with uncaught exception of type NSException

rn 0.61.2
    "react-native-gesture-handler": "^1.4.1",
    "react-native-reanimated": "^1.3.0",

**Comment by franjorub** [comment]
TouchableOpacity from gesture handler inside the TabView crash the app in iOS release too

**Comment by satya164** [comment]
Please check https://github.com/kmagiera/react-native-gesture-handler/issues/320

**Comment by lake2** [comment]
same issue +1 on RN 0.61.2
