### ISSUE TITLE
multiple background colors in one view

### ISSUE THREAD

**Issue by adremalin** [react-native-community/react-native-tab-view#88]
Hi!

I want to have many differently coloured background sections in one View. Is there a way to set color of a View part based on a Key word? I tried to do it in the renderRow() method in ListView, but it didn't override the background color set in TabVieExample _renderScene. 

Like this:
https://i.stack.imgur.com/LkQEF.png

Thanks!

**Comment by satya164** [comment]
Inside your `renderRow` function you can check for something in `rowData` and set background color accordingly. You should post the question on StackOverflow to get more detailed answers which other people can also find easily.
