### ISSUE TITLE
_this.setState is not a function

### ISSUE THREAD

**Issue by iSaBo96** [react-native-community/react-native-tab-view#883]
### Current behaviour

Hello,

i have an Problem with this Library.
I use React_native 0.60.
The Swipe is not working and if i touch on the second Tab, get the followed error:

Screenshot: 
![image](https://user-images.githubusercontent.com/40924536/65161937-bdde5880-da38-11e9-9655-d245843f0909.png)

### Code sample

```
import * as React from 'react';
import { View, StyleSheet, Dimensions } from 'react-native';
import { TabView, SceneMap } from 'react-native-tab-view';

const screenHeight = Math.round( Dimensions.get( 'window' ).height );
const screenWidth = Math.round( Dimensions.get( 'window' ).width );

const styles = StyleSheet.create({
    scene: {
        flex: 1,
    },
});

const FirstRoute = () => (
    <View style={[styles.scene, { backgroundColor: '#ff4081' }]} />
);

const SecondRoute = () => (
    <View style={[styles.scene, { backgroundColor: '#673ab7' }]} />
);

const App = () => {

    state = {
        index: 0,
        routes: [
            { key: 'first', title: 'First' },
            { key: 'second', title: 'Second' },
        ]
    };

  return (
      <TabView
          navigationState={this.state}
          renderScene={SceneMap({
              first: FirstRoute,
              second: SecondRoute,
          })}
          onIndexChange={index => this.setState({ index })}
          initialLayout={{ width: Dimensions.get('window').width }}
      />

  );
};

export default App;`
```

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | android
| react-native                 | 0.60.5
| react-native-tab-view        | 2.10.0
| react-native-gesture-handler |1.4.1
| react-native-reanimated      |1.2.0

I Hope someone can help me with this error

**Comment by ivanstnsk** [comment]
This is not a bug. Just use class based component if you want to use setState() function. You're using functional component instead.

**Comment by VincenzoCarlino** [comment]
If you wanna use functional component you should use it like this:
`const FirstRoute = () => (
    <View style={[styles.scene, {backgroundColor: '#ff4081'}]}/>
);

const SecondRoute = () => (
    <View style={[styles.scene, {backgroundColor: '#673ab7'}]}/>
);

const Page = (props: Props) => {
    const [index, setIndex] = React.useState(0);
    const routes = {
        index: index,
        routes: [
            {key: 'first', title: 'First'},
            {key: 'second', title: 'Second'},
        ]
    };

    return (
        <>
            <StatusBar backgroundColor={properties.color} animated={true} barStyle={"light-content"}/>
            <SafeAreaView style={styles.safeArea}>
                <TabView
                    navigationState={routes}
                    renderScene={SceneMap({
                        first: FirstRoute,
                        second: SecondRoute,
                    })}
                    onIndexChange={index => setIndex(index)}
                    initialLayout={{width: Dimensions.get('window').width}}
                />
            </SafeAreaView>
        </>
    )
};`
