### ISSUE TITLE
TouchableItem Touchable Hope to use react-native-gesture-handler 

### ISSUE THREAD

**Issue by supermavericks** [react-native-community/react-native-tab-view#884]
Touchable for react-native on Android performace is slow somtimes! Hope to use  TouchEvent from react-native-gesture-handler

**Comment by satya164** [comment]
I'd accept a PR adding a `renderTouchable` prop on tab bar which lets your render your own touchable.

**Comment by njdancer** [comment]
@satya164 Have just submitted a PR for this.

@supermavericks See #929 for example usage with RNGH Touchables
