### ISSUE TITLE
Tab Paging is broken on tvOS, Android TV

### ISSUE THREAD

**Issue by vvasanth86** [react-native-community/react-native-tab-view#886]
react-native-tab-view's tab navigation seems to be broken on tv screens (tvOS and AndroidTV/FireTV). 

### Current behaviour

Navigation between the tabs works fine. Selecting any highlightable item in the first tab (button in this case) also works fine. But on all other tabs, when trying to select the highlightable item, the tab pages back to first tab. Wierdly though, the focus still seems to remain on the highlightable item (button in this case) and it fires on press, and the first tab is visible.

### Expected behaviour

We should be able to select highlightable items on all tabs on tvOS, Android TV and FireTV too. 

### Code sample

We are using the basic sample in the examples folder from this repo.

### Screenshots (if applicable)

![out](https://user-images.githubusercontent.com/137230/65336764-90cea900-dbe4-11e9-9eb5-ee80ac90ea0d.gif)

### What have you tried

- We have tried toggling various params, `lazy`, `scrollEnabled`, among others, nothing helped.
- We tried tweaking the `timingConfig` to figure out if the translate back to first tab is caused from within the Pager, but the un-intended translate happens at a `normal` speed, while the intended translate happens using the configured `timingConfig`. So, its unclear if this is caused by a bug in the Pager or something else.

### Your Environment

| software                     | version
| ---------------------------- | -------
| tvos               | 12.4
| react-native                 | 0.60.5
| react-native-tab-view        | 2.10.0
| react-native-gesture-handler | 1.3.0
| react-native-reanimated      | 1.1.0
| node                         | 12.1.0
| npm                  | 6.9.0

**Comment by SashaVons** [comment]
Still a bug 😩
