### ISSUE TITLE
You cannot customise styling for selected tab. 

### ISSUE THREAD

**Issue by LeoUrushi** [react-native-community/react-native-tab-view#888]
Current behaviour:

You can change the entire background colour of the tab menu bar. However, you cannot highlight selected item by changing the font colour or selected tab colour. 

renderTabBar props do not recognise “activeColor” or “inactiveColor”. 

Try the following settings. 

````


        renderTabBar={props =>
        <TabBar
          {...props}
          indicatorStyle={{ 
            backgroundColor: 'blue', 
            height:3 }}
          style={{ backgroundColor: 'lightgrey' }}
          renderLabel={({ route, focused, color }) => (
          <Text style={{ 
            fontSize: 18,
            activeColor: 'blue',
            inactiveColor: 'white',
            fontWeight: 'bold', 
            margin: 10 }}>
            {route.title}
          </Text>
        )}
        />
      }

````

Expected behaviour:
Highlighted menu item will have blue font. the other items will have white. But instead, the font colour stays black. 

Your Environment: 

| software                     | version
| ---------------------------- | -------
| ios or android               | iOS
| react-native                 | 0.60.4
| react-native-tab-view        |^2.10.0
| react-native-gesture-handler | ^1.3.0
| react-native-reanimated      | ^1.1.0
| node                         |
| npm or yarn                  |

**Comment by satya164** [comment]
> renderTabBar props do not recognise “activeColor” or “inactiveColor”.

You're not passing these props to `TabBar` in your code. You have them in `Text`'s style prop.

**Comment by LeoUrushi** [comment]
Oh I see. Thanks. I'm getting closer. How do I do that, exactly? So far, I've tried below. And neither worked. 


Option 1


        renderTabBar={props =>
        <TabBar
          {...props}
          activeColor={'blue'}
          inactiveColor={'white'}
          indicatorStyle={{ 
            backgroundColor: 'blue', 
            height:3 }}
          style={{ backgroundColor: 'lightgrey' }}
          renderLabel={({ route, focused, color }) => (
          <Text style={{ 
            fontSize: 18,
            fontWeight: 'bold', 
            margin: 10 }}>
            {route.title}
          </Text>
        )}
        />
      }



Option 2 



        renderTabBar={props =>
        <TabBar
          {...props}
          indicatorStyle={{ 
            backgroundColor: 'blue', 
            height:3 }}
          style={{ 
          	backgroundColor: 'lightgrey',
          	activeColor: 'blue',
          	inactiveColor: 'white'
           }}
          renderLabel={({ route, focused, color }) => (
          <Text style={{ 
            fontSize: 18,
            fontWeight: 'bold', 
            margin: 10 }}>
            {route.title}
          </Text>
        )}
        />
      }
