### ISSUE TITLE
Suggested edit - how to disable tabBar

### ISSUE THREAD

**Issue by LeoUrushi** [react-native-community/react-native-tab-view#889]
This is NOT a bug. Just a suggested edit for the documentation. 
Under the “renderTabBar” section. 

I believe the correct way to disable the tabBar is as follows. 

Currently: 
renderTabBar = () => null;

Suggested: 
renderTabBar = {() => null}

Just add curly braces. It worked for me. That’s all.

**Comment by pluvd7j** [comment]
In that case I have 5  Tabs here i want to disable one particular Tab,how can i do that?
