### ISSUE TITLE
Scenes loading before clicked with lazy property

### ISSUE THREAD

**Issue by TylerZubke** [react-native-community/react-native-tab-view#890]
### Current behaviour

Link to demo: https://snack.expo.io/B1kGRZKDH

If I click the 'SECOND' tab it alerts '2', which is expected. Then if I click back to the 'FIRST' tab, it alerts '3'. This happens in the simulator and on iOS devices every time. Weirdly, it occasionally works correctly in the Snack, but about 80% of the time it doesn't work as expected. Android seems to be fine. I can only get this behavior by clicking a tab to the left of the selected tab.

### Expected behaviour

With the lazy property I would expect that it doesn't alert '3' until I click the tab labeled 'THIRD'.

### Code sample

https://snack.expo.io/B1kGRZKDH

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios (device and simulator)  |  any version
| react-native                 | 0.60.3
| react-native-tab-view        | 2.10.0
| react-native-gesture-handler | 1.3.0
| react-native-reanimated      | 1.2.0
| node                         | 10.16.0
| npm or yarn                  | npm

**Comment by wenkangzhou** [comment]
same issue

**Comment by M4rk9696** [comment]
I'm facing the same issue
Is  #813 related?

@satya164 Have created a small repro in which I reproduced this
https://github.com/M4rk9696/tab-view-lazy-load-bug

| software                     | version
| ---------------------------- | -------
| ios or android               | both
| react-native                 | 0.61.5
| react-native-tab-view        | 2.11.0
| react-native-gesture-handler | 1.5.2
| react-native-reanimated      | 1.4.0
| node                         | v10.16.0
| npm or yarn                  | yarn

**Comment by M4rk9696** [comment]
@satya164 What is the purpose for `layout.width` in the check? I was trying to find the RCA, removing it seems to make it work

https://github.com/react-native-community/react-native-tab-view/blob/b4fc7c4d4a9eb31139e30034eaeb02fde7bb09e9/src/SceneView.tsx#L110

**Comment by Donhv** [comment]
any update ?

**Comment by M4rk9696** [comment]
@satya164 Can you reopen this please?

**Comment by TylerZubke** [comment]
In case anyone stumbles across this, I've had a much better experience with https://github.com/ptomasroos/react-native-scrollable-tab-view.

**Comment by sanghavan** [comment]
Got same issue

**Comment by hungpv19** [comment]
any solution ?

**Comment by marcin-solvenet** [comment]
> @satya164 What is the purpose for `layout.width` in the check? I was trying to find the RCA, removing it seems to make it work
> 
> https://github.com/react-native-community/react-native-tab-view/blob/b4fc7c4d4a9eb31139e30034eaeb02fde7bb09e9/src/SceneView.tsx#L110

@Mark1626 when I remove layout.width as you suggested,I observed that componentDidMount is called everytime when you change tab and go back so it's not a good option since your scene will be recreated on every focus.
