### ISSUE TITLE
Disable Particular Tab

### ISSUE THREAD

**Issue by pluvd7j** [react-native-community/react-native-tab-view#891]
I Want to disable particular tab in react-native-tab-view. 

### Current behaviour

here only we can disable the swipe but i need to disable tab view also 

### Expected behaviour

I Want to disable particular tab.

### Code sample
Didn't Tried
For Syntax Highlighting check this [link](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

### Your Environment

| software                     | version
| ---------------------------- | -------
|  android          |
| react-native     0.58.5            |
| react-native-tab-view    2.10.0    |
| react-native-gesture-handler 1.1.0 |  react-native-reanimated  1.2.0    |
| node         10.15.3                |
| npm    6.9.0               |

**Comment by hahalalamummy** [comment]
You can handle index update
`handleIndexChange = index => {
    if (index != 2) {
      this.setState({index});
    }
  };`

**Comment by pinomartin** [comment]
> You can handle index update
> `handleIndexChange = index => { if (index != 2) { this.setState({index}); } };`

Nice! I made a solution based on this. 
Adding a isDisabled (boolean) prop to my route object. Example below.
`export type Route = {
  key: string;
  title: string;
  // eslint-disable-next-line no-undef
  component: () => ComponentType<JSX.Element> | JSX.Element;
  testID: string;
  accessibilityLabel?: string;
  isDisabled?: boolean;
  isLastTab?: boolean; //to show or not a divider between tabs
};`
Then on onIndexChange prop , pass one function like this. (thanks @hahalalamummy !!!!) 
`const onChangeIndex = (newIndex: number, routes:Route[] ) => {
    if(!routes[newIndex].isDisabled){
      setIndex(newIndex);
    }
  };
`
Then made the styles of the disabled state and ask for the isDisabled prop exists or not, printing on screen if it's true.


https://user-images.githubusercontent.com/53881911/145489918-c67c7d23-2688-4937-afe7-08daec006091.mov
