### ISSUE TITLE
How to use .png image files in menu tabs

### ISSUE THREAD

**Issue by LeoUrushi** [react-native-community/react-native-tab-view#894]
I have .png image files I’d like to use in place of text menu items. 
Instead of spelling out “Home”, “Profile” and so on, I have .png image icons that depict the functionality of each page. 

From the main instruction page below, it looks like ‘icon’ function might be able to do what I’m trying to do. But I don’t know exactly how to do that.  

https://github.com/react-native-community/react-native-tab-view

Is there an example of using image files instead of text menu items?

**Comment by rat-moonshine** [comment]
I tried to use by `renderIcon` property for displaying a PNG image, but that did not worked:

```
<TabView
          renderIcon={this.renderIcon}
          onIndexChange={this.handleIndexChange}
          navigationState={this.state}
          renderScene={this.renderScene}
          initialLayout={{width: width}}/>
        );

renderIcon = ({ route }) => {
      switch (route.key) {
        case 'add':
          return <Image source={require('./../../images/someImage.png')} width={20}/>;
        default:
          return null;
      }
    };
```

Can someone please help how to do this? Or it is broken (?)

**Comment by ahtisham09** [comment]
@rat-moonshine  did you get solution ?

**Comment by rat-moonshine** [comment]
> @rat-moonshine did you get solution ?

Unfortunately, this still broken for me. I even forgot of this now )
