### ISSUE TITLE
Doesn't work expo web

### ISSUE THREAD

**Issue by jjg77** [react-native-community/react-native-tab-view#896]
First, the expo snack is broken.  

Second, this doesn't work on expo web, I get repeated errors: 

muteWarnings.fx.ts:21 Reanimated: createNode is unimplemented on web

**Comment by RichardLindhout** [comment]
You can use this for know: https://github.com/RichardLindhout/react-native-web-tab-view

**Comment by obiwankenoobi** [comment]
any updated about it? still seems not to work with `expo web`

**Comment by RichardLindhout** [comment]
It should work, but I don't use expo web. This is a Typescript error with a @ts-ignore it should work.

**Comment by bikashsahucbnits** [comment]
I guess Latest Expo SDK version 36 causes the issue..It worked pretty well with the lower 35 version
Hope to get some solution soon !!
