### ISSUE TITLE
Support infinite tabs natively

### ISSUE THREAD

**Issue by satya164** [react-native-community/react-native-tab-view#898]
We should support infinite tabs in the library, so user can swipe in either direction infinitely.

### Considerations

- The length of the `routes` array is unknown upfront, and routes can be added both to the beginning of the array and the end of the array
- We can't keep all of the pages rendered, otherwise there'll be issues with memory usage

### How we want to implement it

Currently the tabview works like this: if the `index` changes, we animate the tab change. For infinite pages, the `index` won't be stable, as pages could be added to the beginning of the routes array which will change the index even if the focused route is the same.

A more reliable approach would be to check the `key` of the focused route. Each `route` has a unique `key` property. Even if the `index` changed, if `route.key` of the focused route didn't change, then we shouldn't do an animated transition. We'll still need to adjust the translation value of the pages, but it should without an animation so that the user doesn't notice that and it happens transparently.

### Test code

User should be able to write the following code to render infinite pages:

```js
function InfiniteTabsExample() {
  const [state, dispatch] = React.useReducer(
    (state, action) => {
      switch (action.type) {
        case 'CHANGE_INDEX': {
          const startIndex =
            action.index < state.index
              ? state.routes[0].index - 1
              : state.routes[1].index;

          return {
            index: state.index,
            routes: [startIndex, startIndex + 1, startIndex + 2].map(i => ({
              key: String(i),
              index: i,
            })),
          };
        }
        default:
          return state;
      }
    },
    {
      index: 1,
      routes: [
        { key: '0', index: 0 },
        { key: '1', index: 1 },
        { key: '2', index: 2 },
      ],
    }
  );

  return (
    <TabView
      renderTabBar={() => null}
      renderScene={({ route }) => (
        <View style={styles.page}>
          <Text style={styles.label}>{route.key}</Text>
        </View>
      )}
      navigationState={state}
      onIndexChange={index => dispatch({ type: 'CHANGE_INDEX', index })}
    />
  );
}
```

**Comment by Naturalclar** [comment]
Hi :) I'd like to tackle on this issue.

**Comment by satya164** [comment]
@Naturalclar feel free

**Comment by darkbasic** [comment]
@satya164 @Naturalclar any news on this?
I need to implement an infinite scrolling calendar, so I could give it a try. Currently I preload the days, but anything more than a dozen has terrible performance despite lazy loading.
![Screenshot_20200317-174804](https://user-images.githubusercontent.com/1047358/76880232-acef9200-6877-11ea-9311-632be1196300.png)

**Comment by darkbasic** [comment]
Did the transition to react-native-pager-view make this feature any easier to achieve?

**Comment by MkNiloufar** [comment]
Did you find any solution?

**Comment by darkbasic** [comment]
I moved to a different library.

**Comment by crzycoder** [comment]
@darkbasic can you tell us which library you are using from support infinity numbers of top tabs ?

**Comment by ht19** [comment]
> @darkbasic can you tell us which library you are using from support infinity numbers of top tabs ?

Have you solve this?

**Comment by crzycoder** [comment]
@ht19 Not yet
