### ISSUE TITLE
Add backend based on react-native-viewpager

### ISSUE THREAD

**Issue by satya164** [react-native-community/react-native-tab-view#899]
Currently our implementation is based on reanimated and gesture handler. But it'll be great to have a pager based on https://github.com/react-native-community/react-native-viewpager to provide a native experience.

**Comment by troZee** [comment]
I would love to work on it <3

**Comment by NoemiRozpara** [comment]
Me too! Just agreed on solution so will be working on it.

**Comment by osdnk** [comment]
It's fixed by https://github.com/software-mansion/react-native-tab-view-viewpager-adapter
