### ISSUE TITLE
ListView inside a tab is not visible until scrolling

### ISSUE THREAD

**Issue by avishayil** [react-native-community/react-native-tab-view#9]
Ref: https://github.com/d-a-n/react-native-multiple-choice/issues/6

**Comment by satya164** [comment]
That's weird. It definitely works in the example. Does the ListView use `removeClippedSubViews`? That's known to be causing issues on iOS in latest React Native version.

**Comment by satya164** [comment]
Related https://github.com/facebook/react-native/issues/1831

**Comment by satya164** [comment]
Any updates on the issue?

**Comment by chirag04** [comment]
i'm using listview inside a tabview already with `removeClippedSubViews` disabled for now. I don't think it's a tab view concern.

**Comment by satya164** [comment]
@chirag04 Thanks. I'm going to close this issue then.
