### ISSUE TITLE
Question: how does the gradient below the tabs work?

### ISSUE THREAD

**Issue by elie222** [react-native-community/react-native-tab-view#90]
I'd like to replicate the design of these tabs somewhere else in my app. Specifically, I'd like to have a light gradient just below an item as this package does with tabs.

This seems to be the relevant line:
https://github.com/react-native-community/react-native-tab-view/blob/master/src/TabBar.js#L24
`elevation: 4`.
(I'm only interested in Android.)

The problem is that this gives me a gradient above and below my item. How does this package manage to get rid of the gradient above the tabs?

**Comment by satya164** [comment]
The container view of the tabview hides the shadow overflow at the top.

**Comment by elie222** [comment]
What are you referring to?
This: https://github.com/react-native-community/react-native-tab-view/blob/master/src/TabViewAnimated.js#L18

I don't see what style is hiding elevation here:
https://github.com/react-native-community/react-native-tab-view/blob/master/src/TabBar.js#L280

**Comment by satya164** [comment]
There's nothing special. Just wrapping it inside a view hides the shadow.

**Comment by elie222** [comment]
So are we seeing the shadow below?
And I don't seem to be having success with wrapping it in a view myself.
