### ISSUE TITLE
Swiping on ios and android causes app crash with production build

### ISSUE THREAD

**Issue by JamesDullaghan** [react-native-community/react-native-tab-view#906]
### Current behaviour

When swiping the tab view on both android and ios the application crashes. Setting `swipeEnabled` to false fixes the issue. Unfortunately our error reporting service isn't reporting stacktraces so we cannot provide one for this issue, but it seems reproduceable.

### Expected behaviour

To be able to swipe between tabs!

### Code sample

```
      <TabView
        navigationState={this.state}
        // eslint-disable-next-line new-cap
        renderScene={SceneMap(sceneMap)}
        onIndexChange={index => this.setState({ index })} // eslint-disable-line
        renderTabBar={props => (
          <View
            style={{
              backgroundColor: theme.color.impact.primary,
            }}
          >
            {header}
            <TabBar
              {...props}
              renderIcon={({ route }) => <SvgXml xml={iconType(route.key)} width="30" height="30" fill={iconColor(route.key)} />}
              indicatorStyle={{ backgroundColor: theme.color.primary }}
              style={{ backgroundColor: theme.color.textLight, borderBottomWidth: 1, borderColor: '#eee' }}
            />
          </View>)
        }
        initialLayout={{ width: Dimensions.get('window').width }}
      />
```

### What have you tried

Rendering a single tab fixes the issue. Setting `swipeEnabled` to false fixes the issue.

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | 11
| react-native                 | 0.61.2
| react-native-tab-view        | ^2.10.0
| react-native-gesture-handler | ^1.4.1
| react-native-reanimated      | ^1.2.0
| node                         | 12.3.1
| npm or yarn                  | yarn 1.17.3

**Comment by EasiGregory** [comment]
We are having the same issue but to be clear touching anywhere in the tab view (not only swipe actions) causes the app to crash. Seems to only be effecting Android devices for us and not iOS(11.2.6 & 12.4). Can confirm that adding `swipeEnabled` set to _false_ fixes the issue. 

**Current Environment:**
Android 8.1.0
Tab view 2.9.0
RN 0.61.2
Node v10.15.3
yarn 1.12.3

**Comment by EasiGregory** [comment]
After digging around for a bit I finally came across an error log when our app crashed with `Unsupported top level event type \"onGestureHandlerStateChange\" dispatched` and after doing a bit of googling came across this [issue](https://github.com/kmagiera/react-native-gesture-handler/issues/320) in react-native-gesture-handler that was quite informative/helpful.

**Comment by kissthedevel** [comment]
Hi!! I had the same problem last some days ago.
After two days of desperate attempts I solved it in the same way of @EasiGregory  .
But..........the day after, my teammate incredulous try to reset "swipeEnabled" to true.....and.......now all it works right!!!
It's a joke... 8-/

I think that the problem is an unalignment of bundle, but we are still investigating.

**Comment by franjorub** [comment]
Hi our teams have the same problem a few days ago, we solved it importing react-native-getsture-handler ^4.x as the first line in the index.js root

import 'react-native-gesture-handler'; <- first code line

looks like is a problem with the production bundle

**Comment by idanlo** [comment]
.

**Comment by JuliaSzymanskaFirmao** [comment]
I had the same problem with react-native-tab-view@3.1.1, downgrade to @2.16.0 helped me!
