### ISSUE TITLE
react-native-router-flux Integration

### ISSUE THREAD

**Issue by t2** [react-native-community/react-native-tab-view#91]
How would this be configured to work with react-native-router-flux?

**Comment by jephtta** [comment]
I had to do exactly this not too long ago. Quite straightforward really. 
Setup the TabBar component as you would normally. Import TabBar into your routes page and set it up as one of your scenes, probably the first. That's it. Works fine.

```
import TabBar from './TabRoutes';  //tabbar is setup in TabRoutes page

<Router sceneStyle={general} titleStyle={navbarTitle} >
    //other scenes possibly
    <Scene hideNavBar  key="home" component={TabBar}  />
   //some other scenes maybe
</Router>
```

**Comment by Naoto-Ida** [comment]
@t2 @jephtta Do you guys happen to have an example repo of this? I am using `react-native-router-flux`'s tabs (which shows at the bottom), but inside one of the tabs I want to use this library's tab.

**Comment by satya164** [comment]
I don't use `react-native-router-flux`, but if you can dispatch an action to change the tab in`onRequestChangeTab` and pass the navigation state for the tab in `navigationSate` props, then it should work.

I'm also working on integration with the new official react navigation library to be released soon.

**Comment by jasan-s** [comment]
@jephtta I wrapped my react-native-tab-view inside a scene similar to your code snippet.  But how would I keep track of the current view. I have nested tabs within main tabs.
