### ISSUE TITLE
onIndexChange issue

### ISSUE THREAD

**Issue by MayarAhmed** [react-native-community/react-native-tab-view#911]
I face an issue with OnIndexChange it's not working correctly  when i press it  and when i used onTabPress also not working correctly 

here is my code 

     ##   <TabView
                            navigationState={this.state}
                            renderScene={({ route }) => {
                                switch (route.key) {
                                  case 'first':
                                    return <cmp 1/>;
                                
                                  case 'second':
                                    return <cmp 2/>;
                                 case 'third':
                                      return <cmp 3/>;
                                }
                              }}
                            onIndexChange={index => {
                                console.log(index)
                                this.setState({ index})}}
                            initialLayout={{ width: Dimensions.get('window').width }}
                            />

  "react-native": "0.61.2",
"react-native-reanimated": "^1.3.0",
"react-native-gesture-handler": "^1.4.1",

Kindly advice as it works once and failed once and I don't know why ?

**Comment by JustalK** [comment]
I got the exact same problem using class component instead of functional way and found out that for some reason.
The setState pass after the new render of the tab component.

It works if you get ride of the setState and let the Tab doing the new render.
Not a good solution but it works.

```
 ##   <TabView
                        navigationState={this.state}
                        renderScene={({ route }) => {
                            switch (route.key) {
                              case 'first':
                                return <cmp 1/>;
                            
                              case 'second':
                                return <cmp 2/>;
                             case 'third':
                                  return <cmp 3/>;
                            }
                          }}
                        onIndexChange={index => {
                            console.log(index)
                            this.setState.index = index}
                        initialLayout={{ width: Dimensions.get('window').width }}
                        />
```
