### ISSUE TITLE
Tabs not swipeable on Android

### ISSUE THREAD

**Issue by KPS250** [react-native-community/react-native-tab-view#916]
### Current behaviour

Tabs are swipeable on iOS but not on Android

### Expected behaviour

Tabs should be swipeable on Android too

### Code sample

```
import React,{Component} from 'react';
import { View, StyleSheet, Dimensions } from 'react-native';
import { TabView, SceneMap } from 'react-native-tab-view';
import SafeArea from '../commons/SafeArea';
 
const FirstRoute = () => (
  <View style={[styles.scene, { backgroundColor: '#ff4081' }]} />
);
 
const SecondRoute = () => (
  <View style={[styles.scene, { backgroundColor: '#673ab7' }]} />
);
 
export default class FavouriteTabs extends Component {

    constructor(props){
        super(props)

        this.state = {
            index: 0,
            routes: [
              { key: 'first', title: 'First' },
              { key: 'second', title: 'Second' },
            ]
        }
    }
  
  render() {
    return (
      <SafeArea>
        <TabView
            navigationState={this.state}
            swipeEnabled={true}
            renderScene={SceneMap({
            first: FirstRoute,
            second: SecondRoute,
            })}
            onIndexChange={index => this.setState({ index })}
            initialLayout={{ width: Dimensions.get('window').width }}
        />
      </SafeArea>
    );
  }
}

const styles = StyleSheet.create({
  scene: {
    flex: 1,
  },
})
```

### What have you tried

Tried setting prop swipeEnabled={true} but no luck

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android                         | android
| react-native                           | 0.61.3
| react-native-tab-view           | 2.10.0
| react-native-gesture-handler | 1.5.0
| react-native-reanimated      | 1.4.0
| node                                      |10.0.0
| npm or yarn                          | npm

**Comment by satya164** [comment]
Please read the docs properly.

**Comment by KPS250** [comment]
Thanks.. missed this extra config for Android
`https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html`

**Comment by Bayramito** [comment]
how did you solved this?
