### ISSUE TITLE
Cannot swipe to switch tab inside a pageSheet modal

### ISSUE THREAD

**Issue by blueberry6401** [react-native-community/react-native-tab-view#919]
### Current behaviour

Using a tab view inside a pageSheet modal, I cannot swipe left/right to switch between tabs.
In iOS 13, swipe pageSheet modal make the modal dismiss. Maybe it conflicts with the gesture? But it also happens with Android too.

### Expected behaviour

Swipe left/right works.

### Code sample

https://snack.expo.io/@hiep95/react-native-tab-view---modal-pagesheet

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | both
| react-native                 | 0.61.4
| react-native-tab-view        |2.10.0
| react-native-gesture-handler |1.5.0
| react-native-reanimated      |1.4.0
| node                         |12.12.0
| npm or yarn                  |yarn 1.19.1

**Comment by andrewhamill** [comment]
I am experiencing this issue as well with any of the presentationStyle, on android.

react-native 0.61.4
react-native-tab-view 2.11.0
react-native-gesture-handler 1.4.0 (1.3.0, 1.2.0 as well)

Thanks!

**Comment by blueberry6401** [comment]
Hi, anyone help?

**Comment by blueberry6401** [comment]
Why is this marked as no-issue-activity.
I provided code example in snack expo right above.

**Comment by tkleisner** [comment]
I have the same problem with react-native-modalbox on Android
