### ISSUE TITLE
Why isn't the icon color changing based on selection?

### ISSUE THREAD

**Issue by judgejab** [react-native-community/react-native-tab-view#92]
I have a sliding tabView with two tabs. The title color changes based on whether the tab is selected. It flicks between #9B9B9B' (lightGrey) for unselected and '#666768' (darkGrey) for selected.

I'm also rendering an icon next to the title. I want the icon color to also change based on which tab is selected.

For some reason, this is not happening and the color of the icon stays at unselected regardless of whether the tab is selected or not.

How can I fix this this? My code is below. Thank you.

```
_renderLabel = (props: any) => ({ route, index }) => {
    const inputRange = props.navigationState.routes.map((x, i) => i);
    const outputRange = inputRange.map(
      inputIndex => inputIndex === index ? '#666768' : '#9B9B9B');
    const color = props.position.interpolate({
      inputRange,
      outputRange,
    });

    return (
      <View style={styles.labelContainer}>
        <FontAwesome
          name={route.title === 'New' ? 'clock-o' : 'fire'}
          size={14}
          color={color === '#666768' ? '#666768' : '#9B9B9B'}
        />
        <Animated.Text style={[styles.label, { color }]}>
          {route.title}
        </Animated.Text>
      </View>
    );
  };
```

**Comment by satya164** [comment]
The code is incorrect. This doesn't look correct, `color={color === '#666768' ? '#666768' : '#9B9B9B'}`

It should be,

```
const AnimatedFontAwesome = Animated.createAnimatedComponent(FontAwesome);

...

<AnimatedFontAwesome
  name={route.title === 'New' ? 'clock-o' : 'fire'}
  size={14}
  style={{ color }}
 />
```

**Comment by judgejab** [comment]
Thank you!
