### ISSUE TITLE
Question on styling tabs a certain way.

### ISSUE THREAD

**Issue by bvelasquez** [react-native-community/react-native-tab-view#924]
### Current behaviour

Trying to get the style I've attached, but can't seem to do it. Should this be possible? The selected tab needs to have a background color, the deselected tab white.

### Screenshots (if applicable)

<img width="343" alt="grow_feed___search" src="https://user-images.githubusercontent.com/2302210/69100816-e1128d80-0a12-11ea-8bbc-4531ca889685.png">

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | ios
| react-native                 | 0.59.9
| react-native-tab-view        | 2.6.0
| react-native-gesture-handler |
| react-native-reanimated      |
| node                         |
| npm or yarn                  |

**Comment by satya164** [comment]
You need a custom tab bar for that. See the README for example.
