### ISSUE TITLE
fontFamily "Arial" is not a system font and has not been loaded through Font.loadAsync.

### ISSUE THREAD

**Issue by obiwankenoobi** [react-native-community/react-native-tab-view#926]
### Current behaviour
While trying to render `TabView` with content in Hebrew on Android - the app crash with error: 

> fontFamily "Arial" is not a system font and has not been loaded through Font.loadAsync.
If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.
If this is a custom font, be sure to load it with Font.loadAsync.

### Expected behaviour

To support Hebrew and the Ariel font (Or maybe a way to change the font to something that work on Android

### Code sample

```
          <TabView
            navigationState={state}
            renderScene={SceneMap(state.routesObject)}
            renderTabBar={props => (
              <TabBar
                {...props}
                renderLabel={({ route, focused, color }) => (
                  <SFTMText>
                    {route.title}
                  </SFTMText>
                )}
                labelStyle={{ color: colors.themeGrey }} 
                style={{ backgroundColor: colors.themeWhite }} 
                indicatorStyle={styles.indicatorStyle}
                activeColor={colors.themeAction}
                scrollEnabled={Object.keys(state.routesObject).length > MAX_TABS_IN_SCREEN}/>
              )
            }
            onIndexChange={index => setState({ ...state, index })}
            initialLayout={{ width: screenWidth }}/>
```

### What have you tried

- To load `Ariel` font through `Font.loadAsync` as suggested

### Your Environment

| software                     | version
| ---------------------------- | -------
| android               | 
| react-native                 | https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz
| react-native-tab-view        | 2.11.0
| react-native-gesture-handler | ~1.3.0
| react-native-reanimated      | ~1.2.0
| node                         |
| npm or yarn                  | npm

**Comment by satya164** [comment]
Please check your code. We're not setting font family anywhere in the library.
