### ISSUE TITLE
Working with Navigator?

### ISSUE THREAD

**Issue by luco** [react-native-community/react-native-tab-view#93]
Guys,

Is there a way to make this work with Navigator? I mean, let's suppose I have 4 tabs, and in each one have a Navigator. Already tried and works. But the thing is I need to `NavigatorBar` work above the `TabViewAnimated`, but I think TabViewAnimated has` overflow hidden`.

Or, how can I bind the TabBarHeader with my navigator?

Thanks

**Comment by jordanpowell88** [comment]
@luco were you able to find a solution? If so can you share your code?  One of my tabs is using a <ListView> but I want to be able to open a typical details view for each row in the ListView.

**Comment by satya164** [comment]
Just render a header outside the tab view, pass a callback to child views to change the title.
