### ISSUE TITLE
Feature request: per screen fine grained swipe enabled

### ISSUE THREAD

**Issue by jsamr** [react-native-community/react-native-tab-view#932]
`swipeEnabled` could take `boolean` *or* a function with the following typescript signature:

```typescript
type SwipeEnableSpecs = {
  left: boolean
  right: boolean
}
type ConditionalSwipeEnable<R> = (state: NavigationState<R>) => SwipeEnableSpecs | boolean
```

**Comment by jsamr** [comment]
Just dropping a message to let the feature request live.

**Comment by vedovato** [comment]
I'd also like this feature

**Comment by vedovato** [comment]
https://github.com/react-native-community/react-native-tab-view/issues/673#issuecomment-458592769
