### ISSUE TITLE
TabBar background changed to "white" then how to change Tab bar title color from default white to another color

### ISSUE THREAD

**Issue by nzrsrk** [react-native-community/react-native-tab-view#934]
### Code sample

For Syntax Highlighting check this [link](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |
| react-native                 |
| react-native-tab-view        |
| react-native-gesture-handler |
| react-native-reanimated      |
| node                         |
| npm or yarn                  |

**Comment by 349989153** [comment]
by setting `labelStyle` prop of TabBar
