### ISSUE TITLE
Using mobx for tab state requires double tap to switch tab

### ISSUE THREAD

**Issue by jehartzog** [react-native-community/react-native-tab-view#935]
### Current behaviour

We use mobx for state rather than React state, typically it works fine but using the simplest code example from this with common mobx state handling results in needing a double press to switch the tab.

I was able to find a fix for this, saw a few issues without resolution here so perhaps may help someone in future.

### Expected behaviour

Tab only requires a single tap to switch.

### Code sample

```js
@observer
class MyComp extends React.Component<Props> {
  @observable private tabState = {
    index: 0,
    routes: [
      {key: 'one', title: 'One')},
      {key: 'two', title: 'Two')}
    ]
  };

  public render(): JSX.Element {
    return (
      <TabView
        navigationState={this.tabState}
        renderScene={({route}) => {
          switch (route.key) {
            case 'one':
              return <One />;
            case 'two':
              return <Two />;
            default:
              return null;
          }
        }}
        onIndexChange={this.handleSetTabIndex}
      />
    );
  }

  @action handleSetTabIndex = (index: number) => {
     // This was our initial solution which is normally fine with mobx but does not work with tab-view
     // this.tabState.index = index;

    // This is the fix we had to make, I suspect this lib is doing a memoization with reference
    // equality checking on tabState
    this.tabState = {
      routes: [...this.tabState.routes],
      index
    };
  };
```

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |Both
| react-native                 |0.61.4
| react-native-tab-view        |2.11.0
| react-native-gesture-handler |1.5.0
| react-native-reanimated      |1.4.0
| node                         |10.17.0
| npm or yarn                  |1.19.2

**Comment by jehartzog** [comment]
Possibly related to #798 #819 #820

**Comment by satya164** [comment]
We won't prevent a re-render when the index changes. Are you sure that your component is re-rendering when you update the state? If not, there's a bug in your component.

Also please provide runnable repro on snack.

**Comment by satya164** [comment]
https://mobx.js.org/best/pitfalls.html#objectsomenewprop-value-is-not-picked-up

**Comment by jehartzog** [comment]
We've been running mobx for over a year and have gotten used to it's various pitfalls, but of course it can still cause some edge cases like this one.

Do you have an example starter snack repro anywhere? I see you close a lot of issues when people don't provide, but it takes a few minutes to set one up initially for this project, would be handy to leave a link to a starter in the issue template if it's so important to have.

https://snack.expo.io/@avariodev/4ac327 - Requires double tap to switch tabs. I'm sure I did something wrong to cause it to do that, but it's a pretty standard mobx implementation, so wanted to throw it up here.

**Comment by satya164** [comment]
> Do you have an example starter snack repro anywhere?

There's a snack link in README, although copying and pasting the quick start code is also enough.

> Requires double tap to switch tabs. I'm sure I did something wrong to cause it to do that, but it's a pretty standard mobx implementation, so wanted to throw it up here

Seems like there's an issue with your setup. If you put a `console.log` in render, you can see that the component doesn't re-render. You can replace the entire tabview with a `Text` and it's the same: https://snack.expo.io/rJ_xI7xCS

Anyway, so I don't use mobx, so I'm not sure, but my guess is that - mobx is trying to be smart and tracks which properties have changed by monitoring if they are accessed in `render`. This library does not access the `index` property in `render`, but uses `componentDidUpdate` internally to imperatively animate the tabs while exposing declarative API. So mobx doesn't see that `index` is used. It works if you spread `routes` array because `routes` array is accessed in `render`.

So if that's actually the issue, you could change your state to something like this:

```js
@observer
class MyComp extends React.Component<Props> {
  @observable private index = 0;

  @observable private routes = [
    {key: 'one', title: 'One')},
    {key: 'two', title: 'Two')}
  ];

  render() {
    return (
      <TabView
        navigationState={{ index: this.index, routes: this.routes }}
        renderScene={({route}) => {
          /* ... */
        }}
        onIndexChange={this.handleIndexChange}
      />
    );
  }

  @action handleIndexChange = (index: number) => {
    this.index = index;
  };
}
```

This should work because when passing `navigationState`, we're accessing `index`. If this works, lemme know and we can add a note in the README. Probably also worth adding this to the mobx pitfalls docs.

**Comment by jehartzog** [comment]
Thanks for the quick follow up, sorry I missed the snack link in the readme.

You nailed the issue, mobx tracks accesses directly inside the render function only, and I guessed based on my testing that this lib was doing something that broke that behavior.

The code example you listed does fix the issue, I just confirmed.

I don't believe mobx docs need any updates, they call out this sort of case [specifically](https://mobx.js.org/best/react.html#mobx-only-tracks-data-accessed-for-observer-components-if-they-are-directly-accessed-by-render), but it may be worth throwing a readme note here for mobx users that `index` is not directly accessed inside the `render` func.

This is likely rather edge case, since I believe it's rather uncommon to use mobx rather than React state everywhere, but thanks for following up and confirming.

**Comment by satya164** [comment]
Thanks for the link. I was expecting it to see under pitfalls. Though from the docs, I see the workaround for things you pass to a library that's rendered (e.g wrapping in `<Observer>`), but seems there's no info on what to do if the data isn't actually rendered/never accessed in render (for example if a prop is only used for side effects, common for animations).
