### ISSUE TITLE
Performance issue in AnimatedComponent.

### ISSUE THREAD

**Issue by nethergrim** [react-native-community/react-native-tab-view#936]
### Current behaviour

Started using this tabs in our application, and during profiling noticed that AnimatedComponent takes ~70ms to be rendered

### Expected behaviour

Would like to make it faster OR an option to disable animation at all.

### Code sample

Nothing special, it could be reproduced on any tab.
```
 <TabView
          lazy
          swipeEnabled={false}
          renderLazyPlaceholder={this._renderLazyPlaceholder}
          navigationState={this.state}
          renderScene={this._renderScene}
          onIndexChange={this._handleIndexChange}
          initialLayout={{ width: Dimensions.get('window').width }}
          renderTabBar={this.renderTabBar} // don't render a tabbar from react-native-tab-view
        />
```

```
 _renderScene = ({ route }) => {
    const children = React.Children.toArray(this.props.children)
    const tabNames = this.props.tabs
    return children[parseInt(route.key, 10)]
  }
```

### Screenshots (if applicable)

![Снимок экрана 2019-12-13 в 11 48 07](https://user-images.githubusercontent.com/5869863/70792050-148dd100-1da1-11ea-86c9-f4525c7a929b.png)
![Снимок экрана 2019-12-13 в 11 47 13](https://user-images.githubusercontent.com/5869863/70792055-15befe00-1da1-11ea-800a-5ef9fd7fad31.png)
![Снимок экрана 2019-12-13 в 11 43 27](https://user-images.githubusercontent.com/5869863/70792065-18b9ee80-1da1-11ea-826e-9f93fc325c1c.png)

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios                | ios simulator 12.2
| react-native                 | 0.61.4
| react-native-tab-view        | 2.11.0
| react-native-gesture-handler | 1.5.2
| react-native-reanimated      | 1.4.0
| node                         | 8.12.0
| npm or yarn                  | npm

**Comment by MathiasBerwig** [comment]
I am facing the same performance issue on my app (render times are similar, varying from 70-200ms). There's also an error about state update on an unmounted `TabBar` in `Pager`.


software | version
-- | --
ios | 12.4.3 (iPhone  6S)
expo | 36.0.0
react-native | 0.61.4
react-native-tab-view | 2.11.0
react-native-gesture-handler | 1.5.2
react-native-reanimated | 1.4.0
node | 8.11.4
npm or yarn | npm

**Comment by vkotlyar** [comment]
Rendered slow for me too.

software | version
-- | --
ios | iPhone 6S 13.3
react-native | 0.61.4
react-native-tab-view | 2.11.0
react-native-gesture-handler | 1.5.2
react-native-reanimated | 1.4.0
node | 8.16.2
npm or yarn | npm

**Comment by lucasluca** [comment]
any solutions on this?

**Comment by nethergrim** [comment]
Yes it's still present in latest version.

**Comment by kamal-j** [comment]
I am also facing this issue.

**Comment by Mohamed-Raid** [comment]
+1
