### ISSUE TITLE
npm issue ('react-native-tab-view'), not able to import { tabBar } from react-native-tab-view

### ISSUE THREAD

**Issue by umairbinqaisar-sl** [react-native-community/react-native-tab-view#945]
### Code sample

For Syntax Highlighting check this [link](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |
| react-native                 |
| react-native-tab-view        |
| react-native-gesture-handler |
| react-native-reanimated      |
| node                         |
| npm or yarn                  |

**Comment by javadi69** [comment]
You should use `import { TabBar } from 'react-native-tab-view';` instead of `import { tabBar } from 'react-native-tab-view';`

**Comment by umairbinqaisar-sl** [comment]
i did that too but the TabBar itself is showing errors, i actually uninstalled and installed the single module even tried to re-install the whole node modules but nothing seems working, i am using "react-native-tab-view": "^1.4.1", idk why the file keeps on showing errors of every class imported from react-native-tab-view.

**Comment by borisvanschooten** [comment]
I have the same problem.  I do not use react-native-tab-view directly, it is an indirect import from react-native-tabs.  So this breaks react-native-tabs for me.  I get the error:

Failed to compile.

./node_modules/react-native-tab-view/lib/module/index.js
"export 'Props' (reexported as 'TabBarProps') was not found in './TabBar'

My guess is this has something to do with your use of .tsx files.

**Comment by benjipott** [comment]
@borisvanschooten same issue on latest `2.12.0`

**Comment by WazzaJB** [comment]
I arrived here because this error was being thrown in "react-navigation-tabs", it is worth noting that if you are using yarn you can create a version resolution to work around this:

```
"resolutions": {
    "react-navigation-tabs/react-native-tab-view": "2.11.0"
 },
```

Thanks for helping me get this solved.
