### ISSUE TITLE
Attempt to invoker virtual method

### ISSUE THREAD

**Issue by zuntilZ** [react-native-community/react-native-tab-view#949]
### Current behaviour

I using example and errors before .  How can i fix. Please?

![123](https://user-images.githubusercontent.com/7069320/72407315-c0a44c80-3791-11ea-81c3-cc75a4a2f3b1.png)

### Code sample

```
import * as React from 'react';
import {View, StyleSheet, Dimensions} from 'react-native';
import {TabView, SceneMap} from 'react-native-tab-view';

const FirstRoute = () => (
  <View style={[styles.scene, {backgroundColor: '#ff4081'}]} />
);

const SecondRoute = () => (
  <View style={[styles.scene, {backgroundColor: '#673ab7'}]} />
);

const initialLayout = {width: Dimensions.get('window').width};

export default function TabViewExample() {
  const [index, setIndex] = React.useState(0);
  const [routes] = React.useState([
    {key: 'first', title: 'First'},
    {key: 'second', title: 'Second'},
  ]);

  const renderScene = SceneMap({
    first: FirstRoute,
    second: SecondRoute,
  });

  return (
    <TabView
      navigationState={{index, routes}}
      renderScene={renderScene}
      onIndexChange={setIndex}
      initialLayout={initialLayout}
    />
  );
}

const styles = StyleSheet.create({
  scene: {
    flex: 1,
  },
});

```

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |android
| react-native                 |0.61.5
| react-native-tab-view        |2.11.0
| react-native-gesture-handler |1.5.0
| react-native-reanimated      |1.4.0
| node                         |
| npm or yarn                  |

**Comment by eugenemlee** [comment]
This seems to have been caused by the recent 1.5.0 update to `react-native-reanimated`. Downgrading to 1.4.0 fixed it for me.

**Comment by zuntilZ** [comment]
> This seems to have been caused by the recent 1.5.0 update to `react-native-reanimated`. Downgrading to 1.4.0 fixed it for me.

i using _react-native-reanimated_  ver 1.4.0

**Comment by eugenemlee** [comment]
Check your lock file and node_modules to check that it wasn't automatically updated to 1.5.0 the last time you ran `yarn install`

**Comment by zuntilZ** [comment]
> Check your lock file and node_modules that it wasn't accidentally updated to 1.5.0 the last time you ran `yarn install`

Thank you. I checked again and ver to 1.5.0 then I write package.json  version 1.4.0 , I run _npm install_  not using yarn install . why package auto update ver 1.5.0 ??? .
