### ISSUE TITLE
Can this active tab indicator be rendered?

### ISSUE THREAD

**Issue by ajonno** [react-native-community/react-native-tab-view#95]
hi there, thanks for publishing this component !

We need to create a tab bar (top) that has an active indicator per the screenshot. I will try your component shortly, however in advance of that do you know if this custom tab indicator can be implemented with your component ?

![image](https://cloud.githubusercontent.com/assets/3005269/21585209/3c485188-d110-11e6-960d-e0463dd125c8.png)

**Comment by satya164** [comment]
@ajonno Yeah, you could use an image for this indicator.

**Comment by ajonno** [comment]
nice one. via ```renderIndicator``` ?

**Comment by satya164** [comment]
yes

**Comment by ajonno** [comment]
dude that was so fast! ok thanks will give it a whirl shortly

**Comment by ajonno** [comment]
need some guidance, im doing some testing but can't seem to modify the behavior of the ```renderIndicator``` prop.

```
onRenderIndicator = (props) => {
     return (
         <View style={styles.indicator}>
            <Text>displays?</Text>
         </View>
     );
};
```

here's the TabBarTop setup:
```
<TabBarTop
       {...props}
       pressColor='rgba(251, 172, 48, 1)'
       onTabPress={this.onHandleTabItemPress}
       renderLabel={this.onRenderLabel(props)}
       renderIndicator={this.onRenderIndicator(props)}   <=== added 
       indicatorStyle={styles.indicator}
       tabStyle={styles.tab}
       tabWidth={90}
       style={styles.tabbar}
/>
```

however there doesnt appear to be any change to the indicator. obviously im just popping some text in the onRenderIndicator method to test but is it instead expecting an <Image> or .. ?

thanks for your help.

**Comment by satya164** [comment]
You actually have to use `TabBar` instead of `TabBarTop` for custom indicator - https://github.com/react-native-community/react-native-tab-view#tabbar- 

And it must be a function, so

```js
__renderIndicator = params => props => (...)
```

You can copy the code from here. Change `Animated.View` to `Animated.Image` for your image - https://github.com/react-native-community/react-native-tab-view/blob/master/src/TabBarTop.js#L70

**Comment by ajonno** [comment]
oh i see. we need the custom indicator for a TopTabBar. any chance you can add this capability?

**Comment by ajonno** [comment]
sorry but i dont quite follow ?  firstly we need a TapBarTop component ie. display tab bar top of view on both ios/droid.

is this currently not possible ? the onRenderIndicator method that I previously displayed (above) is invoked. however if i return the following from this method (below), there is no change to the TopTabBar indicator.

```
onRenderIndicator = props => {
   const { width, position } = props;
   const translateX = Animated.multiply(position, width);

  return (
  <Animated.Image
    source={require('../images/myIndicator.png')}
    style={[ styles.indicator, { width, transform: [ { translateX } ] } ]}
  />
  );
};
```

**Comment by satya164** [comment]
@ajonno `TabBarTop` is just a `TabBar` with indicator and some styling.

**Comment by ajonno** [comment]
ahh sorry i should have checked the return .... i was assuming it was a separate component. all good now thanks!
```
render() {
    return (
      <TabBar
        {...this.props}
        renderLabel={this.props.renderLabel || this._renderLabel}
        renderIndicator={this._renderIndicator}
      />
    );
  }
```
