### ISSUE TITLE
tab view not changing tab

### ISSUE THREAD

**Issue by iamleeg** [react-native-community/react-native-tab-view#950]
### Current behaviour

I've followed the instructions in the README to set up `react-native-tab-view` with `react-native-gesture-handler` and `react-native`. I'm running my app in the Android VM, on Linux (Ubuntu 18.04). I didn't do any of the linking things because they're either iOS-only or it says they're not needed on RN > 0.60.0, but I _did_ update `MainActivity.java` with the gesture handler view. I'm not using the wix gesture handler, FWIW.

I paste exactly the example code from the `react-native-tab-view` README quick start into `App.js`. One of two things happens in the Android VM:

1. "Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference", which is [reported elsewhere](https://github.com/software-mansion/react-native-gesture-handler/issues/711) and is probably not related to the bug I'm trying to report, which is the behaviour below.
2. If the app actually renders correctly, then it shows the magenta ("First") view with the "FIRST" tab selected in the tab bar. But then it's impossible to navigate to the other tab. If I click on "SECOND" in the tab bar, it doesn't change, although the tab bar button animates to register the click. I can't swipe between tabs, either.

### Expected behaviour

I expect that clicking on the tab bar buttons changes tab.

### Code sample

I used exactly the code in the Quick Start section of this repo's `README.md`, [from this commit](https://github.com/react-native-community/react-native-tab-view/commit/88d93bd619aa65ef7745407e73bda4e43cc9eb65).

### Screenshots (if applicable)

N/A

### What have you tried

I've tried logging the `setIndex` and `renderScene` callbacks, and here's what I see:

 - clicking the tab bar buttons _does_ call `setIndex` in a stateful way. In other words, initially tab 0 ('first') is selected, clicking first does nothing, clicking second calls `setIndex` with 1 as the arg. Subsequently, clicking second does nothing, and clicking first calls `setIndex` with 0 as the arg.
 - on any click, `renderScene` is called twice. The first time, the route has `route.key = first`, then `route.key = second`. The order doesn't change, and it always gets called with two different routes.

I've also tried replacing the functional `TabViewExample` component with a classical component; replacing the uses of `React.useState` with explicit management of the component's `state`; and replacing `SceneMap()` with an artisanally-typed `renderScene()` function. None of these changed the behaviour.

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | android
| react-native                 | 0.61.5
| react-native-tab-view        | 2.11.0 
| react-native-gesture-handler | 1.5.3
| react-native-reanimated      | 1.5.0
| node                         | v8.10.0 (same behaviour with v13.6.0)
| npm or yarn                  | npm

**Comment by ukasiu** [comment]
It works for me with `react-native-reanimated` 1.4.0

**Comment by iamleeg** [comment]
Confirmed, thanks. I'll try to produce a minimal case to report upstream.

**Comment by ukasiu** [comment]
@iamleeg also it seems to be fixed in react-native-reanimated 1.6.0

**Comment by lorenzomilesi** [comment]
I'm sorry if I write here, but I can't understand if the behavior is strictly related to this thread.
@iamleeg , you mentioned `Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference` and, since I have the same problem rendering a TabBar, I'd like to know if you solved it. Updating `react-native-reanimated` seems to fix the problem of changing tab, but when I randomly get this other error, I can't swipe between tabs until I reload the app.

**Comment by iamleeg** [comment]
@lorenzomilesi that appears to be [this issue](https://github.com/software-mansion/react-native-gesture-handler/issues/711).

**Comment by lorenzomilesi** [comment]
Ok thanks. I thought you had something more. Cause I'm just rendering a `TabBar` outside the `TabView` and getting the error, not using pan or any other gesture handler. Thanks anyway
