### ISSUE TITLE
Custom tabBar and default indicator

### ISSUE THREAD

**Issue by micheilsgrey** [react-native-community/react-native-tab-view#957]
### Current behaviour
New to react-native and animations, want to make style same as on attached image. Is it even possible to do like mine? I read README but since i am new i do not understan alot from those guides. In examples i see if custom tab bar creaded the default  indicator not working. Is it possible to make custom tab bar with some animations and having the default behavior with default indicator?
### Screenshots (if applicable)

![Redesign+App-LoL+in+One+-+Ui+%E2%80%93+Figma+-+Google+Chro](https://user-images.githubusercontent.com/8958040/73244372-dadf2100-41ba-11ea-9588-e9e1bd071485.png)

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | android
| react-native                 | ~0.61.4
| react-native-tab-view        |^2.11.0
| react-native-gesture-handler |^1.5.3
| react-native-reanimated      |^1.7.0
| node                         |v13.6.0
| npm or yarn                  |6.13.4

**Comment by micheilsgrey** [comment]
And if i understand right if i want this whole bar scrollable i need to implement whole logic for scrollable bar same as in this lib?

**Comment by satya164** [comment]
If you use a custom tab bar, you need to implement all tab bar related functionality yourself. What you posted in the picture seems achievable with custom label with `renderLabel` and custom indicator with `renderIndicator`.

**Comment by micheilsgrey** [comment]
> If you use a custom tab bar, you need to implement all tab bar related functionality yourself. What you posted in the picture seems achievable with custom label with `renderLabel` and custom indicator with `renderIndicator`.

can i use animations with `renderLabel `for example making (glowing/text shadow) and change title color like you did in example in CustomTabBarExample.tsx ? Do i need just wrap in `<Animated.View />`  the `<Text />` component and in same place put separator component ? Plz give me advice i am realy noob in this....
