### ISSUE TITLE
hide a tab if it contains empty data

### ISSUE THREAD

**Issue by hanaechahid** [react-native-community/react-native-tab-view#958]
Hi,

I Have a tabbar contains 3 tabs: elearning, stages and documents each of them contains some data and may some tabs not contain anything, what I want is:
if stages tab didn't contain any data so it should not be displaying in tabbar that means in this cas I will have just 2 tabs elearning and documents.

how can I do that?

thank you

**Comment by arun1705** [comment]
Hello Team,
Is the above mentioned functionality  achieved?

**Comment by Ankit13Rid** [comment]
Reopen this issue.
