### ISSUE TITLE
Render page only when tab is pressed

### ISSUE THREAD

**Issue by vidhyalakshmirbt** [react-native-community/react-native-tab-view#96]
Hi ,
Is there any way page is rendered only when tab is pressed/tapped /swipe is made
Because as of now all corresponding pages of the tab is getting loaded.
Componentdidmount method of all tab's associated pages are getting executed now.

Thanks

**Comment by satya164** [comment]
Use the `lazy` prop.

**Comment by vidhyalakshmirbt** [comment]
is there any example of using that keyword "LAZY"? 
Thanks,
Vidhya

**Comment by satya164** [comment]
Just pass the prop to `TabViewAnimated`.

`<TabViewAnimated lazy ...other props />`

**Comment by vidhyalakshmirbt** [comment]
Thanks @satya164
