### ISSUE TITLE
Style error when switching tabs

### ISSUE THREAD

**Issue by thaiphamvan** [react-native-community/react-native-tab-view#961]
### Current behaviour

Style error when switching tabs

## TabView
import * as React from 'react';
import {View, StyleSheet, Dimensions, StatusBar} from 'react-native';
import {TabView, SceneMap} from 'react-native-tab-view';

const FirstRoute = () => (
  <View style={[styles.scene, {backgroundColor: '#ff4081'}]} />
);

const SecondRoute = () => (
  <View style={[styles.scene, {backgroundColor: '#673ab7'}]} />
);

const initialLayout = {width: Dimensions.get('window').width};

export default function TabViewExample() {
  const [index, setIndex] = React.useState(0);
  const [routes] = React.useState([
    {key: 'first', title: 'First'},
    {key: 'second', title: 'Second'},
  ]);

  const renderScene = SceneMap({
    first: FirstRoute,
    second: SecondRoute,
  });

  return (
    <TabView
      navigationState={{index, routes}}
      renderScene={renderScene}
      onIndexChange={setIndex}
      initialLayout={initialLayout}
      style={styles.container}
    />
  );
}

const styles = StyleSheet.create({
  container: {
    marginTop: StatusBar.currentHeight,
    marginHorizontal: 30,
  },
  scene: {
    flex: 1,
  },
});
## Run TabView
![Screenshot from 2020-02-05 14-05-03](https://user-images.githubusercontent.com/23287244/73818700-883bdf80-4820-11ea-8cfd-e1a39045a70b.png)

### Screenshots (if applicable)
![Screenshot from 2020-02-05 13-59-30](https://user-images.githubusercontent.com/23287244/73818386-d4d2eb00-481f-11ea-9193-d7621ff81ac1.png)
![Screenshot from 2020-02-05 13-59-48](https://user-images.githubusercontent.com/23287244/73818424-ee743280-481f-11ea-8028-d93f66934c80.png)

### Your Environment

| software                     | version
| ---------------------------- | -------
| react-native                 |0.61.5
| react-native-tab-view        |2.13.0
| react-native-gesture-handler |1.5.6
| react-native-reanimated      |1.7.0
| node                         |13.7.0
| npm                 |6.13.6

**Comment by felix4321** [comment]
I have the same problem - event in this snack demo: https://snack.expo.io/@satya164/react-native-tab-view-lazy-load 
(opened with chrome on mac)

![Screenshot 2020-02-12 at 08 33 47](https://user-images.githubusercontent.com/50043030/74312651-68517200-4d72-11ea-9100-6c8fff11b866.png)

**Comment by Simon-Simvest** [comment]
Also seeing this on Android when the width of the TabView is not 100% of the screen. Does not happen on iOS.

RN: 61.5
react-native-tab-view: 2.13.0

**Comment by 11csive** [comment]
Also seeing this on Android when the width of the TabView is not 100% of the screen. Does not happen on iOS.

RN: 61.5
react-native-tab-view: 2.13.0
