### ISSUE TITLE
Scrollable Topbar

### ISSUE THREAD

**Issue by theobouwman** [react-native-community/react-native-tab-view#97]
I can't find a way to make the topbar scrollable when there are to many items.
Like in the example below:
![Image scroll](http://www.androidhive.info/wp-content/uploads/2015/09/android-scrollable-tab-layout.png)

Thanks in advance.

**Comment by satya164** [comment]
Pass the prop `scrollEnabled` to the tab bar. Check the examples.

**Comment by theobouwman** [comment]
Thanks
