### ISSUE TITLE
How to remove ripple effect when press TabBar?

### ISSUE THREAD

**Issue by rickyrsyah** [react-native-community/react-native-tab-view#972]

**Comment by JungHsuan** [comment]
same here

**Comment by Harsh-6026** [comment]
> pressColor={'transparent'}

you have to add this line in 


tabBaroption={{pressColor:'transparent'}}


--as simple as that

**Comment by kiveemusic9** [comment]
**this worked for me** 
`screenOptions = { { tabBarPressColor: "transparent" } }`

**Comment by alvAro365** [comment]
@kiveemusic9 answer works with react-navigation material top tabs navigator  version 6 and @JungHsuan answer works with react-native-tab-view
