### ISSUE TITLE
[web] tab bar indicator position is not correct when tab bar scroll is enabled

### ISSUE THREAD

**Issue by maxired** [react-native-community/react-native-tab-view#973]
### Current behaviour
Hi,
currently when using react-native-web, the indicator position in the tab bar is not correct when scroll is enabled in the tab bar.

### Expected behaviour
The indicator should be placed below the active label

### Code sample

https://snack.expo.io/SyKo0GpQ8

### Screenshots (if applicable)
![Screenshot from 2020-02-21 10 17 52](https://user-images.githubusercontent.com/1194083/75020665-75b5dd00-5493-11ea-9e8f-13fb27a6a9f0.png)

### What have you tried
I tried to understand the issue. It seems to be because when calculating the transformX position, we don't take into account the scroll position.

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |
| react-native                 |
| react-native-tab-view        | 2.13.0
| react-native-gesture-handler |
| react-native-reanimated      |
| node                         |
| npm or yarn                  |

**Comment by maxired** [comment]
I managed to get it working by using 
``` javascript
 onScroll={({ nativeEvent }) => {
              this.scrollAmount.setValue(nativeEvent.contentOffset.x);
            }}
``` 
instead of https://github.com/react-native-community/react-native-tab-view/blob/master/src/TabBar.tsx#L391-L397

I have no idea so far if this is a bug in tab-view or in reanimated. 
BTW, another thing that seems to be not working in web is the scroll velocity detection, which also rely in reanimated

**Comment by rnike** [comment]
Is this still an issue on the current version? 

We are working with `react-native-tab-view:2.15.1` and the issue is still not solved, wonder if upgrade helps
