### ISSUE TITLE
Can we add `index` to `Route`?

### ISSUE THREAD

**Issue by wong2** [react-native-community/react-native-tab-view#978]
which is the index of the route, this will make some situation easy, for example in `renderScene` I can use `route.index === index` to check whether the scene being rendered is the  focused scene

**Comment by satya164** [comment]
If you need index, pass it explicitly. Passing it to every screen by default is going to re-render every screen when index changes which is going to be very bad for performance.

**Comment by wong2** [comment]
@satya164 I don't understand isn't adding `route.index` the same as `route.key`?
