### ISSUE TITLE
Bug with @exponent/ex-navigation

### ISSUE THREAD

**Issue by theobouwman** [react-native-community/react-native-tab-view#98]
I found a bug when using this tab view in combination with @exponent/ex-navigation's bottom tabs.

### How to reproduce
1. A @exponent/ex-navigation tabview with a react-native-tab-view (animated) in a tab.
2. Then switch back and forth to a @exponent/ex-navigation tab.
3. Trying to swipe to another tab in the react-native-tab-view doesn't work anymore then.
Shown below:
<img src="https://media.giphy.com/media/l3vReVoB978Xi9mvK/source.gif" height="500">

**Comment by jkhedani** [comment]
@theobouwman I'm using the exact same setup as you. react-native-tab-view in an exponent nav tab view and things work fine for me. Were you able to track down the issue? Any thoughts on what might be causing the issue?

**Comment by theobouwman** [comment]
@jkhedani I was not able to find the issue so far...
But I think that the mounting and dismounting of the components might cause the issue.

**Comment by jkhedani** [comment]
Hmm odd. If you want to post some sample code I don't mind helping you troubleshoot a bit. Also, I'm using react-native-tab-view 0.0.42 with React Native 0.39.

**Comment by rauliyohmc** [comment]
Happening to me as well, with the latest version of Ex-navigation, 2.9.1. Wasn't taking place with my previous 2.5.0. Maybe worth it to port the issue there?

**Comment by CharlesMangwa** [comment]
This issue seems to have been solved with `react-navigation` [here](https://github.com/exponent/ex-navigation/issues/415#issuecomment-283412054), given that Expo is migrating to it.

**Comment by CharlesMangwa** [comment]
Closed #98.
