### ISSUE TITLE
Unmount cleanup

### ISSUE THREAD

**Issue by jmparsons** [react-native-community/react-native-tab-view#99]
The method `onRequestChangeTab` persists to call the method passed to it after the component is unmounted. 

If it is passed a method to setState such as the `_handleChangeTab` method in the examples, then this will throw a `setState` warning on an unmounted component.

To reproduce - run the example, click on a tab that animates, then click the back button immediately to see the setState warning appear.

It might be a timing issue with the Animation. After looking through the source code it looks as if both `onRequestChangeTab` and `navigationState` are fired from `_jumpToIndex`. 

The change in `navigationState` after unmounting is probably introducing this bug in ex-navigation:

https://github.com/exponent/ex-navigation/issues/271

**Comment by satya164** [comment]
Probably makes sense to add a check here before calling the method - https://github.com/react-native-community/react-native-tab-view/blob/master/src/TabViewTransitioner.js#L187

Up for a PR?

**Comment by jmparsons** [comment]
Yeah I can give it a shot. What's the best way to setup the dev? I haven't used flow and probably need to link the project folder to the example.

**Comment by satya164** [comment]
Sorry for not replying earlier. You just need to clone the project and run npm install in both the parent and example directories.
